### ISSUE TITLE
Clean support

### ISSUE THREAD

**Issue by camilstaps** [AlDanial/cloc#100]
[Clean](http://clean.cs.ru.nl/Clean) is a general purpose, state-of-the-art, pure and lazy functional programming language designed for making real-world applications.

File extensions: `.icl`, `.dcl`

Comments:

* Singleline, starting with `//`
* Multiline or inline between `/*` and `*/`. This can be nested, therefore in `/* x /* y */ z */`, `z` will still be a comment.

Example code: https://github.com/camilstaps/iClean/blob/master/iclean.icl combines both comment styles. `.dcl` and `.icl` files are not significantly different for counting lines of code.

Thanks!

**Comment by AlDanial** [comment]
I should mention that cloc is unable to process nested comments.  This limitation comes from the Perl module Regexp::Common::Comment which cloc uses to identify C++ comments.

**Comment by camilstaps** [comment]
Yeah, well, so be it. It's not extensively used anyway. Thanks for the quick response!
