### ISSUE TITLE
*TeX support

### ISSUE THREAD

**Issue by camilstaps** [AlDanial/cloc#107]
Would be nice to support *TeX. It is fairly simple:

File extension: `.tex`, `.sty`, `.cls`, `.dtx`

Comments:

* Singleline, starting with `%`
* Multiline or inline does not exist.

Example code for example here: https://git.camilstaps.nl/NWI-IBC017-Calculus-Kansrekenen.git/raw/master/assignment7.tex. There are no differences between the four different file extensions for comment handling.

Thanks!

**Comment by AlDanial** [comment]
I left out the ``cls`` extension for now because that conflicts with Visual Basic and will require extra code to process.  I won't be able to get to that for a while.  However I did add the BibTeX style file extension ``bst`` so now we have
<pre>
> ./cloc --explain TeX
TeX
    filter remove_matches  ^\s*%
    filter remove_inline  %.*$
    extensions: bst, dtx, sty, tex
</pre>

**Comment by camilstaps** [comment]
Great, thanks!
