### ISSUE TITLE
Antlr support (new language support)

### ISSUE THREAD

**Issue by ramanawithu** [AlDanial/cloc#109]
Is it possible to add Antlr parser code?

**Comment by AlDanial** [comment]
https://github.com/AlDanial/cloc#AdditionalLanguages

**Comment by ramanawithu** [comment]
1. File extension example, *.g
2. Comment style - supports both C style comments /**/ and C++/Java style single line comments //
3. Few links to example code.

A) https://github.com/apache/drill/blob/master/logical/src/main/antlr3/org/apache/drill/common/expression/parser/ExprParser.g

B) https://github.com/apache/phoenix/blob/master/phoenix-core/src/main/antlr3/PhoenixSQL.g

Let me know if more information is needed. Most of Java/Scala/C# parsers uses Antlr as frontend parser.
