### ISSUE TITLE
Support for Puppet's configuration language

### ISSUE THREAD

**Issue by tianyin** [AlDanial/cloc#11]
Hi, 

I'd like to add support for Puppet's configuration language. Currently, CLOC treats it as PASCAL, and the LOC is very incorrect (I tested using the sample code below which has 19 LOC).

```
cloc sample.pp
...
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Pascal                           1              3             15              6
-------------------------------------------------------------------------------
``` 

Could you point me how to write the plugin? Thanks!
</br>

**1. File extensions associated with the language.**
.pp
</br>

**2. A description of how comments are defined**
It supports two styles of comments:
https://docs.puppetlabs.com/puppet/latest/reference/lang_comments.html
 
(1) Shell-stype (begin with `#`)
```
# This is a comment
```

(2) C-style (delimited by slashes with inner asterisks.)
```
/*
  this is a comment
*/
```
</br>

**3. Sample code**
```
#sample.pp

case $operatingsystem {
  centos, redhat: { $service_name = 'ntpd' }
  debian, ubuntu: { $service_name = 'ntp' }
}

package { 'ntp':
  ensure => installed,
}

service { 'ntp':
  name      => $service_name,
  ensure    => running,
  enable    => true,
  subscribe => File['ntp.conf'],
}

file { 'ntp.conf':
  path    => '/etc/ntp.conf',
  ensure  => file,
  require => Package['ntp'],
  source  => "puppet:///modules/ntp/ntp.conf",
  # This source file would be located on the Puppet master at
  # /etc/puppetlabs/code/modules/ntp/files/ntp.conf
}
```
Here is a brief intro of the language:
https://docs.puppetlabs.com/puppet/4.2/reference/lang_summary.html

**Comment by AlDanial** [comment]
Which version of cloc are you using?  The current development version, 1.65, correctly identifies your sample code as Puppet:

    https://github.com/AlDanial/cloc v 1.65  T=0.04 s (26.3 files/s, 684.0 lines/s)
    -------------------------------------------------------------------------------
    Language                     files          blank        comment           code
    -------------------------------------------------------------------------------
    Puppet                           1              4              3             19
    -------------------------------------------------------------------------------

You can get the dev code from https://github.com/AlDanial/cloc/raw/master/cloc

**Comment by tianyin** [comment]
Oh, I used an `apt-get` one. I will use the latest one. Thanks @AlDanial !
