### ISSUE TITLE
GLSL files are not recognized

### ISSUE THREAD

**Issue by theoden8** [AlDanial/cloc#115]
Hello, if nobody minds, I will be straightforward.

    $ ls; cloc .
    fragment_shader.frag  vertex_shader.vert
           2 text files.
           2 unique files.
           2 files ignored.

The program does not recognize opengl shading language files ([GLSL](https://en.wikipedia.org/wiki/OpenGL_Shading_Language)). Here is the list of extensions (currently, 6) and explanations for them:

http://stackoverflow.com/a/26531467/4811285

It's not a mainstream language, but is kind of recognizable and used language (since it has a bunch of plugins for vim/emacs/sublime/atom).

Good luck and have a nice day!

**Comment by AlDanial** [comment]
I also need to know how comments are defined in GLSL.  I took a cursory look at both links you gave but couldn't find comment explanations.

**Comment by theoden8** [comment]
Although this is strictly unofficial, but since both languages are designed for C programmers I took a look at syntax highlighting and digraphs-trigraphs page (https://en.wikipedia.org/wiki/Digraphs_and_trigraphs#C).

<img width="193" alt="comment" src="https://cloud.githubusercontent.com/assets/12466435/16848224/5c82421e-49fd-11e6-8752-e85c6272751a.png">

**Comment by AlDanial** [comment]
with git commit ee428cc :
<pre>
> cloc --explain GLSL
GLSL
    filter call_regexp_common  C++
    extensions: comp, frag, geom, glsl, tesc, tese, vert
</pre>
