### ISSUE TITLE
Request support of .po files

### ISSUE THREAD

**Issue by f2404** [AlDanial/cloc#118]
Which are used for translations in GTK programming.
Description: https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html
Example: https://github.com/xfce-mirror/xfce4-terminal/blob/master/po/en_AU.po
Thanks.

**Comment by AlDanial** [comment]
with git commit 33b77cf
<pre>
> ./cloc --explain 'PO File'
PO File
    filter remove_matches  ^\s*#[^,]
    extensions: po
</pre>

**Comment by f2404** [comment]
Thanks!
