### ISSUE TITLE
Request for LFE support

### ISSUE THREAD

**Issue by skovsgaard** [AlDanial/cloc#119]
Lisp Flavored Erlang is currently ignored, and it would be nice to have support for this.

Syntactically, it's very close to Common Lisp and my current workaround is adding a line to Cloc, which maps .lfe files to 'Lisp' which is working out quite well.

Line comments are defined using `;` and multi-line comments are opened with `#|` and closed with `|#`.

Sample source code can be found [in the language's Github repository](https://github.com/rvirding/lfe/tree/develop/examples).

**Comment by AlDanial** [comment]
with git commit a5eb6e1
<pre>
> ./cloc --explain LFE                                                           
LFE
    filter remove_matches  ^\s*;
    filter remove_between_general  #|  |#
    extensions: lfe
</pre>

**Comment by skovsgaard** [comment]
Thanks so much! That was fast.
