### ISSUE TITLE
Request for vuejs support

### ISSUE THREAD

**Issue by flavius** [AlDanial/cloc#120]
Please support .vue files, they are vuejs components, as documented here: https://vuejs.org/guide/components.html

**Comment by AlDanial** [comment]
I cloned the vuejs git repo and wasn't able to locate a single .vue file.  Also the components guide does not mention anything about the .vue file extension being associated with components.  Where can I find sample files?

**Comment by flavius** [comment]
https://github.com/vuejs/vue-hackernews/tree/gh-pages/src/components

The special thing about them is that one file can have different languages inside, js, html, or css (and those can have a different language like here: https://github.com/vuejs/vue-hackernews/blob/gh-pages/src/components/ItemView.vue )

**Comment by AlDanial** [comment]
One of cloc's limitations is that it cannot discern multiple languages in a file so the vue.js component counter will not be as smart as you'd like.  For now it will recognize count comments in HTML and JavaScript styles.

With git commit 9d20d26:
<pre>
> cloc --explain 'Vuejs Component'
Vuejs Component
    filter remove_html_comments
    filter call_regexp_common  HTML
    filter call_regexp_common  C++
    extensions: vue
</pre>
