### ISSUE TITLE
Add support for RapydScript

### ISSUE THREAD

**Issue by kovidgoyal** [AlDanial/cloc#121]
RapydScript is a language that is very similar to python (it gets transpiled to JavaScript). Comments, strings and line continuation syntax is all identical to Python. RapydScript files have a .pyj file extension.

Currently, I use cloc --force-lang=Python,pyj

It would be nice to have builtin support.

https://github.com/kovidgoyal/rapydscript-ng

**Comment by AlDanial** [comment]
With git commit ab68482,
<pre>
cloc --explain RapydScript
RapydScript
    filter remove_matches  ^\s*#
    filter docstring_to_C
    filter call_regexp_common  C
    filter remove_inline  #.*$
    extensions: pyj
</pre>

**Comment by kovidgoyal** [comment]
Thanks :)
