### ISSUE TITLE
Complex regular subexpression recursion limit (32766) exceeded and  ignore files

### ISSUE THREAD

**Issue by mikybone** [AlDanial/cloc#125]
Hi
thanks for your good project.

845 files ignored, How Solve this problem?

> cloc src
>     9242 text files.
>     9242 unique files.
> Complex regular subexpression recursion limit (32766) **exceeded** at script/cloc-1.
> 70.pl line 9005.
>      **854 files ignored.**

> github.com/AlDanial/cloc v 1.70  T=28.00 s (330.1 files/s, 18141.1 lines/s)
> -------------------------------------------------------------------------------
> Language                     files          blank        comment           code
> -------------------------------------------------------------------------------
> Java                          9242          50465          33857         423629
> -------------------------------------------------------------------------------
> SUM:                          9242          50465          33857         423629
> -------------------------------------------------------------------------------

all files were java.

**Comment by AlDanial** [comment]
To see which files were ignored and why, add this switch:
<pre>
    --ignored=ignored.txt
</pre>
It will create a text file, <tt>ignored.txt</tt>, with the name of each ignored file and the reason it was ignored.

A fix was added for the "recursion limit" problem after v1.70 was released.  Try running with the current development version of cloc (from https://github.com/AlDanial/cloc/raw/master/cloc)

**Comment by AlDanial** [comment]
no follow-up, closing
