### ISSUE TITLE
Can't use an undefined value as an ARRAY reference

### ISSUE THREAD

**Issue by 0xmohit** [AlDanial/cloc#126]
```
$ cloc --version
1.60
```

What did I do?

```
$  cloc --exclude-dir=build,dist,target,tmp,x86_64-unknown-linux-gnu .
   73773 text files.
   42610 unique files.                                          
Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498.
```

The current directory contains [`rust`](https://github.com/rust-lang/rust/).

The NEWS file suggests that the [issue](https://github.com/AlDanial/cloc/blob/master/Unix/NEWS#L391) was fixed in 1.60.

I'll attempt to gather meaningful information from the logs; setting `-v=3` seems to emit quite a bit.  The file is huge; I'll attempt to make a home for it.

```
$  cat -n /usr/bin/cloc | sed -n '1490,1510p'
  1490      ++$nCounted;
  1491      printf "Counting:  %d\r", $nCounted 
  1492          unless (!$opt_progress_rate or ($nCounted % $opt_progress_rate));
  1493      next if $Ignored{$file};
  1494      if ($Exclude_Language{$Language{$file}}) {
  1495          $Ignored{$file} = "--exclude-lang=$Language{$file}";
  1496          next;
  1497      }
  1498      my $Filters_by_Language_Language_file = !@{$Filters_by_Language{$Language{$file}} };
  1499      if ($Filters_by_Language_Language_file) {
  1500          if ($Language{$file} eq "(unknown)") {
  1501              $Ignored{$file} = "language unknown (#1)";
  1502          } else {
  1503              $Ignored{$file} = "missing Filters_by_Language{$Language{$file}}";
  1504          }
  1505          next;
  1506      }
  1507
  1508      my ($all_line_count,
  1509          $blank_count   ,
  1510          $comment_count ,
```

**Comment by mrdeveloperdude** [comment]
lennart@katana:~/waterwell_ng/repos/waterwell-dispenser-client/client/lib$ cloc .
   77905 text files.
   61055 unique files.                                          
Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498.

**Comment by AlDanial** [comment]
@0xmohit: please try again with a newer version of cloc.

@mrdeveloperdude: you're not giving much to go on... which version of cloc?  which version of perl?

**Comment by 0xmohit** [comment]
@AlDanial I can confirm that the issue does not exist using the [latest commit](https://github.com/AlDanial/cloc/blob/16d4893e119796ce89f215148f92477cdbde1bd9/cloc).  Wonder why these distros choose to package rather [old](https://launchpad.net/ubuntu/xenial/+source/cloc) versions.

Closing this as there isn't anything to fix here.  Thanks.

**Comment by 0xmohit** [comment]
@AlDanial I can confirm that the issue does not exist using the [latest commit](https://github.com/AlDanial/cloc/blob/16d4893e119796ce89f215148f92477cdbde1bd9/cloc).  Wonder why these distros choose to package rather [old](https://launchpad.net/ubuntu/xenial/+source/cloc) versions.

Closing this as there isn't anything to fix here.  Thanks.

**Comment by BIG-CHENG** [comment]
just happened in version 1.60

------------------------------------------------------
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cloc is already the newest version (1.60-1.1).
0 upgraded, 0 newly installed, 0 to remove and 299 not upgraded.

$ cloc .
    9801 text files.
    9688 unique files.                                          
Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498.

**Comment by AlDanial** [comment]
This bug has long been fixed.  Grab the latest release, 1.76, from https://github.com/AlDanial/cloc/releases, and rerun with that.

**Comment by sabrehagen** [comment]
1.60 is still the default distribution in 18.10 as of Feb 2019 :(

**Comment by AlDanial** [comment]
https://wiki.ubuntu.com/Releases says 18.10 == Cosmic Cuttlefish and
https://launchpad.net/ubuntu/+source/cloc says Cosmic Cuttlefish should give you cloc 1.76-1 (itself old, but a big improvement over 1.60).  Either I'm not interpreting the Ubuntu wiki correctly or there's a configuration goof that's sending out an old version.

I'll ask the Ubuntu cloc package maintainer what's up.

**Comment by sabrehagen** [comment]
@AlDanial Thanks for investigating. I was running 18.10 but had an old apt source which cloc was being pulled from. Starting with a fresh 18.10 container shows cloc at 1.76-1. My error!

**Comment by AlDanial** [comment]
@sabrehagen thanks for clearing it up so quickly.  As it happens I'd already queried Jari, only to immediately after send him a second "nevermind" note.  No harm, no foul :)
