### ISSUE TITLE
Add support for Mako language

### ISSUE THREAD

**Issue by toirl** [AlDanial/cloc#128]
I am asking for addition of the mako language to cloc.

Mako is a templating language for Python: See http://www.makotemplates.org/

File extension is ".mako"
Comments in Mako are beginning with "##"
For more informations See the above link.

I already have a working version here but I am not sure on how to set the following points correct:

1. Scale Factor
1. Header section in result yaml file for tests

I will create a new pull request.

Best regards.

**Comment by toirl** [comment]
For the records: 
PL was https://github.com/AlDanial/cloc/pull/129
Open points regarding scale factor and header section are not solved yet.

**Comment by AlDanial** [comment]
Neither scale factor nor header (I'm assuming you're talking about the section below header: in tests/outputs/Mako.mako.yaml) are important.  The scale factor output no longer appears in the default output; its content was always rather dubious ("N lines of Mako == x lines of C?").  The header section in the YAML file is merely metadata about the run.  It isn't used in comparing results between runs.
