### ISSUE TITLE
Make it available for apk package manager.

### ISSUE THREAD

**Issue by mkungla** [AlDanial/cloc#134]
Still one of the best it's kind - would be nice to have it available for Alpine Linux to use it with docker images

**Comment by AlDanial** [comment]
OK, how do I do that?

**Comment by mkungla** [comment]
Starting point can be found at [Creating an Alpine package](http://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package).

**Comment by maxwell-k** [comment]
I just discovered `cloc` is currently available in the community repository for Alpine Linux:
https://pkgs.alpinelinux.org/package/v3.7/community/x86_64/cloc

That may be enough to close this, or would you prefer a pull request adding Alpine Linux to the README?

**Comment by mkungla** [comment]
yes would be nice to add it to readme https://github.com/AlDanial/cloc#install-via-package-manager

**Comment by AlDanial** [comment]
I updated the README to include
<pre>
apk add cloc                           # Alpine Linux
</pre>
(I'm hoping that's the right command!)

**Comment by mkungla** [comment]
yes very nice
