### ISSUE TITLE
Add tsx for TypeScript

### ISSUE THREAD

**Issue by ericjeney** [AlDanial/cloc#142]
Would you be able to add `.tsx` as a file extension for TypeScript? It's their [JSX mode filetype](https://www.typescriptlang.org/docs/handbook/jsx.html). Thanks!

**Comment by AlDanial** [comment]
It's in cloc v1.70 which was released in July, ref https://github.com/AlDanial/cloc/releases (the tsx extension was added back in February with #57).

**Comment by ericjeney** [comment]
Thanks for the quick response! However, this doesn't seem to be working for me. Only `.ts` files are being parsed as TypeScript, and not `.tsx`. I have the latest v1.70 installed via Homebrew.

Steps to reproduce:
1. Install v1.70 using Homebrew.
2. Create a directory with one file named `test.tsx` with the contents:

       const test: string = "Testing";

3. Execute `cloc .`:

       1 text file.
       1 unique file.                              
       1 file ignored.

4. If I instead run `cloc --ignored=ignored.txt .`, the contents of `ignored.txt` are:

       ./test.tsx: language unknown (#3)

If I run on a different directory that has contents than `cloc` recognizes, it prints its version as:

    github.com/AlDanial/cloc v 1.70  T=0.66 s (128.0 files/s, 10486.4 lines/s)

**Comment by AlDanial** [comment]
That's odd.  Could you try with the git master?  All you need to do is download the Perl source file (https://raw.githubusercontent.com/AlDanial/cloc/master/cloc) and make it executable; installation is trivial.

When I run (with the git master) I get
<pre>
> cloc testing.tsx 
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.71  T=0.01 s (176.1 files/s, 176.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TypeScript                       1              0              0              1
-------------------------------------------------------------------------------
</pre>

**Comment by ericjeney** [comment]
Seems to work fine with master, but not when I download the 1.70 release (https://github.com/AlDanial/cloc/releases/download/v1.70/cloc-1.70.pl) directly.

**Comment by AlDanial** [comment]
I looked at the 1.70 code and you're right, tsx support is missing there.  My bad.  (Wondering how I did a commit in Feb that wasn't included in the July release?)

**Comment by ericjeney** [comment]
No worries. Thanks!
