### ISSUE TITLE
Does not include all PowerShell file extensions

### ISSUE THREAD

**Issue by alejandro5042** [AlDanial/cloc#144]
PowerShell files can also have extensions of `.psm1` (modules) and `.psd1` (data files). Since most of my PowerShell code is in modules, `cloc` ignores them.

For example:

```
classifying ./GitHelpers/GitHelpers.psm1
-> classify_file(./GitHelpers/GitHelpers.psm1)
./GitHelpers/GitHelpers.psm1 extension=[psm1]
-> peek_at_first_line(./GitHelpers/GitHelpers.psm1)
<- peek_at_first_line(./GitHelpers/GitHelpers.psm1)
<- classify_file(./GitHelpers/GitHelpers.psm1)=(unknown)
```

**Comment by AlDanial** [comment]
I added `psm1` but not `psd1`, which is data, right?  If `psd1` needs to be added as well, does it follow the same syntax rules as PowerShell itself?  If not, please point me to a reference that describes comments in these files.

**Comment by alejandro5042** [comment]
Thank you! `.psd1` files are almost exclusively used as module manifest files. If you classify such files for other languages as code, then you should also include them. They can also be used to store resource strings, localized strings, etc. It's a subset of the language, much like JSON is to JavaScript. You'll note that it has the same syntax as `.ps1` files, but restricted.

Here's a description of a manifest file: https://msdn.microsoft.com/en-us/library/dd878337(v=vs.85).aspx

**Comment by AlDanial** [comment]
ok, added `psd1` as well
