### ISSUE TITLE
Multiple report files in different formats with one cloc execution

### ISSUE THREAD

**Issue by FlorianWolters** [AlDanial/cloc#145]
Is there any possibility to create multiple report-files in different data formats with one `cloc`  invocation? I am using cloc 1.70.

**Example:** The following does not work, but only generates one file `cloc.xml`.

    cloc -json -report-file=cloc.json --xml -report-file=cloc.xml src

This feature would be useful in a Continuous Integration environment.

**Comment by reflexdemon** [comment]
@FlorianWolters I had the same need and found a workaround for this.

If you already had `npm` you can do the following.

```
npm install -g xml2json-command
```
Now, generate the xml report.
```
cloc --xml -report-file=cloc.xml src
```
Now, you can convert xml to json.
```
xml2json < cloc.xml > cloc.json
```
For more details on this go to https://github.com/Inist-CNRS/node-xml2json-command

**Comment by AlDanial** [comment]
cloc's output generation logic is pretty ugly.  I studied the code to see if it could bear the addition of a loop over all output types and quickly realized the current ugliness would explode into outright hideousness.

I'll therefore decline to implement such a capability and recommend the use of external tools such as suggested by @reflexdemon
