### ISSUE TITLE
Custom `--vcs` command doesn't work as expected

### ISSUE THREAD

**Issue by artemave** [AlDanial/cloc#147]
This works as expected:
![image](https://cloud.githubusercontent.com/assets/23721/21613556/9d1d0522-d1cd-11e6-86a5-19f229be5352.png)

But not this?
![image](https://cloud.githubusercontent.com/assets/23721/21613603/d20c4a7c-d1cd-11e6-8a69-5b57c7a4b386.png)

I am expecting to see the breakdown table, but it is not there. Why?

Ultimately I want to compare test/production code ratio.

**Comment by AlDanial** [comment]
Thanks for reporting this; yes, your expectation is correct that the second command should work.  I will investigate.

**Comment by AlDanial** [comment]
The problem was caused by a surprising interaction between the output of the `--vcs` provided "find" and the "find" built into Perl's File::Find module.  Please re-open if commit 85308fa doesn't work for you.

**Comment by artemave** [comment]
Works, thank you!
