### ISSUE TITLE
Usage text is huge

### ISSUE THREAD

**Issue by justinpitts** [AlDanial/cloc#150]
The default usage help text is quite long, and scrolls the most useful information off the screen.

As an infrequent user of cloc, it would be helpful if invoking cloc without any options gave a short synopsis of required input and most-used options, that required less than 80 lines to display. Of course, something like cloc --help ought to display the entire text.

**Comment by AlDanial** [comment]
That's a great idea.  The only catch is the most-used options will differ between users.  Commit 33366d4 adds a super trimmed-down version showing `--diff` as the primary option.
