### ISSUE TITLE
cloc fails when using sshfs

### ISSUE THREAD

**Issue by pgkos** [AlDanial/cloc#156]
When I try to run cloc in a directory inside a mounted sshfs directory (when I am mounting a remote Windows-cygwin drive from Linux), it always fails:
`cloc .`
outputs
```
       0 text files.
       0 unique files.       
       0 files ignored.

1 error:
Unable to read:  .
```

I have narrowed down the cause to this:
`-r $file_or_dir`, e.g. `-r '.'`
is always false inside a sshfs-mounted directory.

**Comment by AlDanial** [comment]
That's a new one for me.  Makes me suspect there will be additional difficulties down the line.  What happens if you comment out the four lines of the surrounding if statement,
```
#        if (!-r $file_or_dir) {
#            push @{$raa_errors}, [$rh_Err->{'Unable to read'} , $file_or_dir];
#            next;
#        }
```
does the code continue on to report correct results?

**Comment by pgkos** [comment]
Yes, when I comment out these lines everything works ok (lines of code are counted correctly), but there are still some "Unable to read" errors on some files (probably only ignored ones).

When I also comment out
```
#     if (!-r $file) {
#         push @{$raa_errors}, [$rh_Err->{'Unable to read'} , $file];
#         return $script_language;
#     }
```
in `peek_at_first_line` then there are no errors.

**Comment by pgkos** [comment]
There is a workaround. When I mount the remote directory with the option `-o uid=1000`:
```
sshfs -o uid=1000 remoteuser@remoteip:/cygdrive mountpoint
```
then cloc works, no errors are reported.

**Comment by AlDanial** [comment]
Ah, that's definitely the preferred solution then.  Thanks for the update.
