### ISSUE TITLE
cloc fails to analyze binutils and sharutils

### ISSUE THREAD

**Issue by andreamattavelli** [AlDanial/cloc#158]
On binutils 2.27 I get the following error:

```bash
$ cloc binutils-2.27
   18600 text files.
   17935 unique files.                                          
Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498.
```

I am on Ubuntu 16.04.1 with cloc version 1.60

EDIT:
cloc crashes also on sharutils 4.15
```bash
$ cloc sharutils-4.15
     670 text files.
     658 unique files.                                          
Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498.
```

**Comment by AlDanial** [comment]
v1.60 is pretty ancient.  Please download 1.72 and try with that.  
https://github.com/AlDanial/cloc/releases/tag/v1.72

Installation is trivial--just run the .pl file from the download.

**Comment by andreamattavelli** [comment]
@AlDanial you're right, it's pretty old. Everything works fine with 1.72!
