### ISSUE TITLE
Add Smalltalk

### ISSUE THREAD

**Issue by krono** [AlDanial/cloc#160]
I'd propose to add Smalltalk:

```
Smalltalk
    filter remove_matches ".*"
    extension st
    3rd_gen_scale 3.8
```

Comments are between double quotes.  
3rd_gen_scale according to given Website.  
Note that Smalltalk also uses `.cs` as extension, but this apparently clashes with C#

**Comment by krono** [comment]
Notes
 *  `".*?"` may be better
 * 3.8 seems low

**Comment by AlDanial** [comment]
The comments--text within double quotes--won't be matched by ``remove_matches`` if they span lines.  I'll need to implement a multiline version of ``remove_matches`` (which isn't hard).  More work is involved in adding another code disambiguator to examine contents of ``.cs`` files and decide if they contain C# or Smalltalk.

Today I'll start with a minimal implementation using just the filter you describe.

The 3rd gen scale factor is pretty notional.  Whether it is 3.8 or 4.2 or whatever shouldn't be significant to anyone.

**Comment by AlDanial** [comment]
Turns out the whole thing was easy--multiline comments, ``.cs`` extension.  Commit 59a0578 should do the trick.

**Comment by krono** [comment]
thanks :)

**Comment by AlDanial** [comment]
Latest commit adds a point on C#/Smalltalk difference if the line ends with a period
