### ISSUE TITLE
Using Cloc within a file.

### ISSUE THREAD

**Issue by azif01** [AlDanial/cloc#163]
Hello all,

Can I use the tool for counting the LoC's within a specific file. I have used it in general so far, where I count the LoC's within a directory or a file at least. But now, I have a specific requirement.

Suppose I have a file name implementation.cpp. So lets say the total lines of code in implementation.cpp is around 2000 but I have a specific part of code which I need to use to Cloc tool at (assume from line 208 to 1200 something). Now i want the summary only for these specific lines. Is there a possibility of doing this using Cloc? 

BR,
Asif

**Comment by AlDanial** [comment]
There's not an automatic way of doing that with cloc.  You'll have to save the desired line range to a separate file and count that.
