### ISSUE TITLE
Unrecognized escape \g

### ISSUE THREAD

**Issue by frozenspider** [AlDanial/cloc#168]
I've installed `cloc` via NPM, and here's what I'm getting:
```
$ cloc . --exclude-dir=target,bin,project,.git --include-lang=Scala,Java
       5 text files.
       5 unique files.
Unrecognized escape \g passed through in regex; marked by <-- HERE in m/(["'])(.*?/)(\*.*?)\g <-- HERE 1.*?(.*?)/ at /d/ProgramFiles/nodejs/node_modules/npm/node_modules/cloc/lib/cloc line 4878.
Unrecognized escape \g passed through in regex; marked by <-- HERE in m/^(.*?)(["'])(.*?/)(\*.*?)\g <-- HERE 1/ at /d/ProgramFiles/nodejs/node_modules/npm/node_modules/cloc/lib/cloc line 4888.
       9 files ignored.
```

It seem that it's caused by this (line 6101 of `cloc` in my `node_modules` dir, and line 6135 in the [latest commit](https://github.com/AlDanial/cloc/blob/de67b464d0bb9d206bd86c642b7e9cd20a5bb4ac/cloc#L6135))
```
    'Java'               => [
                                # separate /* inside quoted strings with two
                                # concatenated strings split between / and *
                                [ 'replace_between_regex', '(["\'])(.*?/)(\*.*?)\g1',
                                  '(.*?)' , '"$1$2$1 + $1$3$1$4"'],
```

**Comment by AlDanial** [comment]
Does this happen for all your Java files or just one?  When I run against ``tests/inputs/Java.java`` it works fine.  If you could post a Java file which triggers this problem, that would be most useful.

**Comment by frozenspider** [comment]
It seems that any Java file causes this. For example, it also happens in empty directory with just [this](https://gist.github.com/frozenspider/822683757bbcf1f1a5e513762a1ca911) file - even if I remove everything but a few characters from it.
It's also worth noticing that I'm Windows 8.1 user.

**Comment by AlDanial** [comment]
I take it you are running the Perl source version, as opposed to the .exe, for Windows?  In that case, which version of Perl is installed on your machine (``perl --version``)?  One simple fix is to comment out the line (wrapped across two physical lines) that starts with ``[ 'replace_between_rexex'``.  Another possible fix is to replace ``\g1`` with ``\\g1`` as Windows may be interpreting the regex differently.  I don't have easy access to a Windows computer otherwise I'd try it.

**Comment by frozenspider** [comment]
```
$ perl --version

This is perl, v5.8.8 built for msys
...
```
Replacing `\g1` with `\\g1` seem to have no effect, but `\\\g1` made the warning go away (with unknown side effects though), and so does commenting out `replace_between_regex` section.
Using compiled windows `.exe` also produces no warning.

**Comment by AlDanial** [comment]
The purpose of that particular line is to catch comment markers inside strings, ie ``"  /*  "`` and separate them into two strings like ``" /`` and ``* "``.  If your input Java files don't have such strings then commenting out the line is the way to go.

The .exe was built with Perl version 5.22.  It is possible 5.8.8 doesn't understand ``\g1``.  If you have the opportunity to install Strawberry Perl on your computer that would give you a powerful, modern version.
