### ISSUE TITLE
LOC is not calculated from C++'s *.CPP files when file extension is uppercase 

### ISSUE THREAD

**Issue by villelaitila** [AlDanial/cloc#177]
.CPP is not included as extension, but it should be, similarly as .cpp. 

.CPP extension is more usual in Windows environments than in Unix. The problem was noticed when running LOC for the code brought from Windows environment. CLOC didn't handle those files at all.

**Comment by AlDanial** [comment]
thanks for the PR, will merge on Friday

**Comment by AlDanial** [comment]
Merged PR #178.
