### ISSUE TITLE
Add cucumber support

### ISSUE THREAD

**Issue by nickrobison** [AlDanial/cloc#180]
It would be awesome if cloc supported [Cucumber](https://cucumber.io/) feature files.

The extension is `.feature`.

Comments are defined using: `#`. As per the [documentation](https://cucumber.io/docs/reference#comments).

A great set of examples are in the diaspora [repository](https://github.com/diaspora/diaspora/tree/master/features).

Thanks!

**Comment by AlDanial** [comment]
Added with commit f9c2e18
