### ISSUE TITLE
Add support for BrightScript

### ISSUE THREAD

**Issue by mikestead** [AlDanial/cloc#181]
This is the language used for Roku development

File extension `.brs`

Comments can be a line prefixed with `REM` or an apostrophe `'`

https://sdkdocs.roku.com/display/sdkdoc/Program+Statements#ProgramStatements-REM

There's some sample code on that same page.

**Comment by AlDanial** [comment]
Am happy to add this but will be a couple of weeks before I can get to any issues.

**Comment by AlDanial** [comment]
BrightScript added with commit abe9eb8

(btw, I'm the happy owner of a Roku device)

**Comment by mikestead** [comment]
@AlDanial Thanks for the update, and for cloc 👍
