### ISSUE TITLE
Support for ignoring based on existing .gitignore file

### ISSUE THREAD

**Issue by MikeWeller** [AlDanial/cloc#182]
Most repos will have a `.gitignore` file with a list of patterns to be ignored from git statuses and operations. It would be useful if cloc could have a `--gitignore` flag (maybe even turned on by default) which would look for these files and automatically exclude files based on the contents.

**Comment by tilmanginzel** [comment]
I think you can already use the `--vcs=git` [option](https://github.com/AlDanial/cloc#Options) to accomplish this.

**Comment by MikeWeller** [comment]
RTFM then, thanks ;)
