### ISSUE TITLE
[UNDEFINED VALUE]Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498

### ISSUE THREAD

**Issue by lsytj0413** [AlDanial/cloc#184]
I use cloc to count the lines of code in my folder ~/.spacemacs.d, and the output is:

# output:
```
    7487 text files.
    6967 unique files.                                          
Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498.
```

# system info:
- OS: gnu/linux ubuntu16.04 TLS
- cloc: installed from apt install cloc

# command:
```
cd ~/.spacemacs.d
cloc .
```

**Comment by AlDanial** [comment]
This sounds like a bug fixed several releases ago.  Please try with v1.72 available at https://github.com/AlDanial/cloc/releases

**Comment by lsytj0413** [comment]
@AlDanial thank you for your help! the v1.72 doesn't have this issue!

**Comment by yoginth** [comment]
Still having it!

**Comment by AlDanial** [comment]
@yoginth :  which version of cloc are you using?  Use
  ``cloc --version``
to find out.  If it is older than 1.74, get 1.74 from https://github.com/AlDanial/cloc/releases/tag/1.74

**Comment by yoginth** [comment]
thanks fixed!
