### ISSUE TITLE
Add support for GraphQL

### ISSUE THREAD

**Issue by frankdugan3** [AlDanial/cloc#186]
Would you consider adding support for GraphQL files?

Extensions are either `.graphql` or `.gql`.
Comments are simple `#` prefixed single lines ([spec](http://facebook.github.io/graphql/#sec-Comments)).

I'm using this custom definition and it seems to work OK:

```
GraphQL
    filter remove_matches ^\s*#
    filter remove_inline #.*$
    extension gql
    extension graphql
    3rd_gen_scale 4.00
```

**Comment by AlDanial** [comment]
GraphQL added with commit 71a43ac.  The definition block you provided was most helpful so thanks for that.
