### ISSUE TITLE
default cloc .

### ISSUE THREAD

**Issue by Kamik423** [AlDanial/cloc#188]
### This is an enhancement request!

Basically every time I use cloc I am in my project and want to see how much code there is. So I type `cloc`, then realizing that it just prints out a help and then typing `cloc .`. Would it be possible to make it do that by default?

**Comment by AlDanial** [comment]
Sure, it would be possible to make it do that by default, but I'm very much against the idea.  I won't implement it.

You could always create your own alias to the cloc command to have it run against ``.``, or edit the source to achieve the same result.  An easy way to do that, by the way, is replace this line
<pre>
die "\n" unless $getopt_success;
</pre>
with
<pre>
push @ARGV, "." unless $getopt_success;
</pre>
(but that obscures some other argument checking).
