### ISSUE TITLE
doesn't work!!!!

### ISSUE THREAD

**Issue by sfinexer** [AlDanial/cloc#195]
doesn't work!!!!
file 1.h in:

file<<"Описание файла конфигурации ###GO"<<"\n\n";

The file is ignored!

**Comment by sfinexer** [comment]
file code  cp1251  !!!

**Comment by AlDanial** [comment]
I'm unable to duplicate the problem.
<pre>
/tmp> echo 'file<<"Описание файла конфигурации ###GO"<<"\n\n";' > 1.h

/tmp> cat 1.h
file<<"Описание файла конфигурации ###GO"<<"\n\n";

/tmp> file 1.h
1.h: UTF-8 Unicode text

/tmp> cloc 1.h
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.73  T=0.01 s (182.0 files/s, 182.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     1              0              0              1
-------------------------------------------------------------------------------
</pre>

Can you attach your file?  I don't know how to set unicode cp1251.

**Comment by sfinexer** [comment]
file<<"РћРїРёСЃР°РЅРёРµ С„Р°Р№Р»Р° РєРѕРЅС„РёРіСѓСЂР°С†РёРё ###GO"<<"\n\n";

http://forex.tiven.ru/GO.h

**Comment by sfinexer** [comment]
http://forex.tiven.ru/GO.h.tar

**Comment by sfinexer** [comment]
The file in archive the link http://forex.tiven.ru/GO.h.tar

**Comment by sfinexer** [comment]
sfinexer@sfinexer:~$ file GO.h
GO.h: ISO-8859 text, with CRLF line terminators
sfinexer@sfinexer:~$ cloc GO.h
bash: cloc: команда не найдена
sfinexer@sfinexer:~$ cloc GO.h
       0 text files.
       0 unique files.                              
       1 file ignored.

**Comment by AlDanial** [comment]
Thanks for making a sample file available.  cloc relies on Perl's "-b" operator to determine whether or not a file is binary, and if it is, it is skipped.  That's what's happening with your file.  You could use cloc's ``--read-binary-files`` option to get around this:

<pre>

/tmp> file GO.h 
GO.h: ISO-8859 text, with CRLF line terminators

/tmp> cloc GO.h 
       0 text files.
       0 unique files.                              
       1 file ignored.

/tmp> cloc --read-binary-files GO.h 
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.73  T=0.01 s (179.2 files/s, 179.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     1              0              0              1
-------------------------------------------------------------------------------
</pre>

**Comment by sfinexer** [comment]
Thanks! Everything works with this parameter.
