### ISSUE TITLE
Cloc 1.64 or 1.72 exe's don't run on Win 10

### ISSUE THREAD

**Issue by JayMarchetti** [AlDanial/cloc#198]
I tried both EXE's on a new Win10 machine and they each just return to the cmd line with nothing output. On my Win7 machine they work fine.

I saw comments on SourceForge regarding this issue which seemed to be considered "fixed" - not so...

Thanks,
Jay

**Comment by AlDanial** [comment]
That's odd because the submitter of https://github.com/AlDanial/cloc/issues/196 is running on Windows 10.  Perhaps there's a policy configuration on your machine that prevents it from running.
