### ISSUE TITLE
Complex regular subexpression recursion limit

### ISSUE THREAD

**Issue by Beyarz** [AlDanial/cloc#199]
C:\Users\beyar>cloc G:\
Can't opendir(G:\System Volume Information): Invalid argument
 at script/cloc-1.72.pl line 3693.
   10491 text files.
   10471 unique files.
Complex regular subexpression recursion limit (32766) exceeded at script/cloc-1.72.pl line 9262.
Counting:  10300

**Comment by AlDanial** [comment]
Fixes for this issue were added after 1.72 were released.  Please try with the latest cloc from git, https://github.com/AlDanial/cloc/raw/master/cloc
