### ISSUE TITLE
Additional language: Forth

### ISSUE THREAD

**Issue by larsbrinkhoff** [AlDanial/cloc#20]
File extensions: 4th, f, for, forth, fr, frt, fth, fs.  [These are supported by GitHub's Linguist.](http://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1018)

Comments:
 - `\` to end of line.
 - `(` to `)` on same line.
 - `(*` starts a multi-line comment ending with `*)`.

Note that the token starting the comment must be surrounded by whitespace.

Links to sample code:
http://github.com/larsbrinkhoff/lbForth/blob/master/kernel.fth
http://github.com/search?q=language%3Aforth+dup+swap&type=Code

**Comment by larsbrinkhoff** [comment]
Rare file extensions: 4, blk, f83, fb, fpm, ft, scr, spf, txt, e4.

**Comment by AlDanial** [comment]
I added support for Forth with many (4th, e4, f83, fb, forth, fpm, fr, frt, ft, fth, rx) of the listed extensions with git commit 121cc5e.

These extensions conflict with Fortran: f, for
This extension conflicts with F#: fs
These extensions (like txt) map to non-code files I'm familiar with: scr, spf

cloc can work with extensions to map to multiple languages but then more work is needed to write a special function that can deduce which of the two or more languages a given file is.  I might revisit that in the future.  Or you could supply the function (see for inspiration cloc's existing subroutines matlab_or_objective_C(), pascal_or_puppet(), Perl_or_Prolog(), et cetera).

**Comment by larsbrinkhoff** [comment]
Thank you!

**Comment by larsbrinkhoff** [comment]
`scr` is just Forth source code without line breaks.  That's why they look strange.

**Comment by AlDanial** [comment]
The integration of your two routines is complete with git commit 88f71e7.

**Comment by larsbrinkhoff** [comment]
Looks good!

**Comment by AlDanial** [comment]
hi Lars, if you have a moment could you respond to the remarks at https://github.com/AlDanial/cloc/issues/103 regarding the use of (* .. *) to denote Forth comments?

**Comment by larsbrinkhoff** [comment]
Yep.
