### ISSUE TITLE
Automatically exclude Go autogenerated files

### ISSUE THREAD

**Issue by andreyvit** [AlDanial/cloc#204]
Let's add an option that ignores autogenerated files in Go language. They have recently standardized on `^// Code generated .* DO NOT EDIT\.$` regular expression found within the first lines of the file, see https://golang.org/s/generatedcode.

Also, if you're interested in making this more general, GitHub Linguist has a large list of battle-tested cases, all of which can be found under [github.com/github/linguist/.../generated.rb](https://github.com/github/linguist/blob/473282d/lib/linguist/generated.rb)

**Comment by AlDanial** [comment]
This is an interesting idea.  I'll add support for it in the near future.

**Comment by AlDanial** [comment]
Just letting you know I haven't forgotten about this.  My plan was to close out remaining issues and make a late July release of 1.74 but that release got dragged out until today.

**Comment by AlDanial** [comment]
cloc had an existing switch, <tt>--no-autogen</tt>, to ignore autogenerated files (such as the ubiquitous <tt>configure</tt> script) and I rolled this feature in with that.  Therefore cloc doesn't automatically ignore Go autogenerated files but instead you have to give it <tt>--no-autogen</tt> to do so.  Here's a demo using the new test files added with this commit:

<pre>
> cloc --by-file tests/inputs/hello_app*.go
       2 text files.
       2 unique files. 
       0 files ignored.

github.com/AlDanial/cloc v 1.75  T=0.01 s (297.2 files/s, 10254.3 lines/s)
------------------------------------------------------------------------------------
File                                             blank        comment           code
------------------------------------------------------------------------------------
tests/inputs/hello_app_autogen.go                    5             19             11
tests/inputs/hello_app.go                            5             18             11
------------------------------------------------------------------------------------
SUM:                                                10             37             22
------------------------------------------------------------------------------------
</pre>

Rerun, this time ignoring the autogenerated file:

<pre>
> cloc --no-autogen --by-file tests/inputs/hello_app*.go
       2 text files.
       2 unique files.
       1 file ignored.

github.com/AlDanial/cloc v 1.75  T=0.01 s (162.2 files/s, 5515.0 lines/s)
---------------------------------------------------------------------------------------
File                                     blank        comment           code
---------------------------------------------------------------------------------------
tests/inputs/hello_app.go                    5             18             11
---------------------------------------------------------------------------------------
</pre>
