### ISSUE TITLE
Consider dropping Russian and Ukrainian translations

### ISSUE THREAD

**Issue by light2yellow** [AlDanial/cloc#207]
Russian translation leads to the website that has some other translation (Bulgarian or Serbian? definitely Slavic).
Ukrainian translation is just a Google Translate mess.

In case Russian translation should lead to http://carrrsmag.com/blog/cloc.html (link from Acknowledgements section), then it's just a Google Translate mess too.

These are not translations. If one wants to use Google Translate, one can do it on his/her own.

**Comment by light2yellow** [comment]
Actually, the link under "Russian" looks a lot like Slovakian language, as I know Czech and Slovakian is very similar. Did not cracked it from the first try, heh :) Though I cannot tell whether it's Google Translate'd or not. So, there's also an error in the Acknowledgements section.

**Comment by AlDanial** [comment]
I took both Russian and Ukrainian links out.  I'm tempted to remove all translation links as I have no clear way to verify them, but suspect someone somewhere gets some benefit.
