### ISSUE TITLE
--vcs=git only works in '.' directory

### ISSUE THREAD

**Issue by SaphuA** [AlDanial/cloc#208]
This works:

`cloc-1.72.exe --vcs=git .`

This does not:

`cloc-1.72.exe --vcs=git c:\Git\Project\`

It gives the error: `fatal: Not a git repository (or any of the parent directories): .git` that is also displayed when running `git ls-files` on a non-git directory.

**Comment by SaphuA** [comment]
This works:

`cloc-1.72.exe --vcs=git .`

This does not:

`cloc-1.72.exe --vcs=git c:\Git\Project\`

**Comment by AlDanial** [comment]
This behavior is by design.  From the usage instructions:
<pre>
        --vcs=<VCS>               Invoke a system call to <VCS> to obtain a list of
                             files to work on.  If <VCS> is 'git', then will
                             invoke 'git ls-files' to get a file list and
                             'git submodule status' to get a list of submodules
                             whose contents will be ignored.  If <VCS> is 'svn'
                             then will invoke 'svn list -R'.  The primary benefit
                             is that cloc will then skip files explicitly
                             excluded by the versioning tool in question,
                             ie, those in .gitignore or have the svn:ignore
                             property.
                             Alternatively <VCS> may be any system command
                             that generates a list of files.
                             <b>Note:  cloc must be in a directory which can read
                             the files as they are returned by <VCS>.</b>  cloc will
                             not download files from remote repositories.
                             'svn list -R' may refer to a remote repository
                             to obtain file names (and therefore may require
                             authentication to the remote repository), but
                             the files themselves must be local.
</pre>
