### ISSUE TITLE
Some used regex functionality is deprecated

### ISSUE THREAD

**Issue by sdicke** [AlDanial/cloc#209]
When I ran cloc recently, the following message was printed: "Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/^(.*?){ <-- HERE [^$]/ at /usr/bin/cloc line 4850."

**Comment by AlDanial** [comment]
Thanks for the heads up.  6c05b63 should run cleanly.
