### ISSUE TITLE
Add support for Idris

### ISSUE THREAD

**Issue by bonds** [AlDanial/cloc#210]
File extensions associated with the language: **idr**
A description of how comments are defined: lines starting with double-dash "**--**" or with three bars "**|||**" 
Links to sample code:
* https://github.com/ziman/lightyear/blob/master/Lightyear/Combinators.idr
* https://github.com/pheymann/specdris/blob/master/src/Specdris/SpecIO.idr

Also, there's "Literate Idris" which has the "**lidr**" extension and everything is a comment *except* lines starting with "**>**", see http://docs.idris-lang.org/en/latest/tutorial/miscellany.html

**Comment by AlDanial** [comment]
1a5e592 adds Idris, Literate Idris

**Comment by bonds** [comment]
Thanks!

**Comment by pascalpoizat** [comment]
see #316 for a proposition of extension to new comments.
