### ISSUE TITLE
Support for TOML

### ISSUE THREAD

**Issue by curio77** [AlDanial/cloc#211]
Hello,

I'd like to see support for [TOML](https://github.com/toml-lang/toml) configuration files:

  - extension: `.toml`
  - comments: `# ...`, unless inside a double-quoted string
  - samples can be found [here](https://github.com/toml-lang/toml#example)

Thanks!

**Comment by AlDanial** [comment]
994bfca adds TOML support, with the exception of recognizing quoted ``#`` -- cloc has a major limitation in not understanding comment markers within quotes.

**Comment by curio77** [comment]
That was fast, thank you very much!
