### ISSUE TITLE
Use of deprecated File::Glob::glob()

### ISSUE THREAD

**Issue by sjoubert** [AlDanial/cloc#214]
Hi,

Here is my environment:
* Debian buster/testing
* cloc 1.70
* perl 5.26.0

and I get the following deprecation warnings:
`File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead. at /usr/bin/cloc line 4281.`

Thanks.

**Comment by AlDanial** [comment]
thanks!
