### ISSUE TITLE
update of chocolatey package

### ISSUE THREAD

**Issue by fforjan** [AlDanial/cloc#217]
Hey guys, are you planning to update the chocolatey package ?

**Comment by fforjan** [comment]
Just to explain the reason, goal is to use this to quickly generate a report during some of our build about stats of source code.

my rule number one is no manual action, so a TFS build definition is doing the job for us.
my rule number two is no remote access to our build agents. We are preparing them with TFS build agent AND chocolatey. Any tools used during build must be deployed via a chocolatey package...

**Comment by fforjan** [comment]
Well..  on your main page you got  : 
Install via package manager
(...)
choco install cloc                     # Windows with Chocolatey

So according to https://chocolatey.org/packages/CLOC,
Those 2 guys are the maintainer : 
AnthonyMastrean
tshak

If you don't know them then I will try to contact them

**Comment by AlDanial** [comment]
Yes, and two lines below the "choco install cloc" it says "Note: I don't control any of these packages."

Looking through the logs, Anthony sent a pull request in May 2016 to notify me of the chocolatey package he created.  I will reach out to him--but I will wait until this Friday when I plan to release v1.74.

**Comment by fforjan** [comment]
Arf.. I'm the one who don't read enough :( sorry

**Comment by AnthonyMastrean** [comment]
Oh, hey, we are _way_ behind! You can always use the "Contact Maintainers" link on the Chocolatey package page. I think most packages are maintained by folks _other_ than the authors, although it's always awesome to get an author onboard.

**Comment by AnthonyMastrean** [comment]
All recent version submitted and awaiting moderation. https://chocolatey.org/packages/cloc

**Comment by fforjan** [comment]
Thanks Anthony !
