### ISSUE TITLE
inefficient,--diff,cloc just uses  one cpu core to run 

### ISSUE THREAD

**Issue by freyzheng** [AlDanial/cloc#22]
system envirenment:LINUX
CLOC version:1.56 
CPU core: 8

QUESTION:
when i use the cloc.pl tool to get difference between tows source codes,
cloc tool just use one cpu core to run .
As follows：
![1ff57782-91e5-4144-b81a-78a00010876e](https://cloud.githubusercontent.com/assets/10445167/10930042/9ffeb1f0-82f5-11e5-92be-1a528e5a9cd0.png)

since inefficiency of using one cpu core,cloc tool takes me too much time to wait the result.

what should i do to increase the efficiency of cloc tool.

**Comment by AlDanial** [comment]
I agree --diff can be terribly slow, esp for substantial projects.

I don't have experience writing multithreaded Perl so it may be quite some time before I am able to spread the diff work across multiple cores.

**Comment by freyzheng** [comment]
I can understand.
Thanks for your reply.

**Comment by stsnel** [comment]
I've been working on a version of cloc which uses multiple processes for counts and diffs. The code is in the multiproc branch of [my fork](https://github.com/stsnel/cloc). It works okay on the Linux systems I've tried, but I haven't tested it on other OSes yet.

If anyone else is interested in trying it out before I send a PR that would be great.

**Comment by AlDanial** [comment]
I took a look (but haven't run it yet); quite a bit of work there, thanks for taking this on.  I'll need to spend time with Parallel::ForkManager to appreciate the nuances.

**Comment by AlDanial** [comment]
@stsnel :  I'm finally ready to devote time to supporting Parallel::ForkManager.  Can you git pull from my master to bring your fork up-to-date?

**Comment by stsnel** [comment]
@AlDanial : great :)  I'll update my branch and check that the parallel code still works with the new cloc version. I expect I'll be able to submit a PR in a couple of days.

**Comment by AlDanial** [comment]
@stsnel : Take your time with the PR; the holiday next week (here in the US) will keep me offline for a while.

**Comment by AlDanial** [comment]
With the latest commit, use ``--processes=4`` for example to use 4 cores.
