### ISSUE TITLE
mkdir error on count-and-diff 

### ISSUE THREAD

**Issue by eduwushu** [AlDanial/cloc#220]
When using count-and-diff option on two paths on my d: drive and specifying an output file like --out=diff.txt the commands fails with:
"mkdir C:\Users\anonymous\Downloads\editordiff.d:\: Invalid argument; The filename, directory name, or volume label syntax is incorrect at script/cloc line 4099.
Seems in this case cloc is using internally an incorrect output file name with .d:\ appended to the end

**Comment by AlDanial** [comment]
I was able to duplicate the problem.  I'll have a fix later this week.

**Comment by AlDanial** [comment]
This should work cleanly now.  The fix is in the development branch and the just-released 1.74 package.

**Comment by eduwushu** [comment]
Awesome! Thank you!
