### ISSUE TITLE
Take ownership of the Chocolatey package

### ISSUE THREAD

**Issue by AnthonyMastrean** [AlDanial/cloc#222]
Packages published by the package author can become "trusted packages". They skip manual moderation and get just automated moderation. This means that updates are available faster for the part of your community that uses Chocolatey. I'm a moderator, so I could ensure that this package earns that status. 

I'd be happy to hand over the package files and provide a quick guide. Here is another [handoff](https://github.com/NickeManarin/ScreenToGif-Chocolatey) that I did recently.

----
https://chocolatey.org/packages/cloc

**Comment by AlDanial** [comment]
I appreciate the offer, and the assistance, but the Windows world is a challenge for me.  I don't own anything that runs Windows.  To make the Windows cloc exe for releases, I rent an AWS instance for an hour or so.  Definitely not ideal.

**Comment by AnthonyMastrean** [comment]
No problem, just wanted to throw it out there! You shouldn't have to rent an AWS instance... modern CI tools like [AppVeyor](https://www.appveyor.com/) seem to provide free resources to open source projects.
