### ISSUE TITLE
Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498.

### ISSUE THREAD

**Issue by wakatta** [AlDanial/cloc#225]
Keep getting: _Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498._

I'm using Ubuntu 16.04 LTS, installed cloc with 'apt'.

Used it like this from command line:
`$ cloc dirname/ `

**Comment by AlDanial** [comment]
This problem was fixed quite a while ago.  Please download the latest version from
https://github.com/AlDanial/cloc/releases
