### ISSUE TITLE
Add support to RAML

### ISSUE THREAD

**Issue by rsrdesarrollo** [AlDanial/cloc#227]
* File extensions associated with the language: RAML
* A description of how comments are defined: Same as YAML
* Links to sample code: https://raml.org/developers/raml-200-tutorial

**Comment by cybercussion** [comment]
I don't see RAML as part of the output still, was this fixed?

**Comment by AlDanial** [comment]
RAML was added more than two years ago.  Perhaps you need a newer version of cloc: https://github.com/AlDanial/cloc/releases
