### ISSUE TITLE
Add support for AsciiDoc

### ISSUE THREAD

**Issue by ineuwirth** [AlDanial/cloc#229]
Please add support for the widely-used AsciiDoc markup language.

1. Extensions: `.asciidoc`, `.adoc` are the recommended extensions, see http://asciidoctor.org/docs/asciidoc-recommended-practices/#document-extension (however AsciiDoc doesn't require specific extension)
2. Comments: `//` for single line and `////`...`////` for multi-line comments, see http://asciidoctor.org/docs/user-manual/#comments
3. Sample file: https://github.com/asciidoctor/asciidoctor/blob/master/man/asciidoctor.adoc

References:
* http://www.methods.co.nz/asciidoc/
* http://asciidoctor.org/docs/user-manual/

**Comment by AlDanial** [comment]
commit 60adf03 supports AsciiDoc

**Comment by ineuwirth** [comment]
Thank you @AlDanial

**Comment by virgo47** [comment]
I just installed this tool using NPM and tried it on my project with AsciiDoc. Eventually Google pointed me here. I see it's committed, but after the release of the most recent version 1.74. When can we expect new release, please?
Great tool BTW, I believe I used it as EXE years ago - at least the output seems the same. Small, fast, useful.

**Comment by AlDanial** [comment]
I'm hoping to release 1.76 before the end of February (2018).

**Comment by AlDanial** [comment]
v1.76 with support for AsciiDoc is released: https://github.com/AlDanial/cloc/releases
