### ISSUE TITLE
Unable to add custom language 

### ISSUE THREAD

**Issue by pwaller24** [AlDanial/cloc#230]
When attempting to add a custom language I always get:

Unexpected data line 5 of lang.txt:
        extension pls

lang.txt looks like this:

PL/SQL
    filter call_regexp_common C
    filter remove_matches ^\s*--
    filter remove_inline --.*$
	extension pls
    3rd_gen_scale 2.29

Wondering what I am doing incorrectly.

**Comment by AlDanial** [comment]
What you're doing is exactly right and it works for me.  The ``lang.txt`` file needs to be indented properly but that may have been taken out by your formatting.  Here's what I'm doing:
<pre>
> cat lang.txt 
PL/SQL
    filter call_regexp_common C
    filter remove_matches ^\s*--
    filter remove_inline --.*$
    extension pls
    3rd_gen_scale 2.29
</pre>
I tell cloc to create an SQL file ``j.pls`` containing the result of a line count of itself:
<pre>
> cloc --sql=j.pls cloc
       1 text file.
       1 unique file.                              
       0 files ignored.
</pre>
Then I tell cloc to count this new file using the custom definition:
<pre>
> cloc --read-lang-def lang.txt j.pls
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.75  T=0.01 s (135.1 files/s, 2566.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
PL/SQL                           1              1              0             18
-------------------------------------------------------------------------------
</pre>

**Comment by pwaller24** [comment]
Thanks for the information.  It appears that Notepad++ was putting in tabs instead of spaces.  I have been able to successfully use a custom language file.
