### ISSUE TITLE
Recursion limit hit on 'Twitter Finagle' code.

### ISSUE THREAD

**Issue by ramanawithu** [AlDanial/cloc#231]
I got the following warnings while counting Twitter Finagle code, hope it helps as test case.

https://github.com/twitter/finagle

    1776 text files.
    1721 unique files.                                          
**Complex regular subexpression recursion limit (32766) exceeded at /home/bhavani/sw/bin/cloc line 9619.
Complex regular subexpression recursion limit (32766) exceeded at /home/bhavani/sw/bin/cloc line 9619.**
     291 files ignored.

github.com/AlDanial/cloc v 1.74  T=2.77 s (535.2 files/s, 63797.6 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Scala                          1318          23525          25908         112574
Java                            103           1729           1728           8380
Ruby                             12            172             37            735
Markdown                         11            125              0            458
Lua                               1             74            105            265
Python                            4             41             65            226
HTML                              7             25              0            219
JSON                             16              1              0            185
CSS                               2             27              7            119
Bourne Again Shell                3             18              1             88
R                                 1             17              6             68
Bourne Shell                      2             11              0             30
SQL                               3              0              0             17
INI                               1              2              2              9
make                              1              4              1              9
--------------------------------------------------------------------------------
SUM:                           1485          25771          27860         123382
--------------------------------------------------------------------------------

**Comment by AlDanial** [comment]
The warning is caused by these files:
<pre>
finagle-base-http/src/test/scala/com/twitter/finagle/http/codec/HttpDtabTest.scala
finagle-core/src/test/scala/com/twitter/finagle/NameTreeParsersTest.scala
</pre>
both of which have ``/*`` embedded in strings.  This is cloc's biggest weakness:  not being able to identify strings and skip these when looking for comments.

**Comment by AlDanial** [comment]
Ref #245, use the new ``--strip-str-comments`` switch introduced with 01ace37 in the development branch.  Works for me.
