### ISSUE TITLE
ProGuard files are detected as Prolog

### ISSUE THREAD

**Issue by vbauer** [AlDanial/cloc#232]
It looks like a problem for Android projects

Details: https://www.guardsquare.com/en/proguard

**Comment by AlDanial** [comment]
The .pro extension is problematic since it maps to 4 languages in cloc already--adding ProGuard will be 5.  I'll have to figure out a way to distinguish its contents from the others, will take a while.

**Comment by vbauer** [comment]
Thank you very much!
