### ISSUE TITLE
summary is missing in --json or --yaml under "output options"

### ISSUE THREAD

**Issue by ramkumar-hgst** [AlDanial/cloc#238]
while running the tool with --json or --yaml as mentioned in "output options" the summary is missing . Any idea why summary is missing? Any plans to implement this feature?

**Comment by AlDanial** [comment]
An oversight; I'll add the sums for YAML and JSON later this week.

**Comment by AlDanial** [comment]
I went to add the summary and was surprised to see they are already there, under "SUM".
Here's proof:

<pre>
> cloc --json --out results.json tests/inputs/hello*                    
       9 text files.
       9 unique files.                              
       0 files ignored.
Wrote results.json
> cloc --yaml --out results.yaml tests/inputs/hello*
       9 text files.
       9 unique files.                              
       0 files ignored.
Wrote results.yaml
</pre>

And a short Python program to read the YAML and JSON files and print them out:
<pre>
> cat dump.py
#!/usr/bin/python3
import yaml
import json
print(yaml.load(open('results.json')))
print(json.load(open('results.json')))

> python3 dump.py
{'header': {'cloc_url': 'github.com/AlDanial/cloc', 'cloc_version': '1.75', 'elapsed_seconds': 0.00845503807067871, 'n_files': 9, 'n_lines': 174, 'files_per_second': 1064.45410709754, 'lines_per_second': 20579.4460705524, 'report_file': 'results.json'}, 'RAML': {'nFiles': 1, 'blank': 5, 'comment': 3, 'code': 62}, 'Brainfuck': {'nFiles': 1, 'blank': 1, 'comment': 3, 'code': 24}, 'Pascal': {'nFiles': 2, 'blank': 2, 'comment': 9, 'code': 10}, 'Kotlin': {'nFiles': 1, 'blank': 0, 'comment': 3, 'code': 9}, 'PL/I': {'nFiles': 1, 'blank': 0, 'comment': 7, 'code': 5}, 'Fortran 90': {'nFiles': 1, 'blank': 0, 'comment': 3, 'code': 4}, 'Fortran 77': {'nFiles': 1, 'blank': 0, 'comment': 6, 'code': 4}, 'Lua': {'nFiles': 1, 'blank': 3, 'comment': 9, 'code': 2}, 'SUM': {'blank': 11, 'comment': 43, 'code': 120, 'nFiles': 9}}
{'header': {'cloc_url': 'github.com/AlDanial/cloc', 'cloc_version': '1.75', 'elapsed_seconds': 0.00845503807067871, 'n_files': 9, 'n_lines': 174, 'files_per_second': 1064.45410709754, 'lines_per_second': 20579.4460705524, 'report_file': 'results.json'}, 'RAML': {'nFiles': 1, 'blank': 5, 'comment': 3, 'code': 62}, 'Brainfuck': {'nFiles': 1, 'blank': 1, 'comment': 3, 'code': 24}, 'Pascal': {'nFiles': 2, 'blank': 2, 'comment': 9, 'code': 10}, 'Kotlin': {'nFiles': 1, 'blank': 0, 'comment': 3, 'code': 9}, 'PL/I': {'nFiles': 1, 'blank': 0, 'comment': 7, 'code': 5}, 'Fortran 90': {'nFiles': 1, 'blank': 0, 'comment': 3, 'code': 4}, 'Fortran 77': {'nFiles': 1, 'blank': 0, 'comment': 6, 'code': 4}, 'Lua': {'nFiles': 1, 'blank': 3, 'comment': 9, 'code': 2}, 'SUM': {'blank': 11, 'comment': 43, 'code': 120, 'nFiles': 9}}
</pre>

Both files have a <tt>SUM</tt> entry.

**Comment by ramkumar-hgst** [comment]
Summary is missing. Please see the below output.
perl cloc-1.74.pl --json --diff --git 5b33c48ab5700493905c8f036ac5847b7c81672b 502b67b38dff378c00b9c951d4d6f98388f289aa

{"header" : {
  "cloc_url"           : "github.com/AlDanial/cloc",
  "cloc_version"       : "1.74",
  "elapsed_seconds"    : 0.707149982452393,
  "n_files"            : 7,
  "n_lines"            : 3747,
  "files_per_second"   : 9.89889015583941,
  "lines_per_second"   : 5298.73448770432},
 "added" : {
  "YAML" : {
    "blank" : "0",
    "nFiles" : "0",
    "code" : "3",
    "comment" : "0"
  },
  "JSON" : {
    "blank" : "0",
    "nFiles" : "0",
    "comment" : "0",
    "code" : "0"
  },
  "Python" : {
    "comment" : "0",
    "code" : "8",
    "nFiles" : "0",
    "blank" : "1"
  }
  },
 "same" : {
  "YAML" : {
    "blank" : "0",
    "nFiles" : "0",
    "code" : "258",
    "comment" : "5"
  },
  "JSON" : {
    "blank" : "0",
    "nFiles" : "0",
    "comment" : "0",
    "code" : "95"
  },
  "Python" : {
    "comment" : "867",
    "code" : "2500",
    "nFiles" : "0",
    "blank" : "0"
  }
  },
 "modified" : {
  "YAML" : {
    "blank" : "0",
    "nFiles" : "2",
    "code" : "2",
    "comment" : "0"
  },
  "JSON" : {
    "blank" : "0",
    "nFiles" : "2",
    "comment" : "0",
    "code" : "7"
  },
  "Python" : {
    "comment" : "0",
    "code" : "1",
    "nFiles" : "3",
    "blank" : "0"
  }
  },
 "removed" : {
  "YAML" : {
    "blank" : "0",
    "nFiles" : "0",
    "code" : "0",
    "comment" : "0"
  },
  "JSON" : {
    "blank" : "0",
    "nFiles" : "0",
    "comment" : "0",
    "code" : "0"
  },
  "Python" : {
    "comment" : "0",
    "code" : "0",
    "nFiles" : "0",
    "blank" : "0"
  }
  }
}
