### ISSUE TITLE
summary is missing for --json or --yaml format along with "--diff --git" 

### ISSUE THREAD

**Issue by ramkumar-hgst** [AlDanial/cloc#239]
Please see the below output the summary is missing. But for the same comand without --json or --yaml we are getting the summary. 

perl cloc-1.74.pl --json --diff --git 5b33c48ab5700493905c8f036ac5847b7c81672b 502b67b38dff378c00b9c951d4d6f98388f289aa

{"header" : {
"cloc_url" : "github.com/AlDanial/cloc",
"cloc_version" : "1.74",
"elapsed_seconds" : 0.707149982452393,
"n_files" : 7,
"n_lines" : 3747,
"files_per_second" : 9.89889015583941,
"lines_per_second" : 5298.73448770432},
"added" : {
"YAML" : {
"blank" : "0",
"nFiles" : "0",
"code" : "3",
"comment" : "0"
},
"JSON" : {
"blank" : "0",
"nFiles" : "0",
"comment" : "0",
"code" : "0"
},
"Python" : {
"comment" : "0",
"code" : "8",
"nFiles" : "0",
"blank" : "1"
}
},
"same" : {
"YAML" : {
"blank" : "0",
"nFiles" : "0",
"code" : "258",
"comment" : "5"
},
"JSON" : {
"blank" : "0",
"nFiles" : "0",
"comment" : "0",
"code" : "95"
},
"Python" : {
"comment" : "867",
"code" : "2500",
"nFiles" : "0",
"blank" : "0"
}
},
"modified" : {
"YAML" : {
"blank" : "0",
"nFiles" : "2",
"code" : "2",
"comment" : "0"
},
"JSON" : {
"blank" : "0",
"nFiles" : "2",
"comment" : "0",
"code" : "7"
},
"Python" : {
"comment" : "0",
"code" : "1",
"nFiles" : "3",
"blank" : "0"
}
},
"removed" : {
"YAML" : {
"blank" : "0",
"nFiles" : "0",
"code" : "0",
"comment" : "0"
},
"JSON" : {
"blank" : "0",
"nFiles" : "0",
"comment" : "0",
"code" : "0"
},
"Python" : {
"comment" : "0",
"code" : "0",
"nFiles" : "0",
"blank" : "0"
}
}
}

**Comment by AlDanial** [comment]
OK I see now, the section is missing when using ``--diff``-- that wasn't clear with your original post.  Anyway please test the fix in the most recent commit.

**Comment by ramkumar-hgst** [comment]
Thanks for the quick fix. The summary is available now.
