### ISSUE TITLE
I'm not able to access the files in zip file.

### ISSUE THREAD

**Issue by praful-dhabekar** [AlDanial/cloc#242]
I'm using
`cloc Study-Material.zip` to access the files which are in 

> Study-Material.zip

 and

 I'm getting following error I'm attaching the screenshots.
![screenshot 20](https://user-images.githubusercontent.com/23056780/32831095-3cd0d9b6-ca1d-11e7-8554-21913bc69a90.png)

**Comment by AlDanial** [comment]
As explained here https://github.com/AlDanial/cloc#compressed_arch, cloc needs an existing command-line capable way of expanding zip files.  There is no standard utility to do this on Windows.  Which utility do you use to expand zip files right now?

**Comment by AlDanial** [comment]
See also https://github.com/AlDanial/cloc/issues/93 on how to use the free 7zip (http://www.7-zip.org/) program with cloc.
