### ISSUE TITLE
Add language Oracle PL/SQL

### ISSUE THREAD

**Issue by monty241** [AlDanial/cloc#246]
The Oracle RDBMS platform provides traditional SQL (*.sql, maybe even *.viw and *.ddl files) with PL/SQL, a procedural extension for SQL.

Over a large number of years Oracle propagates various file name patterns in standards, but these I find most often:

- *.bod: package body
- *.spc : package specification
- *.fnc: function
- *.prc: procedure
- *.trg: database trigger

Some sample pieces of code: [Oracle PL/SQL](https://docs.oracle.com/cd/B10500_01/appdev.920/a96624/a_samps.htm)
Code in the public: [our company](http://www.invantive.nl/over-invantive/nieuws/entryid/1003/sneller-en-beter-relaties-invoeren-in-je-crm-systeem-invantive-estate) and [our company 2](http://www.invantive.com/about-invantive/news/entryid/1004/using-gravatarcom-with-oracle-plsql-in-invantive-vision).
I've added also some simple but large other objects.

**Comment by monty241** [comment]
[bubs#taken.txt](https://github.com/AlDanial/cloc/files/1532871/bubs.taken.txt)

[bubs_tak_ard.txt](https://github.com/AlDanial/cloc/files/1532913/bubs_tak_ard.txt)

[bubs$taken-body.txt](https://github.com/AlDanial/cloc/files/1532877/bubs.taken-body.txt)

[bubs$taken-spec.txt](https://github.com/AlDanial/cloc/files/1532872/bubs.taken-spec.txt)

**Comment by AlDanial** [comment]
I didn't follow the purpose of the four ``bub.*`` files since their extensions don't map to the five you listed but took one of the files, ``bub_tak_ard.txt`` and renamed it with ``.prc`` to use for testing.

**Comment by monty241** [comment]
@AlDanial thanks for adding them. The bubs* I could only add as txt, since the original extensions were forbidden by github :-)
