### ISSUE TITLE
Add support for fish shell

### ISSUE THREAD

**Issue by Konstruktionist** [AlDanial/cloc#249]
I've tried the `cloc --write-lang-def=my_definitions.txt`  
`cloc --read-lang-def=my_definitions.txt` route, but the additions I made are not accepted. I get the cloc usage page.

The fish definitions I added were:

```
Fish Shell
    filter remove_matches ^\s*#
    filter remove_inline #.*$
    extension fish
    script_exe fish
    3rd_gen_scale 3.81
    end_of_line_continuation \\$
```

The settings I copied from the zsh definitions and placed them at the end of the file.

for an example of a fish script: https://github.com/Konstruktionist/fish/blob/master/conf.d/git_helpers.fish

for info about fish:
https://fishshell.com

**Comment by AlDanial** [comment]
You did everything correctly except, I suspect, giving cloc an input to count (one or more files or directories).  I copied your definition and was successful with ``cloc --read-lang-def=my_definitions.txt testdir``.

In any event, I just did commit 20254a7 which adds Fish Shell support

**Comment by Konstruktionist** [comment]
That was fast. Thanks
