### ISSUE TITLE
Counting Linux source code broken.

### ISSUE THREAD

**Issue by jmeasow** [AlDanial/cloc#250]
~/ws$ cloc linux-source-4.4.0/
   53655 text files.
   51580 unique files.                                          
Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498.
~/ws$ 

~/ws$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"

**Comment by AlDanial** [comment]
This duplicates earlier closed issues (eg #225).  Your version of cloc is a bit old as this bug has been fixed a ways back.  Newer releases available at https://github.com/AlDanial/cloc/releases.
