### ISSUE TITLE
Issue if target directory has spaces

### ISSUE THREAD

**Issue by xxMUROxx** [AlDanial/cloc#254]
## Aim

I want to count a directory that has spaces within the name

## Commands with issues

    cloc "directory with spaces"
    cloc 'directory with spaces'

## Output

    Unable to read:  directory
    Unable to read:  with
    Unable to read:  spaces

## Workaround

    cd into "directory with spaces"
    cloc .

## Suggestion

Make that `cloc "directory with spaces"` handles the string within the quotes as single not multiple directories.

## Environment

|version|has bug|behavior|
|---|---|---|
|v1.74|yes|Treats `directory with spaces` as 3 directories
|v1.64|no|Treats `directory with spaces` as 1 directory
  
### Remarks
Furthermore I have tested something. If all 3 directories `directory`, `with`, `spaces` exists, then only `spaces` is count

**Comment by AlDanial** [comment]
Which operating system are you on?  I'm unable to duplicate this problem on Linux; there it works well:
<pre>
> mkdir 'a b'
> cp cloc-1.74.pl 'a b'
> ls 'a b'
cloc-1.74.pl*
> cloc 'a b'
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.75  T=0.11 s (9.0 files/s, 109845.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Perl                             1            787           1292          10059
-------------------------------------------------------------------------------
</pre>

Another possible work-around for you is to prefix spaces with backslash:
<tt>cloc directory\ with\ spaces</tt>

**Comment by Trilarion** [comment]
Operating system is Windows. At least there I have the issue too.

**Comment by AlDanial** [comment]
I'm also unable to duplicate the problem on Windows.  Both the v1.74 exe and source version work:

**Comment by AlDanial** [comment]
The screenshot jpg didn't attach, here's the text I see in my cmd window:
<pre>
C:\Users\IEUser>cloc-1.74.pl "a b"
       1 text file.
       1 unique file.
       1 file ignored.

github.com/AlDanial/cloc v 1.74  T=0.11 s (9.1 files/s, 3626.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                1             79             35            285
-------------------------------------------------------------------------------

C:\Users\IEUser>.\cloc-1.74_x86.exe "a b"
       1 text file.
       1 unique file.
       1 file ignored.

github.com/AlDanial/cloc v 1.74  T=0.50 s (2.0 files/s, 798.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                1             79             35            285
-------------------------------------------------------------------------------
</pre>

(The directory <tt>"a b"</tt> contains a copy of the file <tt>cloc\tests\inputs\aa\bb\cc\plasma.c</tt>)

**Comment by Trilarion** [comment]
Maybe try with the Powershell and with a full path including back slashes.

**Comment by xxMUROxx** [comment]
@AlDanial it works with the powershell but on my PC not with cmd.
OS: Windows 1709 Build 16299.125

**Comment by AlDanial** [comment]
@xxMUROxx which version of cloc are you running?  source (`cloc-1.74.pl``)?  64 bit exe (`cloc-1.74.exe``)? 32 bit exe (``cloc-1.74_x86.exe``)?

If you are running the 64 bit exe, try the 32 bit in cmd.

**Comment by xxMUROxx** [comment]
@AlDanial true, I am using `x64`. The `x86` works

**Comment by AlDanial** [comment]
I deleted the 64 bit exe from the releases area.
