### ISSUE TITLE
Search for specific extensions within a directory

### ISSUE THREAD

**Issue by johnnycopperstone** [AlDanial/cloc#256]
Is it possible to use `cloc` to search for specific extensions within an entire directory? I'd like to make a distinction between different Javascript files we've got.

As an example:

`cloc src/**/*.web.js`
`cloc src/**/*.mobile.js`

**Comment by AlDanial** [comment]
See <tt>--match-f</tt> in https://github.com/AlDanial/cloc#Options
<pre>
cloc --match-f='\.mobile\.js' src/
cloc --match-f='\.web\.js' src/
</pre>
Also throw in <tt>--by-file</tt> to convince yourself it it picking up the right files.

**Comment by johnnycopperstone** [comment]
Thanks @AlDanial was missing the appendage of the dir file at the end.
