### ISSUE TITLE
Some python files not counted

### ISSUE THREAD

**Issue by owillebo** [AlDanial/cloc#258]
I have Python files holding only a doc string, i.e. holding only;

'''
.. GAIUS-test
   recurse: True
'''

These files are not counted.

If I append a line holding okko=5 then the files are included.

**Comment by AlDanial** [comment]
I'm unable to duplicate this problem.  My theory is the doc string contains UTF-16 characters which might cause the file to be interpreted as binary.  (cloc uses Perl's ``-b`` operator, which isn't that smart, to determine whether a file is text or binary).  Try running with the ``--read-binary`` switch.

**Comment by owillebo** [comment]
I did some more troubleshooting and found that the uniqueness functionality
is the cause. Case closed. Thanks for your help
