### ISSUE TITLE
Add Dockerfile variants support

### ISSUE THREAD

**Issue by b1f6c1c4** [AlDanial/cloc#264]
In (classical) [multistage](https://docs.docker.com/engine/userguide/eng-image/multistage-build/#before-multi-stage-builds) docker build, we have `Dockerfile.build`, `Dockerfile.test`, `Dockerfile`, etc.

Currently, `cloc` can understand `Dockerfile` only, but not the variants. `Dockerfile.build` is detected as `NAnt script`, while `Dockerfile.test` is ignored. In my opinion, it would be better to check if the file name contains `\bDockerfile\b`, not `^Dockerfile$`.

**Comment by AlDanial** [comment]
I added <tt>Dockerfile.build</tt> and <tt>Dockerfile.test</tt>, but am reluctant to make it match a the more general regex; I can envision it inadvertently matching README's, HTML files, etc.
