### ISSUE TITLE
--Diff not working on two directories if there are spaces in directory name

### ISSUE THREAD

**Issue by mr2001** [AlDanial/cloc#267]
This is not producing any output because the directory names have spaces:
cloc-1.74.exe --diff "MS Comp baseline" "MS Comp latest">output.txt

But if I remove the spaces, it works:
cloc-1.74.exe --diff "MS_Comp_baseline" "MS_Comp_latest">output.txt

Please investigate.

Regards,
M.R.

**Comment by AlDanial** [comment]
Duplicates #254.  Solution: use ``cloc-1.74_x86.exe`` from the release area, https://github.com/AlDanial/cloc/releases
