### ISSUE TITLE
Arguement list too long at cloc --diff

### ISSUE THREAD

**Issue by zekmasa** [AlDanial/cloc#273]
Hi,

I tried to capture the LOC using "--diff" option, but I got an error as below.

Can't exec "/bin/sh": Argument list too long at /usr/local/bin/cloc line 4176.
Failed to create tarfile of files from git. at /usr/local/bin/cloc line 4179.

In this line the tool try git archive, but could not execute because of exceeding command line buffer (ARG_MAX).

- Environment

Ubuntu 16.04.3 (4.13.0-32-generic)
ARG_MAX is 2097152

- Reproduce procedure

1.  execute cloc --diff 2 commits which have many diff files.
  I used AOSP environment as below
   $ repo init -u https://android.googlesource.com/platform/manifest -b android-8.1.0_r14
   $ repo sync -j8
   $ cd art/
   $ cloc --diff commit A commit B
     (commit A is the bottom of the branch and B is HEAD)

It is depending on ARG_MAX value error occurs or not

I guess that the issue caused by overflow of ARG_MAX, so I think that the argument of git archive should be restricted the value within ARG_MAX to be fixed.

BRs,
zekmasa

**Comment by AlDanial** [comment]
More than two million command line arguments, wow.

I tried to reproduce the issue but the ``repo sync -j8`` command, after about 5 minutes of downloads and other things scrolling up the screen, ends with ``error: Exited sync due to fetch errors``.  I repeated the command four or five times thinking each time it would make more progress but it isn't clear that it is.

**Comment by zekmasa** [comment]
If you could not download Android source code via repo, you can reproduce same issue on linux.git.

- Procedure

1. Download linux kernel source code via git
 $ cd (your directory)
 $ git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
2. Checkout the latest (I checked out v4.14.13)
 $ cd (your directory)/linux-stable
 $ git checkout v4.14.13
3. Do cloc --diff between top and bottom commit hash as below
 $ cloc --diff 1da177e4c3f41524e886b7f1b8a0c1fc7321cac2 b8447222eb207d5a5ec20a0f357065963dabdcd0

Maybe you can see the argument list too long error.

BRs,
zekmasa

**Comment by AlDanial** [comment]
Yes, I'm able to reproduce the issue with that.  Now some head-scratching while I figure out a solution....

**Comment by zekmasa** [comment]
Hi, I've tested on android environment. I could not find "Argument list too long" error but it seems that the diff result was incorrect as below (between android O-MR1 and P-preview-1)

From result, cloc counted that all code was removed and, not counted additional,modified and same code.
It seems that diff algorithm is incorrect.

-----------------------------------------------------------------------------------
Language                         files          blank        comment           code
-----------------------------------------------------------------------------------
Python
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                             1            103             46            530
HTML
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                             4             51              0             99
Bourne Shell
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                             1              4              0             20
C++
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                            93          11084           6819          84610
Protocol Buffers
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                             6           1578           3231           2308
Windows Resource File
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                             2              4              0             40
C
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                             3             88             57            369
Java
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                           629          59149         146619         372913
make
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                           197           1658           1688           4142
C/C++ Header
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                            10            484            959           1336
XML
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                           968           4276          22631         215251
-----------------------------------------------------------------------------------
SUM:
 same                                0              0              0              0
 modified                            0              0              0              0
 added                               0              0              0              0
 removed                          1914          78479         182050         681618
-----------------------------------------------------------------------------------

BRs,
zekmasa

**Comment by AlDanial** [comment]
While the error was easy to fix, finding it took a long time.  Please try again with the code pushed with commit 6a8947b.  Using it, I get this summation block:
<pre>
SUM:
 same                                    0              0         338862        1176680
 modified                             5550              0          50413         422913
 added                               44121        2732617        2931033       15269245
 removed                              9979         482660         647237        2709640
</pre>

Also it takes much longer, 10 minutes on my laptop, since it is doing real work and not skipping most of it as before.

**Comment by zekmasa** [comment]
I tested with https://github.com/AlDanial/cloc/commit/6a8947b590a721d828914c5f816f74d38aae2700 and it seemed to work counting fine.
I close the
