### ISSUE TITLE
Support for Xtend

### ISSUE THREAD

**Issue by tsaglam** [AlDanial/cloc#276]
Support for Xtend would be great!
Xtend is a Java dialect and therefore very similar to Java ([www.eclipse.org/xtend](https://www.eclipse.org/xtend/)).
- Extension: .xtend
- Comments are defined the same way as in Java:
```xtend
/**
 * JDoc comment.
 */
class XtendClass {
	/*
	 * Block comment.
	 */
	def foo() {
		println("Hello World!") // In-line comment.
		// Single comment line.
	}
}
```
The only tricky part might be dealing with [template expressions](https://www.eclipse.org/xtend/documentation/203_xtend_expressions.html#templates). They are basically Strings but they allow for readable string concatenation. A normal Java comment identifier inside a template expression is not a comment, it is part of the String. Inside template expressions, `«««` is used to comment out an entire line ([more info](https://www.eclipse.org/xtend/documentation/203_xtend_expressions.html#templates)).
```xtend
class TemplateExample {
	def templateMethod() '''
	    // This is not a comment, it is part of the template expression.
	    /*
	     * This not a comment, it is part of the template expression.
	     */
            ««« This is a comment!
	'''
}
```
Here are other examples: [example1](https://github.com/kit-sdq/XAnnotations/blob/master/bundles/edu.kit.ipd.sdq.activextendannotations/src/edu/kit/ipd/sdq/activextendannotations/DelegateDeclared.xtend) & [example2](https://github.com/tsaglam/JavaCodeEcorification/blob/master/src/main/java/jce/generators/EFactoryImplementationGenerator.xtend)

**Comment by AlDanial** [comment]
I added Xtend, with caveats:  for the most part, cloc does not identify strings within code and therefore can't tell whether or not comment markers appears within a string.  This is a known limitation of the tool.  Additionally, I haven't figured out how to match the  ``«««`` marker in Perl so that is also not handled.

**Comment by tsaglam** [comment]
Thanks for your work!
