### ISSUE TITLE
Error: Can't use an undefined value as an ARRAY reference at script/cloc-1.76.pl line 1970.

### ISSUE THREAD

**Issue by mr2001** [AlDanial/cloc#278]
I am running the following script and get above error:

"D:\LOC\cloc-1.76.exe" --diff "D:\LOC\file1_baseline" "D:\LOC\file1_latest" --diff-timeout 100000 --force-lang-def="D:\LOC\lang_file.txt"  

Below is **lang_file.txt**

C++
    filter call_regexp_common C++
    extension C
    extension CPP
    extension c++
    extension cc
    extension cpp
    extension cxx
    extension pcc
    3rd_gen_scale 1.51
    end_of_line_continuation \\$
C/C++ Header
    filter call_regexp_common C++
    extension H
    extension h
    extension hh
    extension hpp
    extension hxx
    3rd_gen_scale 1.00
    end_of_line_continuation \\$
C
    filter call_regexp_common C++
    extension c
    extension ec
    extension pgc
    3rd_gen_scale 0.77
    end_of_line_continuation \\$
make
    filter remove_matches ^\s*#
    filter remove_inline #.*$
    extension Gnumakefile
    extension Makefile
    extension am
    extension gnumakefile
    extension makefile
    extension mk
    filename Gnumakefile
    filename Makefile
    filename gnumakefile
    filename makefile
    script_exe make
    3rd_gen_scale 2.50
    end_of_line_continuation \\$
XML
    filter remove_html_comments
    filter call_regexp_common HTML
    extension XML
    extension xml
    3rd_gen_scale 1.90
DTD
    filter remove_html_comments
    filter call_regexp_common HTML
    extension dtd
    3rd_gen_scale 1.90
SQL
    filter call_regexp_common C
    filter remove_matches ^\s*--
    filter remove_inline --.*$
    extension SQL
    extension psql
    extension sql
    3rd_gen_scale 2.29
Ruby
    filter remove_matches ^\s*#
    filter remove_below_above ^=begin ^=end
    filter remove_inline #.*$
    extension rake
    extension rb
    filename Rakefile
    filename rakefile
    script_exe ruby
    3rd_gen_scale 4.20
    end_of_line_continuation \\$
Perl
    filter remove_below ^__(END|DATA)__
    filter remove_matches ^\s*#
    filter remove_below_above ^=head1 ^=cut
    filter remove_inline #.*$
    extension perl
    extension plh
    extension plx
    extension pm
    extension pm6
    script_exe miniperl
    script_exe perl
    script_exe perl5
    script_exe perl6
    3rd_gen_scale 4.00
Python
    filter remove_matches ^\s*#
    filter docstring_to_C
    filter call_regexp_common C
    filter remove_inline #.*$
    extension py
    script_exe python
    script_exe python2.6
    script_exe python2.7
    script_exe python3
    script_exe python3.3
    script_exe python3.4
    script_exe python3.5
    3rd_gen_scale 4.20
    end_of_line_continuation \\$
DOS Batch
    filter remove_matches ^\s*rem
    extension BAT
    extension BTM
    extension CMD
    extension bat
    extension btm
    extension cmd
    3rd_gen_scale 0.63
MSBuild script
    filter remove_html_comments
    filter call_regexp_common HTML
    extension csproj
    extension vbproj
    extension vcproj
    extension wdproj
    extension wixproj
    3rd_gen_scale 1.90
Windows Resource File
    filter call_regexp_common C++
    extension rc
    extension rc2
    3rd_gen_scale 1.00

**Comment by AlDanial** [comment]
Thanks for the bug report, should be fixed with commit 634297d.  Please reopen if that's not the case.

**Comment by mr2001** [comment]
Please forgive my ignorance but how can I get a Windows  executable that includes this fix?

**Comment by AlDanial** [comment]
I make and upload Windows executables only for releases.  But you can make your own Windows executable if you have Perl installed, ref the section "Create your own executable" below https://github.com/AlDanial/cloc#building_exe

Having Perl installed (I recommend http://strawberryperl.com/) gives you the additional benefit of being able to run the cloc source code directly without need for an exe.
