### ISSUE TITLE
Update the homebrew recipe

### ISSUE THREAD

**Issue by ruurd** [AlDanial/cloc#28]
The homebrew recipe still points to the sourceforge site. It probably also should refer to a more modern version instead of 1.64.

**Comment by AlDanial** [comment]
This is a homebrew issue rather than a cloc issue, but nonetheless I opened an issue for them at
https://github.com/Homebrew/homebrew/issues/45877 pointing them here.

**Comment by ruurd** [comment]
homebrew is a community effort meaning you're supposed to be the one maintaining the recipe. After all you are the one with intimate knowledge about your own piece of software isn't it?

**Comment by ruurd** [comment]
https://github.com/Homebrew/homebrew/pull/45880

**Comment by ruurd** [comment]
https://github.com/Homebrew/homebrew/pull/45882 this is a good try.

**Comment by AlDanial** [comment]
Fair enough; thanks for the intro on Homebrew.  Being Linux based I know little about working on a Mac.

**Comment by ruurd** [comment]
No problem. And being a Linux guy you would feel right at home on a Mac really.
