### ISSUE TITLE
"Out of memory!nique files"

### ISSUE THREAD

**Issue by mr2001** [AlDanial/cloc#280]
I am running the following script:
"D:\\LOC\cloc-1.76.exe" --diff "D:\LOC\folder1" "D:\LOC\folder2" --diff-timeout 3000 --out=test.txt
Both folders contain only one xml file, I attached below (they are identical)
After a very long time (hours) I get the following error:

       1 text file.
       1 text file.
       2:        2 unique files.
       Out of memory!nique files.

XML file attached.
[test100.zip](https://github.com/AlDanial/cloc/files/1793578/test100.zip)

**Comment by AlDanial** [comment]
Commit fff9d47 fixes the problem of memory and timeout when inputs are the same.
