### ISSUE TITLE
cloc - Failed to create tarfile of files from git

### ISSUE THREAD

**Issue by ramkumar-hgst** [AlDanial/cloc#284]
We are getting below error while generating the LOC using below command.

Command:
perl cloc-1.74.pl --quiet --force-lang="CMake",txt --diff --git 9026dcc56e7f3a3fbbb758a66bd2663842147a01 e98cc0126afc6813e34bb94d475d886dcab0b1a2 

Error:
sh: 1: Syntax error: "(" unexpected
Failed to create tarfile of files from git. at cloc-1.74.pl line 3816.

**Comment by ramkumar-hgst** [comment]
I ran the script with verbose option. In the git archive output one file is listed like this.
"dir1/dir2/dir3/file (copy).c"

Is this causing the script to fail?

**Comment by AlDanial** [comment]
Some git-related fixes were added with v1.76, give that a try,
https://github.com/AlDanial/cloc/releases

**Comment by ramkumar-hgst** [comment]
I tried with that version too. Same error occurred.
perl cloc-1.76.pl --diff --git 9026dcc56e7f3a3fbbb758a66bd2663842147a01 e98cc0126afc6813e34bb94d475d886dcab0b1a2

sh: 1: Syntax error: "(" unexpected
Failed to create tarfile of files from git. at ../../tools/jenkins/loc/cloc-1.76.pl line 4179.

**Comment by AlDanial** [comment]
I was able to duplicate the problem.  Please try the fix in the development branch, https://github.com/AlDanial/cloc/blob/master/cloc

**Comment by ramkumar-hgst** [comment]
Yes. It is working fine now. Are you going to create a 1.77 release?

**Comment by AlDanial** [comment]
My plan is two releases a year.  Next one will be July 2018.
