### ISSUE TITLE
z/OS: Assembly and JCL

### ISSUE THREAD

**Issue by AppleEater1403** [AlDanial/cloc#287]
Hello,
i really like CLOC but I've found two small errors:

The first one is that comments in z/OS assembly files are counted as code. "Normal" comments (as opposed to comments which are inside a macro definition) have an asterix in the first column:
http://publibz.boulder.ibm.com/cgi-bin/bookmgr_OS390/BOOKS/ASMR1010/2.2.4?DT=20040728153937)
To solve this you could add  `[ 'remove_matches'      , '^\*'    ]` into `%{$rhaa_Filters_by_Language}{Assembly}`.

The other "error" is really just a small imperfectcy regarding JCL (Job Control Language) comments. Inside the `remove_jcl_comments` - subroutine the regex `m{^\s*//\*}` is used to detect comments. But the two slashes and the asterix are required to be in the frist three columns of the line. So it should be `m{^//\*}` instead.

Greetings. Keep up the good work :)

**Comment by AlDanial** [comment]
Thanks for the corrections.
