### ISSUE TITLE
Nested OCaml comments handled incorrectly.

### ISSUE THREAD

**Issue by rmn30** [AlDanial/cloc#291]
In OCaml comments are enclosed in `(* ... *)` and can be *nested*. This is useful for temporarily disabling code containing comments e.g.:
```OCaml
(* don't want x for now
(* 
nested comment
*)
let x = 1;;
*)
let y = 1;;
```
cloc currently counts this as 4 comment lines and 3 code lines because it treats the first `*)` as the end of the comment. It should be counted as 6 comment lines and 1 code line.

**Comment by rmn30** [comment]
cloc also fails to count correctly if the comment delimiters are contained with strings e.g.:
```
let x = "(*";;
let y = 1 ;;
let z = "*)";;
```
is counted as 1 comment and 2 code lines but should be 3 code lines and no comments.

**Comment by AlDanial** [comment]
cloc has two fundamental limitations, and you've just described both of them.

cloc uses regular expressions (rather than full up lexers) to identify comments and thus cannot handle nested comments using the same markers, ``(*`` and ``*)`` in this case.  Having said that, I've added custom handlers for some languages; if you can come up with pseudocode that properly deals with OCaml comments, I'll gladly code that up and integrate it into cloc.

**Comment by rmn30** [comment]
> cloc has two fundamental limitations, and you've just described both of them.

Sorry, I didn't mean to denigrate your very useful work -- I just wanted to make sure the issue was documented so it doesn't catch people by surprise and might eventually be fixed!

Of the two issues I think nested comments is more important to fix for OCaml -- they are explicitly supported but do not work in languages like C. A simple handler would scan looking for `(*` or `*)`, incrementing a variable when it sees the former and decrementing it for the latter. If the (initiallly zero) variable is more than zero then treat the code as comment. The slightly tricky part is catching multiple open or close comments on the same line if using line based scanning. I think it's OK to treat a line as code if there is any non-comment, non-whitespace content. This wouldn't handle the string issue correctly but would be OK for most code and no worse than other parsers.

**Comment by AlDanial** [comment]
I'll take a shot at a custom filter but it may be a couple of weeks away.

**Comment by AlDanial** [comment]
Give commit ba9926d a try; it should handle both nested comments and comments in strings.  The cloc option ``--strip-comments nc`` can be useful for testing as it will create a new file with a ``.nc`` extension (meaning "no comments") that has all comments removed.

**Comment by rmn30** [comment]
Yes it seems to work, thank you very much. I tried it on the two examples above and this even nastier example that Markdown's syntax highlighting gets wrong:
```OCaml
let x = 1;;
(* asdf
let y = "*)";;
asdf *)
let z = 1;;
```
(2 lines code and three lines comment)

**Comment by rmn30** [comment]
Re-opening because having looked at the code I saw another evil case:
```Ocaml
let x="multi line strings
are allowed in ocaml";;
(* asdf
let y = "*)
";;
asdf *)
let z= 1;;
```
Should be 3 code / 4 comment.
Currently cloc only exempts strings if they are on a single line. To fix this you need another variable, `$in_string` which you could invert every time you see a `"` (except you should ignore `\"`). Sorry to be awkward but couldn't help myself. Feel free to ignore -- I expect your parser is good enough for almost all real world OCaml.

**Comment by AlDanial** [comment]
Indeed, that's tricky.  I tried a few ideas in code but it was like whack-a-mole, fix one corner case and break another.  I'm going to pass on this but will certainly entertain a PR if you come up with a solution.
