### ISSUE TITLE
New version issue with custom language definition

### ISSUE THREAD

**Issue by Kaelten** [AlDanial/cloc#299]
I have a local DSL that uses the same file extension as PL/M does in the latest version.  I'd rather not have to use the force flag and maintain a file with all of the language definitions, sync it across my computers, etc.  

Is it possible to somehow give my custom definition precedence over the built-in PL/M def?

**Comment by AlDanial** [comment]
If you tell me what your language looks like I can add a routine that tries to figure out if it is your language or PL/M.  cloc already has a dozen such routines to disambiguate files (most notorious is the ``.m`` extension which maps to five languages).  Most languages have readily identifiable characteristics so the accuracy of such disambiguators is quite good.

Alternatively you could edit the cloc source code and simply get rid of PL/M in your version.

Finally I've added in the development version the ability to read a config file so cloc will look for command line options there, saves you from having to enter them every time you run the tool.  If you want to go that route you'll need to pull the latest dev version.
