### ISSUE TITLE
Dollar sign in file name breaks cloc

### ISSUE THREAD

**Issue by dmitryash** [AlDanial/cloc#304]
Files in test git repository:

```
$ ls -l
-rw-r--r-- 1 dmitry users  49 Jun  7 19:42 special-file-with-$dollar.c
```

When I run cloc with `--diff` options I get an error:
```
$ cloc --vcs=git --git --report-file=report.txt --diff v2 v3
fatal: pathspec 'special-file-with-\.c' did not match any files
Failed to create tarfile of files from git. at ../cloc/cloc line 4400.
```

The more interesting case - it is possible to print environment variable, looks like some kind of security bug. Think of some web service that allows counting lines of code that it is possible to execute code remotely. If I create a file with special name:
```
$ ls -l
-rw-r--r-- 1 dmitry users 19 Jun  7 19:51 my-user-name-is-$USER.c
```

I get exaclty what I wanted:
```
$ cloc --vcs=git --git --report-file=report.txt --diff v5 v6 
fatal: pathspec 'my-user-name-is-\dmitry.c' did not match any files
Failed to create tarfile of files from git. at ../cloc/cloc line 4400.
```

**Comment by AlDanial** [comment]
@dmitryash : thank you for submitting #301, #302, #303 and #304.  It will be a few days before I have time to investigate any of them.
