### ISSUE TITLE
Undef size error when trying to read a file

### ISSUE THREAD

**Issue by Lepidora** [AlDanial/cloc#306]
I was running cloc on `/` (as you do) and I found that it crashed with this error message:

````
make_file_list(/Users/<user>/Library/Google/GoogleSoftwareUpdate/Reports/com.google.Chrome) undef size at /usr/local/Cellar/cloc/1.76/libexec/bin/cloc line 4310.
````

When I went to the Reports directory, it was empty. I'm assuming it's somehow trying to read the com.google.Chrome file when it doesn't exist and subsequently breaks.

I'm using cloc 1.76 on macOS 10.11.6.

**Comment by AlDanial** [comment]
Thanks for reporting this; the crash was due to debug statements that should have been replaced a long time ago.  Fixed with commit c2cc7a3.
