### ISSUE TITLE
The output yaml is invalid when a file name has the space and the sharp sequentially

### ISSUE THREAD

**Issue by ks888** [AlDanial/cloc#312]
Hi, thank you for this excellent tool! I'm using this tool for many files and write the results in yaml. It works well for most cases, but I noticed sometimes the output yaml file is not parsable.

After some investigation, it turns out the file name which contains the ` #` like 'sam #ply.py' causes the problem. In such a case, the yaml like below is printed and it is not parsable because `#ply.py:` is treated as the comment.

```

---
# github.com/AlDanial/cloc
header :
  cloc_url           : github.com/AlDanial/cloc
  cloc_version       : 1.76
  elapsed_seconds    : 1.02099013328552
  n_files            : 1
  n_lines            : 1
  files_per_second   : 0.979441394582358
  lines_per_second   : 0.979441394582358
./sam #ple.py :
  blank: 0
  comment: 0
  code: 1
  language: Python
SUM:
  blank: 0
  comment: 0
  code: 1
  nFiles: 1
```

The oneliner below will reproduce this issue:

```
$ echo "print('Hello world')" >'sam #ple.py'; cloc --quiet --yaml --by-file './sam #ple.py' | ruby -r yaml -e 'YAML.load STDIN'
/Users/yagami/.rbenv/versions/2.4.0/lib/ruby/2.4.0/psych.rb:377:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 12 column 1 (Psych::SyntaxError)
        from /Users/yagami/.rbenv/versions/2.4.0/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
        from /Users/yagami/.rbenv/versions/2.4.0/lib/ruby/2.4.0/psych.rb:325:in `parse'
        from /Users/yagami/.rbenv/versions/2.4.0/lib/ruby/2.4.0/psych.rb:252:in `load'
        from -e:1:in `<main>'
```

I think a simple workaround is to quote all the string value with `"`, but it may be too verbose in most cases and also it will break most tests.

**Comment by AlDanial** [comment]
Thanks for reporting this problem.  Commit e58f96a should handle this correctly.

**Comment by ks888** [comment]
Quick! Thank you very much!
