### ISSUE TITLE
fatal: pathspec 'Kernel/Animations\' did not match any files

### ISSUE THREAD

**Issue by hawkli-1994** [AlDanial/cloc#313]
I have encountered a bug like "fatal: pathspec 'Kernel/Animations\' did not match any files". I know this is caused by a space in the path. I want to know which line the error was thrown in. I want to fix it.

**Comment by AlDanial** [comment]
You can run cloc with a high level of debug output using ``-v 3``, that may help you narrow the location.

Other than that, you don't leave much for me to go by.  Could you create a tar file containing fake data with a similar directory structure that duplicates the problem and post that?

**Comment by AlDanial** [comment]
no response, closing

**Comment by Montesdodgers13** [comment]
Close

**Comment by Montesdodgers13** [comment]
Closed
