### ISSUE TITLE
Specify Gradle as own language

### ISSUE THREAD

**Issue by kkopper** [AlDanial/cloc#314]
Similar to Maven, which is based on XML but still exposed as a language of its own, Groovy or Kotlin based Gradle scripts should be counted separately.

In particular, it seems that `pom.xml` is identified as a Maven file although being an XML-file. For Gradle, all scripts are either named `*.gradle` if using the standard Groovy DSL (`build.gradle`, ...), or `*.gradle.kts` if using the Kotlin DSL (`build.gradle.kts`, ...). The first case is currently counted as *Groovy* code, while the latter is counted as *Kotlin* code. As far as I'm concerned, files matching these criteria should be mentioned as *Gradle*.

**Comment by AlDanial** [comment]
Commit 3921f3f applies the changes you suggest.
