### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by pascalpoizat** [AlDanial/cloc#315]
Hello

when I run `cloc` I get a warning, even with a version command.

```
❯ cloc --version
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/({ <-- HERE |})/ at /usr/local/Cellar/cloc/1.76/libexec/bin/cloc line 8555.
1.76
```

Possibly related to https://github.com/AlDanial/cloc/issues/209 but is seems related to the Pascal language, while here I have none (version command).

I have installed `cloc` using:

```
brew install cloc
```

**Comment by AlDanial** [comment]
This is fixed in the development version (ref #307) if you'd like to try that: https://github.com/AlDanial/cloc/raw/master/cloc
