### ISSUE TITLE
Add the ability to specify encoding when saving output on file

### ISSUE THREAD

**Issue by labilbe** [AlDanial/cloc#318]
Currently, content is written on XML file using ANSI encoding.
In some cases, I have files with french accent "é" (i.e. Réponse.cs).
When this case is found, the XML generated is malformed.

If I open the XML file (with SublimeText or Notepad) and force UT8 encoding when saving it, the XML malformation is fixed.

Should it be possible to be able to specify an output encoding when saving the XML file?

Thanks.

**Comment by AlDanial** [comment]
I set the XML (and XLS) encoding to UTF-8.  Please try the code on the development branch and see if your filenames are handled better.

**Comment by Montesdodgers13** [comment]
Clise

**Comment by Montesdodgers13** [comment]
Closed

**Comment by Montesdodgers13** [comment]
Close

**Comment by Montesdodgers13** [comment]
Close

**Comment by labilbe** [comment]
I'm sorry but the saved file is still saved with ANSI encoding (tested with v1.78).
A way to check this on Windows is to open the file with notepad.exe.
Then go to "File -> Save As...". The encoding used is the one selected at the bottom of the window.
![sshot-2](https://user-images.githubusercontent.com/54315/45365106-12f0be80-b5dc-11e8-9b8d-b873bbefff66.jpg)

**Comment by adrian-at-dmi** [comment]
I can report the same problem for v1.78. I have german umlauts (ä, ü, ö) in some of my files and running cloc produces a malformed `.xml`-file, which - for example - can't be parsed by the SLOCCount Jenkins plugin.

Did some testing with v1.80 though and tried the following flags:
```
--file-encoding utf8
--file-encoding=utf8
--file-encoding=utf-8

--file-encoding utf16
--file-encoding=utf16
--file-encoding=utf-16
```

Always got two error messages
```
Unknown PerlIO layer "encoding" at script/cloc line 5433.
print() on closed filehandle $OUT at script/cloc line 5440.
```
and the `result.xml` was not created.

**Comment by AlDanial** [comment]
@adrian-at-dmi which version of Perl are you using (``perl --version``) and on what OS?

**Comment by adrian-at-dmi** [comment]
I used the windows executables (exe) for both v1.78 and v1.80 on Windows 10 and Windows Server 2008 R2 machines. Results were identical for both operating systems.

**Comment by AlDanial** [comment]
OK, I duplicated the problem with the Windows exe:
<pre>
PS Z:\> .\cloc-1.80.exe --by-file --file-encoding utf8 --xml --out t.xml .\tests\inputs\Réponse.cs
       1 text file.
       1 unique file.
       0 files ignored.
Unknown PerlIO layer "encoding" at script/cloc line 5433.
print() on closed filehandle $OUT at script/cloc line 5440.
</pre>
However the Perl source version works fine:
<pre>
PS Z:\> .\cloc-1.80.pl --by-file --file-encoding utf8 --xml --out t.xml .\tests\inputs\Réponse.cs
PS Z:\> 
</pre>
(and the file ``t.xml`` contains the ``Réponse.cs`` file name properly).

So the ``pp`` tool I use to convert the source to .exe has a flaw... I'll have to do research to see if there's a work-around.

**Comment by AlDanial** [comment]
I was able to figure out a work-around to making a Windows exe which can use different file encodings.  This one works for me.
[cloc-1.81.zip](https://github.com/AlDanial/cloc/files/2477371/cloc-1.81.zip)

**Comment by adrian-at-dmi** [comment]
Nice, v1.81 works for me too. The result file is now properly UTF-8 encoded and the error messages are gone 😄 

Since the README says that odd version numbers are considered beta: Would you recommend the `cloc-1.81.exe` for "production use" or is there a plan for v1.82 anytime soon (maybe with additional bug fixes or improvements)?

Thanks for your hard work. Much appreciated 👍

**Comment by AlDanial** [comment]
This particular exe is good for production use.  The git history shows only minor changes have been added since the 1.80 release.  Unless someone discovers a severe issue with 1.80, I do not expect to release 1.82 this calendar year.
