### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by nijikon** [AlDanial/cloc#323]
@AlDanial would it be possible to create a new release? We would appreciate it, as we need this fix https://github.com/AlDanial/cloc/issues/321. We don't want to monkey patch or run `master` in production.

**Comment by AlDanial** [comment]
I agree a release is long overdue.  I've been waiting for a reply on #320 to fix a potential issue counting in ``--git`` mode.  That's the last hold up.  If I don't hear a reply within a week, I'll do a release.

**Comment by nijikon** [comment]
Thanks!

**Comment by AlDanial** [comment]
v 1.78 is out.

**Comment by Montesdodgers13** [comment]
Close

**Comment by Montesdodgers13** [comment]
Closed

**Comment by Montesdodgers13** [comment]
Closed

**Comment by Montesdodgers13** [comment]
Closed

**Comment by f2404** [comment]
@Montesdodgers13 Could you please stop spamming? Thanks!
