### ISSUE TITLE
`Unix/cloc` has a hardcoded Perl path

### ISSUE THREAD

**Issue by lembacon** [AlDanial/cloc#325]
In version 1.7.8, `Unix/cloc` has a hardcoded Perl path at its first line which seems undesired.

https://github.com/AlDanial/cloc/blob/68277d651e5decf6aabfe91065f00ba03beec42c/Unix/cloc#L1

**Comment by AlDanial** [comment]
Ugh!  That's awful; was testing different versions and forgot to reset it.  I'll re-release the 1.78 tar ball in a few minutes.

**Comment by AlDanial** [comment]
cloc-1.78.tar.gz in the release area should now have Unix/cloc with ``#!/usr/bin/env perl`` on the first line.

Thanks for reporting this problem.
