### ISSUE TITLE
Incorrect handling of block-comment delimiter inside string

### ISSUE THREAD

**Issue by pageer** [AlDanial/cloc#33]
Hi!  I've run into an issue where cloc is reporting incorrect lines counts in certain cases involving block comment delimiters inside a string in PHP code.  I've attached a test script that demonstrates the issue.  I have not yet tried it with any other languages.

The test file contains three functions.  The first has a `/*` inside a string literal and the third has a block comment above it.  (In this example, the block comment is a PHPDoc docblock, but the issue happens with a plain block comment too).  The correct counts for this file are 4 comment lines and 16 code lines.  However, the actual output from cloc is 11 comment and 9 code.  

Base on my testing, it looks like cloc is incorrectly flagging the `/*` and `*/` as valid comment delimiters in the following cases:

1. They occur inside a string literal in code.
2. They occur inside a trailing line comment (`#` or `//` in PHP) on a line that starts with some code.  Note that the delimiters are correctly ignored if they occur in a line comment that *doesn't* have any code before it, i.e. the line is just whitespace and comment.

Note that if no closing `*/` is found in a string literal, a real block comment, or a comment as described above, the initial `/*` is correctly ignored.  (Actually, the only reason I even noticed this is because I ran cloc on a file that had a `/*` in a string literal at line 60 and didn't have a single `*/` until about 500 lines later.)

[cloc-test.php.txt](https://github.com/AlDanial/cloc/files/43058/cloc-test.php.txt)

**Comment by jolkdarr** [comment]
Issue in C/C++ files.
Consider the following snippet:
```c
char* x1 = "/*";
int   x2 = 1000;
char* x3 = "*/";
```
We get the following result:
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                1              0              2              1
-------------------------------------------------------------------------------
```
Instead oft:
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                1              0              0              3
-------------------------------------------------------------------------------
```

**Comment by AlDanial** [comment]
This is a known problem, ref
https://github.com/AlDanial/cloc#limitations
I will happily accept pull requests that implement string parsing.

**Comment by AlDanial** [comment]
I recognize this problem is a failure for cloc but at the same time do not anticipate solving the problem.  A correct solution would require implementation of a parser for each supported language and that is beyond cloc's scope.

**Comment by jolkdarr** [comment]
I agree with you. The task is not easy and the limitation is tolerable.
Maybe, in a future release, we should attempt to process only languages that use pair of quotes ```"..."``` within a single line with the possibility to use ```\"``` in the string.
