### ISSUE TITLE
ReasonML support

### ISSUE THREAD

**Issue by sgrove** [AlDanial/cloc#330]
[ReasonML](https://reasonml.github.io/) is a different syntax for OCaml, and it'd be great to have support for it! It does have native support for JSX however, hopefully that doesn't overly complicated things.

1. File extensions are `.re` and `.rei` (for the implementation and interface files, respectively)
2. Comments are [*only*](https://reasonml.github.io/docs/en/overview) defined with `/* */`
3. Happy to link to examples depending on what you're looking for, here's a good tutorial that progressively builds up examples: http://2ality.com/2017/12/modules-reasonml.html

**Comment by AlDanial** [comment]
ReasonML support added with 50e718c.
