### ISSUE TITLE
Possibility to compare multiple runs of CLOC in the database

### ISSUE THREAD

**Issue by Ninido** [AlDanial/cloc#332]
Hello,

I have successfully used CLOC for creating SQLite database with one run. Then used ODBC to pull the SQLite database into one of the BI programs and results where great. 

Now, I would like to append another run to the same database. 

What I would like to do is run the same scan, with the same parameters (same catalogues and project names), every (day / week / month). This would allow me to extract change vector between two runs/dates. For example: Project Xs codebase have grown Y% between two dates.

When I look at the database schema that is created I can’t see any way to distinct nValues in the t table between two runs. 

So ... first question is, have I missed something, is it possible to diferentiate two or more CLOC runs in the t table ?

If not, would you be interested in adding that functionality? I don’t have any pearl skills, but as I have quickly checked the code and simplest solution would be to add Date column (just date, without the time) to the t table.

If I understand the code correctly (IF :)), that could be solved by adding column `Date          varchar(500)   ,` to $schema at line 3293 and pushing the value to the "insert into" row 3374 `strftime("%Y-%m-%d", localtime(time()));` (I am guessing the syntax) 

Observe. I dont know if sugested changes would affect code at other places. 

What do you think?

**Comment by Ninido** [comment]
Hello again and thank you for quick response.

I have now tried the alternatives provided. And thanks for alternative nr 3, that was most promising but unfortunately it did not work.

#### The reason why first alternative will not work is this ...

Given following scenario:
- I am running cloc on first every month
- I am running cloc on 3 projects

In this case my Project column will have following values: (using _ to split name with date )

|Project
| ------ 
| Proj A_2018-08-01
| Proj B_2018-08-01
| Proj C_2018-08-01
| Proj A_2018-09-01 
| Proj B_2018-09-01 
| Proj C_2018-09-01
| Proj A_2018-10-01 
| Proj B_2018-10-01 
| Proj B_2018-10-01 
... etc

If I want to compare only one project (say Project A) reading data from one column would work. But if i want to compare multiple project like this table for example:

|  | 2018-08-01 | 2018-09-01 | 2018-10-01 |
| ------ |------ |------ |------ |
| **Proj A** | 23233 | 23433 | 23733 |
| **Proj B** | 43343 | 46543 | 50043 |
| **Proj C** | 5656 | 6096 | 6726 |
| **Proj D** | 6565 | 6585 | 6599 |

Than honestly I cannot se how would. Because **one database column contains both X and Y axis** in this case. In BI tools you usually choose following: X-axis column, Y-axis column, Data Column (Which is automatically filtered by choice of X and Y axis’s).

#### Second alternative
I am running this tool on 467 different GIT repositories where every repository is a "Project" in CLOC. The resulting SQLite database is 16 mb. And with that amount of data I cannot work with SQLite interface, where as you suggested database attachment is possible. I need more powerful tools to deal with the data. 

What I use is that I use SQLite ODBC and connect one of BI tools to the database. In my case Microsoft Power BI. Literally in seconds I am able to get graphs that pinpoint pain areas. That I then look in more detail.

#### Third alternative
I was really hoping on this one. I executed folowing rows after every run 

```
#PowerShell
Invoke-Expression "$($sqliteExec) $($database) `"alter table t add column date text default '';`""
Invoke-Expression "$($sqliteExec) $($database) `"update t set date = '$($DateStr)' where date is ''´";
```

This does what is expected. But next CLOC run breaks because generated SQL from CLOC have 9 columns and after update the table have 10 columns. 

And because insert into commands are not named
```
insert into t values('Project nme', 'TypeScript', 'C:\Projects\Ninido\file.ts', 'C:\Projects\Ninido', 'file.ts', 32, 12, 76, 92.000000);
```
I get an error. 
```
table t has 10 columns but 9 values were supplied
```

But it will work if insert columns are named.
```
insert into t ( Project, Language, File, File_dirname, File_basename, nBlank, nComment, nCode, nScaled ) values('Project name', 'TypeScript', 'C:\Projects\Ninido\file.ts', 'C:\Projects\Ninido', 'file.ts', 32, 12, 76, 92.000000);
```

I am really appreciating your help. 
Can you reconsider your decision or add column names to CLOC SQL Inserts?

**Comment by AlDanial** [comment]
I like the idea of named columns.  The only issue is that is nearly doubles the amount of SQL text emitted.  I therefore added in a31f19f an option, enabled with  ``--sql-style Named_Columns``, to add these names.  Does this work for you?

**Comment by Ninido** [comment]
Yes, that will do it. Thanks.
