### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by leipert** [AlDanial/cloc#334]
I use the current definition to detect [SVG][0] in a code base (not sure about `3rd_gen_scale` though). SVG detection would help in frontend centric code bases, that might contain icons and/or illustrations.

```
SVG
    filter remove_html_comments
    filter call_regexp_common HTML
    extension svg
    extension SVG
    3rd_gen_scale 1.90
```

Example files:
- https://commons.wikimedia.org/wiki/File:SVG_logo.svg
- https://commons.wikimedia.org/wiki/File:Escut_oficial_de_B%C3%A9tera_(1955).svg

[0]: https://en.wikipedia.org/wiki/Scalable_Vector_Graphics

**Comment by AlDanial** [comment]
Thanks for the info. SVG support is added with 157d706.  The 3rd gen scale factor is quite speculative so the value is nearly irrelevant.  I used 1.0.
