### ISSUE TITLE
—ignored does not output in xml 

### ISSUE THREAD

**Issue by jamesspo** [AlDanial/cloc#339]
Hi, is it by design, or just me getting it wrong? Using the —xml switch does not output ignored files in xml format. 

Is there a a way to achieve this?

BTW thanks for the .80 update. Fantastic stuff as ever.

**Comment by AlDanial** [comment]
That was by design; the different output formats were meant only for the main results, never would have guessed the debug files need to be anything but text.

But now that you mention it I suppose it would make for easier programmatic ingestion.  I'll keep this open while I look at it some more.

**Comment by AlDanial** [comment]
Give 470af7d a try.

**Comment by jamesspo** [comment]
Thanks for this update. Sorry it too me a while to get to it.
The additional functionality looks good. Do you know if/when it will be available in a formal release?

**Comment by AlDanial** [comment]
I'm thinking January 2019 for the next release.
