### ISSUE TITLE
Deprecated Regex Use

### ISSUE THREAD

**Issue by lindgrenj6** [AlDanial/cloc#345]
Running Fedora 29, Perl 5.28.0
I get this when running cloc: 

Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by<-- HERE in m/({ <-- HERE |})/ at /bin/cloc line 7801.

**Comment by AlDanial** [comment]
If you use the latest version of cloc, 1.80, you'll see this is fixed; was reported earlier with #307.

**Comment by lindgrenj6** [comment]
@AlDanial my bad! This is just the latest version on Fedora so I assumed I had the latest. Closing.
