### ISSUE TITLE
Enhancement request - select only specific subdirectories

### ISSUE THREAD

**Issue by mr2001** [AlDanial/cloc#346]
I need to count lines of code in a specific sub-directory named 'gen' and I cannot just hard code the path to this directory because it can be anywhere inside a root directory (the path is variable). 
I cannot use match-d (i.e. --match-d = 'gen') as it's REGEX based and I don't want to include all sub-directories that contain 'gen'.
Please provide a new way to count loc only in specific directories.

**Comment by AlDanial** [comment]
cloc and ``--match-d`` can already handle your situation.

Let's say I have four source files spread across this directory structure:
<pre>
 /tmp/gen/c++.C
 /tmp/gen/gen/fortran.f
 /tmp/gen/gen/gen/python.py
 /tmp/gen/gen/gen/gen/ansi_C.c
</pre>
and I want to count the Fortran file in ``/tmp/gen/gen``, but not any of the other files.  Starting in the ``/tmp`` directory, if I run cloc with only ``--by-file`` and no other arguments I'll see all four files:
<pre>
/tmp> cloc --by-file gen
       4 text files.
       4 unique files.
       0 files ignored.

github.com/AlDanial/cloc v 1.81  T=0.01 s (474.4 files/s, 29412.1 lines/s)
--------------------------------------------------------------------------------------
File                                    blank        comment           code
--------------------------------------------------------------------------------------
gen/gen/fortran.f                          15             53            109
gen/c++.C                                   9              4             23
gen/gen/gen/python.py                       5              3             15
gen/gen/gen/gen/ansi_C.c                    0              7              5
--------------------------------------------------------------------------------------
SUM:                                       29             67            152
--------------------------------------------------------------------------------------
</pre>

To isolate files in the ``/tmp/gen/gen`` directory I can craft a regex which matches the initial ``gen/gen`` but then does a negative look-ahead assertion to reject all subsequent directories with a ``gen``:

<pre>
/tmp> cloc --by-file --fullpath --match-d '/tmp/gen/gen(?!.*/gen)' gen
       1 text file.
       1 unique file.
       0 files ignored.

github.com/AlDanial/cloc v 1.81  T=0.01 s (147.9 files/s, 26179.3 lines/s)
-------------------------------------------------------------------------------
File                             blank        comment           code
-------------------------------------------------------------------------------
gen/gen/fortran.f                   15             53            109
-------------------------------------------------------------------------------
</pre>

I find https://regex101.com/ helpful in creating and checking unusual regular expressions.
