### ISSUE TITLE
Counting lines in VB6 forms and controls doesn't count control code

### ISSUE THREAD

**Issue by craigsa1** [AlDanial/cloc#347]
When counting VB6 forms or controls it appears CLOC does not count the controls and metadata code that is used to render the form. When I open the file in a text file editor with line numbers I see that there’s a total of 130 lines.  There’s not much too this form – it basically has three sections:

Upper Section:  All of the code that contains the position and properties of the various UI elements, like this:
Begin VB.Form frmChoice 
   BorderStyle     =   1  'Fixed Single
   Caption         =   "Server Unavailable"
   ClientHeight    =   3030
   ClientLeft      =   45
   ClientTop       =   330
   ClientWidth     =   4590
   BeginProperty Font 
      Name            =   "Segoe UI"
      Size            =   8.25
      Charset         =   0
      Weight          =   400
      Underline       =   0   'False
      Italic          =   0   'False
      Strikethrough   =   0   'False
   EndProperty

Middle Section:  Standard comments that used to be added to all of our projects, like this:
' Copyright � 2001-2003
' All Rights Reserved.

Lower Section:  All of the code that you see when you open the project in VB (event handlers, mostly), like this:
Public Message As String
Option Explicit
Private Sub btnExit_Click()
    UserChoice = 3
    Unload Me
End Sub

CLOC:  18 lines of 130 qualify as “code” and 112 lines of comments.  

As you can see, CLOC does not appear to count all of the lines of code that position the textboxes and set the various properties.  Instead, it reported almost all of these lines as “comment” lines.  

Should these lines be counted as code?

**Comment by AlDanial** [comment]
Please attach a complete file that demonstrates the problem.

Also, it will be a week or so before I'm able to investigate fully.

**Comment by craigsa1** [comment]
Thanks for looking at this... I attached the file.

[frmChoice.zip](https://github.com/AlDanial/cloc/files/2600333/frmChoice.zip)

**Comment by AlDanial** [comment]
Looks like cloc is precisely following its rules for Visual Basic, namely, to count everything above a line beginning with ``Attribute VB_Name ...`` as a comment.

I'm not a VB programmer--I just applied rules other VB programmer(s?) supplied me at least six years ago.  But the fact that no other VB programmers have faulted this logic since the makes me think I ought to leave it as-is.
