### ISSUE TITLE
Using strip-str-comments to avoid "Complex regular subexpression recursion limit" does not count comments

### ISSUE THREAD

**Issue by tchajed** [AlDanial/cloc#350]
I'm running into #245 (and its many duplicates) due to a `/*` in a string:

```
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.80/libexec/bin/cloc line 9051.
```

I can silence this error with `--strip-str-comments`, but unfortunately this causes all comments to become lines of code, which is problematic.

## System info
- target language: Go
- cloc version 1.80
- macOS 10.14.1
- perl:
  ```
  This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
  (with 2 registered patches, see perl -V for more detail)
  ```

## Reduced reproduction

This is the best I could do, by deleting random parts of the code while still making sure it looks like Go and preserves the error:

```go
package fs

func List() []string {
	afero.Glob("/*")
}

func (fs aferoFs) AtomicCreateWith(fname string, data []byte) {
	tmpFile := Sprintf("%s.tmp", fname)
}

// this is a comment

func deleteTmpFiles(fs afero.Fs) {
	if err != nil {
		panic(err)
	}
	for _, n := range tmpFiles {
		fs.Remove()
		if err != nil {
		}
	}
}
```

**Comment by AlDanial** [comment]
Thanks for your report; it revealed a glaring logic error with how ``--strip-str-comments`` was dealing with comments.  It mistakenly replaced all comments with the literal 'xx' instead of just those in quotes.
