### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by mr2001** [AlDanial/cloc#351]
Hello,

I requested a new feature a while ago so that CLOC can wait an indefinite period of time until the count completes. It shows as as done, however the documentation was not updated. Please confirm that using the syntax below will force CLOC to wait as long as needed in order to count all lines of code and will not timeout before the count completes:
**--timeout 0**

**Comment by villelaitila** [comment]
The original need is addressed in https://github.com/AlDanial/cloc/commit/1252dc0b71740fb64757b984b8af28f86a90b433 released in 1.84

**Comment by AlDanial** [comment]
Yes, ``--timeout 0`` will allow unlimited time.  Thanks for pointing out the web documentation was out of date, should be good now.
