### ISSUE TITLE
Consistent URL scheme to download cloc

### ISSUE THREAD

**Issue by matthiasdiener** [AlDanial/cloc#352]
Could you please make the URL scheme for cloc releases (https://github.com/AlDanial/cloc/releases) consistent between versions? E.g., the URL to download v1.80 is 
https://github.com/AlDanial/cloc/releases/download/v1.80/cloc-1.80.tar.gz 
while v1.78 has the URL
https://github.com/AlDanial/cloc/releases/download/1.78/cloc-1.78.tar.gz
(note the missing 'v' before the first '1.78').

This makes it easier for packing tools such as Spack (see e.g. this PR: https://github.com/spack/spack/pull/10029/files)

Thank you!

**Comment by AlDanial** [comment]
Yes, that was messy.  I updated the releases by removing the 'v' and will follow the pure numeric form in the future.

**Comment by matthiasdiener** [comment]
Nice, thanks!

**Comment by foutrelis** [comment]
cloc-1.82.tar.gz appears to be available as https://github.com/AlDanial/cloc/files/3142727/cloc-1.82.tar.gz

The `3142727` part can't be resolved automatically (i.e.: isn't based on the version). How come the tarball is apart from the regular release assets?

**Comment by AlDanial** [comment]
Might have been a temporary issue; when I hover over the link it resolves to
https://github.com/AlDanial/cloc/archive/1.82.tar.gz

**Comment by AlDanial** [comment]
OK I see what you were talking about; I removed the link that was added by github to the summary section.
