### ISSUE TITLE
Support eex files in Elixir

### ISSUE THREAD

**Issue by eksperimental** [AlDanial/cloc#353]
While it is not documented (I've meant trying to submit this addition for ages), Elixir supports a third file extension, which is `.eex` which is the default templating system
more info.
https://hexdocs.pm/eex/EEx.html

**Comment by AlDanial** [comment]
``.eex`` has been supported for more than three years, ref 
https://github.com/AlDanial/cloc/commit/c012198345cb16df4cbbe4534c1ac8df7511e31f#diff-edcdf5f167fed588d696189d1befe8dc
<pre>
> cloc --show-ext eex
eex             -> EEx
> cloc --explain EEx
EEx
    filter remove_between_general  <%#  %>
    extensions: eex
</pre>
The latest release, 1.80, will get you that plus lots of bug fixes.

**Comment by eksperimental** [comment]
Then, the readme file should reflect this

**Comment by AlDanial** [comment]
True, ``README.md `` was out of date for a while.  I updated it with a lot of new content on Dec. 3 (although I don't recall if ``eex`` was added then or earlier). It does appear now:
<pre>
> grep -n eex README.md                                               
977:EEx                        (eex)
</pre>

**Comment by eksperimental** [comment]
I see, Eex is listed a its own language, and it should be the third extension missing in Elixir.
