### ISSUE TITLE
Bundled Regexp::Common licensing issue

### ISSUE THREAD

**Issue by relrod** [AlDanial/cloc#36]
Hey! Thanks for `cloc`, it's awesome!

I maintain the `cloc` package in Fedora and just got [notified](https://bugzilla.redhat.com/show_bug.cgi?id=1281479) that Cloc bundles a version of `Regexp::Common` that both [Fedora](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Bad_Licenses) and [GNU](https://www.gnu.org/licenses/license-list.html#ArtisticLicense) consider non-free. Newer versions of Regexp::Common use other licenses in addition, which *are* considered free.

Would it be possible to either bump the bundled `Regexp::Common` to something with a free license or (perhaps preferably) stop bundling it and just depend on it and use its API? Would this break anything? (I'm not sure what the original reason for bundling was.)

**Comment by AlDanial** [comment]
hi @relrod I'm a big fan of Fedora, used Fedora Core 4 many years ago and all revs after until about Fedora 20 (eventually moved to Ubuntu).

Thanks for your efforts in maintaining the Fedora package for cloc!

I will certainly grab the latest Regexp::Common and will roll it into cloc to give you a workable licensing setup.  I expect to have a few hours free this coming Friday and will tackle that then. 

I know, it seems weird (other adjectives probably spring to your mind as well) to embed Regexp::Common and other dependencies inside cloc.  When I first started, my funders were manager-types who weren't proficient at running <code>perl -MCPAN -e shell</code> to install dependencies.  They needed something that just runs, batteries included, etc.  I've found it convenient myself, when working on a new machine or one not connected to the internet or not having privileges to install modules, and have cloc work right off the bat.  Inelegant, admittedly, but wonderful convenience.

**Comment by AlDanial** [comment]
Commit 157c370 includes Regexp::Common 2013031301.

**Comment by relrod** [comment]
@AlDanial Thank you so much for the quick fix and the explanation!

**Comment by relrod** [comment]
@AlDanial do you know when this might land in a release? Not sure if I should bump the package to use a git snapshot or not - if a release is pending fairly soon, I'll probably just wait it out.

**Comment by AlDanial** [comment]
Is Jan 31 2016 too late for the next release?

I had another thought:  when someone pulls cloc from a package, the package manager should automatically handle dependencies.  Therefore in future releases I'll also include a "no-included-dependencies" version of cloc which will need Regexp::Common, Digest::MD5, and Algorithm::Diff as external dependencies.

**Comment by AlDanial** [comment]
I've released v1.66 which contains a version of cloc stripped of the internally-bundled Regexp::Common and Algorithm::Diff.  You can find it in the "Unix/" subdirectory of the source distribution.  This should be much easier (& cleaner) for package maintainers like yourself.
