### ISSUE TITLE
Consider fatpacking dependencies

### ISSUE THREAD

**Issue by Grinnz** [AlDanial/cloc#362]
The modules Regexp::Common and Algorithm::Diff are included in a somewhat complex way. It may be possible to leverage [App::FatPacker](https://metacpan.org/pod/App::FatPacker) to automate their inclusion as they both appear to be pure-perl modules. Essentially you would maintain the source script and then use fatpack commands to generate a script that contains the required code from these modules packed into it.

As a side note, Digest::MD5 has been part of the Perl core distribution since 5.8 (similar to Time::HiRes).

**Comment by Grinnz** [comment]
A recipe could look something like this:

```
fatpack packlists-for Algorithm::Diff Regexp::Common >packlists
fatpack tree `cat packlists`
fatpack file cloc.source >cloc
```

**Comment by AlDanial** [comment]
I can't figure it out, perhaps you know what's going on:  I have ``Algorithm::Diff`` installed as can be seen by
<pre>
> perl -MAlgorithm::Diff -e 'print $Algorithm::Diff::VERSION'
1.1903
</pre>

however the ``fatpack`` can't find it: 

<pre>
> fatpack packlists-for Algorithm::Diff Regexp::Common >packlists
Failed to load Algorithm::Diff: Can't locate Algorithm::Diff in @INC (@INC contains: lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/local/share/perl/5.22.1/App/FatPacker.pm line 149.

Make sure you're not missing a packlist as a result
Failed to load Regexp::Common: Can't locate Regexp::Common in @INC (@INC contains: lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/local/share/perl/5.22.1/App/FatPacker.pm line 149.

Make sure you're not missing a packlist as a result
</pre>

Anything obvious I need to do?

**Comment by Grinnz** [comment]
Did you install it via a system package? These often omit the packlists that FatPacker needs to function. A workaround is to install it into a local::lib and load it from there when packing.

**Comment by Grinnz** [comment]
Oh I misread the error, it is failing to load the module itself. Unfortunately the fatpack script still installs with an incorrect shebang so maybe it is running under the wrong perl. Try running it as `perl -S fatpack ...`

**Comment by AlDanial** [comment]
I switched to a machine that has only one Perl installed, ``/usr/bin/perl`` (5.22.1), and added ``App::FatPacker`` via ``cpan install App::FatPacker``(as root). 

Still get the same error.

**Comment by AlDanial** [comment]
I'm thinking FatPacker isn't quite ready for production use yet.  I'll revisit this in 6 months or so.
