### ISSUE TITLE
a "total" column is desired

### ISSUE THREAD

**Issue by zenglian** [AlDanial/cloc#364]
```
 blank        comment           code     total=(blank+comment+code)
1                2                        3           6
```

**Comment by AlDanial** [comment]
I added documentation that explains how you can use the ``--sql`` option to create output with a "total" column: https://github.com/AlDanial/cloc#custom-column-output-

**Comment by zenglian** [comment]
I still hope this is the default behavior so everyone does not need to google/search the document, and most of them would just give it up.

**Comment by ruohola** [comment]
Yes, would be really useful to just have a `--totals` flag or something which add the column.

**Comment by ruohola** [comment]
@AlDanial Would you be open to this if I would make a PR?

**Comment by AlDanial** [comment]
Sure, I'll consider a PR.

I'll be checking that the proposed code implements ``--total`` for all output variations, that is, ``--csv``, ``--yaml``, ``--xml``, ``--json``, ``--sql``.

**Comment by ruohola** [comment]
Might not have time do this after all.

**Comment by Keavon** [comment]
@AlDanial it would be awesome to have this reopened since a simple `--total` flag would be a considerable UX improvement. Thanks ❤️.

**Comment by wcjcn** [comment]
您的邮件已经收到，谢谢您。祝您生活愉快。

**Comment by AlDanial** [comment]
a5747ef7 added a total column for counts by language and by file, try
`cloc --fmt 2 your_code/` (by language) and
`cloc --fmt 3 your_code/` (by file)
The total is only written to STDOUT, not to CSV, YAML, XML, SQL or JSON files.

**Comment by AlDanial** [comment]
Correction:  I meant `cloc --fmt 5 your_code/` for by-file counts

**Comment by Keavon** [comment]
Very glad to see it @AlDanial, thank you! Do you think making `--total` an alias for these would help provide users with an easier user experience for this likely common use case?

**Comment by AlDanial** [comment]
`--total` may appear in a future release.  I'm in a slow process of re-implementing the output generator and haven't decided on how the UI will appear.  Next step is to support `--diff` in this new scheme, after that updates to CSV, etc, maybe then I'll have a sense for what's convenient, intuitive, and so on.
