### ISSUE TITLE
Complex regular subexpression recursion limit error

### ISSUE THREAD

**Issue by joshbressers** [AlDanial/cloc#365]
Hello,

I hit this error message
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.80/libexec/bin/cloc line 9051.

You can reproduce the issue with these steps
```
wget https://raw.githubusercontent.com/elastic/logstash/master/x-pack/src/test/java/org/logstash/xpack/test/RSpecTests.java
cloc RSpecTests.java
```

Let me know if you need anything else. Thanks for a great tool!

**Comment by AlDanial** [comment]
The problem was caused by the comment markers in ``"spec/**/*_spec.rb"``.  cloc's handling of these is kind of kludgey.  This tweak prevents the warning you saw though.
