### ISSUE TITLE
Add option to analyze a specific branch

### ISSUE THREAD

**Issue by dannyloweatx** [AlDanial/cloc#366]
Currently when I use cloc with the script I am building, I have to download the file as a zip file based on the branch or I have to find the latest commit and determine the branch. It would be optimal to specify the branch name within the command line. 
Ex.
cloc https://github.com/AlDanial/cloc.git --branch=master

**Comment by AlDanial** [comment]
That would be an amazing feature, but I do not plan to implement it.  I've deliberately avoided adding capabilities to download content from the internet for the can of worms it opens.

I'd consider a PR though.

**Comment by dannyloweatx** [comment]
I created a work-around for a nice solution using python. I did this for a
job interview :-)

https://github.com/dannyloweatx/checkmarx

If anyone else wants to do the same thing.

Thanks,
Danny

**Comment by AlDanial** [comment]
Nicely done!  I added a link to this at https://github.com/AlDanial/cloc#wrapping-cloc-in-other-scripts- .  
Let me know if you want the description expanded or modified.
(hope you got the job, btw)

**Comment by dannyloweatx** [comment]
Thanks! I appreciate that!
