### ISSUE TITLE
how to exclude specific types of comments

### ISSUE THREAD

**Issue by sadeshwar94** [AlDanial/cloc#367]
Hi, I would like to know how to exclude a specific type of comments types when counting lines of code using cloc ? Thank you.

**Comment by AlDanial** [comment]
Can you give an example of a type of comment to exclude?  If you can define such a comment with a regex there's a remote possibility this could be implemented.

**Comment by sadeshwar94** [comment]
Hi, I would like to specify the comments by myself, because in the case of the comments depends on the language files I do cloc,  
for an example, 
1. in the case of java language included repository,
   a). //
   b). /* abc */
   c). /** abc */ 
type of comments.

**Comment by sadeshwar94** [comment]
issue moved to #368
