### ISSUE TITLE
file extension collison between visua basic (.cls) and visualforce apex class (.cls)

### ISSUE THREAD

**Issue by sadeshwar94** [AlDanial/cloc#368]
HI, I'm getting different count comment output when cloc visualforce project which includes apex classes, I have found related project here [https://github.com/couchand/cloc-force/issues/1](url), 
i would like to know if you can help me with to deifine the differentiate between vb cls and apex cls language files, thank you.

**Comment by AlDanial** [comment]
The link you posted doesn't lead anywhere for me.  No matter.  To distinguish VB .cls and Apex .cls I'll first need a collection of examples for each.  I have some VB already, can you point me to Apex files?

**Comment by sadeshwar94** [comment]
Hi, 
Im sorry for the wrong link that I have added in the above comment, please sue following URL, [https://github.com/couchand/cloc-force/blob/master/force-def.txt](url) , i have tried this URL it does work for count comments of the apex class, but it doenst count deleted code when diff between two hash commits, im sorry to let you again there's no way i can point for Apex files that im using since its private data. Thank you.

**Comment by AlDanial** [comment]
I don't need your particular private Apex files, I just need some arbitrary representative Apex files to see if I can identify characteristics that would distinguish Apex from VB.  Perhaps you can make some dummy files?

**Comment by sadeshwar94** [comment]
@AlDanial Thank you for your quick response, The best I could help you is  with this project which I found on GitHub which is similar to the project that im working on, [https://github.com/financialforcedev/apex-mdapi/tree/master/apex-mdapi/src/classes](url) please check under .cls files, 
following additional comment syntax also count as a comment in salesforce project,
 1. /*** Comment here ***/ 
if you could help me to add this comment type as an additional other than normal comment syntax in apex classes,  Thank you. 👍

**Comment by AlDanial** [comment]
ae7050a adds support for Apex classes and  identifies ``.cls`` files as either Apex classes or Visual Basic based on their contents.
