### ISSUE TITLE
Mixed comments in single line badly processed

### ISSUE THREAD

**Issue by jolkdarr** [AlDanial/cloc#37]
When block comments and line comment are used in a single line, ```cloc```gets confused and miscounts comments and LS for the processed file. Observed with C/C++ files.
Example:
```c
/* data 1 */ // KO, processed as LS
int i;

/* data 2 */ /* OK, processed as comment */
int j;
```
Result:
```
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                1              1              1              3
```
Expected:
```
C                                1              1              2              2
```

**Comment by AlDanial** [comment]
I created a new branch, dev, and in it put git commit 914f775 which includes a big change in how C and C++ are counted.  Instead of using Regexp::Common's C comment regex then manually removing // comments, the change uses Regexp::Common's C++ comment regex.  This counts your mixed-comment example correctly; I'd appreciate it if you'd grab the code and tested it.

I'll need to do a good bit of testing myself before this goes to the master branch.

**Comment by jolkdarr** [comment]
Thanks for the quick fix and bug details.
First, I will perform tests with C/C++ files mixing comments and comments.
Other languages that have special syntax for multiline comments will be checked in a second round.

**Comment by jolkdarr** [comment]
I tested the ```cloc``` script from the ```dev``` branch with the following files (respectively C, CoffeeScript, C++ and JavaScript):
```c
/* data 1 */ // KO, processed as LS
int i;

/* data 2 */ /* OK, processed as comment */
int j;
```
```coffeescript
### data 1 ### #
i = 10

### data 1 ### ### xxxxxx ###
j = 55
```
```cpp
/* data 1 */ // KO, processed as LS
int k;

/* data 2 */ /* OK, processed as comment */
int l;
```
```js
/* data 1 */ // KO, processed as LS
var n = 100;

/* data 2 */ /* OK, processed as comment */
var b = n + 1;
```
The results are:
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Javascript                       1              1              1              3
C                                1              1              2              2
C++                              1              1              2              2
CoffeeScript                     1              1              2              2
-------------------------------------------------------------------------------
SUM:                             4              4              7              9
-------------------------------------------------------------------------------
```
With JavaScript files _ using C comment syntax, the bug is still present.
Further testing later..

**Comment by jolkdarr** [comment]
Note: the official name is JavaScript, ;)

**Comment by AlDanial** [comment]
On dev I did <code>s/Javascript/JavaScript/g</code> and also updated the filters for JavaScript, C#, Scala, Kotlin, and all other languages that recognize C++ style comments.

**Comment by jolkdarr** [comment]
All my tests are successful with the last commit. Bug sounds fixed. :)

**Comment by AlDanial** [comment]
Thanks for your testing efforts.
