### ISSUE TITLE
Disagree with line count

### ISSUE THREAD

**Issue by GitUser275** [AlDanial/cloc#370]
This extract from an Arduino sketch:

//Only do this if PC (Kenwood power setting) has changed:
      // Extract power setting
       if (new_PC==true){
        String power_value=(store_PC.substring(2,5));  //extract the power value from the PC response string
        KEN_pwr = power_value.toInt();                 //then convert that extracted string to integer
      //  Serial.print("Integer power = ");
      //  Serial.println(KEN_pwr);
       }

is reported by cloc-1.64 as having 1 comment line and 7 code lines.   All the indented comments seem to have been counted as code lines.  

Thanks.

**Comment by AlDanial** [comment]
A recent version of cloc, for example 1.80, will give better results.  This uses the current development version:
<pre>
github.com/AlDanial/cloc v 1.81  T=0.01 s (161.8 files/s, 1294.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              1              0              4              4
-------------------------------------------------------------------------------
</pre>

**Comment by GitUser275** [comment]
Thanks for letting me know I was not using the latest version.  I downloaded ver 1.80 and used it with my ino file but it produced the same incorrect results as before:

[cid:93fabf74-ba9f-4cc2-9d36-fed8d3c3e0c9]

Perhaps the file type influences the count result.  I have attached the test file that I used.

You showed the results for ver 1.81.  Did it work because you used 1.81 or because you used a different file extension?

Thanks,

Andy

________________________________

**Comment by AlDanial** [comment]
Yes, the source file's extension is important.  cloc uses that to determine which language filter to use.  What is the exact name of the file you're passing to cloc?

**Comment by GitUser275** [comment]
The test file was .ino.  When the extension was changed to .cpp the results were the same except that report showed language as C++ instead of Arduino Sketch:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\ANDY\cloc>cloc-1.80 test2.ino
       1 text file.
       1 unique file.
       0 files ignored.

github.com/AlDanial/cloc v 1.80  T=0.50 s (2.0 files/s, 16.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Arduino Sketch                   1              0              1              7
-------------------------------------------------------------------------------

C:\Users\ANDY\cloc>cloc-1.80 test2.cpp
       1 text file.
       1 unique file.
       0 files ignored.

github.com/AlDanial/cloc v 1.80  T=0.50 s (2.0 files/s, 16.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              1              0              1              7
-------------------------------------------------------------------------------



________________________________

**Comment by AlDanial** [comment]
This is a real mystery then.  Please upload the file so that I can have a closer look.  Something weird is going on.

**Comment by GitUser275** [comment]
Files with extension cpp or ino are not allowed.  Please rename the attached file from .txt to .ino and then .cpp.

[test2.txt](https://github.com/AlDanial/cloc/files/2897249/test2.txt)

**Comment by GitUser275** [comment]
I looked at the files with a hex editor and found the comment indentation is formed by 0xA0 and 0x20.   If the file is edited so the indent is formed by only 0xA0 then cloc produces the correct line counts.

I can't change what the Arduino IDE editor produces so hopefully cloc can be revised to see 0xA0 as a space character.

**Comment by AlDanial** [comment]
Yes, those 0xA0's are throwing things off.  I dug around cloc a bit and saw I added support for Arduino Sketch files (*.ino) a long time ago so I wondered how it could be that this problem hasn't shown up before?

For more insight, I installed the Arduino IDE, v1.8.8 for Linux 64, then saved the default file that the editor starts with, namely, ``sketch_feb24a.ino``:
<pre>
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
</pre>

I ran cloc on it and got the expected result:
<pre>
github.com/AlDanial/cloc v 1.81  T=0.01 s (156.9 files/s, 1411.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Arduino Sketch                   1              3              2              4
-------------------------------------------------------------------------------
</pre>

The file does contain 0x20 0xA0's, but never at the beginning of a line.  Is it possible your IDE has a weird setting?

**Comment by GitUser275** [comment]
"Is it possible your IDE has a weird setting?"

I'm not aware of any setting that I have changed from default.  My test files were created from a much larger .ino file by mouse click block copy and paste into notepad.   I only did that because the code line count seemed much too large when I tested the entire original sketch file.

In the original .ino file the comment idents were created by a mixture of tabs and spaces.  I suspect the tabs inserted by the IDE editor are the source of the problem.

________________________________

**Comment by AlDanial** [comment]
Had to throw the towel in on this one, in a sense, in that I added a new filter to be able to strip out problem characters like 0xA0.  The counts of ``*.ino`` files look correct now.
