### ISSUE TITLE
support for Lua nested comments

### ISSUE THREAD

**Issue by ziggurat29** [AlDanial/cloc#371]
Lua allows nesting of comments by supplying a variable number of '=' between the [[ and ]] (which must match in both cases.
The nested comments are quite handy for commenting out blocks of code which themselves contain comments (I'm sure you've tried this with C, and know you have to 'open' the internal close comment block to make it work.

E.g.
```
--[===[
multi 
line 
comment
--[==[
still comment
--[=[
still comment
--[[
still comment
--]]
--]=]
--]==]
--]===]
```

as a temporary workaround hack, I altered the filter thusly:
```
    'Lua'                => [
[ 'remove_between_general', '--[=====[', ']=====]' ],
[ 'remove_between_general', '--[====[', ']====]' ],
[ 'remove_between_general', '--[===[', ']===]' ],
[ 'remove_between_general', '--[==[', ']==]' ],
[ 'remove_between_general', '--[=[', ']=]' ],
                                [ 'remove_between_general', '--[[', ']]' ],
                                [ 'remove_matches'      , '^\s*\-\-' ],
                            ],
```
This only works to the additional 'levels' I specified -- there is no language requirement to use 'levels'; you simply can have as many '=' as you like and the closing tag must match that number.

A proper workaround would possibly be to have a regex for the opening tag like:
--\[\[(=*)\]\]
and then the closing tag would be synthesized from the captured number of '=' inserted between ']' s.

I don't think there is an existing mechanism for this sort of dynamic tag generation, so I guess it would need a little coding.

**Comment by AlDanial** [comment]
While the workaround hack for five levels isn't especially pretty, I'm more tempted to add that than code a general solution at the moment.  I'm more than happy to look at a general solution as a PR though.
