### ISSUE TITLE
Line count, exceeded timeout:

### ISSUE THREAD

**Issue by dluminello** [AlDanial/cloc#372]
Hello,

I am scanning several of our git repositories with cloc and it seems that I get this particular error on common files among the repositories.  Some (most) of them are from open source libraries.
Below are the ones that show up in all the scans that utilize them.

swagger-ui.min.js
angular.min.js
jspdf.min.js
d3.js

**Comment by AlDanial** [comment]
If you're working with the Perl source version (as opposed to the Windows exe), you can make a tweak to try to get around this.  Search for this code block

<pre>
        # Unusual inputs, namely /* within strings without
        # a corresponding */ can cause huge delays so put a timer on this.
        my $max_duration_sec = scalar(@lines)/1000.0; # est lines per second
           $max_duration_sec = 1.0 if $max_duration_sec < 1;
#print "max_duration_sec=$max_duration_sec\n";
        eval {
            local $SIG{ALRM} = sub { die "alarm\n" };
            alarm $max_duration_sec;
            no strict 'refs';
            @lines = &{$subroutine}(\@lines, @args);   # apply filter...
            alarm 0;
        };
</pre>
then change the line
<pre>
$max_duration_sec = 1.0 if $max_duration_sec < 1;
</pre>
to have a value much larger than 1.0.  This is the number of seconds to allow the parser to do its thing.  However, you may not be pleased with the result as this is in a code branch where the parser is already confused and may take a long time with little to show for its efforts.  These minified JavaScript files really mess up cloc's line-centric parsing model.

**Comment by dluminello** [comment]
Thanks you for the reply.  As of right now we are using the Windows exe version and not the Pearl source version.  For now at least I understand what the problem is and not counting a couple hundred (if that) lines of code in those files is not a huge issue.

**Comment by asadcr** [comment]
@AlDanial I have similiar issue, CLOC is flaky, sometimes there is exceeded Timeout, sometimes it doesn't. Could it be possible to provide a switch for this. similar to `--diff-timeout`

**Comment by wrljet** [comment]
I get the timeout, too, Windows 7 with a SSD.
On assembler source files, large-ish ones.

**Comment by duaneking** [comment]
How do I fix this? The issue says closed, but I have this exact issue on the newest binary.

**Comment by duaneking** [comment]
Using the `--timeout` param doesn't seem to be well documented. 

The help makes it seem like it's completely different and it doesn't create the output that makes it seem like it's going to be a problem for people trying to do things such as run CLOC on the chromium code base.

It needs dramatically updated, and is a critical doc bug. When I scanned the help parameters before running everything I should have been able to easily see that this was going to be a problem for me, And I'm on ssd's so this shouldn't be a problem for me anyway so I cant help but feel like a timeout that by default is not even documented is just bad design.

**Comment by duaneking** [comment]
#867
