### ISSUE TITLE
No such file or directory at C:/Strawberry/perl/lib/File/Find.pm line 470.

### ISSUE THREAD

**Issue by dluminello** [AlDanial/cloc#373]
Hi,

I have one repository that I am scanning and the job keeps failing with the below error.
Can't cd to ../../../../../../../.. from C:\Jenkins\jobs\Test-CLOC\workspace\temp/sites/all/modules/contrib/service_container/modules/providers/service_container_annotation_discovery/tests/modules/service_container_annotation_discovery_test/src/Plugin/Plugin5/Plugin5A: No such file or directory at C:/Strawberry/perl/lib/File/Find.pm line 470.

I did see in another issue/comment about Long paths under windows being an issue.  So I did set the Git longpaths to true.  Not sure what else the issue could be.
git config --system core.longpaths true

**Comment by AlDanial** [comment]
Yeah, this is a repeat of #58.  The limitation is within Perl itself so there isn't much I can do.  A suggestion was made under that issue about UNC paths, so possibly try that--and report results there too.
