### ISSUE TITLE
cloc counts python triple-quoted strings as comments

### ISSUE THREAD

**Issue by rrthomas** [AlDanial/cloc#375]
But this is only the case when they're docstrings!

Tested with 1.74 and 1.80.

**Comment by AlDanial** [comment]
I get that a triple quoted string on the RHS of an = would be a regular string, not a comment.  I can check for that.  But it gets trickier, to the point at which I'm parsing the Python language itself.  Example:  a triple quoted string passed as an argument to a function.  Not a comment, but hard to identify as such.

**Comment by rrthomas** [comment]
It's precisely the second case that is failing for me: a triple-quoted string passed as an argument.

**Comment by AlDanial** [comment]
Python docstrings may have to appear as a new entry under https://github.com/AlDanial/cloc#limitations-

Here's where I'm at.  I created this test input which runs in Python 3.7.1:
<pre>
#!/usr/bin/python
"""docstring: yes"""
def Len(a, b, c="""
        docstring: no"""):
    """
    docstring: yes
    """
    return a + len(c)
a = """docstring: no"""
b = Len(3, len('"""'), """
        docstring: no""")
c = Len(0, """ ( docstring: no
                 """);   """docstring: yes
"""
"""docstring: yes """ """docstring: yes """
"""docstring: yes """ ; a = """docstring: no
"""; """docstring: yes """
d = \
    """
    docstring: no
    """ \
"""docstring: yes """ """docstring: yes """
e = \
    """
    docstring: no
    """ """docstring: yes """
f = ' """ ' """
    docstring: yes"
    """ """docstring: yes """
</pre>

My attempts to identify the ``yes`` and ``no`` cases have been ineffective.  I know you're a skilled programmer--can you devise pseudo-code to parse this?

**Comment by rrthomas** [comment]
Thanks very much for looking into this. I think it's a job for a proper parser; solving it successfully in an ad-hoc way would be very tricky. So given that full-blown parsing is outside cloc's remit, I think filing it under "limitations" is better.

I'd be quite happy to have a switch that counts strings as code rather than comments; presumably (unlike the C example!) that would be straightforward to implement? For now I'm using sloccount, which seems to do that (as far as I can tell from a brief comparison of line counts).

**Comment by AlDanial** [comment]
Yes, adding the switch was easy.

**Comment by rrthomas** [comment]
You're a star, many thanks!

**Comment by ybalcanci** [comment]
@AlDanial I think docstrings indicated with triple-single-quotation are counted as code instead of comment.
