### ISSUE TITLE
diff count between last two commit hash

### ISSUE THREAD

**Issue by sadeshwar94** [AlDanial/cloc#376]
Hi, im getting this error when I try to get diff count between last two commits,

`cloc --diff --by-file  HEAD^ HEAD
    5367 text files.
Error: in correct length fh array when preparing diff at step 6.
`
is there any way that i can get cloc counts between last two commits hashes without giving hash commit manually, Thank you.

**Comment by AlDanial** [comment]
You forgot to include the ``--git`` switch.  This works:
<pre>
cloc --git --diff --by-file HEAD^ HEAD
</pre>

**Comment by sadeshwar94** [comment]
@AlDanial yes it did work, Thank you
