### ISSUE TITLE
git cloc diff showing the same file as both added and removed in diff-alignment

### ISSUE THREAD

**Issue by p27130** [AlDanial/cloc#378]
We are using a command of this form to calculate LOC between one branch and another branch where HASH1 is on one git branch and HASH2 is on another git branch:
cloc --git --diff HASH1 HASH2 --by-file --report-file=/tmp/report --diff-alignment=/tmp/da

When I look at /tmp/da (for diff-alignment) it contains something that looks like this.  Note that the same file name is both added and removed which I would not expect:

---
Files added: 1
  + /tmp/QoCbOZnqN8/common/inc/somefile.h ; C/C++ Header

Files removed: 1
  - /tmp/MUWimuzpxT/common/inc/somefile.h ; C/C++ Header
---

And the /tmp/report looks something like this.  Again, notice that somefile.h is both added and removed:

---
common/inc/somefile.h
 same                                                                                     0              0              0
 modified                                                                                 0              0              0
 added                                                                                  225           7412           3512
 removed                                                                                  0              0              0
common/inc/somefile.h
 same                                                                                     0              0              0
 modified                                                                                 0              0              0
 added                                                                                    0              0              0
 removed                                                                                212           7407           3399
---

But if we manually copy out somefile.h at HASH1 and HASH2 and run "cloc --diff" without the git options we get the correct answer which is that there were some lines modified between HASH1 and HASH2 but the file was not entirely recreated.

The issue is...   Why would cloc show in a git diff-alignment the same file name both added and removed?

Unfortunately I can't send the code example because it is proprietary.  I tried to create a simple example of the problem but it was difficult to recreate using a simple example.   I did isolate the issue down to a specific commit that we have.  And that commit has some file adds, some file deletes, some file modifications, some R100 codes (meaning that files were moved to another directory), and even an R095 code (meaning that a file was moved to a new name but is 95% similar to a prior to commit.

Turning on verbosity for this issue I can see that cloc is doing a git archive of the file.  I typed that command manually and it worked.  I then untarred the archives and did a diff between those untarred archives and that seemed to work.   But somehow cloc still calculates that a file by the same name has a diff-alignment issue between two git hashes???

**Comment by AlDanial** [comment]
Definitely weird.  Until I'm able to reproduce the behavior you're seeing, I doubt I'll be able to figure this out.  When you created your simple example, did the git commit have the same characteristics and Rxxx codes as the original?

**Comment by p27130** [comment]
I tried to have the simple example match the code base.  However, I am unsure as to what is causing the diff-alignment to show the same file as added/removed so it was difficult to say where I should take the simple example in order to make it more accurate.  Perhaps one thing that would help would be a brief description of how the diff-alignment is determined with cloc.  For example, if I use the simple git command of "git diff --name-only HASH1 HASH2" it shows me that the files described are modified (which is correct) rather than being added/deleted.   So if the raw git commands are showing the files as modified I would have thought that the cloc diff-alignment would also show the files as modified rather than as deleted and re-added.   But perhaps the calculation of the diff-alignment with git is using a different algorithm which I would need to understand to at least a basic level in order to see where to take the simple example to make it more accurate.

**Comment by AlDanial** [comment]
If you're up for it, I can guide you through placing debug statements in the Perl source to pinpoint how one file is inserted into both added and removed lists.  The first step would be to uncomment the print statements on lines 1545-1547.  Then add a ``die`` statement to stop the run there:
<pre>
 1539 align_by_pairs(\%{$unique_source_file{$fset_a}}      , # in
 1540                \%{$unique_source_file{$fset_b}}      , # in
 1541                \@files_added_tot                     , # out
 1542                \@files_removed_tot                   , # out
 1543                \@file_pairs_tot                      , # out
 1544               );
 1545 use Data::Dumper;
 1546 print "added : ", Dumper(\@files_added_tot);
 1547 print "removed : ", Dumper(\@files_removed_tot);
 1548 die;
</pre>

**Comment by p27130** [comment]
Thanks for the response.  I am using cloc version 1.80 so I found the align_by_pairs on line 1529 rather than line 1539.  I made that edit and received the dump.   For the dump I protected the proprietary nature of the source by changing the names of the files to be consistent with this issue report.  Specifically somefile.h.  In the specific scenario that I am running in to there are actually a total of 7 of these files where I would expect them to be diffed rather than showing up as "Added/Removed".  So those become "somefile.h", somefile2.h, ..., somefile7.h in the dump.   All other filenames which were diffed correctly are then listed as "ok" in the dump.  Here is the output:

      60 text files.
      32 text files.
added : $VAR1 = [ue files.
          '/tmp/CCybV9xYIY/common/src/somefile5.cpp',
          '/tmp/CCybV9xYIY/ok1',
          '/tmp/CCybV9xYIY/common/src/somefile6.c',
          '/tmp/CCybV9xYIY/common/inc/somefile2.h',
          '/tmp/CCybV9xYIY/dir/inc/somefile7.h',
          '/tmp/CCybV9xYIY/common/inc/somefile.h',
          '/tmp/CCybV9xYIY/common/inc/somefile3.h',
          '/tmp/CCybV9xYIY/ok2',
          '/tmp/CCybV9xYIY/common/inc/somefile4.h'
        ];
removed : $VAR1 = [
          '/tmp/gUo_ssw4l5/ok3',
          '/tmp/gUo_ssw4l5/common/inc/somefile3.h',
          '/tmp/gUo_ssw4l5/ok4',
          '/tmp/gUo_ssw4l5/ok5',
          '/tmp/gUo_ssw4l5/ok6',
          '/tmp/gUo_ssw4l5/ok7',
          '/tmp/gUo_ssw4l5/ok8',
          '/tmp/gUo_ssw4l5/ok9',
          '/tmp/gUo_ssw4l5/ok10',
          '/tmp/gUo_ssw4l5/common/inc/somefile2.h',
          '/tmp/gUo_ssw4l5/ok11',
          '/tmp/gUo_ssw4l5/ok12',
          '/tmp/gUo_ssw4l5/common/inc/somefile4.h',
          '/tmp/gUo_ssw4l5/ok13',
          '/tmp/gUo_ssw4l5/ok14',
          '/tmp/gUo_ssw4l5/ok15',
          '/tmp/gUo_ssw4l5/dir/inc/somefile7.h',
          '/tmp/gUo_ssw4l5/ok16',
          '/tmp/gUo_ssw4l5/ok17',
          '/tmp/gUo_ssw4l5/ok18',
          '/tmp/gUo_ssw4l5/common/inc/somefile.h',
          '/tmp/gUo_ssw4l5/ok19',
          '/tmp/gUo_ssw4l5/common/src/somefile6.c',
          '/tmp/gUo_ssw4l5/ok20',
          '/tmp/gUo_ssw4l5/ok21',
          '/tmp/gUo_ssw4l5/ok22',
          '/tmp/gUo_ssw4l5/ok23',
          '/tmp/gUo_ssw4l5/common/src/somefile5.cpp',
          '/tmp/gUo_ssw4l5/ok2',
          '/tmp/gUo_ssw4l5/ok24',
          '/tmp/gUo_ssw4l5/ok25',
          '/tmp/gUo_ssw4l5/ok26',
          '/tmp/gUo_ssw4l5/ok27',
          '/tmp/gUo_ssw4l5/ok28',
        ];
Died at /tools/utilities/cloc/cloc-1.80/cloc.debug_issue_378 line 1539, <$fh> line 32.

**Comment by AlDanial** [comment]
Next up you'll need to uncomment the debug statements in ``align_by_pairs()``.  This is the routine that populates the added and removed arrays.  I'll need you to tell me which lines in this routine add your somefile.h to both lists.  It is likely you'll need to add your own print statements; my guess is even if you're not a Perl programmer you'll know what to do.

**Comment by p27130** [comment]
Some initial feedback...

The %added contains entries that look like this. Note that the same file is shown twice but the second prefix does not include the /tmp/...
$VAR2 = '/tmp/aXlI1trUGA/common/inc/somefile.h';
$VAR3 = '/common/inc/somefile.h';

The %deleted contains the same file twice by comparison:
$VAR18 = '/tmp/0RDDr7bT_4/common/inc/somefile.h';
$VAR19 = '/tmp/0RDDr7bT_4/common/inc/somefile.h';

It looks like the other 6 files that show up as added/deleted show a similar pattern of being listed twice in %deleted and in the %added the second occurrence does not have the /tmp prefix.

**Comment by p27130** [comment]
There is a difference between leading_dir_L and leading_dir_R.   Specifically leading_dir_L has a suffix to /tmp/blah whereas leading_dir_R does not.   That seems to be where %added has one entry with /tmp/blah as the prefix and another entry without /tmp/blah as the prefix.

Let's call that suffix to leading_dir_L as "somesubdir".   In this particular git commit there were some files in "somesubdir" which were moved up a directory level.   For example, "git mv somesubdir/* ." and then add/commit that.   That then has leading_dir_L set to /tmp/blah/somesubdir whereas leading_dir_R has /tmp/blah without the somesubdir extension.

Then when it comes to the %added and %deleted the hash gets files put in to these hashes because of the condition "$f unless defined $stripped_L{$f};".   Where $f may NOT be in stripped_L because $stripped_L has /tmp/blah/somesubdir whereas stripped_R does not have somesubdir.

The issue is something along those lines.   However, that said...  I tried a couple of modifications to try to protect against that scenario and it didn't work.   It might give you a clue though as to what is going on.

**Comment by p27130** [comment]
Going back to the 7 files...   They are not in "somesubdir" on the stripped_L.

So the ones that are in "somesubdir" that got moved one directory up did get calculated correctly as being "common".   But for those files modified that were not originally in "somesubdir" those are the ones where the leading_dir_L has "somesubdir" as a suffix but the 7 files were never in "somesubdir".

So it seems like the calculation to add "somesubdir" as a "leading_dir_L" is ok for those files that were moved one level up.  But for those files that were modified that were not in "somesubdir" those are the ones that show up as added/removed rather than as modified because the leading_dir_L is calculating "somesubdir" differences where the 7 files were not in "somesubdir".

**Comment by AlDanial** [comment]
Thanks for doing the deep dive into this.  Based on your evidence I'll make a git repo that has characteristics you're describing:  variations of files starting in a subdir, being modified, then moved one dir up, modified again, with git commits at every step.  I'll do cloc git diff's for all pairwise commits to see if I can capture the behavior.

**Comment by p27130** [comment]
Thanks.  Keep in mind that the 7 files that were shown as added/removed were not in the "somedir".  So although there was a seperate activity of moving files one directory up that side effect seemed to be to have a different "leading_dir_L".  But the 7 files that were shown as added/removed were modified but not originally in "somedir".  The hypothesis which I can't seem to prove is that the addition of "somedir" to the suffix of leading_dir_L causes the other 7 files which were not in "somedir" to go out of "diff-alignment".

**Comment by AlDanial** [comment]
I'm uncertain 63d213c will help this situation but I did make what I believe to be improvements in how ``--git --diff`` works.  Please try it out if you get a chance.

**Comment by p27130** [comment]
Thanks for the commit at 63d213c.  Some good news and bad news...   The good news is that the files that were showing as new and then deleted are now being diffed properly with this commit.  The bad news is that files that were simply "moved" from one directory to another directory are showing as being added/removed rather than diffed.  On the previous version of cloc those were being shown as correctly diffed.  So now we have shifted the problem.  Specifically, the 7 files that were previously shown as added/removed are correctly diffed now.  But now I have another set of 21 files which moved directories which on the previous version of cloc had them diffed but with this new version they show up as added/removed.  So 7 steps forward and 21 steps back...   Maybe I can identify a simple use case.

**Comment by p27130** [comment]
Ok, here is an easy example to demonstrate the problem with commit 63d213c...   What I would expect is that file1.c, file2.c, and file3.c would end up being diffed rather than being marked as added/removed.  But the result of adding cloc is that only file2.c is diffed correctly.  The file1.c and file3.c show up as added/removed in /tmp/out2 after the script is run.  And /tmp/out1 reports file1.c and file3.c twice (as being fully added/removed) rather than being diffed....

#!/bin/bash
git init
mkdir dir
echo "unsigned int test=0;" > dir/file1.c
printf "unsigned int test2=0;\n" > dir/file2.c
echo "unsigned int test3=0;" > dir/file3.c
git add --all
git commit -m "master commit1"
git checkout -b branch1
git mv dir/file2.c .
mkdir dir2
git mv dir/file3.c dir2/
git add --all
git commit -m "branch1 commit1"
cloc --git --ignore-whitespace  --diff `git show-ref -s master | head -1` `git show-ref -s | head -1` --by-file --report-file=/tmp/out1 --diff-alignment=/tmp/out2

**Comment by AlDanial** [comment]
After running your script, master has
<pre>
dir/file1.c
dir/file3.c
dir/file2.c
</pre>
and branch1 has
<pre>
dir/file1.c
dir2/file3.c
</pre>
The diff alignment logic should pair up files by common path names and the only common name between these is ``dir/file1.c``.  Anything else ought to be seen as an addition or removal.  So, yes, there is a bug because your example shows the alignment isn't working the way I intended--the file that should have been diff'ed is ``dir/file1.c``, not ``dir/file2.c``.  I'll investigate.

Also, I agree, ``file1.c`` shows up twice in the output, definitely wrong.   However ``file3.c`` correctly appears as two separate files, namely ``dir/file3.c`` and ``dir2/file3.c``.

**Comment by p27130** [comment]
Sounds good.  I might suggest that we close this issue with what you have mentioned above (once fixed) and then open up a lower priority issue with investigating whether cloc can use the "git similarity index" as mentioned in the following.

A description of the lower priority issue might go like this...

In an ideal world cloc would consider file3.c as the same file and not two different files.  If you are familiar with the "git similarity index" it becomes apparent that git already knows that a file is the same as used on a previous commit with possibly some small subset of changes.  For example, if you run this command after the simple example above: `git diff --name-status `git show-ref -s master | head -1` `git show-ref -s | head -1`` then what you will see is something like this:

`R100    dir/file3.c     dir2/file3.c
R100    dir/file2.c     file2.c`

The R100 indicates that it is 100% the same and therefore git knows that dir/file3.c was moved to dir2/file3.c.  If you were to modify the simple example to add a line to file3.c as a third commit on branch1 like so:

`#!/bin/bash
echo "unsigned int test4=0;" >> dir2/file3.c
git add --all
git commit -m "branch1 commit2"`

And then again run `git diff --name-status `git show-ref -s master | head -1` `git show-ref -s | head -1`` it will show something like this:

`R050    dir/file3.c     dir2/file3.c
R100    dir/file2.c     file2.c`

In the above example, we have not only moved file3.c from dir to dir2 but we have additionally modified 50% of the lines in the file.  And git knows this thru a "git similarity index" of R050 which means 50% similar.

The idea here is that cloc could update its diff-alignment based on this git similarity index when --git and --diff options are passed to cloc to figure out whether a file should be diffed or whether it should be considered newly added and then deleted.

The reason for this enhancement request is because developers move files in directories around all the time.  And quality metrics for a development organization likely should not "double count" line of code metrics for files that were simply moved to another directory.  In other words, the quality organization of a development team would receive faulty metrics if we consider files that were moved to another directory to be "newly created code" because it isn't newly created code.  Rather it is just reorganized code in to a separate directory.

**Comment by AlDanial** [comment]
I'm implementing the git similarity index you suggested.  One thing I'm struggling with is how to interpret git's output when file paths have spaces (not common on Linux but ever-present on Windows).

I expanded your bash script to include
<pre>
git init
mkdir dir
echo "unsigned int test=0;" > dir/file1.c
printf "unsigned int test2=0;\n" > dir/file2.c
echo "unsigned int test3=0;" > dir/file3.c
echo "print(1);"  > 'dir/file with spaces.c'
echo "print(11);" > 'dir/another file with spaces.c'
echo "print(21);" > 'dir/no_spaces.c'
git add --all
git commit -m "master commit1"
git checkout -b branch1
git mv dir/file2.c .
mkdir dir2
echo "print(2);" > 'dir/file with spaces.c'
git mv dir/file3.c dir2/
git mv 'dir/another file with spaces.c' dir2/no_spaces.c
git mv 'dir/another file with spaces.c' dir2/
git mv 'dir/no_spaces.c' dir2/
git add --all
git commit -m "branch1 commit1"
</pre>
after which `` git diff -M --name-status <hash left> <hash right>`` reports
<pre>
 M       dir/file with spaces.c
 R100    dir/file3.c     dir2/file3.c
 R100    dir/another file with spaces.c  dir2/no_spaces.c
 R100    dir/file2.c     file2.c
</pre>
There are many ways to fail parsing the third line properly.  Let me know if you have any ideas on separating the left and right file paths.

**Comment by hid-saka** [comment]
The original issue has happened again.

C:\git\repository1>cloc --git --diff --by-file 80768712defb1c66264c9f796abeb17976787160 cba73d28c921e59150a62e8a22391256d8a305a5
       1 text file.
       2 text files.
       4 files ignored.

github.com/AlDanial/cloc v 1.88  T=0.65 s (6.1 files/s, 121.2 lines/s)
-------------------------------------------------------------------------------------------------------------------------
File                                                                                blank        comment           code
-------------------------------------------------------------------------------------------------------------------------
c:\users\xx00000\appdata\local\temp\slf2vpqhpu\module1\aspnet_users.cs
 same                                                                                   0              0              0
 modified                                                                               0              0              0
 added                                                                                  5             10             23
 removed                                                                                0              0              0
c:\users\xx00000\appdata\local\temp\orbnnmwdh8\module1\aspnet_users.cs
 same                                                                                   0              0              0
 modified                                                                               0              0              0
 added                                                                                  0              0              0
 removed                                                                                4              8             20
c:\users\xx00000\appdata\local\temp\slf2vpqhpu\module1\aspnetdb.cs
 same                                                                                   0              0              0
 modified                                                                               0              0              0
 added                                                                                  1              8              0
 removed                                                                                0              0              0
-------------------------------------------------------------------------------------------------------------------------
SUM:
 same                                                                                   0              0              0
 modified                                                                               0              0              0
 added                                                                                  6             18             23
 removed                                                                                4              8             20
-------------------------------------------------------------------------------------------------------------------------

SHA1:80768712defb1c66264c9f796abeb17976787160
SHA2:cba73d28c921e59150a62e8a22391256d8a305a5

I modified aspnet_users.cs between SHA1 and SHA2.
I did not remove/add aspnet_users.cs.
I modified aspnet_users.cs as :
aspnet_users1.cs -> aspnet_users2.cs
(attached files)

I'd appreciated if you could investigate this issue.
Thank you.

cloc : v1.88
OS : Windows10 
unzip : 5.51-1
Git hosting service : Bitbucket
Git : 2.22.0.windows
TortoiseGit : Version 2.11.0

[aspnet_Users.zip](https://github.com/AlDanial/cloc/files/6113996/aspnet_Users.zip)

**Comment by AlDanial** [comment]
File renames, like aspnet_users1.cs -> aspnet_users2.cs,  confuse cloc.  It takes extra logic to unravel these in git (which cloc does currently not attempt).  To cloc it looks like the file was removed, then added.

**Comment by hid-saka** [comment]
I'm sorry for your confusing.
I did not rename the files.
"aspnet_users1.cs -> aspnet_users2.cs"
is just for my explanation
(after the issue happened).

**Comment by AlDanial** [comment]
Your zip file contains two files, ``aspnet_Users1.cs`` and ``aspnet_Users2.cs``, not a git repo that I can use git hashes on as you showed (``cloc --git --diff --by-file 80768712defb1c66264c9f796abeb17976787160 cba73d28c921e59150a62e8a22391256d8a305a5``).  Not surprisingly, doing the diff on these two files works fine:

<pre>
/tmp/378> cloc --diff aspnet_Users1.cs aspnet_Users2.cs 
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C#
 same                            0              0              8             18
 modified                        1              0              0              2
 added                           0              1              2              3
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            0              0              8             18
 modified                        1              0              0              2
 added                           0              1              2              3
 removed                         0              0              0              0
-------------------------------------------------------------------------------
</pre>

**Comment by hid-saka** [comment]
Thank you for your help and support.

Let me attach the repository on the next comment.
I don't use repo.

I suppose this issue seems to happen on particular environment.
But some users may face this issue.
So if you could not reproduce this issue,
could you please instruct me how to do on my environment for your debugging ?

**Comment by hid-saka** [comment]
[repository1.zip](https://github.com/AlDanial/cloc/files/6138043/repository1.zip)

**Comment by AlDanial** [comment]
Yes, that repository is helpful.  On Linux the result looks correct:

<pre>
/tmp/repository1> cloc --git --diff --by-file 80768712defb1c66264c9f796abeb17976787160 cba73d28c921e59150a62e8a22391256d8a305a5
github.com/AlDanial/cloc v 1.89  T=0.05 s (80.0 files/s, 860.1 lines/s)
------------------------------------------------------------------------------------------
File                                                 blank        comment           code
------------------------------------------------------------------------------------------
module1/aspnet_Users.cs
 same                                                    0              8             18
 modified                                                0              0              2
 added                                                   1              2              3
 removed                                                 0              0              0
module1/AspNetDB.cs
 same                                                    0              0              0
 modified                                                0              0              0
 added                                                   1              8              0
 removed                                                 0              0              0
------------------------------------------------------------------------------------------
SUM:
 same                                                    0              8             18
 modified                                                0              0              2
 added                                                   2             10              3
 removed                                                 0              0              0
------------------------------------------------------------------------------------------
</pre>

If you go to https://github.com/AlDanial/cloc/issues/552 you'll find a link to cloc-1.89.zip which is a Windows executable, not a zip file.  Download it, rename it to ``cloc-1.89.exe``, and see if you get better results.

**Comment by hid-saka** [comment]
Thank you very much !!!
cloc-1.89.exe works fine !!!
But one diff operation makes the message
"Process can not access to files. Another process is using them."
I'm a little bit worried.
But the result is correct.

`
C:\git\repository1>cloc --diff --by-file 21932c1561bf6652ba5caefcc3705c5d0cef6a7a 9c1b4332c0d0b9038648177063b03b1ec61b4bb7
Process can not access to files. Another process is using them.
[C:/Users/XX00000/AppData/Local/Temp/UqfgTz5KQf.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in C:/Users/PS46138/AppData/Local/Temp/UqfgTz5KQf.zip,
        and cannot find C:/Users/PS46138/AppData/Local/Temp/UqfgTz5KQf.zip.zip, period.
       0 text files.
       1 text file.
       3 files ignored.

github.com/AlDanial/cloc v 1.89  T=0.91 s (4.4 files/s, 33.1 lines/s)
-------------------------------------------------------------------------------------------------------------------------
File                                                                                blank        comment           code
-------------------------------------------------------------------------------------------------------------------------
module1\aspnet_Roles.cs
 same                                                                                   0              0              0
 modified                                                                               0              0              0
 added                                                                                  4              8             18
 removed                                                                                0              0              0
-------------------------------------------------------------------------------------------------------------------------
SUM:
 same                                                                                   0              0              0
 modified                                                                               0              0              0
 added                                                                                  4              8             18
 removed                                                                                0              0              0
-------------------------------------------------------------------------------------------------------------------------
`

I suppose this issue can be closed
(I don't care about p27130-san's issue).
