### ISSUE TITLE
Recognize WebAssembly files

### ISSUE THREAD

**Issue by camilstaps** [AlDanial/cloc#383]
[WebAssembly](http://webassembly.org/) has a [text format](http://webassembly.github.io/spec/core/text/conventions.html) which could be recognized.

1. Common file extensions are `.wat` and `.wast`.
2. Single-line comments start with `;;`. As far as I know there are no multi-line comments.
3. See the test files in https://github.com/WebAssembly/spec/tree/master/test/core for example code.

Many thanks in advance!

**Comment by AlDanial** [comment]
I'm a fan of the WebAssembly project.

**Comment by camilstaps** [comment]
Thanks!
