### ISSUE TITLE
Should we support openSUSE?

### ISSUE THREAD

**Issue by wjn740** [AlDanial/cloc#384]

**Comment by AlDanial** [comment]
What do you mean exactly?

**Comment by wjn740** [comment]
> What do you mean exactly?

If we could setup a package for openSUSE?

**Comment by AlDanial** [comment]
I encourage you to take the lead on this!

I personally don't manage packages for any OS or distribution.

**Comment by wjn740** [comment]
> I encourage you to take the lead on this!
> 
> I personally don't manage packages for any OS or distribution.

Got it.

**Comment by dumprop** [comment]
Is there any progress? I see cloc in OBS ( https://software.opensuse.org/package/cloc )
But still no official package...

**Comment by AlDanial** [comment]
@dumprop : go for it; create a cloc package for OpenSUSE

**Comment by phrxmd** [comment]
I've been maintaining an OpenSUSE package for `cloc` for a while, you can download it at https://build.opensuse.org/package/show/home:rxmd/cloc

**Comment by includesec-erik** [comment]
@AlDanial another issue that can be closed? Looks like @phrxmd started the OpenSUSE package

**Comment by AlDanial** [comment]
@includesec-erik thanks for the heads-up.
