### ISSUE TITLE
wrong git diff calculation in case if files deleted from "old" git revision and no added or modified

### ISSUE THREAD

**Issue by maxbelo** [AlDanial/cloc#386]
command 
cloc-1.80.pl --git --diff --diff-timeout=60 <git_hash_1> <git_hash_2> 
<git_hash_2> corresponds to the git revision where 2 files are removed from source control, so the list of changed files is empty for the <git_hash_2> and it causing to 'git archive -o $Tarfile <git_hash_2> ' command inside of git_archive function which means that whole repository will be archived and using in comparison step

**Comment by AlDanial** [comment]
I'm able to duplicate the problem.  While I was at it, I discovered a related issue which happens with added files.  Will take some time to fix.

**Comment by maxbelo** [comment]
Thanks for the prompt response.
Just in case it might help you with the fix, to unblock my task I made
dirty fix in my local copy of cloc.pl - check number of files in the array
right before call 'git archive' and if it is 0 create empty tar archive
'tar -cf $tarname -T /dev/null' . It works fine for removed or added files
but only on Linux.

ср, 24 апр. 2019 г. в 5:53, AlDanial <notifications@github.com>:

**Comment by AlDanial** [comment]
I'm still struggling with this one.  I thought I had a script that duplicated the problem but was actually hitting a different error.  Basically I'm not able to make the code fail when the old commit has no files in it.  Please try running the script ``tests/inputs/issues/386/make_386_repo.sh`` in an empty directory.  The idea is that the 4th commit produces an empty repo and running cloc --diff with it should trigger the error.  On my system (Ubuntu 16.04) it runs cleanly.

I will be releasing v1.82 soon but it won't have any changes for this issue.

**Comment by maxbelo** [comment]
Hello, sorry for the delayed response. I was able successfully reproduce the issue with cloc v 1.82 with your script tests/inputs/issues/386/make_386_repo.sh. Probably my initial description of the issue was unclear, so  if look to the below output you will probably see the problem. Especially look to the CLOC output for the diff between commits 1 and 2, and between commits 2 and 3.
About diff between commits 1 and 2:
`cloc --git --diff` says that 2 C files were removed and 1 Python file added but in reality for commit 2 only 1 Python file added as showed when we ask CLOC to compare two .tar archives.

About diff between commits 2 and 3:
Actually the same story, `cloc --git --diff` produced wrong output about added/deleted files.

[master (root-commit) 3885290]
 2 files changed, 22 insertions(+)
 create mode 100644 hello1.c
 create mode 100644 hello2.c
[master de6ca05]
 1 file changed, 5 insertions(+)
 create mode 100644 stuff.py
rm 'hello1.c'
[master 45d1ce8]
 1 file changed, 12 deletions(-)
 delete mode 100644 hello1.c
rm 'hello2.c'
rm 'stuff.py'
[master 79be060]
 2 files changed, 15 deletions(-)
 delete mode 100644 hello2.c
 delete mode 100644 stuff.py
HASH4=79be060 - removed stuff.py & hello2.c, repo is empty
HASH3=45d1ce8 - removed hello1.c, repo with 2 files stuff.py & hello2.c
HASH2=de6ca05 - added stuff.py
HASH1=3885290 - added hello1.c & hello2.c
++++++++++++++++++++++++++++++++++++++++++
Diff between 1 (3885290) and  2 (de6ca05)
       2 text files.
       1 text file.
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=2.13 s (0.5 files/s, 0.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         2              0             10             12
Python
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           1              0              1              4
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           1              0              1              4
 removed                         2              0             10             12
-------------------------------------------------------------------------------
       2 text files.
       3 text files.
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.85 s (1.2 files/s, 1.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            2              0             10             12
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
Python
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           1              0              1              4
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            2              0             10             12
 modified                        0              0              0              0
 added                           1              0              1              4
 removed                         0              0              0              0
-------------------------------------------------------------------------------
++++++++++++++++++++++++++++++++++++++++++
Diff between 2 (de6ca05) and 3 (45d1ce8)
       1 text file.
       2 text files.
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=2.04 s (0.5 files/s, 0.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           1              0              3              7
 removed                         1              0              7              5
Python
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           1              0              1              4
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           2              0              4             11
 removed                         1              0              7              5
-------------------------------------------------------------------------------
       3 text files.
       2 text files.
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.84 s (1.2 files/s, 1.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            1              0              3              7
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1              0              7              5
Python
 same                            1              0              1              4
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            2              0              4             11
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1              0              7              5
-------------------------------------------------------------------------------
++++++++++++++++++++++++++++++++++++++++++
Diff between 3 (45d1ce8) and 4 (79be060)
       2 text files.
       0 text files.
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=1.97 s (0.5 files/s, 0.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1              0              3              7
Python
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1              0              1              4
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         2              0              4             11
-------------------------------------------------------------------------------
       2 text files.
       0 text files.
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.75 s (1.3 files/s, 1.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1              0              3              7
Python
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1              0              1              4
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         2              0              4             11
-------------------------------------------------------------------------------
++++++++++++++++++++++++++++++++++++++++++
Diff between 4 (79be060) and  1 (3885290)
       0 text files.
       2 text files.
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=1.97 s (0.5 files/s, 0.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           2              0             10             12
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           2              0             10             12
 removed                         0              0              0              0
-------------------------------------------------------------------------------
       0 text files.
       2 text files.
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.74 s (1.4 files/s, 1.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           2              0             10             12
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           2              0             10             12
 removed                         0              0              0              0
-------------------------------------------------------------------------------
++++++++++++++++++++++++++++++++++++++++++
Diff between 1 (3885290) and 4 (79be060)
       2 text files.
       0 text files.
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=1.97 s (0.5 files/s, 0.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         2              0             10             12
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         2              0             10             12
-------------------------------------------------------------------------------
       2 text files.
       0 text files.
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.76 s (1.3 files/s, 1.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         2              0             10             12
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         2              0             10             12
-------------------------------------------------------------------------------

**Comment by AlDanial** [comment]
The changes in 63d213c give the same results for both the tar diffs and the git diffs with the test script.  I'm hoping it solves your problem too.

**Comment by maxbelo** [comment]
looks like issue is fixed. thanks for your efforts.

**Comment by AlDanial** [comment]
Glad to hear it.  ``--git --diff`` has proven surprisingly challenging to get right.
