### ISSUE TITLE
how to include file extension with hypen ? 

### ISSUE THREAD

**Issue by sadeshwar94** [AlDanial/cloc#387]
hi, i would like to know how to include file extension with a hyphen `(.page-meta.xml), (cls-meta.xml)` using `--read-lang-def`  as well you can see in the output some of XML extensions files has been recognised, but 6 files have been ignored which includes ` (.page-meta.xml), (cls-meta.xml)` extenstions, 
```
cloc --diff --git --by-file-by-lang 2f53218 6rb1y6c4 --read-lang-def=object.txt
       1 text file.
      19 text files.
       6 files ignored.

github.com/AlDanial/cloc v 1.80  T=0.16 s (6.3 files/s, 6.3 lines/s)
---------------------------------------------------------------------------------------------------------------------
File                                                                            blank        comment           code
---------------------------------------------------------------------------------------------------------------------
src/pages/VF_SG__edit.page
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                             55            104           1031
 removed                                                                            0              0              0
src/classes/CL_Traffic_Logic.cls
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                             88             63            819
 removed                                                                            0              0              0
src/classes/CL_TrafficController.cls
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                             90            166            379
 removed                                                                            0              0              0
src/pages/VF_TrafficRegList.page
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                             20             35            217
 removed                                                                            0              0              0
src/classes/X_CL_Kyou.cls
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                             33             35            108
 removed                                                                            0              0              0
src/classes/CM_SearchCondition.cls
 same                                                                               0             21             85
 modified                                                                           0              1              0
 added                                                                              0              4              2
 removed                                                                            0              0              0
src/classes/CL_TrafficRegObject.cls
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                              6             55             60
 removed                                                                            0              0              0
src/classes/CL_SagKin.cls
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                             15             26             31
 removed                                                                            0              0              0
src/classes/CL_MsgMap.cls
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                             10             16             31
 removed                                                                            0              0              0
src/classes/CL_SagHis.cls
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                             15             30             28
 removed                                                                            0              0              0
src/pages/VF_TrafficRegList.page-meta.xml
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                              0              0              5
 removed                                                                            0              0              0
src/classes/CL_KyoH.cls-meta.xml
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                              0              0              5
 removed                                                                            0              0              0
src/pages/VF_SagEdit.page-meta.xml
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                              0              0              5
 removed                                                                            0              0              0
---------------------------------------------------------------------------------------------------------------------
SUM:
 same                                                                               0             21             85
 modified                                                                           0              1              0
 added                                                                            332            534           2721
 removed                                                                            0              0              0
---------------------------------------------------------------------------------------------------------------------

```

**Comment by AlDanial** [comment]
Your post is a bit confusing--you say the ``.page-meta.xml`` and ``.cls-meta.xml`` files are ignored but your results have three such files:
<pre>
src/pages/VF_TrafficRegList.page-meta.xml
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                              0              0              5
 removed                                                                            0              0              0
src/classes/CL_KyoH.cls-meta.xml
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                              0              0              5
 removed                                                                            0              0              0
src/pages/VF_SagEdit.page-meta.xml
 same                                                                               0              0              0
 modified                                                                           0              0              0
 added                                                                              0              0              5
 removed                                                                            0    
</pre>

It would be more convincing to run without ``--by-file-by-lang`` but include ``--ignored=ig.txt`` then see which files exactly were ignored.  Also valuable would be the contents of your ``object.txt`` language definition file.

In any case I tried to duplicate the issue with a direct count.  First I copied three XML files from the cloc test directory and gave them the extensions you're interested in:
<pre>
cp tests/inputs/drupal.mxml   CL_KyoH.cls-meta.xml
cp tests/inputs/vbox.fxml     VF_SagEdit.page-meta.xml 
cp tests/inputs/XML.xml       .
</pre>

Next I created this language definition file, ``langdef.txt``:
<pre>
CLSXML
    filter remove_html_comments
    filter call_regexp_common HTML
    extension cls-meta.xml
    3rd_gen_scale 1.90
PAGEXML
    filter remove_html_comments
    filter call_regexp_common HTML
    extension page-meta.xml
    3rd_gen_scale 1.90
</pre>

then ran cloc.  It had no difficulty separating the new ``.page-meta.xml`` and ``.cls-meta.xml`` extensions from regular XML:
<pre>
> cloc --by-file-by-lang --read-lang-def langdef.txt *xml                                                                                                            
       3 text files.
       3 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.01 s (393.9 files/s, 15754.2 lines/s)
--------------------------------------------------------------------------------------
File                                    blank        comment           code
--------------------------------------------------------------------------------------
CL_KyoH.cls-meta.xml                       23              2             77
VF_SagEdit.page-meta.xml                    2              3              8
XML.xml                                     0              2              3
--------------------------------------------------------------------------------------
SUM:                                       25              7             88
--------------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CLSXML                           1             23              2             77
PAGEXML                          1              2              3              8
XML                              1              0              2              3
-------------------------------------------------------------------------------
SUM:                             3             25              7             88
-------------------------------------------------------------------------------
</pre>
