### ISSUE TITLE
Option to count tokens instead of lines or characters

### ISSUE THREAD

**Issue by eyalroz** [AlDanial/cloc#389]
After reading #234, it immediately occurred to me it that parsed tokens are a more valid measure of code size than characters. After all,
```
my_value = perform_some_actions();
```
is the same thing as
```
v = do_stuff();
```

I realize this is a tall order and perhaps out-of-scope for this project, but - I'll just put it out there.

**Comment by AlDanial** [comment]
Theoretically it's a fine idea.  However cloc does not parse languages; it is strictly regular-expression based.  For this reason, character counting is possible (although unlikely to be implemented in the foreseeable future), but counting tokens is not.  You'll need a smarter counter than cloc!
