### ISSUE TITLE
Suggestion: gif file replacement

### ISSUE THREAD

**Issue by jolkdarr** [AlDanial/cloc#39]
Many Unicode characters are arrows.
Maybe one of them could be used for the `readme.md` file allowing to get rid of the `up.gif` file.

For example, the following line:
```md
# [Basic Use![^](up.gif)](#___top "click to go to top of document")
```
would be replaced with:
```md
# [Basic Use &#9650;](#___top "click to go to top of document")
```
and rendered:
# [Basic Use &#9650;](#___top "click to go to top of document")

Modern browsers handle Unicode charsets (UTF-8...) with no difficulty.
A nice table provides arrows available at http://unicode-table.com/en/sets/arrows-symbols/ .

**Comment by AlDanial** [comment]
Excellent tip, thanks!  I implemented the up triangle you showed.
