### ISSUE TITLE
cloc --git with --diff uses single quotes for file paths, failing under Windows

### ISSUE THREAD

**Issue by dueringa** [AlDanial/cloc#390]
Tested versions: 1.80 and 1.82

When I call `cloc.exe -v --git --diff v2.04 v2.08` in a git repository on a Windows command prompt, it fails with the following debug output:

~~~
git ls-tree --name-only -r v2.04
git ls-tree --name-only -r v2.08
git diff-tree -r --no-commit-id --name-only v2.04 v2.08
git archive -o X:\Temp\IGiG6e0AIW.zip v2.04  'README.txt'
fatal: pathspec ''README.txt'' did not match any files
Failed to create tarfile of files from git. at script/cloc line 4512.
~~~

The same applies for `--count-and-diff` in version 1.82 (The count phase works, but the diff fails).

This might be because of the use of single quotes for `'README.txt'` (which is present in one version but not the other). As far as I know the Windows command prompt interprets these differently (literally?).

The same command works on an MSYS2/MinGW64 shell (version 1.80):

~~~
$ cloc -v --git --diff v2.04 v2.08
git ls-tree --name-only -r v2.04
git ls-tree --name-only -r v2.08
git diff-tree -r --no-commit-id --name-only v2.04 v2.08
git archive -o /tmp/Bg6Zox_Scj.tar v2.04  'README.txt'
git archive -o /tmp/riUC2C0hhv.tar v2.08
mkdir /tmp/B0LsCqNIUo
cd    /tmp/B0LsCqNIUo
tar xf '/tmp/Bg6Zox_Scj.tar'
mkdir /tmp/BVEG3gsrD9
cd    /tmp/BVEG3gsrD9
tar xf '/tmp/riUC2C0hhv.tar'
Using temp file list [/tmp/mToYk3HkV_]
       1 text file.
Using temp file list [/tmp/C9mW1szw2l]
     777 text files.
     318 files ignored.
~~~

**Comment by AlDanial** [comment]
What happens if you invoke the offending ``git`` command on Windows (without a MinGW shell) using double quotes instead of single?
<pre>
git archive -o test.zip v2.04  "README.txt"
</pre>
As I'm sure you've guessed, I wrap the files in quotes to protect against spaces in file names.

**Comment by dueringa** [comment]
If I use double quotes, there are no errors.
However, the output _only_ contains the Readme.txt file (but that's also true if I use no quotes) - according to the git documentation. The same problem exists when I execute cloc on the MinGW shell. So the diff actually says "Added x files" (added all source files).  In this repo, README.txt is present in v2.04, but not in v2.08. -- But I guess that's another issue.

**Comment by dueringa** [comment]
See #386

**Comment by AlDanial** [comment]
Do you have the possibility of running the Perl source version on your computer instead of the ``.exe``?  I'm hoping you're able to check if the latest commits help your problem.

**Comment by dueringa** [comment]
Tested with Strawberry Perl v5.28.1, on commit https://github.com/AlDanial/cloc/commit/a1520d9760a71a95ffabffc20f06011c90ad618b

~~~
perl x:\cloc\cloc -v --git --diff v2.04 v2.08
git ls-tree --name-only -r v2.04
git ls-tree --name-only -r v2.08
git archive -o X:\Temp\nq79pMrJ5A.zip v2.04  (lots of double-quotes files)
git archive -o X:\Temp\0_FnbxOnXC.zip v2.08  (lots of double-quotes files)
mkdir X:\Temp\WRfCkE70g0
cd    X:\Temp\WRfCkE70g0
unzip -qq -d . "X:\Temp\nq79pMrJ5A.zip"
mkdir X:\Temp\bHiCUsaTPU
cd    X:\Temp\bHiCUsaTPU
unzip -qq -d . "X:\Temp\0_FnbxOnXC.zip"
Using temp file list [X:\Temp\ck3v1Ck00t]
     754 text files.
Using temp file list [X:\Temp\2VtwTSeVTD]
     777 text files.
Using temp dir [X:\Temp\Up7k2GMpKx] to install Regexp::Common
     633 files ignored.

github.com/AlDanial/cloc v 1.83  T=17.68 s (0.1 files/s, 0.1 lines/s)

(plausible diff stats)
~~~

Looks fine for me, I'd say this is fixed. Works also under MSYS2 shell.
Thanks!

**Comment by AlDanial** [comment]
excellent, thanks for testing
