### ISSUE TITLE
"cloc . --json --by-file" produces invalid json

### ISSUE THREAD

**Issue by astef** [AlDanial/cloc#391]
On windows the JSON key name includes backslashes:

```
...
".\MyProject\obj\project.assets.json" :{
  "blank": 0,
  "comment": 0,
  "code": 5958,
  "language": "JSON"},
...
```

The problem is that backslash is an escape character in JSON. And for some paths the resulting json is invalid. It's pretty frustrating.

**Comment by AlDanial** [comment]
Thanks for reporting this problem.  The fix in 08c1e46 should do the trick.
