### ISSUE TITLE
cloc does not descend to the sub-directories of a mounted network share

### ISSUE THREAD

**Issue by myelsukov** [AlDanial/cloc#392]
cloc does not descend to the sub-directories of a mounted SMB network share.
I suspect this happens because network directories are misidentified as files and ignored because their size is reported as zero.

My perl is: perl 5, version 28, subversion 2 (v5.28.2) built for x86_64-linux-thread-multi:

Log:
```
-> make_file_list(.)
files(./support)  zero size
files(./main)  zero size
       0 text files.
<- make_file_list()
-> remove_duplicate_files
<- remove_duplicate_files
       0 unique files.                              
-> count_files()
<- count_files()
       3 files ignored.
```
Both `./support` and `./main` are directories:

```
> ls -la
total 0
drwxr-xr-x 2 username users 0 Jun 17  2017 .
drwxr-xr-x 2 username users 0 May 29 23:22 ..
drwxr-xr-x 2 username users 0 Jun 17  2017 main
drwxr-xr-x 2 username users 0 Jun 17  2017 support
```

**Comment by AlDanial** [comment]
What is the output of these commands?
<pre>
stat main
perl -e 'print "is dir\n" if -d "main"'`
cloc main
cloc main/*
cloc --follow-links .
</pre>

**Comment by myelsukov** [comment]
```
> stat main
  File: main
  Size: 0         	Blocks: 0          IO Block: 1048576 directory
Device: 38h/56d	Inode: 74976848    Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/username)   Gid: (  985/   users)
Access: 2017-06-17 13:08:45.658991700 -0700
Modify: 2017-06-17 13:08:45.658991700 -0700
Change: 2017-06-17 13:08:45.658991700 -0700
 Birth: 2017-06-17 13:08:44.836013100 -0700

> perl -e 'print "is dir\n" if -d "main"'
is dir

> cloc main
       7 text files.
       7 unique files.                              
       9 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.65 s (3.1 files/s, 169.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Ant                              1              3              1             65
XML                              1              4              6             31
-------------------------------------------------------------------------------
SUM:                             2              7              7             96
-------------------------------------------------------------------------------
> cloc main/*
      27 text files.
      25 unique files.                              
      24 files ignored.

github.com/AlDanial/cloc v 1.82  T=0.61 s (14.7 files/s, 871.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSP                              7             22              0            401
Ant                              1              3              1             65
XML                              1              4              6             31
-------------------------------------------------------------------------------
SUM:                             9             29              7            497
-------------------------------------------------------------------------------

> cloc --follow-links .
     770 text files.
     765 unique files.                                          
     686 files ignored.

github.com/AlDanial/cloc v 1.82  T=17.46 s (6.9 files/s, 972.6 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Java                             50           1713            680          10628
Bourne Again Shell               45            315            443           1338
awk                               7             59             31            666
JSP                               7             22              0            401
SQL                               3             23              0            162
XML                               3             13             12            144
Groovy                            1             30              0            124
Bourne Shell                      2              5             16             73
Ant                               1              3              1             65
Ruby                              1              4              3              6
--------------------------------------------------------------------------------
SUM:                            120           2187           1186          13607
--------------------------------------------------------------------------------
```

**Comment by AlDanial** [comment]
All indications suggest cloc is actually descending into ``main`` (and presumably ``support``, too, because ``cloc --follow-links .`` shows more output than ``cloc main``).  However I'm puzzled by the difference between ``cloc main`` and ``cloc main/*``--those I would have expected to give the same result (assuming ``main`` doesn't have subdirectories that begin with ``.``).

Also curious is the low files-per-second processing rate; your SMB connection must be really slow.  I'm wondering if that is somehow is messing up directory traversal?  cloc uses the Perl ``File::Find`` module to traverse the file system, essentially doing what this command would do
<pre>
perl -MFile::Find -e 'find(\&wanted, DIR); sub wanted { print "$File::Find::name\n"}'
</pre>
where ``DIR`` could be ``"."`` to start at the current directory.  Additionally, along the way cloc does a series of checks to skip ignored directories, eg ``.git/`` and so on, which takes extra time.  Maybe the filesystem layer times out or something during the descent?  I'm totally guessing at this point.

**Comment by myelsukov** [comment]
https://www.perlmonks.org/bare/?node_id=46125

**Comment by myelsukov** [comment]
https://perldoc.perl.org/File/Find.html

> $dont_use_nlink

You can set the variable $File::Find::dont_use_nlink to 1 if you want to force File::Find to always stat directories. This was used for file systems that do not have an nlink count matching the number of sub-directories. Examples are ISO-9660 (CD-ROM), AFS, HPFS (OS/2 file system), FAT (DOS file system) and a couple of others.

You shouldn't need to set this variable, since File::Find should now detect such file systems on-the-fly and switch itself to using stat. This works even for parts of your file system, like a mounted CD-ROM.

If you do set $File::Find::dont_use_nlink to 1, you will notice slow-downs.

**Comment by myelsukov** [comment]
This is from File::Find. It explains everything. SMB reports number of link = 2 for all directories.
>	if ($nlink == 2 && !$no_nlink) {
>	    # This dir has no subdirectories.

**Comment by AlDanial** [comment]
If you modify your copy of the cloc source code by adding line 44 as shown here
<pre>
   42 use File::Find;
   43 use File::Path;
   44 $File::Find::dont_use_nlink = 1;
   45 use File::Spec;
</pre>
does that resolve the issue you're seeing?  If yes, I'll add an option to do the same.  I don't want to have this on for all runs due to the performance hit.

**Comment by myelsukov** [comment]
Yes, that would work, I tried it before.
You can check the directory and apply the flag automatically:

```
stat -f main
  File: "main"
    ID: dda49afc00000000 Namelen: 255     Type: smb2
Block size: 1024       Fundamental block size: 1024
Blocks: Total: 8638742220 Free: 7179867276 Available: 7179867276
Inodes: Total: 0          Free: 0
```
Note the type of the filesystem in the output.

**Comment by AlDanial** [comment]
Well that's the issue--stat the directory or not.  If I stat every directory it is like setting nlink=1 permanently.

Instead I introduced a new switch ``--stat`` which will set nlink=1.

**Comment by myelsukov** [comment]
I am sorry I didn't express myself clearly. Obviously I didn't propose to do the `stat` for each directory. I meant that you could check if a top-level directory was on a `smb2` share then you should set `dont_use_nlink = 1` just for that directory, because it won't work otherwise.

Of course it's absolutely up to you if you don't want to make your otherwise great utility a little bit smarter :)

**Comment by AlDanial** [comment]
Please attach the output from the command
<pre>
perl -e '@a= stat("smb_dir"); print join("\n", @a), "\n"'
</pre>
where ``smb_dir`` is one of your SMB mount points (``main``?).  I want to see Perl's version of the ``stat`` output as that's what cloc will see.

**Comment by myelsukov** [comment]
```
> perl -e '@a= stat("main"); print join("\n", @a), "\n"'
56
74976848
16877
2
1000
985
0
0
1497730125
1497730125
1497730125
1048576
0

> stat main
  File: main
  Size: 0         	Blocks: 0          IO Block: 1048576 directory
Device: 38h/56d	Inode: 74976848    Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/username)   Gid: (  985/   groupname)
Access: 2017-06-17 13:08:45.658991700 -0700
Modify: 2017-06-17 13:08:45.658991700 -0700
Change: 2017-06-17 13:08:45.658991700 -0700
 Birth: 2017-06-17 13:08:44.836013100 -0700

> stat -f main
  File: "main"
    ID: dda49afc00000000 Namelen: 255     Type: smb2
Block size: 1024       Fundamental block size: 1024
Blocks: Total: 8638742220 Free: 7177854448 Available: 7177854448
Inodes: Total: 0          Free: 0
```

**Comment by AlDanial** [comment]
Will be some time before I'm able to test my solution on a variety of file systems.

**Comment by myelsukov** [comment]
Sure thing. Take your time :)

**Comment by AlDanial** [comment]
Apologies this has taken so long.  The latest commits scan the top-level inputs for directories that have nlink == 2.  If any are found, the ``--stat`` switch is set (meaning ``$File::Find::dont_use_nlink`` will be set to 1).  Can you see if it works the way you intended?

**Comment by myelsukov** [comment]
It works fine for me. Thank you!

I think it's a good compromise between performance and usability.
Obviously, this approach won't work if the SMB shared directory is not a top-level one, but I believe that situation like that is rather exotic :).

**Comment by AlDanial** [comment]
Great.
