### ISSUE TITLE
Add support for Cython *.pxd and *.pxi files

### ISSUE THREAD

**Issue by KM4YRI** [AlDanial/cloc#395]
``cloc`` does not read or count lines from *.pxd files (Cython definition) and *.pxi files (Cython include).  The source code is syntactically identical to *.pyx files, and can be line-counted using the same logic.

This should be a relatively easy fix, and would help me out because currently ``cloc`` tells me I only have 200 lines of code written, when it should be more like 3100.

**Comment by AlDanial** [comment]
Your timing is good as ``.pxd`` and ``.pxi`` were added just yesterday with PR #394.  If you use the development version you'll see
<pre>
 cloc --explain Cython
Cython
    filter rm_comments_in_strings  "  /*
    filter rm_comments_in_strings  "  //
    filter remove_matches  ^\s*#
    filter docstring_to_C
    filter call_regexp_common  C
    filter remove_inline  #.*$
    extensions: pxd, pxi, pyx
</pre>

**Comment by KM4YRI** [comment]
That's perfect, thank you!
