### ISSUE TITLE
Ignore auto generated files by identifier

### ISSUE THREAD

**Issue by jnyrup** [AlDanial/cloc#396]
Auto-generated files in C# often contains a commentary header that indicates that it was auto-generated by some tool.

E.g.
```c#
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
```

Analyzers use this comment to exclude files for analysis.

It would be nice to be able to easily exclude such files from code counting.
E.g. `--exclude-by-identifier='<auto-generated>'`

**Comment by AlDanial** [comment]
I implemented your request with a couple of minor variations:  the switch name is ``--exclude-content`` and, to give greater flexibility, its argument is a regex rather than a literal.  ``--exclude-content='<auto-generated>`` ought to work fine in any case.
