### ISSUE TITLE
JSON-formatted reports are not supported by --sum-reports

### ISSUE THREAD

**Issue by vaughandroid** [AlDanial/cloc#397]
If I use `--sum-reports` on reports which have been created using the `--json` option, it reports 0 lines.

e.g.

> \>./cloc-1.82.pl --sum_reports --json --out=foo projectA/report.json projectB/report.json -v
> Wrote foo.file

Gives me this foo.file:
```
{"header" : {
  "cloc_url"           : "github.com/AlDanial/cloc",
  "cloc_version"       : "1.82",
  "elapsed_seconds"    : 0.00374698638916016,
  "n_files"            : 0,
  "n_lines"            : 0,
  "files_per_second"   : 0,
  "lines_per_second"   : 0,
  "report_file"        : "foo.lang"},
"SUM": {
  "blank": 0,
  "comment": 0,
  "code": 0,
  "nFiles": 0} }
```

If this is not expected to work, it would be helpful if:

1. The operation could fail, rather than appearing to succeed.
2. The docs could make this clear.

**Comment by AlDanial** [comment]
Yes, it is a limitation that only the plain inputs can be used to sum reports.  I updated the code to emit a warning if it fails to extract results from the summation inputs and also updated the README.
