### ISSUE TITLE
How can I use the globbing in the exclude-list-file? 

### ISSUE THREAD

**Issue by wejczhu** [AlDanial/cloc#399]
I have many directories with same name, like **a/config**, **b/config**, to exclude all **/config/** directories , I need to manually add all the directories in the exclude list file.

Now I know `--exclude-dir=config` can exclude all /config/ in the project but Can I use globbing like ***/config** to  achieve the same effect  in exclude list file?

**Comment by AlDanial** [comment]
``--match-d`` can do what you want, see https://github.com/AlDanial/cloc/issues/346 for an example.

**Comment by AlDanial** [comment]
More specifically, use
<pre>
cloc --fullpath --not-match-d '.*?/config\b'   your_source_code
</pre>

Here's a full example
<pre>
> find .
.
./dd
./dd/bb
./dd/bb/config.c
./dd/bb/cc
./dd/bb/ee
./dd/bb/ee/TeapotRenderer.cpp
./a/config
./a/config/C-Ansi.c
./a/config/temp.c
./a/Fortran77.f
./a/hello.f
./b
./b/acpclust.R
./b/sample.R
./b/c
./b/c/config
./b/c/config/qsort_demo.m
./b/c/config/Octave.m
./b/c/config/Mathematica_1.m
./b/c/config/Lanczos.m
./b/c/XML.xml
./b/utilities.R

> cloc --by-file .
      14 text files.
      14 unique files.                              
       1 file ignored.

github.com/AlDanial/cloc v 1.83  T=0.02 s (852.9 files/s, 100213.9 lines/s)
--------------------------------------------------------------------------------
File                                         blank        comment           code
--------------------------------------------------------------------------------
./b/utilities.R                                 41            276            524
./dd/bb/ee/TeapotRenderer.cpp                   49             55            182
./b/acpclust.R                                  54             35            170
./b/c/config/Lanczos.m                           0              0             48
./dd/bb/config.c                                22             22             44
./b/c/config/qsort_demo.m                       11             11             25
./b/c/config/Mathematica_1.m                    12              8             11
./a/config/C-Ansi.c                              2              2              7
./b/sample.R                                     0              1              4
./a/hello.f                                      0              6              4
./a/Fortran77.f                                  1              2              3
./a/config/temp.c                                2              0              3
./b/c/XML.xml                                    0              2              3
./b/c/config/Octave.m                            0              1              2
--------------------------------------------------------------------------------
SUM:                                           194            421           1030
--------------------------------------------------------------------------------

> cloc --fullpath --not-match-d '.*?/config\b' --by-file .
       8 text files.
       8 unique files.                              
       3 files ignored.

github.com/AlDanial/cloc v 1.83  T=0.01 s (556.8 files/s, 104406.9 lines/s)
--------------------------------------------------------------------------------
File                                         blank        comment           code
--------------------------------------------------------------------------------
./b/utilities.R                                 41            276            524
./dd/bb/ee/TeapotRenderer.cpp                   49             55            182
./b/acpclust.R                                  54             35            170
./dd/bb/config.c                                22             22             44
./b/sample.R                                     0              1              4
./a/hello.f                                      0              6              4
./a/Fortran77.f                                  1              2              3
./b/c/XML.xml                                    0              2              3
--------------------------------------------------------------------------------
SUM:                                           167            399            934
--------------------------------------------------------------------------------
</pre>

**Comment by wejczhu** [comment]
Thanks alot!
