### ISSUE TITLE
Support for Elm 

### ISSUE THREAD

**Issue by davidrusu** [AlDanial/cloc#4]
Hi, thanks for this wonderful tool. 

It would be great to have support for Elm, the syntax of Elm is very heavily inspired by Haskell so hopefully we can reuse the Haskell code.
http://elm-lang.org/

Comments are exactly the same as they are in Haskell, here's the reference for comments in elm:
http://elm-lang.org/docs/syntax#comments

All Elm files end in '.elm'

Some sample code can be found here:
http://elm-lang.org/examples

for a non trivial sized sample see:
http://elm-lang.org/examples/pong

Please let me know anything else you might need, and anything I can do to help

**Comment by AlDanial** [comment]
Support for Elm added with git commit caa59df.
