### ISSUE TITLE
No names of ignored files

### ISSUE THREAD

**Issue by ruv** [AlDanial/cloc#401]
`--ignored` option does not work: the file is created but remains empty, despite of a report  many ignored files. Output fragment example:
```
    1496 text files.
    1480 unique files.
Wrote ignored.list.txt
     270 files ignored.
```

`ignored.list.txt` is empty.

Version: cloc-1.82.exe

**Comment by AlDanial** [comment]
I am able to duplicate this problem on Windows, very strange.  Will investigate.

**Comment by AlDanial** [comment]
The current development version doesn't have this problem so I made a Windows exe from it.
[cloc-1.83.zip](https://github.com/AlDanial/cloc/files/3400117/cloc-1.83.zip)

**Comment by gshuflin** [comment]
I've also encountered this bug. I did some testing on my linux system, and it looks like it was specifically commit 470af7d1271f8b6cd5ce86bc6fc8c4252e08ce43 "support --csv, --json, --md, --xml, --yaml for --ignored output, #339" that broke this feature. Unfortunately I don't know perl myself and that commit is rather large and I can't immediately spot what might've gone wrong with it, but hopefully it's a good starting point for debugging this.

**Comment by AlDanial** [comment]
@gshuflin I appreciate your work to isolate the faulty commit.  However I'm pretty sure the problem has already been fixed in the development version of cloc.  Can you confirm?

**Comment by gshuflin** [comment]
Ah, yes, it looks like the `master` branch as of right now doesn't have this problem. Would it be possible for you to publish a numbered 1.83 release that works in linux/OSX as well?

**Comment by AlDanial** [comment]
The odd numbered versions are merely copies of the development branch at a given point.  This one is the cloc source from commit 608f37603 earlier today.  My plan is to make the next formal release, 1.84, in September.
[cloc-1.83.pl.zip](https://github.com/AlDanial/cloc/files/3437801/cloc-1.83.pl.zip)
