### ISSUE TITLE
SaltStack .sls files?

### ISSUE THREAD

**Issue by johnnybubonic** [AlDanial/cloc#403]
Your project is *fantastic*, before I start. It's by far the best code stats generator I've used.

So [SaltStack](https://www.saltstack.com/) uses what it calls [states](https://docs.saltstack.com/en/latest/ref/states/) (or "state files"). These are... get ready for this... jinja2-parsed YAML. Which by itself isn't a problem, necessarily, but their canonical file extension is `.sls`. Which is, because it conflicts with the Schema profile in cloc.

Is there a way to add a detection and differentiation between the two?

**Comment by AlDanial** [comment]
Thanks for your kind words.  If you can point me to sample SaltStack .sls files they'll be helpful to devise a subroutine that identifies those files v. Scheme code.  I'll be looking for commonly used keywords in those files.

**Comment by johnnybubonic** [comment]
Sure!

Trying to match keywords might be difficult because there's a *lot*. But here's some example ones ("formulas" are just openly distributed pre-written states and such for common tasks):

* [here's one for dovecot](https://github.com/saltstack-formulas/dovecot-formula/blob/master/dovecot/init.sls)
* [nginx (this one uses includes in init.sls to call the other .sls files)](https://github.com/saltstack-formulas/nginx-formula/tree/master/nginx)
* [mysql (same modularity/include system as nginx)](https://github.com/saltstack-formulas/mysql-formula/tree/master/mysql)

[This](https://docs.saltstack.com/en/latest/ref/states/all/) is a list of modules (e.g. you'll see a "file" mentioned there. it's called via something like "file.managed:" in the sls file).
Similarly, [these](https://docs.saltstack.com/en/latest/ref/modules/all/index.html) might be found as well (slightly different, "execution" modules).

BUT what I might recommend instead is first, if the file ends in .sls, try to test it for jinja2. If that passes, try testing it for YAML (with dummy jinja2 values substituted in). If THAT passes, it'd be same to assume, I think, that it's a SaltStack State file. Yes?

**Comment by AlDanial** [comment]
If cloc were coded in Python then sure, the jinja2, then YAML load attempts would be reasonable.  But I've painted myself into a pretty tight corner w/Perl and not wanting to add external dependencies so I'm taking the fast and cheap route of scanning for ``{%`` markers and the like.  See if 4463907 works for you.

**Comment by johnnybubonic** [comment]
ah, gotcha. i mean, to be fair, even if it was in python it'd require an external dep for jinja2 and yaml. :)

but just tested master:HEAD (4463907193ce1ff3e266cfbcb9a9752b6e667c65), and YEP! works great! SaltStack states are correctly detected and not detected as Schema. I don't have any Schema files I can test against to make sure they aren't being detected as SaltStack, but I can confirm this correctly identifies Salt state files. Thank you!

**Comment by AlDanial** [comment]
cool
