### ISSUE TITLE
Argument list too long at cloc --diff

### ISSUE THREAD

**Issue by kentgitbub** [AlDanial/cloc#404]
Hi!
Tried to use the --diff option on a not so large git repo and got this error: 

sh: /cmd/git: Argument list too long
Failed to create tarfile of files from git. at C:\REPOS\cloc\cloc line 4657.

Ran the command with the -v flag and it showed a list of files. Pasted the output into a file to get the size and it was roughly 90k. 

Running cloc on a Windows machine with git installed. (mingw or cygwin issue?)

Also saw the #213 but it doesn't work for me. 

(Additional info: It works on a linux machine)

**Comment by AlDanial** [comment]
Which version of cloc?  Also, is the large git repo public?  If yes, post the URL so I can try it out.

**Comment by kentgitbub** [comment]
Hi.
Thanks for the swift reply.

I’m trying out the latest as of today, 1.83. Unfortunatelly it is a private repo so I can’t pass you a URL but I’m sure that any public repo will do since I have tried it on a couple of ours and as soon as there are a couple of hundreds of files I get the problem mentioned in the ticket. (I tried it on maven, cloned from https://github.com/apache/maven.git, and I got the same result)

I’m responsible for a jenkins CI environment and we’ve got Windows, Mac and Linux platforms and I should perhaps mention that pointing out the same repositories in Linux works!!! In Windows, nope. Pretty sure it has to do with the size of the arguments passed during processing and the limits in Windows.

Should also add that I cloned your repo from github and I’m running the command using perl so I’m not using any compiled version.

Also, Perl comes bundled with git:

C:\REPOS\cloc>git --version
git version 2.20.1.windows.1

C:\REPOS\cloc>perl -v

This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-msys-thread-multi

Copyright 1987-2018, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

Hope this helps.

Regards
-- Kent Granstrom


Från: AlDanial <notifications@github.com>
Skickat: den 31 juli 2019 05:31
Till: AlDanial/cloc <cloc@noreply.github.com>
Kopia: Kent Granström <kent.granstrom@bankid.com>; Author <author@noreply.github.com>
Ämne: Re: [AlDanial/cloc] Argument list too long at cloc --diff (#404)


Which version of cloc? Also, is the large git repo public? If yes, post the URL so I can try it out.

**Comment by AlDanial** [comment]
Good info.  There's a chance the Windows solution may be solved easily since you're running the Perl source version.  Search for this line
<pre>
        my $FILES_PER_ARCHIVE = 1_000; 
</pre>
and just reduce the value to, say, 100.  (In case you're not familiar with it, the _ in 1_000 is just syntactic sugar that's ignored in Perl).

**Comment by kentgitbub** [comment]
Will do. 
As of now I', exploring this path: 
[FilePathTooLong](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows)

**Comment by kentgitbub** [comment]
The FilePathTooLong track was a dead end. **No difference**. 

Changing the $FILES_PER_ARCHIVE variable **made a difference
[cloc_output.txt](https://github.com/AlDanial/cloc/files/3450031/cloc_output.txt)
**. I don't get this error now and it continues with the calculations. 100 and 200 appears to work. Tried a few other values and, in my case, somewhere around 287-288 it appears to fail since it prints out the "sh: /cmd/git: Argument list too long" message. I would have thought that the whole operation would fail at this stage but it continues with the calculations and in the end, presents a completely different result which may perhaps be questionable. I have attached the result from a few runs. 

-- Kent

**Comment by AlDanial** [comment]
Any result with the Argument list too long message can be considered junk.  I'm interested in two things here:  with ``$FILES_PER_ARCHIVE`` equal to 100, do the Windows results match Linux?  and do values of 100 and 200 give the same result on Windows?

If the answer to both questions is Yes, I'll lower the value on Windows to 100 and consider that the fix.

**Comment by kentgitbub** [comment]
The only difference between 100, 200 on Windows and 1000 on linux is the time it takes to process the files. It is a LOT faster on the linux machine. I ran the same diff command saving ithe result in the rpt100, rpt200 and rpt1000-linux files 

**diff rpt100.txt rpt1000-linux.txt**
1c1
< github.com/AlDanial/cloc v 1.83  T=45.52 s (0.0 files/s, 0.0 lines/s)
---
> github.com/AlDanial/cloc v 1.83  T=7.43 s (0.1 files/s, 0.1 lines/s)

**diff rpt100.txt rpt200.txt**
1c1
< github.com/AlDanial/cloc v 1.83  T=45.52 s (0.0 files/s, 0.0 lines/s)
---
> github.com/AlDanial/cloc v 1.83  T=85.37 s (0.0 files/s, 0.0 lines/s)

[rpt100.txt](https://github.com/AlDanial/cloc/files/3454915/rpt100.txt)
[rpt200.txt](https://github.com/AlDanial/cloc/files/3454917/rpt200.txt)
[rpt1000-linux.txt](https://github.com/AlDanial/cloc/files/3454918/rpt1000-linux.txt)

**Comment by AlDanial** [comment]
Curious that 200 on Windows is slower than 100; I would have expected the opposite.  I'll change the value to 100 on Windows then.
