### ISSUE TITLE
 --follow-links will invalidate --exclude-dir 

### ISSUE THREAD

**Issue by wejczhu** [AlDanial/cloc#407]
When I try to use  --follow-links and --exclude-dir meantime , I found that --exclude-dir will nolonger works in some cases, for me it seems like a bug and this issue is related to #286

The detail scenarios are as follow：
### 1.
├── 1.cpp
├── 2.cpp
├── link -> /home/xxx/Desktop/link
└── Test
    ├── 3.cpp
    └── 4.cpp
 cloc * exclude-dir=Test                                 
 **result:**  `3.cpp and 4.cpp are ignored correctly`
 cloc * exclude-dir=Test   --follow-links         
 **result:**  `3.cpp and 4.cpp are ignored correctly`

### 2.
├── 1.cpp
├── 2.cpp
├── level
│   └── Test
│       ├── 3.cpp
│       └── 4.cpp
└── link -> /home/xxx/Desktop/link
 cloc * exclude-dir=Test                                 
 **result:**  `3.cpp and 4.cpp are ignored correctly`
 cloc * exclude-dir=Test   --follow-links         
 **result:**  `no files are ignored`

So if the Test directory is a subdirectory, I can not use both --follow-links and --exclude-dir at same time.

**Comment by AlDanial** [comment]
Give 8b7a7e2 a try.

**Comment by wejczhu** [comment]
Thanks for your hotfix, but there are still some problems

scenario:
├── 1.cpp
├── 2.cpp
└── level
&emsp; └── Test
&emsp;&emsp;├── 3.cpp
&emsp;&emsp;├── 4.cpp
&emsp;&emsp;└── level2
&emsp;&emsp;&emsp;&emsp;├── 5.cpp
&emsp;&emsp;&emsp;&emsp;└── 6.cpp
cloc * exclude-dir=Test
result: `3.cpp, 4.cpp, 5.cpp and 6.cpp are ignored correctly`
cloc * exclude-dir=Test --follow-links
result: `3.cpp and 4.cpp are ignored , 5.cpp and 6.cpp still be counted`

**Comment by AlDanial** [comment]
Thanks for continuing to check this combination.  I'm pretty sure I have the right logic now; bd3b2a4

**Comment by wejczhu** [comment]
Now it works, Thanks!

**Comment by AlDanial** [comment]
Thanks for testing.
