### ISSUE TITLE
wrongly named Ruby file identified as Prolog causes wrong count

### ISSUE THREAD

**Issue by td-amadeus** [AlDanial/cloc#408]
A very simple Ruby file (see below) having the extension .pl and a she-bang line causes the she-bang line being counted twice, giving a comment count of -1:

-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Prolog                           1              1             -1              3
-------------------------------------------------------------------------------

-----8<----- example code -----8<-----
!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), "/some_code.rb")
-----8<-----
The fix is easy, you'll get a pull-request.

**Comment by td-amadeus** [comment]
OK, as I can't create a PR you get the fix as attached patch.
[cloc-issue-408.patch.txt](https://github.com/AlDanial/cloc/files/3519125/cloc-issue-408.patch.txt)

**Comment by AlDanial** [comment]
Even a test case, nicely done!
