### ISSUE TITLE
Unstable LOC Detection

### ISSUE THREAD

**Issue by asadcr** [AlDanial/cloc#410]
Please see file 
[AP821B.txt](https://github.com/AlDanial/cloc/files/3550028/AP821B.txt). (Rename it to `AP821B.I` since `SWIG` files cannot be uploaded here)

The ideal numbers should be `Blank:3` `Comment:7` and `Code:40`. but sometimes it reports `Blank:3` `Comment:47` and `Code:0` which is unstable

**Comment by AlDanial** [comment]
I ran cloc 1,000 times against your file using
<pre>
for i in `seq -w 1 1000`
do
  echo -n "$i "
  cloc AP821B.i  | grep SWIG
done
</pre>
and got the same answer (3 blank, 7 comment, 40 code) each time.  Don't know how to duplicate the problem you're seeing.

**Comment by asadcr** [comment]
I could not reproduce this error also. It happened randomly in our product and vanished after a couple days. we can close this now. Thank you
