### ISSUE TITLE
[Feature Request]: Add option `--smart` to parse `scm ignore` file, to avoid counting non-tracked source code.

### ISSUE THREAD

**Issue by stevenleeS0ht** [AlDanial/cloc#412]
It will be awesome to add option `--smart` to parse `scm ignore` file, to avoid counting non-tracked source code.

**Comment by AlDanial** [comment]
There's already a ``--vcs`` switch that allows you to define your source control system (currently only git and subversion) and ignore non-controlled files.

Did you have something different in mind?

**Comment by stevenleeS0ht** [comment]
@AlDanial , it is nice for me. I didn't notice it before.
