### ISSUE TITLE
Ignore file not being generated

### ISSUE THREAD

**Issue by oculushut** [AlDanial/cloc#415]
Hi there,

I am running

`````
cloc . --ignored ignore.txt
`````
The report says that several files have been ignored and a ignore.txt has been generated.  However, the ignore.txt file is empty.  My expectation was that the ignore.txt file would contain a list of the ignored files and the reason why they were ignored.

Am I missing something?

(Great tool btw!)

Thanks!

**Comment by AlDanial** [comment]
yeah, there was a problem with v1.82 but it's been fixed in the development version, ref #401
