### ISSUE TITLE
Some inaccuracies in "Limitations" section of readme file

### ISSUE THREAD

**Issue by MustafaYesilyurt** [AlDanial/cloc#416]
Hi! I'm using cloc to work on a project, and I want to express my gratitude and appreciation to everyone who worked hard making the program. I hope my post can be helpful in improving it as much as possible.

When I was looking over some cloc results for C, C++, and Java (among others), I noticed some discrepancies with the data. Upon investigating the readme's section describing cloc's limitations, I found the first listed point to be inaccurate. It reads as the following:
**"Lines containing both source code and comments are counted as lines of code."** 

There are exactly two cases where this statement is accurate (also note that these cases do not constitute flaws or limitations):

**The following lines are counted CORRECTLY as CODE:**
`/*insert comment here*/ println("hello world");`
`println("hello world"); //insert comment here`

Where the listed limitation breaks down, however, is when a line contains both source code and a **multi-line** comment where **_the code precedes the comment as_, in this example**.

**This line is counted INCORRECTLY as a COMMENT:**
`println("hello world"); /*insert comment here*/`

As you may guess, this has proven to be extremely damaging to my data, with code line counts being far lower than they are supposed to be.

**Comment by AlDanial** [comment]
Which version of cloc are you using, and on what platform?  I'm unable to reproduce this rather severe bug.  Here's what I tried:

<pre>
/* hello.java */
import java.io.*;
class Hi {
  static public void main( String args[] ) {
    System.out.println( "Hello World!" );  /*
                                              insert comment here
                                            */
  }
}
</pre>
which should have three comments--the first line plus the 2nd and 3rd lines of the multi-line comment--and the rest code.  cloc agrees:
<pre>
> cloc hello.java 
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.83  T=0.01 s (146.3 files/s, 1316.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                             1              0              3              6
-------------------------------------------------------------------------------
</pre>

Similarly for C++,
<pre>
// hello.C
#include <iostream>
int main ()
{
    std::cout << "hello" << std::endl;  // comment 1
    std::cout << "again" << std::endl;  /* comment
                                           2 */
}
</pre>
gives
<pre>
> cloc hello.C
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.83  T=0.01 s (144.3 files/s, 1154.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              1              0              2              6
-------------------------------------------------------------------------------
</pre>

**Comment by MustafaYesilyurt** [comment]
I am using Ubuntu on a Windows 10 system. The version number is 1.74

**Comment by MustafaYesilyurt** [comment]
All right, that solved the problem. I had version 1.74, but those problems are corrected with 1.82. Thanks!
