### ISSUE TITLE
About --not-match-d regex

### ISSUE THREAD

**Issue by Leon-Zhang** [AlDanial/cloc#417]
How to ignore following 2 folders using --not-match-d:

./folder-lev1/folder-lev2-1
./folder-lev1/folder-lev2-2

Thanks.

**Comment by AlDanial** [comment]
``--not-match-d 'folder-lev2-[12]'``

**Comment by Leon-Zhang** [comment]
@AlDanial Thanks, but I think this will have problem, because there are other folders contains same subfolder name which I dont want to exclude, like:
./folder2-lev1/folder-lev2-1
./folder2-lev1/folder-lev2-2

**Comment by AlDanial** [comment]
Post a series of instructions, or a zip or tar file, that create the file and directory structure you want to test this on, then explain which directories you want the counter to include and which to exclude.

**Comment by Leon-Zhang** [comment]
@AlDanial I only want to exclude these 2 2nd level folders:

./folder-lev1/folder-lev2-1
./folder-lev1/folder-lev2-2

and include all other folders in any situation.

Thanks.

**Comment by AlDanial** [comment]
Yes, precisely, that's what my solution will do.

If you want to prove me wrong, post a zip file containing a directory tree it fails on.
