### ISSUE TITLE
JSON Output not valid for C/C++ report

### ISSUE THREAD

**Issue by bcoov** [AlDanial/cloc#418]
In version 1.72 of CLOC, the JSON output formats C/C++ values with a forward slash for the section label:
```
...
"C/C++ Header" :{
  "nFiles": 1,
  "blank": 2,
  "comment": 3,
  "code": 4},
...
```

The latest stable version (1.82) now uses a backward slash in the section label, creating invalid JSON:
```
...
"C\C++ Header" :{
  "nFiles": 1,
  "blank": 2,
  "comment": 3,
  "code": 4},
...
```

**Comment by AlDanial** [comment]
I'm not seeing that at all:
<pre>
cloc-1.82.pl --json tests/inputs/locale_facets.h   

{"header" : {
  "cloc_url"           : "github.com/AlDanial/cloc",
  "cloc_version"       : "1.82",
  "elapsed_seconds"    : 0.0114791393280029,
  "n_files"            : 1,
  "n_lines"            : 1588,
  "files_per_second"   : 87.1145450391509,
  "lines_per_second"   : 138337.897522172},
"C/C++ Header" :{
  "nFiles": 1,
  "blank": 191,
  "comment": 780,
  "code": 617},
"SUM": {
  "blank": 191,
  "comment": 780,
  "code": 617,
  "nFiles": 1} }
</pre>

Is it possible you have a locally-modified version of cloc or one that uses a local language definition file?

**Comment by AlDanial** [comment]
My mistake; you're right:
<pre>
./cloc-1.82.pl --windows --json tests/inputs/locale_f
acets.h

{"header" : {
  "cloc_url"           : "github.com/AlDanial/cloc",
  "cloc_version"       : "1.82",
  "elapsed_seconds"    : 0.0120220184326172,
  "n_files"            : 1,
  "n_lines"            : 1588,
  "files_per_second"   : 83.1807075995558,
  "lines_per_second"   : 132090.963668095},
"C\C++ Header" :{
  "nFiles": 1,
  "blank": 191,
  "comment": 780,
  "code": 617},
"SUM": {
  "blank": 191,
  "comment": 780,
  "code": 617,
  "nFiles": 1} }
</pre>

Thanks for reporting this.

**Comment by bcoov** [comment]
No worries, I was just re-running to make sure I wasn't crazy. It probably would've helped if I had specified a Windows platform originally though :smile: Glad to help!

**Comment by AlDanial** [comment]
I take it since you're on Windows you don't have an easy way to check the update in d748eb2?

**Comment by bcoov** [comment]
Took a little work, but I managed. Looks like that fixed it!
