### ISSUE TITLE
Add support for GDScript

### ISSUE THREAD

**Issue by 29jm** [AlDanial/cloc#42]
This is the scripting language for the Godot game engine.
The file extension is .gd and the comments are everything following a # to the end of the line, like in python and most other scripting languages.
Here's a sample file https://github.com/godotengine/godot/blob/master/demos/2d/area_input/input.gd

**Comment by AlDanial** [comment]
git commit edf467f adds support for GDScript.

Can .gd files also be invoked with a #! first line?  If yes, what is the name of the executable?  godot?

**Comment by 29jm** [comment]
I'm pretty sure they can't be invoked with a #! as they're meant to run as a part of a "scene" and not on their own.
Thank you!
