### ISSUE TITLE
Can't take log of 0 at /usr/local/bin/cloc line 1181 when --html

### ISSUE THREAD

**Issue by mensfeld** [AlDanial/cloc#423]
Steps to reproduce:

```
git clone https://github.com/mensfeld/broken-cloc.git
cd broken-cloc
cloc --html *
```

result:

```
       1 text file.
       1 unique file.                              
Can't take log of 0 at /usr/local/bin/cloc line 11818.
```

the md files aren't created.

The md file that is in place contains only whitespace.

**Comment by AlDanial** [comment]
+1 for submitting an issue for an undocumented feature :)

**Comment by mensfeld** [comment]
+1 for fixing an issue for an undocumented feature :)

Looking forward to a release (if doable).

**Comment by AlDanial** [comment]
My plan is two releases a year.  Unfortunately we're near the beginning of a cycle (1.84 came out a month ago) so expect another five months or so before the next release.
