### ISSUE TITLE
Cloc Doesn't Count Multi-line comment

### ISSUE THREAD

**Issue by Drgon00** [AlDanial/cloc#424]
Hi @AlDanial, 
Do you have any comment on the below section - 

> _#if 0 
      do something 
      still a comment 
    Closing multiline comment 
#endif_ 

The above comment is w.r.t to C
As far as I have used and varify this Cloc will not count the above lines as a comment.

**Comment by MustafaYesilyurt** [comment]
I was not under the impression that those lines are to be counted as comments in C. The only lines that are, as a standard, counted as comments, are lines prefaced with "//" or, for multi-line comments, in between "/*" and "*/". Every online source I consulted says the same.

**Comment by AlDanial** [comment]
The reply by @MustafaYesilyurt is correct--what you have shown is a compiler pragma, not a comment.  cloc does not deal with pragma's.

**Comment by Drgon00** [comment]
Hi AIDanial, @MustafaYesilyurt thanks for the clarification 

> Cloc doesn't count compiler pragma. 
It would be really helpful if you mentioned this in Cloc Doc.

**Comment by AlDanial** [comment]
Good idea.  I added this as Limitation 6, https://github.com/AlDanial/cloc#limitations-

**Comment by Drgon00** [comment]
thanks, @AlDanial now it will more clear and avoid confusion 

> cloc treats compiler pragma's for example, #if / #endif, as code even if these **are are** used to block lines of source from being compiled; the blocked lines still contribute to the code count.

Just a suggestion, replace the lines with below suggestion -:  

> cloc treats compiler pragma's, for example #if / #endif, as code even if these are used to block lines of source code from being compiled; the blocked lines still contribute to the code count.

**Comment by AlDanial** [comment]
Good catch, thanks.
