### ISSUE TITLE
Not able to use --diff and --include-ext options together when the same command is looped into different path set

### ISSUE THREAD

**Issue by anand0422** [AlDanial/cloc#425]
mainpath1 and mainpath2 (This has base path of source)
subpathList (list containing specific folder directory inside the mainpath)

iterC = 1
for item in subpathList:
       os.system("cloc-1.84.exe --include-ext=c,cpp,h --report_file=somefile"+str(iter)+".txt --diff-timeout 0 --diff "+mainpath1+item+" "+ mainpath2+item)
      iterC = iterC +1

This is python code to generate difference between main business logic instead of supporting file. In short the below command is executed in a loop till all the items in the list(**subpathList**) are done.
**cloc-1.84.exe --include-ext=c,cpp,h --report_file=somefile.txt --diff <set1> <set2>**

**Comment by AlDanial** [comment]
Let's start by separating the Python environment from what cloc is being asked to do.  Replace
<pre>
os.system("cloc-1.84.exe --include-ext=c,cpp,h --report_file=somefile"+str(iter)+".txt --diff-timeout 0 --diff "+mainpath1+item+" "+ mainpath2+item)
</pre>
with
<pre>
print("cloc-1.84.exe --include-ext=c,cpp,h --report_file=somefile"+str(iter)+".txt --diff-timeout 0 --diff "+mainpath1+item+" "+ mainpath2+item)
</pre>
then post the output from this print statement.  Better yet, invoke each line manually and see what happens.

**Comment by anand0422** [comment]
I have checked each line  manually, the paths which only contains "C/Cpp" and "h" extensions are executed, i can that
C
Same
Modified
Added
Removed

C/C++ header
Same
Modified
Added
Removed

These statistics are displayed, and if the path containing other than "C"/"h" like in my case XML,yaml,ini,html,asm,bat,shell files those statistics are also displayed when i use any combination of options.
1. --diff and --include-ext=c,cpp,h and --diff-timeout 0
2. --diff and --exclude-ext=XML,html,yaml,asm,ini,bat,sh and --diff-timeout 0
3. --diff and --exclude-lang="XML","Assembly","yaml","html","INI","Batch" --diff-timeout 0

In your tool help, it is mentioned that these skip while counting files, can these options be used while using "diff" options?

**Comment by anand0422** [comment]
I will send you the output in 2 days

**Comment by anand0422** [comment]
cloc-1.84.exe --exclude-ext=xml,html,yaml --diff src\external src_\external --diff-timeout 0 **(Refer the output3.txt)**
cloc-1.84.exe --include-ext=c,cpp,h --diff src\external src_\external --diff-timeout 0 **(Refer the output2.txt - Only output is perfect)**
cloc-1.84.exe --exclude-lang="XML","Assembly","YAML","CSS","HTML","INI","Batch","JavaScript","Python","Bourne Shell" --diff src\external src_\external --diff-timeout 0 **(Refer the output1.txt)**

**Only the output from the option --include-ext gives proper output. Other 2 options --exclude-ext and --exclude-lang doesnt give required output, excluded items are also available in the report.**

**Comment by anand0422** [comment]
[output3.txt](https://github.com/AlDanial/cloc/files/3813685/output3.txt)
[output2.txt](https://github.com/AlDanial/cloc/files/3813686/output2.txt)
[output1.txt](https://github.com/AlDanial/cloc/files/3813687/output1.txt)

**Comment by anand0422** [comment]
Currently i am using the "--include-ext" as it is giving me desired output.
Currently i am blocked with the problem which i had raised to you. Issue: 432 (https://github.com/AlDanial/cloc/issues/432)

**Comment by AlDanial** [comment]
Let's start with the failure of ``--diff`` with ``--exclude-lang`` together.  Since I don't have access to your code base, I'm testing with two older releases of cloc:
<pre>
cloc --diff-timeout 0 --exclude-lang XML,"DOS Batch",Focus,MUMPS,XQuery,xBase --diff cloc-1.80.tar.gz cloc-1.84.tar.gz
</pre>
All the languages I asked to be exclude are excluded.  What happens with this command for you?

**Comment by anand0422** [comment]
--include-ext option works fine, so i am using this option
I have used the --exclude-lang="XML","Assembly","YAML","CSS","HTML","INI","Batch","JavaScript","Python","Bourne Shell" with parameter

I could see in the report having summary of excluded lang "XML","Python","Bourne Shell" please check the uploaded file output1.txt

**Comment by AlDanial** [comment]
Please supply information needed to reproduce the problem; see https://github.com/AlDanial/cloc#reporting-problems-

**Comment by anand0422** [comment]
All the command executed output files are attached, i didn't understand what i am missing.

Output of command is available in your issue page.
https://github.com/AlDanial/cloc/files/3813687/output1.txt

**Comment by AlDanial** [comment]
Yes, I have the output.  But to really examine the underlying problem you're experiencing I need the input--the files and directories being counted--as well.  I don't necessarily _your_ exact input, but just some input that shows the problem.

**Comment by AlDanial** [comment]
Can't replicate.
