### ISSUE TITLE
XHTML files aren't all JavaServer Faces files

### ISSUE THREAD

**Issue by bedney** [AlDanial/cloc#43]
Many of us use XHTML outside of JavaServer faces ;-).

Right now, we're forced to use the additional flag:

`--force-lang="HTML",xhtml`

And then it counts them as "HTML" files, which isn't accurate.

**Comment by AlDanial** [comment]
git commit cb08ee3 introduces XHTML as a new supported language and associates the .xhtml extension with it (sorry JavaServer Faces).  Not knowing better I'm using the HTML counter also for XHTML--your comment suggests this isn't the right thing to do.  If it isn't, let me know what would be better.

**Comment by bedney** [comment]
Thanks for the patch! Yea, I'd rather have completely separate counter for XHTML... or maybe use the XML counter. XHTML is, after all, an XML language. But it really would just be better to have a separate counter for XHTML. I do have a project that has all 3 kinds of files in it (HTML, XHTML and generic XML) and splitting them out into the 3 counters would be the best for me. Thanks again!

**Comment by AlDanial** [comment]
OK, just post an issue if the XHTML counts aren't coming out the way you expect.

**Comment by bedney** [comment]
This looks exactly right. Thank you!
