### ISSUE TITLE
When new file is added in on source --diff option generates the report as one file added and removed

### ISSUE THREAD

**Issue by anand0422** [AlDanial/cloc#432]
There are two versions of source code.
src - original base code
src_ - new file added in one of folder in the original base code

Attached the 2 outputs having both source version same and 2nd output with "src_" version having one new added file.
![output](https://user-images.githubusercontent.com/23243408/68287911-850e4780-00a9-11ea-959a-93ec28049612.png)

**Comment by AlDanial** [comment]
Rerun with this additional argument: ``--diff-alignment=file_pairs.txt`` then post the lines of ``file_pairs.txt`` which show the added file.

**Comment by anand0422** [comment]
I could not send the file_pairs.txt as my i had to check with my management but have done some more test to identify exact cause.

Initially when i raised the issue i had done following steps:
1. src/folder1/folder2  - There is a file "hal_api.c" had created a duplicate file "hal_api2.c", these both file exact identical match without any difference

The file_pairs.txt has this information:
Files added: 1
  + src_/folder1/folder2/hal_api2.c ; C

Files removed: 1
  - src/folder1/folder2/hal_api.c ; C **(This was not removed but shows as removed)**

**Output:** duplicate file with different name causes this issue

**With new Test:**
1. src/folder1/folder2  - There is a file "hal_api.c" had created a duplicate file "hal_api2.c" but have changed the function names in the file "hal_api2.c" to make them look different.

**Output: ** I can the out shows perfectly fine.
you can see the output in the attached log. duplicate file with different name causes this issue
![output](https://user-images.githubusercontent.com/23243408/68362854-be4cc300-014e-11ea-88fe-5ff7eb6d3974.png)

**Comment by AlDanial** [comment]
Please supply information needed to reproduce the problem; see https://github.com/AlDanial/cloc#reporting-problems-

**Comment by AlDanial** [comment]
Are you able to craft a pair of directories you can share with me to demonstrate this?  I can't do anything with your screen shots.
