### ISSUE TITLE
Getting this error:- Sequence \k... not terminated in regex

### ISSUE THREAD

**Issue by Pacchu01** [AlDanial/cloc#434]
I am getting this error. May I know how to resolve this. It will be really great if you help me on this. Thanks in advance.

Sequence \k... not terminated in regex; marked by <-- HERE in m/^C:\Users\k <-- HERE User\Desktop/ at C:\Users\username\AppData\Roaming\npm\node_modules\cloc\lib\cloc line 12129.

**Comment by AlDanial** [comment]
Please supply information needed to reproduce the problem; see https://github.com/AlDanial/cloc#reporting-problems-
