### ISSUE TITLE
Add LOC Detection for .vbp extension

### ISSUE THREAD

**Issue by asadcr** [AlDanial/cloc#439]
.vbp is Visual Basic 5/6 project extension. How hard would it be to detect LOC's in vbp extension ?

I see the extension is commented out. 
https://github.com/AlDanial/cloc/blob/513dac6572e135a0a754ff6783b0047902d7547e/cloc#L7595

AFAIK .vbp is not auto-generated. Not sure about CLOC Context.

**Comment by AlDanial** [comment]
shouldn't be hard given the necessary information, ref
https://github.com/AlDanial/cloc#requesting-support-for-additional-languages-

**Comment by asadcr** [comment]
thank you. will provide those shortly. would it also be possible to provide some documentation on how to add a new language so that we can open a PR directly and contribute ?

**Comment by AlDanial** [comment]
Until I have formal documentation, please look at PR #430 (specifically the diff https://github.com/AlDanial/cloc/commit/eb634a4249fd85cee6512344530d83069bbf8718).  It is an excellent example of what's needed for cloc to support a new language, including a unit test.
