### ISSUE TITLE
Support for Crystal

### ISSUE THREAD

**Issue by meskyanichi** [AlDanial/cloc#44]
http://crystal-lang.org/

Syntax is very similar to Ruby.

- Shell script with `#! /usr/bin/env crystal`
- Comments with `#` (like Ruby)
- File extension `.cr` (instead of `.rb` in Ruby)
- No `Rakefile`/`Gemfile`/etc (unlike Ruby).

Example code of a lib I just wrote: https://github.com/meskyanichi/commander

**Comment by AlDanial** [comment]
git commit 66294de adds support for Crystal.  Please test it out and let me know if it works as you expect.

**Comment by meskyanichi** [comment]
That was quick! It appears to work perfectly. Thanks! :+1:
