### ISSUE TITLE
SugarSS support

### ISSUE THREAD

**Issue by toastal** [AlDanial/cloc#440]
[SugarSS](https://github.com/postcss/sugarss) is an alternative syntax for the popular PostCSS toolchain. Syntactically it's almost identical to Sass's indented syntax. One syntactical difference between it and Sass however is that one can [break long lines into several for readability](https://github.com/postcss/sugarss#multiline) (but does this count as one line for `cloc` or multiple?).

**Comment by AlDanial** [comment]
Please provide the items described at
https://github.com/AlDanial/cloc#requesting-support-for-additional-languages- 

cloc counts physical, as opposed to logical lines and so will count each line of a long split line.

**Comment by toastal** [comment]
SugarSS MIME-type is `text/x-sugarss` with `.sss` file extension.

Sample (more at @ any `.sss` file in the [SugarSS's tests](https://github.com/postcss/sugarss/tree/master/test/cases):

```sss
.one
  background: linear-gradient(rgba(0, 0, 0, 0), black)
              linear-gradient(red, rgba(255, 0, 0, 0))

.two
  background:
    linear-gradient(rgba(0, 0, 0, 0), black)
    linear-gradient(red, rgba(255, 0, 0, 0))
```

Comments:

```sss
/*
 Multiline comments
 */

// Inline comments
```
