### ISSUE TITLE
Automatically detect git/svn repos and set --vcs accordingly

### ISSUE THREAD

**Issue by wolframroesler** [AlDanial/cloc#443]
Proposed extension: Add command line option `--vcs=auto` which behaves like this:

* If directory `.git` exists, behave like `--vcs=git`.
* If invoked for a Subversion repo (don't know how to detect that), behave like `--vcs=svn`.
* Else, behave as if invoked without `--vcs`.

The same could be accomplished in the current version already with `--vcs=magic` where `magic` is a command that provides an appropriate file list.

Example command line:

```
$ cloc --vcs==auto .
```

In fact, I'd like to put something like `alias cloc=cloc --vcs=auto` into my profile to make it "just do the right thing".

**Comment by mms0536** [comment]
I think this is not a good idea.
During actual use, multiple git repositories may be nested or exist submoudle, for example:

```
repoA/.git
repoA/repoB/.git
```

When you execute the command in `repoA`, if you use `--vcs = auto`, you can only get the file list of `repoA`, leaving out `repoA/repoB/`

**Comment by wolframroesler** [comment]
@mms0536 In the case you describe, how would `--vcs=git` behave? I'd expect `--vcs=auto` to do exactly the same.

Speaking in bash terms, behave like this when invoked with `--vcs=auto`:

```sh
my_cloc() {
    if [ -d .git ];then
        cloc --vcs=git $*
    elif [ -d .svn ];then
        cloc --vcs=svn $*
    else
        cloc $*
   fi
}
```

**Comment by AlDanial** [comment]
@mms0536 : the proposed ``--vcs=auto`` would not preclude one from using ``--vcs=git``.  I'm inclined to implement this.
