### ISSUE TITLE
Default to current directory

### ISSUE THREAD

**Issue by wolframroesler** [AlDanial/cloc#444]
Current behaviour: Invoking `cloc` without any file/directory/hash parameter displays an error message.

Proposed modification: If no file/directory/hash is specified on the command line, behave as if `.` was specified.

Example command line: 

```
$ cloc --vcs=git
```

should behave identically to

```
$ cloc --vcs=git .
```

**Comment by AlDanial** [comment]
I'm not keen on this idea because it makes the user interface inconsistent.  For example why should ``--vcs=git`` work differently from most other switches, eg, ``--json`` or ``--fullpath``?  I'd have to make all the switches behave the same way, ultimatly getting down to just ``cloc`` by itself without args.

**Comment by wolframroesler** [comment]
I'm afraid I didn't make myself clear. The suggestion is not about `--vcs`, that was just an example; the suggestion is to use `.` as the source directory when the caller doesn't specify one explicitly.

Current behaviour:

```
$ cloc
(shows usage message)
$ cloc .
(counts code lines in current directory)
```

Suggested new behaviour:

```
$ cloc
(counts code lines in current directory, same as "cloc .")
$ cloc .
(counts code lines in current directory as before)
```

This shall work with `--vcs`, `--json`, and all other options.

May I ask you to reconsider the suggestion?

**Comment by AlDanial** [comment]
Thanks for the clarification, makes sense now.  It's not a bad idea, but it would hide the brief usage banner--actually a small advertisement--which I like.

**Comment by wolframroesler** [comment]
Well it's your choice of course, but ... sacrificing usability for advertising? That's not the Open Source spirit.

It's not the Unix spirit either. I'm glad that `ls`, `du`, `grep -r` etc. all default to the current directory when I don't specify one.

**Comment by AlDanial** [comment]
Everything you're saying is true.  Displaying the advertisement violates the Open Source and the Unix spirit.  I thought I was being helpful but now I see I'm vain.
