### ISSUE TITLE
Allow user to output results in json format

### ISSUE THREAD

**Issue by stardust85** [AlDanial/cloc#45]
json is my favourite serialization format and I need to handle the output programatically - from python

**Comment by AlDanial** [comment]
Help me out here... what is it you're after?  You want cloc to count json files (it already does)?  You want cloc to write results in json?  You want to load json into Python?

**Comment by stardust85** [comment]
Sorry for my brevity, I'd like to be able to get the results in json format, because it is the most convenient format for parsing in python and I need to post-process the results in python. Or more concretely, I need to prepare them for drawing them in zabbix for different revisions.

**Comment by AlDanial** [comment]
Sure, I can add a json output option.  May be a few weeks before I get to it though.  In the meantime, please give the YAML serialization a try; works great with Python.

First create YAML output with cloc:

<code>
cloc --yaml --out x.yaml bin
</code>

Next, load the YAML file <code>x.yaml</code> into a Python variable.  Here's a sample ipython session:

<code>
 In [1]: import yaml

 In [2]: x = yaml.load(file('x.yaml'))

 In [3]: x

 Out[3]: {'Bourne Shell': {'blank': 53, 'code': 448, 'comment': 94, 'nFiles': 30},
 'C': {'blank': 4, 'code': 50, 'comment': 19, 'nFiles': 1},
 'HTML': {'blank': 151, 'code': 8866, 'comment': 207, 'nFiles': 30},
 'MATLAB': {'blank': 0, 'code': 22, 'comment': 1, 'nFiles': 1},
 'Perl': {'blank': 2004, 'code': 22682, 'comment': 4221, 'nFiles': 164},
 'Python': {'blank': 101, 'code': 553, 'comment': 284, 'nFiles': 3},
 'SUM': {'blank': 2313, 'code': 32621, 'comment': 4826, 'nFiles': 229},
 'header': {'cloc_url': 'http://cloc.sourceforge.net',
  'cloc_version': 1.65,
  'elapsed_seconds': 0.519536018371582,
  'files_per_second': 440.777909331042,
  'lines_per_second': 76529.8239083068,
  'n_files': 229,
  'n_lines': 39760,
  'report_file': 'x.yaml'}}
</code>

**Comment by AlDanial** [comment]
git commit 0682cde implements --json output

**Comment by stardust85** [comment]
Awesome! Thanks a lot! When Can I expect this to be released?

**Comment by AlDanial** [comment]
You can pull the source from the master branch now.  The next release will be in a week or two.
