### ISSUE TITLE
Diff LOC Count is Inconsistent with Regular LOC Count

### ISSUE THREAD

**Issue by asadcr** [AlDanial/cloc#450]
`PS E:\dd> cloc --diff --ignore-case --ignore-whitespace --quiet --skip-uniqueness --by-file --diff-timeout 300 A.js B.js`
```
github.com/AlDanial/cloc v 1.84  T=0.50 s (8.0 files/s, 182.0 lines/s)
-------------------------------------------------------------------------------
File                           blank        comment           code
-------------------------------------------------------------------------------
A.js
 same                              0             66             25
 modified                          0              0              0
 added                             0              0              0
 removed                           0              0              0
-------------------------------------------------------------------------------
SUM:
 same                              0             66             25
 modified                          0              0              0
 added                             0              0              0
 removed                           0              0              0
-------------------------------------------------------------------------------
```
`PS E:\dd> cloc ./ -exclude-dir=node_modules --by-file --strip-str-comments --skip-uniqueness --timeout=300`
```
       2 text files.
       2 unique files.
       1 file ignored.

github.com/AlDanial/cloc v 1.84  T=0.50 s (4.0 files/s, 364.0 lines/s)
-------------------------------------------------------------------------------
File                             blank        comment           code
-------------------------------------------------------------------------------
.\A.js                               0             71             20
.\b.js                               0             71             20
-------------------------------------------------------------------------------
SUM:                                 0            142             40
-------------------------------------------------------------------------------
PS E:\dd>
```

**Comment by asadcr** [comment]
[A.txt](https://github.com/AlDanial/cloc/files/4030095/A.txt)
[b.txt](https://github.com/AlDanial/cloc/files/4030096/b.txt)
Please rename the txt files to js

These are the input files.
I understand that the file is confusing cloc but i think the LOC should be consistent

**Comment by AlDanial** [comment]
cloc is consistent; you are not. You use ``--strip-str-comments`` in the second case but not in the first.  If both commands have this switch they return consistent counts:

<pre>
> cloc -exclude-dir=node_modules --by-file --strip-str-comments --skip-uniqueness --timeout=300  A.js b.js
       2 text files.
       2 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.85  T=0.03 s (61.5 files/s, 5598.1 lines/s)
-------------------------------------------------------------------------------
File                             blank        comment           code
-------------------------------------------------------------------------------
A.js                                 0             71             20
b.js                                 0             71             20
-------------------------------------------------------------------------------
SUM:                                 0            142             40
-------------------------------------------------------------------------------
> cloc --strip-str-comments --diff --ignore-case --ignore-whitespace --quiet --skip-uniqueness --by-file --diff-timeout 300 A.js b.js

github.com/AlDanial/cloc v 1.85  T=0.02 s (187.1 files/s, 4255.7 lines/s)
-------------------------------------------------------------------------------
File                           blank        comment           code
-------------------------------------------------------------------------------
A.js
 same                              0             71             20
 modified                          0              0              0
 added                             0              0              0
 removed                           0              0              0
-------------------------------------------------------------------------------
SUM:
 same                              0             71             20
 modified                          0              0              0
 added                             0              0              0
 removed                           0              0              0
-------------------------------------------------------------------------------
</pre>
