### ISSUE TITLE
 Unsupported text file format

### ISSUE THREAD

**Issue by zhuheng-mark** [AlDanial/cloc#451]
I have a c file, but cloc cannot calculate the number of lines of code in it。

$ cloc --version
1.84

$ cloc ./Common.h
       0 text files.
       0 unique files.
       1 file ignored.

[Common.h.zip](https://github.com/AlDanial/cloc/files/4038247/Common.h.zip)

**Comment by AlDanial** [comment]
<pre>
> cloc Common.h
       0 text files.
       0 unique files.                              
       1 file ignored.
</pre>

The ``--ignored`` switch will create a text file explaining why files were ignored:

<pre>
> cloc --ignored=ign.txt Common.h                 
       0 text files.
       0 unique files.                              
Wrote ign.txt
       1 file ignored.
> cat ign.txt 
Common.h: binary file
</pre>

It thinks this is a binary file (the test uses Perl's ``-b <file>`` operator to determine this).  I imagine Perl is confused by the file encoding and characters that appear in the comment fields.  No matter, you can force cloc to read binary files:

<pre>
> cloc --read-binary Common.h                     
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.85  T=0.01 s (118.2 files/s, 15010.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                     1             18             31             78
-------------------------------------------------------------------------------
</pre>

**Comment by zhuheng-mark** [comment]
Thanks for your help, cloc is really a great tool
