### ISSUE TITLE
Support Vala

### ISSUE THREAD

**Issue by aggalex** [AlDanial/cloc#452]

**Comment by AlDanial** [comment]
Please provide the items described at
https://github.com/AlDanial/cloc#requesting-support-for-additional-languages-

**Comment by aggalex** [comment]
Sure.
## Extensions:
- .vala (vala files) 
- .vapi (vapi files for introspection with c files)

## Comments
    // Comment continues until end of line

    /* Comment lasts between delimiters */

    /**
     * Documentation comment
     */

## Links to sample code
https://wiki.gnome.org/Projects/Vala/ValaForJavaProgrammers
https://wiki.gnome.org/Projects/Vala/Examples

**Comment by AlDanial** [comment]
I went to add vala support and saw it is already in there.  Try the latest release of cloc, 1.84, from https://github.com/AlDanial/cloc/releases
