### ISSUE TITLE
"Complex regular subexpression recursion limit" even with `--strip-str-comments`

### ISSUE THREAD

**Issue by svdo** [AlDanial/cloc#454]
Hi,

First of all: may thanks for your work on `cloc`, we all greatly appreciate it!

I just ran into the warning `Complex regular subexpression recursion limit (32766) exceeded at cloc line 9879`. This is version 1.84 by the way, installed using homebrew.

This is the JavaScript code that triggers the warning:

```javascript
function createServer () {
  server.use(bodyParser.text({ type: '*/*' }))

  server.post('/:queueId', async function (request, response) {
    response.status(200).end()
  })

  server.get('/:queueId', async function (request, response) {
    const message = state
    response.status(200).send(message).end()
  })

  return server
}
```

Searching over here I found the `--strip-str-comments` option, but that does not fix the issue in this particular case. The analysis output is the same, both with and without the option. And it is also correct by the way, so that's why I'm calling it a warning.

**Comment by AlDanial** [comment]
As you may have guessed, the ``'*/*'`` was messing things up--but not in the way I expected.  The logic for handling comments embedded in strings was actually working, it was just that I'd defined JavaScript strings to be defined by just ``"..."`` (like C, C++).  I updated the code to also recognize strings defined by ``'...'`` and that cleaned it up.

**Comment by svdo** [comment]
Awesome, that was very fast! 😀 Thanks!
