### ISSUE TITLE
Provide diff-input method to provide list of files to compare

### ISSUE THREAD

**Issue by asadcr** [AlDanial/cloc#455]
Hi,
Would it be possible to provide cloc with a list of files to do the diffing

something like
cloc --diff input1.txt input2.txt

where input1.txt and input2.txt contain list of fileNames

input1.txt
src/A/FileA.cs;C#
src/A/FileB.cs;C#

input2.txt
src/B/FileA.cs;C#
src/B/FileB.cs;C#

This way we could be able to specify which files to match and which language to use.

**Comment by AlDanial** [comment]
This is a good idea and I'll implement it before the next release.

**Comment by AlDanial** [comment]
Instead of two input files the new option takes one file.  Examples of allowed formats for that file can be found in
https://github.com/AlDanial/cloc/blob/master/tests/inputs/issues/455/list.txt
https://github.com/AlDanial/cloc/blob/master/tests/inputs/issues/455/list_align.txt
