### ISSUE TITLE
Detect XML Files

### ISSUE THREAD

**Issue by asadcr** [AlDanial/cloc#456]
Hi, I have seen that CLOC can detect script files by reading their content, specifically first line.
Would it be possible to also read and detect XML file by reading the first line

Example File would be
```XML
<?xml version="1.0" encoding="utf-8"?>
<!--
    This file is automatically generated by Visual Studio .Net. It is 
    used to store generic object data source configuration information.  
    Renaming the file extension or editing the content of this file may   
    cause the file to be unrecognizable by the program.
-->
<GenericObjectDataSource DisplayName="AllAssetsResultSet" Version="1.0" xmlns="urn:schemas-microsoft-com:xml-msdatasource">
   <TypeInfo>NaviPlan.Datasources.AccumulationGoalData.AllAssetsResultSet, NaviPlan.Datasources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null</TypeInfo>
</GenericObjectDataSource>
```

I believe if the first line starts with `<?xml ` it should be detected as XML

**Comment by AlDanial** [comment]
True, cloc can be updated to scan for the first line of a text file--if the text file has no extension.  The file extension always takes priority.

You didn't provide the file name for the example above.  Do your XML file have extensions?

**Comment by asadcr** [comment]
The extension is .datasource. But the extension is generic. the data format is not limited to XML only. can be any format.
Eg, *.properties *.config extensions are too generic and can contain any format of data. This is why i wanted to scan the first line irrespective of the file extension.

**Comment by AlDanial** [comment]
You're suggesting cloc should examine the first line of not only files with no extension, but also every file with an extension that isn't already recognized?

**Comment by asadcr** [comment]
Yes. Any file (with or without extension), if it is not recognized by CLOC, CLOC examines the first line.

**Comment by AlDanial** [comment]
The potential performance hit is a bit concerning.  Imagine a repo with many data files.  I suppose I'll need to implement this and run some benchmarks before I complain about performance.

**Comment by AlDanial** [comment]
The performance impact was negligible so this check is now done.

**Comment by asadcr** [comment]
@AlDanial Stupid question. Will this also be functional with `--diff` ?

**Comment by AlDanial** [comment]
Yes.
