### ISSUE TITLE
Git+diff slower & wrong since 1.84 

### ISSUE THREAD

**Issue by cbek** [AlDanial/cloc#458]
Hi.

Since 1.84 the strategy to collect files from a git repository via git archive has changed.
The new strategy collects all union files from all commits.
This leads to 2 issues:
- speed - for larger repositories this will take 10-100times more 
- accuracy of commits with only deleted file(s) or only added file(s) 

Let me show an example of the [cloc_submodule_test](https://github.com/AlDanial/cloc_submodule_test) repository.
In commit, [ae0d26e](https://github.com/AlDanial/cloc_submodule_test/commit/ae0d26ea943df50b5867a6486af7b6cbbd627f5f) was only a file deleted

**v 1.84**

```
cloc --diff --git 04179b6 ae0d26e
       8 text files.
       7 text files.
       0 files ignored.                             

github.com/AlDanial/cloc v 1.84  T=0.12 s (68.5 files/s, 10405.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++
 same                            1             49             55            182
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1             76            114            365
C
 same                            2             70             46            231
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
Fortran 90
 same                            1              1              2              3
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
MATLAB
 same                            1              0              1              2
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
Python
 same                            1              4             11              2
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
Markdown
 same                            1              0              0              2
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            7            124            115            422
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1             76            114            365
-------------------------------------------------------------------------------
```

**How it should behave in my opinion**

```
cloc --diff --git 04179b6 ae0d26e
       1 text file.
       0 text files.
       0 files ignored.                             

github.com/AlDanial/cloc v 1.85  T=0.11 s (9.1 files/s, 5059.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1             76            114            365
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1             76            114            365
-------------------------------------------------------------------------------
```

**Comment by cbek** [comment]
Provided a fix/suggestion:
https://github.com/AlDanial/cloc/pull/459

**Comment by AlDanial** [comment]
I just completed a project that consumed nearly all my free time and can finally work on this again.  

Here's a brief recap of where I think things stand, please correct any oversights:  Your PR fixes cloc's ``--diff`` logic but does not correctly handle the ``--count-and-diff`` path.  Output for the two cases using the example above and cloc from your TechMiners-feature-issue458 branch, commit d431a9cba is:

<pre>
cloc_submodule_test> cloc --diff --git 04179b6 ae0d26e                                                                                
       1 text file.
       0 text files.
       0 files ignored.                             

github.com/AlDanial/cloc v 1.85  T=0.04 s (27.1 files/s, 15028.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1             76            114            365
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1             76            114            365
-------------------------------------------------------------------------------
</pre>
which looks great, however
<pre>
cloc_submodule_test> cloc --count-and-diff --git 04179b6 ae0d26e
04179b6::
       8 text files.
       8 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.85  T=0.05 s (169.0 files/s, 25683.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              2            125            169            547
C                                2             70             46            231
Fortran 90                       1              1              2              3
MATLAB                           1              0              1              2
Markdown                         1              0              0              2
Python                           1              4             11              2
-------------------------------------------------------------------------------
SUM:                             8            200            229            787
-------------------------------------------------------------------------------

ae0d26e::
       7 text files.
       7 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.85  T=0.07 s (96.8 files/s, 9139.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                2             70             46            231
C++                              1             49             55            182
Fortran 90                       1              1              2              3
MATLAB                           1              0              1              2
Markdown                         1              0              0              2
Python                           1              4             11              2
-------------------------------------------------------------------------------
SUM:                             7            124            115            422
-------------------------------------------------------------------------------

diff 04179b6 ae0d26e::
       8 text files.
       7 text files.
       0 files ignored.
               
github.com/AlDanial/cloc v 1.85  T=0.11 s (71.6 files/s, 10881.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++
 same                            1             49             55            182
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1             76            114            365
C
 same                            2             70             46            231
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
Fortran 90
 same                            1              1              2              3
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
MATLAB
 same                            1              0              1              2
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
Markdown
 same                            1              0              0              2
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
Python
 same                            1              4             11              2
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            7            124            115            422
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1             76            114            365
-------------------------------------------------------------------------------
</pre>
still shows the old logic for the diff portion.  Do you have time/energy to
fix that, or shall I give it a shot?

**Comment by cbek** [comment]
@AlDanial 
Currently, my time is limited.
Also not sure how it should look like.
Please, go ahead and give it a shot.

I can help with more tests after implementation is done.
