### ISSUE TITLE
Diff error (quoted comments?)

### ISSUE THREAD

**Issue by asadcr** [AlDanial/cloc#463]
Hi, I went through the discussion in #15 for the same issue.
Unfortunately this is not working in my scenario.
Please see files 

[Trust_FO1.txt](https://github.com/AlDanial/cloc/files/4138900/Trust_FO1.txt)
[Trust_FO2.txt](https://github.com/AlDanial/cloc/files/4138901/Trust_FO2.txt)

```powershell
PS D:\> cloc --diff --exclude-dir=node_modules --by-file --strip-str-comments --skip-uniqueness --ignore-case --ignore-whitespace --diff-timeout 600 --force-lang=C++ Trust_FO1.txt Trust_FO2.txt
       1 text file.
       1 text file.
       0 files ignored.

1 error:
Diff error (quoted comments?):  Trust_FO1.txt

github.com/AlDanial/cloc v 1.82  T=8.00 s (0.1 files/s, 0.1 lines/s)
-------------------------------------------------------------------------------
File                           blank        comment           code
-------------------------------------------------------------------------------
Trust_FO1.txt
 same                              0              0              0
 modified                          0              0              0
 added                           268           2775          12556
 removed                           0              0              0
-------------------------------------------------------------------------------
SUM:
 same                              0              0              0
 modified                          0              0              0
 added                           268           2775          12556
 removed                           0              0              0
-------------------------------------------------------------------------------
PS D:\>
```

**Comment by AlDanial** [comment]
The root cause of the problem turns out to be a bug in the sdiff() function from the Algorithm::Diff Perl module.  I submitted a bug report, https://rt.cpan.org/Public/Bug/Display.html?id=131629

I'll have to figure out what cloc should do in such situations; nothing obvious comes to mind.

**Comment by asadcr** [comment]
suggession. replace strings with some fixed text. 
eg `"{     "` => `"there was a string here"`

so all string will be replaced while a valid value which is not error prone to cloc

**Comment by AlDanial** [comment]
The problem has nothing to do with strings.  Any arrangement of characters could trigger the bug.
I think the point you're making is "ignore the error and move on"?  That's the only solution I believe.

**Comment by asadcr** [comment]
yes exactly. u got my point. "ignore the error and move on"
