### ISSUE TITLE
Support of pipeline

### ISSUE THREAD

**Issue by ramanawithu** [AlDanial/cloc#465]
I wish the tool could also support the following format,

`find src -regex '.*\.py' | cloc`

**Comment by AlDanial** [comment]
That's an interesting idea.  Get 413289a then give this a try:
``find src -regex '.*\.py' | cloc --list-file -``

**Comment by ramanawithu** [comment]
No it didn't work.
```
> find src -regex '.*\.py' | cloc --list-file -
Unable to read -; ignoring.
       0 text files.
       0 unique files.
       0 files ignored.

```

**Comment by ramanawithu** [comment]
The pipe line feature would be quite useful. I could use find & xargs combination, however I get one output per file.

**Comment by AlDanial** [comment]
The baseline version of cloc will give that error but the one I just committed shouldn't.  What is the md5sum of the cloc you're running?  Mine is
``24dbaa62abefc06874e12d52aa3c0122  cloc``

Also, what's your OS & OS version?

**Comment by ramanawithu** [comment]
I had my edits for some custom file types, to count on a domain specific language. Here is the check af7bf8955184e3bd343f675978db4120, version "1.76".

**Comment by AlDanial** [comment]
The point of the md5sum is to make sure you had the version of cloc with the new feature.  Yours doesn't match so you're not running the code I updated.  If you want to test the new feature you'll need to download and run the latest.  Get it from https://github.com/AlDanial/cloc/blob/master/cloc

**Comment by ramanawithu** [comment]
Oh, sorry. I missed that you had updated the code. Yes, it worked, thanks.

```
github.com/AlDanial/cloc v 1.85  T=0.71 s (373.6 files/s, 52152.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         266           6350           8843          21935
-------------------------------------------------------------------------------
SUM:                           266           6350           8843          21935
-------------------------------------------------------------------------------
```
