### ISSUE TITLE
Clojure docstrings are not counted as comments

### ISSUE THREAD

**Issue by BrunoBonacci** [AlDanial/cloc#466]
Hi,

`cloc` seems not accounting for Clojure's docstrings.
I know that docstrings are technically not comments, however they serve
the same purpose as comments in many other languages.

In Clojure (and all LISP dialects) there is the belief that the code
is just data and the data is code. This property is called [Homoiconicity](https://en.wikipedia.org/wiki/Homoiconicity).

That is the reason why languages like Java only have comments, which
are ignored by the parser, to describe their functions/methods; while
Clojure use Strings to documents API.

Additionally there are different ways to `comment` functions.
If we consider the following example:

```
cat > /tmp/comments.clj <<\EOF
(ns user)

;; Just a utility function
(defn hello
  "This function greets a person or the entier world.
   If the person name is provided then it prints a message like:

   Hello John!

   If no name is provided then it prints the following message:

   Hello World!

   "
   ([]
     (hello "World"))
   ([name]
     (printf "Hello %s!\n" name)
    (flush)))


(comment
  (println "This is not executed!"))


#_(println "Also this is not executed!")
EOF
```

When I run `cloc` on this file i get the following:

```
$ cloc /tmp/comments.clj
       1 text file.
       1 unique file.
       0 files ignored.

github.com/AlDanial/cloc v 1.84  T=0.02 s (64.7 files/s, 1682.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Clojure                          1              9              1             16
-------------------------------------------------------------------------------
```

The 1 line comment is the line starting with semicolon `;`, however I
think the docstrings should be considered in the comments section.
Possibly also the lines which are wrapped into a `(comment ...)` block
and lines which have a commented form via `#_`.

Again, I know that docstrings, technically, are not comments, however
I guess that one might want to use `cloc` to quickly evaluate what
ratio of comments/code you have in a codebase.  In that case I think
that `cloc` would mis-report most of Clojure/ClojureScript code.

What's your thoughts on this?

Bruno

**Comment by AlDanial** [comment]
That's reasonable--but what are the parsing rules to identify a docstring in Clojure?

**Comment by BrunoBonacci** [comment]
To parse docstrings it is as follow:

1. an open parenthesis
2. followed by something stating with `def` such as: `def, defn, defn-, defmulti, defmethod, defprotocol ....` generally it is a symbol (token) starting with `def`
3. followed by one or more whitespaces
4. followed by a symbol name
5. followed by an OPTIONAL string within double quotes and it could be multiline

`(def.* symbol <docstring>? .*)`

For the `comment` block
1. an open parenthesis
2. followed by `comment`
3. followed by any other form up to the **matching** parenthesis

Is this enough?

**Comment by BrunoBonacci** [comment]
here a more formal grammar
https://github.com/antlr/grammars-v4/blob/master/clojure/Clojure.g4

**Comment by AlDanial** [comment]
As mentioned on the main page, cloc doesn't formally parse languages, instead, for the most part it merely applies regex's to identify comments.  There are many ways for this to go wrong, primarily with comment markers embedded in strings.  cloc is an imperfect tool in this regard.

Nonetheless I'll take a shot at crafting regex's that implement the above, excluding nested comments which need a true parser.

Alternatively, I'm happy to review a PR that implements the solution.

**Comment by AlDanial** [comment]
Parsing the nested parentheses is proving too much for me to handle the docstrings and ``(comment .. )`` properly.  I'll close this issue but as I mentioned, if you or anyone else can implement a solution in Perl I will include it.
