### ISSUE TITLE
Include .properties file in lines of code count 

### ISSUE THREAD

**Issue by dharm6619** [AlDanial/cloc#467]
Include **.properties** file for counting lines of code and display it as a separate fields as like other languages

**Comment by AlDanial** [comment]
https://github.com/AlDanial/cloc#requesting-support-for-additional-languages-

**Comment by AlDanial** [comment]
I'll close in two weeks unless I get more info.

**Comment by dharm6619** [comment]
Currently I'm getting output like - 

--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                         1066          58784          93880         240932
C/C++ Header                      8            322            374           1616
reStructuredText                 14            368            228            598
Bourne Shell                      4             15             11             80
XML                               2              0              2             28
JSON                             12              0              0             12
Bourne Again Shell                1              0              0              2
--------------------------------------------------------------------------------
SUM:                           1107          59489          94495         243268
--------------------------------------------------------------------------------
but I want - 
github.com/AlDanial/cloc v 1.84  T=12.02 s (92.1 files/s, 33043.6 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                         1066          58784          93880         240932
C/C++ Header                      8            322            374           1616
reStructuredText                 14            368            228            598
Bourne Shell                      4             15             11             80
XML                               2              0              2             28
JSON                             12              0              0             12
Properties                      -                   -           -                  - 
Bourne Again Shell                1              0              0              2
--------------------------------------------------------------------------------
SUM:                           1107          59489          94495         243268
--------------------------------------------------------------------------------
suggest me for this solution

**Comment by AlDanial** [comment]
If you're unable to supply the requested information, another option is to add your own custom language definition as explained at https://github.com/AlDanial/cloc#create-custom-language-definitions-
