### ISSUE TITLE
include bazel files

### ISSUE THREAD

**Issue by gabroo** [AlDanial/cloc#469]
examples: https://github.com/bazelbuild/bazel/tree/master/examples

comments are started with #

files to include: BUILD, WORKSPACE, .bzl, 
I've also seen: .BUILD, .bazel,

**Comment by AlDanial** [comment]
Dang, just realized .bzl also resolves to Starlark.

More work for me...

**Comment by AlDanial** [comment]
Reading https://docs.bazel.build/versions/master/skylark/language.html makes me think .bzl should be Starlark.  If you disagree, how can a Starlark .bzl be distinguished from a Bazel .bzl?

Also the last push had a goof that ignores *.BUILD and *.bazel files, will roll that fix in when this is straightened out.

**Comment by AlDanial** [comment]
I take it the Bazel support works as intended now.  The .BUILD and .bazel fixes were added with subsequent commits.
