### ISSUE TITLE
.tsv data files resolve to RobotFramework

### ISSUE THREAD

**Issue by jwueller** [AlDanial/cloc#473]
To my knowledge, TSV is usually understood as "tab-separated values", a tabular data structure. I find it highly questionable to assign an entire data format to a single tool/framework. Counterexample: XML isn't classified as Selenium Test Suites either.

I request dropping the classification of the TSV file extension as RobotFramework entirely. It seems to have a dedicated file extension thats better suited anyway.

**Comment by AlDanial** [comment]
Fair point.

**Comment by jwueller** [comment]
That was fast, thank you!
