### ISSUE TITLE
Svelte Support

### ISSUE THREAD

**Issue by rhucle** [AlDanial/cloc#474]
Is it possible to add support for [Svelte](https://svelte.dev)?

Svelte, like Vue.js, includes different languages (HTML, CSS, JavaScript) in a single file.

**Comment by AlDanial** [comment]
Supply the info described at
https://github.com/AlDanial/cloc#requesting-support-for-additional-languages-
and see https://github.com/AlDanial/cloc#limitations- item #3

**Comment by rhucle** [comment]
1. `.svelte`
2. `<!-- comment -->`
3. https://svelte.dev/examples

Limitation #3 noted.
