### ISSUE TITLE
The file path contains Japanese

### ISSUE THREAD

**Issue by Sori31** [AlDanial/cloc#475]
When I run cmd:  Cloc --list file C:\Test.txt => report error: Unable to read file
File Test.txt  contains content
     C:\LOC\新しいフォルダー\FileTest.sql
You can hepl me, thanks you.
But if run cmd : Cloc  C:\LOC\新しいフォルダー\FileTest.sql  => Showing successful results

**Comment by AlDanial** [comment]
The list file switch has a hyphen, "``--list-file``", possibly you're just missing that.  Try
<pre>
cloc --list-file C:\Test.txt 
</pre>

**Comment by Sori31** [comment]
I used cloc-1.84
I created the Test.txt file with the following content
     C:\LOC\新しいフォルダー\FileTest.sql
When I run : cloc --list-file C:\Test.txt   => Unable to read file
But if run cmd : Cloc C:\LOC\新しいフォルダー\FileTest.sql => Showing successful results

You can hepl me, thanks you

**Comment by AlDanial** [comment]
If you post both versions of ``Test.txt``--one created by your ``WriteAllLines()`` and one created by Notepad--then I'll try to figure out why the first one fails but the second one works.

**Comment by Sori31** [comment]
I have now fixed the error as: 
    File.WriteAllLines(path, createText, Encoding.GetEncoding("shift-jis"))
Thanks you
