### ISSUE TITLE
exclude-lang option doesn't work properly in version 1.76 and above.

### ISSUE THREAD

**Issue by balamurugan-gnanasam** [AlDanial/cloc#476]
The exclude-lang option worked fine in version 1.70. But it doesn't work properly in version 1.76 and above when used with --diff option. It still shows the excluded language in the output. Below is the output.

```
cloc --exclude-lang='C' --diff linux-yocto-4.19/drivers/usb/common/ linux-yocto-new/drivers/usb/common/
       5 text files.
       4 text files.
       6 files ignored.

github.com/AlDanial/cloc v 1.84  T=0.01 s (179.2 files/s, 29570.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1             65             45            211
make
 same                            0              0              3              4
 modified                        1              0              0              0
 added                           0              0              0              0
 removed                         0              0              1              1
-------------------------------------------------------------------------------
SUM:
 same                            0              0              3              4
 modified                        1              0              0              0
 added                           0              0              0              0
 removed                         1             65             46            212
-------------------------------------------------------------------------------
```

**Comment by AlDanial** [comment]
Thanks for bringing this to my attention.  It will have a fix soon.

**Comment by AlDanial** [comment]
with the fix:
<pre>
> cloc --exclude-lang C --diff linux-yocto-4.19.111/drivers/usb/common/ linux-yocto-4.19.112/drivers/usb/common/
       5 text files.
       5 text files.
       8 files ignored.                             

github.com/AlDanial/cloc v 1.85  T=0.01 s (103.7 files/s, 1140.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
make
 same                            1              2              4              5
 > cloc --exclude-lang C --diff linux-yocto-4.19.111/drivers/usb/common/ linux-yocto-4.19.112/drivers/usb/common/
       5 text files.
       5 text files.
       8 files ignored.                             

github.com/AlDanial/cloc v 1.85  T=0.01 s (103.7 files/s, 1140.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
make
 same                            1              2              4              5
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            1              2              4              5
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         0              0              0              0
-------------------------------------------------------------------------------
<pre>
