### ISSUE TITLE
'"perl"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by baruchiro** [AlDanial/cloc#478]
I run `npm cloc` and I getting the next error:

> '"perl"' is not recognized as an internal or external command, operable program or batch file.

Looking at this package it seems clear that `perl` must be installed on the computer to run the executable file. But I don't think it's written in the README run requirements.

**Comment by AlDanial** [comment]
It wasn't clear if you were referring to the cloc README or the README for the npm package of cloc.  I added the Perl requirement information in cloc's README.  I don't manage the other one.
