### ISSUE TITLE
Thanks for writing cloc

### ISSUE THREAD

**Issue by jorinvo** [AlDanial/cloc#48]
I just stop by to say thank you for this nice utility!
You can see my favorite use-case here: https://jorin.me/git-cloc/

Keep up the good work!

(Feel free to close the issue. Just couldn't see another way to contact you.)

**Comment by zbeekman** [comment]
:+1:

**Comment by AlDanial** [comment]
<pre>
git ls-files | xargs cloc
</pre>
is a nice trick.  Last summer I was asked by someone to implement a <code>.gitignore</code> reader to automatically skip files not part of a git repo.  This sounded like a great idea and I agreed to implement it--only to discover it is not trivial!

I will refer the user to your work-around until I implement a <code>.gitignore</code> reader (if ever).

Thanks for your post.
