### ISSUE TITLE
Complex regular subexpression recursion limit (32766) on comment parsing

### ISSUE THREAD

**Issue by bjmoose61** [AlDanial/cloc#483]
Hi,
I used -v 3 to narrow down the problem and I'm getting this output on java files with the following "interesting" input:

rm_comments file=src/main/java/my/path/here/MyClassNameOne.java sub=call_regexp_common^M
-> call_regexp_common for C++^M
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.84/libexec/bin/cloc line 9879.^M
<- call_regexp_common^M

which contains the following code snippet:
```
@Controller
@RequestMapping(value="payroll/**")
public class MyClassNameOne extends BaseController {
...etc...
}
```

rm_comments file=src/main/java/my/path/here/MyClassNameTwo.java sub=call_regexp_common^M
-> call_regexp_common for C++^M
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.84/libexec/bin/cloc line 9879.^M

Which contains the following code snippet:
```@Provider
@Produces({"application/*+xml", "text/*+xml"})
@Consumes({"application/*+xml", "text/*+xml"})
public class MyClassNameTwo extends JAXBElementProvider {
...etc...
}
```

rm_comments file=src/main/java/my/path/here/MyClassThree.java sub=call_regexp_common^M
-> call_regexp_common for C++^M
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.84/libexec/bin/cloc line 9879.^M
<- call_regexp_common^M

Code Snippet:
```
@Provider
@Produces({"application/*+xml", "text/*+xml"})
@Consumes({"application/*+xml", "text/*+xml"})
public class MyClassThree extends JAXBXmlTypeProvider {
```

rm_comments file=servlets/src/main/java/my/path/here/MyClassFour.java sub=call_regexp_common^M
-> call_regexp_common for C++^M
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.84/libexec/bin/cloc line 9879.^M
<- call_regexp_common^M

Which contains the following code snippet:
```
@Controller
@RequestMapping("/manage_geocodes/**")
public class MyClassFour extends MyBaseClass {
...etc...
}
```

**Comment by AlDanial** [comment]
Try rerunning with the ``--strip-str-comments`` switch, ref https://github.com/AlDanial/cloc#complex-regular-subexpression-recursion-limit-

The problem is caused by the ``/*`` characters within the strings; these trick cloc into thinking they are start-of-comment markers.

**Comment by bjmoose61** [comment]
Thanks for the quick reply, and sorry for taking so long to get back to this issue.
I guess only one question remains - why is the "call_regexp_common for C++" method getting invoked for a file with a .java file extension and when the "--include-lang=Java" command line parameter is supplied?

**Comment by AlDanial** [comment]
Many languages, including Java, JavaScript, Go--in fact, more than 70 languages defined in cloc--have C++ style comments.  Easier to have all of them reuse the same parser.

**Comment by bjmoose61** [comment]
Of course they do.  That was a stupid thing of me to say.
