### ISSUE TITLE
support file preprocessors

### ISSUE THREAD

**Issue by nkiesel** [AlDanial/cloc#484]
Hi,
we have some custom file formats, including compressed XML which contains source code as CDATA attribute.  I do have a script which can expand such files into their contained sources, but seems I cannot teach cloc to handle these files because the "archive extraction" only works for the whole content and not for individual files.  Are there any plans to support a per-file (or per-language) pre-processing so that this could be automated within cloc instead of scripting around it?

One potentially tricky aspect is that such archives can contain source files in different languages (e.g. Java and Kotlin).  Thus, ideally the output of this would be fed recursively into cloc again and then totaled as usual.

**Comment by AlDanial** [comment]
My first reaction is that this is quite a niche request.  Makes me wonder if there are other possible use cases, or if anyone else has this need? Still, I won't rule it out just yet.  To get a better sense of what's involved I'll need sample files and probably the extractor script to see what it would take to make this work.

I should also mention I plan to issue the next release in a week or two and have the current development version locked from new features.

**Comment by nkiesel** [comment]
Yes, maybe a niche request. I initially got my hopes up when I read "can process zip files", which lead to this.  I currently work around it by

1. create git clone in temp directory using `git clone --shared --branch $branch $repo $dir`
2. find, extract content, remove source file
3. run cloc on resulting tree
4. remove tree

That works well enough for me and I can do whatever crazy transformations I need in step 2.

BTW: I ran into a few "timeout while stripping comment" errors for 350 line PL/SQL or JS files.  I currently "solved" this by setting the minimal runtime for this step from the hardcoded 1 second to 30 seconds.  being able to specify that min via a cmd line parameter would be nice.

**Comment by AlDanial** [comment]
Regarding your last comment, cloc v1.84 has a ``--timeout`` switch that lets you specify this time on the command line.
I'm going to close this issue as I don't see a common use for the requested capability.
