### ISSUE TITLE
exclude-dir not working in some cases

### ISSUE THREAD

**Issue by khoabui1412** [AlDanial/cloc#488]
Hi,
I want to exclude files in some folders, but it has some problems:
- cloc-1.86.exe --by-file --exclude-dir=example code --include-lang=C++,C# D:\v3_test\fffff --report-file=report.txt -> **cannot exclude folder example code**.
- cloc-1.86.exe --by-file --exclude-dir="example code" --include-lang=C++,C# D:\v3_test\fffff --report-file=report.txt -> **can exclude folder example code**.
- cloc-1.86.exe --by-file --exclude-dir=folder1,folder2 --include-lang=C++,C# D:\v3_test\fffff --report-file=report.txt -> **can exclude folder1, folder2**.
- cloc-1.86.exe --by-file --exclude-dir=folder1,folder2,"example code" --include-lang=C++,C# D:\v3_test\fffff --report-file=report.txt -> **cannot exclude folder example code**.

So the question is how to exclude folder1, folder2, example code folder.
Please check and give feedback.

Thank you very much.

**Comment by khoabui1412** [comment]
I figured out we can use --not-match-d="folder1|folder2|example code" instead.
Thanks.

**Comment by AlDanial** [comment]
Thanks for the update.  The exact issue is that ``example code`` has a space in it and is treated by the command line parser as two separate entities.  The command
<pre>
cloc-1.86.exe --by-file --exclude-dir=example code --include-lang=C++,C# D:\v3_test\fffff --report-file=report.txt 
</pre>
tells cloc to exclude the directory ``example``.  The word ``code`` is dangling and not matched to anything.  By wrapping these in quotes you group them together.
