### ISSUE TITLE
Version 1.86: Has Virus

### ISSUE THREAD

**Issue by Sori31** [AlDanial/cloc#490]
When download V 1.86, Synmantec found virus Security risk detected: WS.Reputation.1

**Comment by AlDanial** [comment]
Definitely don't use the exe if you think it has a virus.  Best to use the source version of cloc, or, failing that, create your own executable as explained at ttps://github.com/AlDanial/cloc#building-a-windows-executable-

In any event, VirusTotal's Symantec analysis says the file is fine:
https://www.virustotal.com/gui/file/1b2e189df1834411b34534db446330d1c379b4bc008af3042ee9ade818c6a1c8/detection
