### ISSUE TITLE
cloc ignoring .BAS files unless renamed to .bas

### ISSUE THREAD

**Issue by Bruno02468** [AlDanial/cloc#493]
I've always used cloc with no complaints, so thanks first of all.

At work, some task required me to chew through a MS VB 3.0 project, namely, its source code files. It's an old project project, we're talking 8.3 uppercase file names here, e.g. CODEFILE.BAS, all encoded as ISO-8859-1. And yet, running `cloc .` in a folder with all and only the .BAS files just reported 10 text, unique, and _ignored_ files.

At first, I thought it was the encoding, or maybe the CRLF line breaks? So I ran all the files through `iconv` and `dos2unix`, turning them all into nice UTF-8 files. To my surprise, cloc still happily ignored every single one of them. Then I tried changing their extensions to lower-case, as in CODEFILE.bas, and weirdly enough, cloc would count their lines perfectly.

I don't know if case-sensitive extensions are a thing, especially since the README claims cloc works under Windows (which up until 10 only offered native support to case-insensitive filesystems, such as NTFS). If it's intended, oh well, I can but claim .BAS should be supported solely because you're very likely to find the uppercase variant, take projects created in the all-uppercase 8.3 filenames era such as the one I've been parsing for example.

Can't make a PR right now though, I'd have to become more comfortable with the code base, maybe something like the commit under issue #177 could just do the trick. Thoughts?

**Comment by AlDanial** [comment]
I'll add ``.BAS`` as an extension for Visual Basic.  Until then you can do  
<pre>cloc --force-lang="Visual Basic",BAS   ...</pre>

**Comment by Bruno02468** [comment]
Absolute legend. Huge thanks!
