### ISSUE TITLE
Don't Counter file sql

### ISSUE THREAD

**Issue by Sori31** [AlDanial/cloc#494]
I has two file sql  (Attach ) : change extension từ txt -> sql
   FileTest.sql : success
but file Book.sql : ignored
 I don't know the reason, your help me.

[Book.txt](https://github.com/AlDanial/cloc/files/4797034/Book.txt)
[FileTest.txt](https://github.com/AlDanial/cloc/files/4797037/FileTest.txt)

Format file Book.sql diff UTF-8  but use --read-binary-file then Cloc don't counter line comment, blank

**Comment by Sori31** [comment]
Case 1: The file Book.sql has format UTF 
                Cloc --unicode C:\Book.sql 
Case 2: Save as file Bool.sql with format UTF-8
                Cloc --unicode C:\Book.sql or  Cloc C:\Bool.sql 
Result : Case 1 <> Case 2

**Comment by AlDanial** [comment]
The original file:
<pre>
> file Book.sql 
Book.sql: Little-endian UTF-16 Unicode text, with CRLF line terminators

(base) vex /tmp> cloc --unicode Book.sql
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SQL                              1              0              0             16
-------------------------------------------------------------------------------
</pre>

The original saved as UTF-8:
<pre>
> file Book_utf8.sql
Book_utf8.sql: UTF-8 Unicode (with BOM) text, with CRLF line terminators

> cloc --unicode Book_utf8.sql   
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SQL                              1              0              0             16
-------------------------------------------------------------------------------
</pre>

I don't see an issue.

**Comment by Sori31** [comment]
I send your file error

[P_EDI_Book.txt](https://github.com/AlDanial/cloc/files/4810848/P_EDI_Book.txt)

![CLOC](https://user-images.githubusercontent.com/62527864/85242721-01537080-b46a-11ea-99f3-ff7a63d11914.png)

**Comment by AlDanial** [comment]
The error text doesn't help me.  What I need is a way to reproduce the problem you're having.  Post the two files shown above and I'll try those.

**Comment by Sori31** [comment]
I'm sorry, I send file. 
You can rename extension file from  txt -> sql 
Pleases help me

[P_EDI_Book.txt](https://github.com/AlDanial/cloc/files/4828677/P_EDI_Book.txt)
[P_EDI_BookF8.txt](https://github.com/AlDanial/cloc/files/4828678/P_EDI_BookF8.txt)

**Comment by AlDanial** [comment]
Thanks for the files, I can duplicate the problem now. It will take me some time to figure this out, has to do with the clumsy way cloc handles Unicode.

**Comment by AlDanial** [comment]
While I don't have a solution, I have a better understanding of the problem.  Briefly, the reported count for ``P_EDI_BookF8.sql`` is correct.  The other file, ``P_EDI_Book.sql``, is encoded in such a way that cloc thinks comments such as ``-- トーハンTONET=V上り実装フラグ`` have embedded newlines and therefore spans two lines with the second line counting as code.

**Comment by Sori31** [comment]
I thank you, hope you have the solution to this problem

**Comment by AlDanial** [comment]
With the fix in a1aef42 I get these results:

<pre>
> cloc --unicode --by-file P*sql
       2 text files.
       2 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.87  T=0.01 s (183.1 files/s, 15200.1 lines/s)
-------------------------------------------------------------------------------
File                             blank        comment           code
-------------------------------------------------------------------------------
P_EDI_Book.sql                      24             36             23
P_EDI_BookF8.sql                    24             36             23
-------------------------------------------------------------------------------
SUM:                                48             72             46
-------------------------------------------------------------------------------
</pre>

**Comment by Sori31** [comment]
You can send me the file Cloc.exe V1.87 because I cannot build it
Thanks you

Vào Th 4, 1 thg 7, 2020 vào lúc 11:01 AlDanial <notifications@github.com>
đã viết:

**Comment by AlDanial** [comment]
[cloc-1.87.zip](https://github.com/AlDanial/cloc/files/4871460/cloc-1.87.zip)

rename from ``.zip`` to ``.exe``
