### ISSUE TITLE
At least on Windows there isn't the option --vcs=<VCS> nor --md

### ISSUE THREAD

**Issue by mobilekosmos** [AlDanial/cloc#495]
In the documentation you write that **--vcs** and **--md** should be available, but running **cloc --help** on Windows with cloc-1.64.exe doesn't show them and running each leads to **Unknown option:vcs**

**Comment by AlDanial** [comment]
The documentation reflects the current version, 1.86.  Give that a try https://github.com/AlDanial/cloc/releases/download/1.86/cloc-1.86.exe
