### ISSUE TITLE
how to summary  from 2020year  to now  create file info;

### ISSUE THREAD

**Issue by kemistep** [AlDanial/cloc#496]
the dir have a long long ago file however i want to summary from 2020 to now file ,how can i use ? thank you

**Comment by kemistep** [comment]
just use the file create_time;

**Comment by AlDanial** [comment]
You can use your operating system to identify files from 2020 until now.  Save those to a text file then use cloc's ``--list-files`` to count those files.  Here's what that looks like in Linux, probably Mac OSX too:

Step 1:  how many days ago was the beginning of the year?
<pre>
> date "+%j"
185
</pre>

Step 2:  find files recursively below the current directory which have a creation time less than 185 days and save those files to a text file, ``files_in_2020.txt`` in this example:
<pre>
> find . -type f -ctime -185 > files_in_2020.txt
</pre>
My opinion is modify time, ``-mtime``, is a better choice than ``-ctime`` for this task.

Step 3:  run cloc against those files
<pre>
> cloc --list-file files_in_2020.txt
</pre>

I'm not familiar enough with Windows to know the equivalent commands there.  I'm not going to add an option to cloc to filter on time though.

**Comment by kemistep** [comment]
thank you
