### ISSUE TITLE
Build Exe file cloc

### ISSUE THREAD

**Issue by Sori31** [AlDanial/cloc#499]
I install Strawberry Perl and  PAR::Packer module when build file cloc from GIT, then messge 
I save as file cloc -> cloc.pl  
when Counter file 
![image](https://user-images.githubusercontent.com/62527864/86708693-60f17480-c043-11ea-9588-006cb4435a02.png)

When sending the file after building gmail, a virus is detected : convert extension file exe -> txt 
Perl code for the first time thanks to support
Help me

**Comment by AlDanial** [comment]
You built the exe with this command?
<pre>
C:> pp -M Digest::MD5 -c -x -o cloc.exe cloc.pl
</pre>
