### ISSUE TITLE
Match path

### ISSUE THREAD

**Issue by jmatsushita** [AlDanial/cloc#5]
Hi there,

I'm trying to ```--not-match-d``` a ```dir/subdir``` (which I do with ```--not-match-d="(dir\/subdir)"``` but it doesn't seem to work. Also there are cases where I'd like to match a directory and file name together like ```dir/file.*``` and for which I need to resort to ```--exclude-list-file```.

I wonder whether you could implement a ```--match``` and ```--not-match``` which would match on the complete relative (or absolute) path (directory + basename)?

Thanks for the great tool!

Jun

**Comment by AlDanial** [comment]
With git commit 5f38877 I added a new switch, --fullpath, that changes the behavior of --match-f and --not-match-f so they look at the file's path too, not just the basename.  Therefore, used together,  --fullpath and --{not-}match-f=REGEX can emulate --{not-}match-d=REGEX but in a more generic way; they can span multiple directories and optionally the file too.

Let me know if it works for you.

**Comment by AlDanial** [comment]
no feedback, assuming all is good
