### ISSUE TITLE
Use md2man instead of podtoman for cleaner doc

### ISSUE THREAD

**Issue by pickfire** [AlDanial/cloc#50]

**Comment by AlDanial** [comment]
The man page generated by <code>pod2man cloc.1.pod</code> looks plenty clean to me.  I'll need compelling evidence to consider rewriting cloc.1.pod as markdown.

**Comment by pickfire** [comment]
I can help to rewrite it.

**Comment by jolkdarr** [comment]
Perhaps the job may be performed by means of an external tool like
http://manpages.ubuntu.com/manpages/oneiric/man1/pod2markdown.1p.html

**Comment by pickfire** [comment]
@jolkdarr Nice idea.

**Comment by AlDanial** [comment]
It's not who or how, but *why*?

What's the matter with the existing output from pod2man that needs fixing and what makes md better?

**Comment by pickfire** [comment]
Yeah, I don't see a reason why too, but I think mostly because markdown is clearer and more simple.

> Simplicity is the best sophistication. -- Leonardo da vinci
