### ISSUE TITLE
Cloc-1.87 --diff  : File consider upper- and lower-case letters 

### ISSUE THREAD

**Issue by Sori31** [AlDanial/cloc#501]
1/ Case 1:  I have struct folder : 
 [Send.zip](https://github.com/AlDanial/cloc/files/4917933/Send.zip)
The Struct created : 
     copy file from SourceNew paste to SourceOld
     rename file SourceOld -> Delete line comment  

command line   C:\Cloc --diff C:\SourceOld C:\SourceNew --by-file 
  Unexpected result : 
![image](https://user-images.githubusercontent.com/62527864/87412703-8823e500-c5f3-11ea-90c3-02bc7fd2ce2c.png)

  It must be : Counter added  SourceNew\P_EDI_Book.sql

2/ Case 2 : 
[Send.zip](https://github.com/AlDanial/cloc/files/4918156/Send.zip)

command line   C:\Cloc --diff C:\SourceOld C:\SourceNew --by-file 
  Unexpected result : 
![image](https://user-images.githubusercontent.com/62527864/87415687-a855a300-c5f7-11ea-8453-6dea5c03ee1f.png)
![image](https://user-images.githubusercontent.com/62527864/87415714-b277a180-c5f7-11ea-8890-b082318f940a.png)
![image](https://user-images.githubusercontent.com/62527864/87415734-bc99a000-c5f7-11ea-8160-087aced2c3d6.png)

 It must be : 
![image](https://user-images.githubusercontent.com/62527864/87415838-ece13e80-c5f7-11ea-8401-08412f769a85.png)

You help me, pleases

**Comment by AlDanial** [comment]
For case 1 you have only one file in SourceOld and one file in SourceNew.  This triggers a branch in cloc to directly compare the two files; this situation has no concept of "added" and no "removed", only "modified", in other words "what is different between the left file and the right file".  
One way around this limitation is to add an additional source file to either directory, for example (on Linux),
``echo "int i;" > SourceOld/x.c``
then the result is
<pre>-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SQL
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           1             24             36             23
 removed                         1             22             32             23
C
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           0              0              0              0
 removed                         1              0              0              1
-------------------------------------------------------------------------------
SUM:
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           1             24             36             23
 removed                         2             22             32             24
-------------------------------------------------------------------------------
</pre>

**Comment by Sori31** [comment]
Cloc is currently distinguishing between filenames with upper and lower case extensions: 
 Ex: filename  Upper.SQL <>  filename Upper.sql
Case True : File Upper.SQL with filename Upper.sql is the same when diff

**Comment by AlDanial** [comment]
On Windows? Linux?  Also try the ``--ignore-case-ext`` switch.

**Comment by Sori31** [comment]
[Send.zip](https://github.com/AlDanial/cloc/files/4957648/Send.zip)

I using command 
   D:\cloc.exe  --diff C:\SourceOld C:\SourceNew --unicode --ignore-case --by-file
 Result TRUE
But when  I add one file in folder SourceNew,  then command line 
    D:\cloc.exe  --diff C:\SourceOld C:\SourceNew --unicode --ignore-case --by-file
Result counter diff three file , but I expected result is only 2 files  
![image](https://user-images.githubusercontent.com/62527864/88131359-004b6580-cc07-11ea-9983-1a3085881e5c.png)
![image](https://user-images.githubusercontent.com/62527864/88131384-0ccfbe00-cc07-11ea-9bf8-b7048103355e.png)
![image](https://user-images.githubusercontent.com/62527864/88131408-18bb8000-cc07-11ea-8a0b-afc60bda3023.png)

**Comment by AlDanial** [comment]
Note there is a difference between ``--ignore-case`` (what you did) and ``--ignore-case-ext`` (what I suggested).

**Comment by Sori31** [comment]
cloc.exe --diff C:\SourceOld C:\SourceNew --unicode --ignore-case-ext --by-file
The result is similar to the image above

**Comment by AlDanial** [comment]
I understand the problem now.  I'll work on a solution.

**Comment by AlDanial** [comment]
Give 42886d5 a try.  There is no need for extra switches, just do
<pre>
perl cloc --diff C:\SourceOld C:\SourceNew --unicode --ignore-case-ext --by-file
</pre>
My result on Windows is
<pre>
github.com/AlDanial/cloc v 1.87  T=0.07 s (30.4 files/s, 197.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SQL
 same                            0              0              2              6
 modified                        1              0              0              0
 added                           0              0              2              0
 removed                         0              0              0              2
Visual Basic
 same                            0              0              0              0
 modified                        0              0              0              0
 added                           1              0              0              1
 removed                         0              0              0              0
-------------------------------------------------------------------------------
SUM:
 same                            0              0              2              6
 modified                        1              0              0              0
 added                           1              0              2              1
 removed                         0              0              0              2
-------------------------------------------------------------------------------
</pre>
