### ISSUE TITLE
please add support for jinja templates

### ISSUE THREAD

**Issue by aelkikhia** [AlDanial/cloc#506]
Could you please add jinja to your list of supported languages the file suffix is normally ".html.jinja2", ".jinja2", or ".jinja"
comments are normally {# ... #}
https://jinja.palletsprojects.com/en/2.11.x/

P.S.
Love the app, definitely nice to have metrics when showing peers how much smaller and cleaner a code base can be.

**Comment by AlDanial** [comment]
heh, I use Jinja (and Flask) myself
