### ISSUE TITLE
--diff commit~1 format is not supported. 

### ISSUE THREAD

**Issue by mms0536** [AlDanial/cloc#507]
First, thank you very much for the implementation -- diff provides the details of adding, deleting, and modifying two commitid return files. 
However, in actual use, I found that the input parameter commit~1 is not supported. 
Command example: 
```
cloc -q --diff  --diff-timeout=300 --by-file --csv  --strip-str-comments e472299f02a3bb41f7fa0296e4d57b5dbe7f0d2b~1 e472299f02a3bb41f7fa0296e4d57b5dbe7f0d2b
```
ErrorMsg:Error: incorrect length fh array when preparing diff at step 6.
Thanks~

**Comment by AlDanial** [comment]
Give 2656fa5 a try.

**Comment by mms0536** [comment]
> Give [2656fa5](https://github.com/AlDanial/cloc/commit/2656fa581245b8facf574c962e11ee09b613aa09) a try.

Thank you very much. He's working properly.
