### ISSUE TITLE
Error "Undefined subroutine &main::Raku_or_Prolog"

### ISSUE THREAD

**Issue by phmccarty** [AlDanial/cloc#510]
I am running cloc version 1.86 and am seeing an error analyzing a tarball containing a file with a `.P6` file extension. The tarball is https://github.com/xianyi/OpenBLAS/archive/v0.3.10.tar.gz, but it can be reproduced with a single file as well:

```
$ echo test > test.P6
$ cloc test.P6
       1 text file.
Undefined subroutine &main::Raku_or_Prolog called at /bin/cloc line 5547.
```

**Comment by AlDanial** [comment]
Wow, thought I had a unit test for Raku which would have caught this a long time ago.  Thanks for reporting.
