### ISSUE TITLE
MATLAB block comments incorrectly counted as code

### ISSUE THREAD

**Issue by stephen-young** [AlDanial/cloc#511]
Using cloc on the following MATLAB source code file `helloworld.m`

```MATLAB
function helloworld()
    %This line is a comment

    disp('Hello world!')

    %{
        This is some text in a block comment
        This is some text in a block comment
        This is some text in a block comment
        This is some text in a block comment
    %}

end
```

The result should be 3 lines of code, 7 lines of comments and 3 blank lines but when I run `cloc` on the file I get 7 lines of code, 3 lines of comments and 3 blank lines. This suggests that `cloc` is treating the lines inside the block comment as code.

**Comment by AlDanial** [comment]
thanks for pointing out this oversight
