### ISSUE TITLE
--diff-list-file with empty source code files makes cloc fail

### ISSUE THREAD

**Issue by hkobr** [AlDanial/cloc#513]
Hi,

I recently discovered the new --diff-list-file option. Thanks, I was waiting for this functionality for a long time.

However, when using the --diff-list-file option with cloc-1.86.pl, the program exits on error after printing some warnings :
```
Use of uninitialized value in string eq at cloc-1.86.pl line 2283.
Use of uninitialized value in hash element at cloc-1.86.pl line 2287.
Use of uninitialized value in sprintf at cloc-1.86.pl line 2291.
Use of uninitialized value in hash element at cloc-1.86.pl line 2292.
Use of uninitialized value in string eq at cloc-1.86.pl line 6140.
Use of uninitialized value in hash element at cloc-1.86.pl line 6144.
Use of uninitialized value in hash element at cloc-1.86.pl line 6165.
Can't use an unedfined value as an ARRAY reference at cloc-1.86.pl line 6165.
```
I figured out the alignment file I passed to --diff-list-file option contains empty files in "Files added" section. When removing them or adding some text in those files, no more error is present.

**Comment by AlDanial** [comment]
thanks for reporting this
