### ISSUE TITLE
Julia docstrings are not treated as comments

### ISSUE THREAD

**Issue by tisztamo** [AlDanial/cloc#520]
In Julia, _"any string appearing at the toplevel right before an object (function, macro, type or instance) will be interpreted as documenting it"_ ([link](https://docs.julialang.org/en/v1/manual/documentation/))

It seems that cloc treats them as code, at least by default:

```
$ uname -a
Linux ws 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat cloc.jl 
"""
    id(x)

The identity function
"""
id(x) = x

$ perl cloc-1.88.pl cloc.jl 
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.88  T=0.00 s (289.9 files/s, 2029.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                            1              2              0              5
-------------------------------------------------------------------------------

```
Just tried out cloc and read in the docs that support for Python docsstrings is existing but limited. It would be nice to have the same for Julia, as typically a huge part of the source code of Julia projects are docstrings.

**Comment by AlDanial** [comment]
Please give a5290d8 a try.  The implementation matches the behavior for Python and so only half-implement what you seek--cloc will treat any triple-quoted string as a docstring, regardless of location.  I'd need a Julia language parser to figure out where objects are defined.  Other code metrics tools have language parsers but cloc just works with regex's.

The ``--docstring-as-code`` switch will make cloc bypass the new logic.

**Comment by tisztamo** [comment]
It works and this is enough for me, thank you very much!
