### ISSUE TITLE
Zig Support

### ISSUE THREAD

**Issue by nsmryan** [AlDanial/cloc#523]
I was wondering if there is a chance of supporting the language Zig. It is very similar to C, but only has single line comments "//" and no other comment style.

I tried to add Zig myself, and the results seem reasonable. I don't know how to get the language scale factor, and I'm not sure all the places that should change to add a new language.

Thank you

**Comment by AlDanial** [comment]
https://github.com/AlDanial/cloc#requesting-support-for-additional-languages-
can you point to a source of sample code?

**Comment by nsmryan** [comment]
Thank you for pointing out that section of the README.md. I should have checked for something like that first.

The extension is ".zig".
Comments are "//".
For an example, https://github.com/ziglang/zig/blob/master/src-self-hosted/codegen.zig for a large Zig file, and https://github.com/ziglang/zig/tree/master/src-self-hosted for many Zig files.
