### ISSUE TITLE
cloc counts client-side comments in .aspx file as "code"

### ISSUE THREAD

**Issue by SIkebe** [AlDanial/cloc#524]
![image](https://user-images.githubusercontent.com/17608272/94402015-6a9ff980-01a6-11eb-928a-3d37e9062fdd.png)

## Expected results
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
ASP.NET                          1              0              7             8
-------------------------------------------------------------------------------
```

## Environment
* Windows 10 (2004)
* Powershell, Command prompt
* cloc v1.88

**Comment by AlDanial** [comment]
The text in green above is an HTML comment--is that also an .aspx comment?  I'm unfamiliar with the ASP.NET family of languages and/or mark-ups and haven't found a definitive source that explains what's a comment in an .aspx file.  Can you point me to a reference?

**Comment by SIkebe** [comment]
>The text in green above is an HTML comment--is that also an .aspx comment?

In ASP.NET Page syntax, there are two valid "comment"s, server-side comments and client-side comments.
aspx file is basically a special form of HTML that allows additional syntax for server-side controls, so usual HTML syntax (HTML tags, comments, etc...) is also valid there. I'll fix the title so that it describes this issue more clearly.
>One common question people ask is what the difference is between using client-side HTML comments and server-side comments.  The key difference is that with client-side comments it is the browser which is ignoring the content within them.
https://weblogs.asp.net/scottgu/Tip_2F00_Trick_3A00_-Using-Server-Side-Comments-with-ASP.NET-2.0-

"ASP.NET MVC 3: Server-Side Comments with Razor"
https://weblogs.asp.net/scottgu/asp-net-mvc-3-server-side-comments-with-razor

"What is the difference between these comments"
https://stackoverflow.com/questions/4033783/what-is-the-difference-between-these-comments

**Comment by SIkebe** [comment]
The same applies to Razor syntax.
https://docs.microsoft.com/en-us/aspnet/web-pages/overview/getting-started/introducing-razor-syntax-c#code-and-markup-comments

**Comment by SIkebe** [comment]
Hmm, server-side comments are counted as "code", too?

![image](https://user-images.githubusercontent.com/17608272/94513278-46e9bb80-0259-11eb-9033-da4330e08d7f.png)

**Comment by AlDanial** [comment]
Let me know if 4b96c2e produces the counts you expect.  You'll need a Perl interpreter--or Windows Subsystem for Linux--to run the source; I generally don't make .exe's until I release a new version.

**Comment by SIkebe** [comment]
@AlDanial I appreciate for your great work! I confirmed that this issue fixed!
