### ISSUE TITLE
cloc $(git ls-files) doesn't know how to handle "-0700" in a filename

### ISSUE THREAD

**Issue by philCryoport** [AlDanial/cloc#526]
Hi all,

Current env on WSL2:
```
 % cloc --version
1.82

 % git --version
git version 2.25.1

 % uname -a
Linux <sanitized> 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 
% cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

One of our private git repos `cloc $(git ls-files)` throws the following error:
```
% cloc -v=9999 $(git ls-files)
Unknown option: 0700
-> load_from_config_file(/home/<sanitized>/.config/cloc/options.txt)
<- load_from_config_file() (no such file: /home/<sanitized>/.config/cloc/options.txt)
```

I've tried the same `cloc $(git ls-files)` command on multiple other private git repos and they work just fine.

This might be the cause:
```
 % git ls-files | grep 0700
data/FedEx_Duty_Tax_Detail_Payer_Detail_5488112.csv 2020-03-11 13_38_58 -0700 (1).csv
```

Do I need to encode the output from `git ls-files` to somehow let cloc know that the "0700" is part of a filename?

**Comment by AlDanial** [comment]
The hyphen before ``0700`` is the real killer; the command line parser thinks it is a switch.  This works for me using cloc 1.88:
<pre>
git ls-files | cloc --list-file -
</pre>
btw, support for counting CSV files was just added a few weeks ago, won't appear until the next release (it does appear in the development version).
