### ISSUE TITLE
subexpression recursion limit issue

### ISSUE THREAD

**Issue by dongshan1986** [AlDanial/cloc#527]
$ Web cloc .
   16521 text files.
   12930 unique files.                                          
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.88/libexec/bin/cloc line 10408.
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.88/libexec/bin/cloc line 10408.
    4100 files ignored.

**Comment by AlDanial** [comment]
See https://github.com/AlDanial/cloc#complex-regular-subexpression-recursion-limit-

Also, not much for me to do unless you provide the input that causes this.
