### ISSUE TITLE
Summary cutoff option

### ISSUE THREAD

**Issue by osibert** [AlDanial/cloc#528]
Often, a large code base contains a handful of infrequently modified or otherwise insignificant files of various types. These are often not interesting for basic use of cloc, where a developer might primarily care about C source and header files, with the rest having only a supporting role.

Would it be reasonable for cloc to have an option, maybe --summary-cutoff <NN>, that would cause it to stop producing summary output as soon as the number of lines summarized so far exceeds NN% of the total number of lines? It would then report the sum of the rest of the files as type "Other". Could also accept <NN>,<type>, where type is "code", "comment", "blank", "any", "file" (where "file" would mean number of files, rather than number of lines).

**Comment by AlDanial** [comment]
Interesting idea, I'll implement this.

**Comment by AlDanial** [comment]
Give 87c4163 a try.  "blank" and "any" aren't implemented--is there any value for these?
