### ISSUE TITLE
Language request: Jam file support

### ISSUE THREAD

**Issue by danielkasza** [AlDanial/cloc#53]
#### File extensions associated with the language

There are no extensions. There are two special named files: `Jamfile` and `Jamrules`.

#### A description of how comments are defined.

Comments are single line only. They start with `#` and end on the end of the line.

#### Links to sample code.

[Documentation](https://swarm.workshop.perforce.com/view/guest/perforce_software/jam/src/Jam.html)

[Haiku uses Jam and the git repository has lots of examples](https://cgit.haiku-os.org/haiku/tree/)

**Comment by AlDanial** [comment]
git commit f5fee54 adds support for Jam

**Comment by danielkasza** [comment]
This was quick! Thank you!
