### ISSUE TITLE
Ability to ignore licence headers (or leading comments)

### ISSUE THREAD

**Issue by Constellarise** [AlDanial/cloc#530]
A lot of the comment count on my code is inflated by the 8 lines of licence header across my hundreds of files (they make up over a third of my comment lines). It would be nice to have a switch to ignore these (or any leading headers).

**Comment by AlDanial** [comment]
How would the cloc interface look?  Ignore by fixed line count starting from the top?  by regex?

**Comment by Constellarise** [comment]
Licence headers are usually always the same so a ``--skip-leading=N`` option would be the easiest (both implementation I assume and API side).

**Comment by AlDanial** [comment]
Would this apply to all file types?  I'm thinking of non-source files like ``.csv``, ``.xml``, ``.html``, ``.css``, etc.  Would ``--skip-leading`` need to also identify file extensions to apply to, eg ``--skip-leading=N;c,h,java,py`` ?

**Comment by Constellarise** [comment]
Honestly I don't know.

**Comment by AlDanial** [comment]
Give 02aae74 a try.  It works in one of two ways: ``--skip-leading N`` will skip the first _N_ lines of every file.  ``--skip-leading N,c,h,java,py`` skips the first _N_ lines of files with one of the given extensions ( ``.c``, ``.h``, ``.java``, ``.py`` in this example).

**Comment by Constellarise** [comment]
That works really well, cut out my 1300 lines of licence headers from the comment count, thank you very much!!
