### ISSUE TITLE
--git --diff <tag1> <tag2> option error / --diff requires two arguments; got 3

### ISSUE THREAD

**Issue by joaosabinon** [AlDanial/cloc#531]
There is a problem with the --diff option. When you are into the directory and you run the cloc, it will works fine ex:

`cloc -v --git --diff tag-1 tag-2`

but, when you need to run cloc specifying the directory, ex:
`cloc -v repository.zip --git --diff tag-1 tag-2`
or
`cloc -v ~/repository/ --git --diff tag-1 tag-2`

you will got the error below:
`--diff requires two arguments; got 3`

I got resolve a part of the problem with the following code:

Removed the lines 1102 - 1108:
```
-if (!$opt_diff_list_file) {
-	die "--diff requires two arguments; got ", scalar @ARGV, "\n"
-		if $opt_diff and !$opt_sum_reports and scalar @ARGV != 2;
-	die "--diff arguments are identical; nothing done", "\n"
-		if $opt_diff and !$opt_sum_reports and scalar @ARGV == 2
-										   and $ARGV[0] eq $ARGV[1];
-}
```

Change the code in the line 4750:
```
 -       my ($Left, $Right) = @{$ra_arg_list};and about it doesn't work with files like zip)
 +       my $Left = @{$ra_arg_list}[1];
 +       my $Right = @{$ra_arg_list}[2];
```

It resolve the problem about the arguments, but, it doesn't resolve the problem about run cloc in another path (the path that I'm in the terminal and the path that the directory be to be analysed) and run cloc in a file.

**Comment by AlDanial** [comment]
Your command
``cloc -v repository.zip --git --diff tag-1 tag-2`` 
 gives cloc three inputs:  ``repository.zip``, ``tag-1``, ``tag-2`` .  Diff works with two inputs.  You need to drop one of these inputs.  If ``repository.zip`` contains a git repo and your objective is to diff code in that repo between ``tag-1`` and  ``tag-2``, you first need to expand the ``.zip`` file, then cd into the expanded directory, then run cloc there.

**Comment by mmcedora** [comment]
@AlDanial In your solution you write on CD into the directory and run cloc from there. However there is a another issue that blocks this for git repo: #699
