### ISSUE TITLE
file missing on huge code base 

### ISSUE THREAD

**Issue by Jack-An** [AlDanial/cloc#532]
I use cloc to statistic a huge code base on MacOS, and I use --by-file-by-lang argument, I find when I use top dir to statistic, some deep file was missing, but when i use more deep dir to start statistic, the file was appear. Or I delete a lot files, the file was appear too. As the code was secret, I can't to upload it. Can nny one to check the recursive list dirs logic?  I don't understand the perl code...

**Comment by AlDanial** [comment]
Most likely the sometimes-missing file is a copy of another file.  Cloc weeds out dupicates.  Run with ``--ignored=missing.txt`` to get a list of files cloc is explicitly skipping.  Or run with ``--skip-uniqueness`` to keep duplicates.

**Comment by Jack-An** [comment]
That's right. Appreciate it.
