### ISSUE TITLE
Definetion Language 

### ISSUE THREAD

**Issue by Sori31** [AlDanial/cloc#537]
I using  cloc-188 --write-lang-def=my_define.txt 
             cloc-188 --force-lang-def=my_define.txt  sourceCounter.sql
   Result : Missing computer language name, line 1 of my_define.txt

Case I customize file define 
             cloc-188  --read-lang-def=my_define.txt sourceCounter.sql 
     Result : Missing computer language name, line 1 of my_define.txt  

[my_define.txt](https://github.com/AlDanial/cloc/files/5606702/my_define.txt)   
[sourceCounter.zip](https://github.com/AlDanial/cloc/files/5606714/sourceCounter.zip)

**Comment by AlDanial** [comment]
Thanks for reporting this problem.  Should work with d61ffd7.
