### ISSUE TITLE
Nested comments in Elm are not supported

### ISSUE THREAD

**Issue by ceddlyburge** [AlDanial/cloc#539]
In Elm, multiline comments can be nested, as below.

```elm
{- a multiline comment
   {- can be nested -}
-}
```

Currently cloc reuses the Haskell code for Elm (`remove_haskell_comments` I think), but Haskell doesn't allow multiline comments, whereas Elm does.

 - [Elm Comment Syntax](https://elm-lang.org/docs/syntax#comments)
 - [Haskell Comment Syntax](https://wiki.haskell.org/Reference_card#Comments)

**Comment by AlDanial** [comment]
This one was kind of tricky so you'll probably want to test whatever odd cases you can devise.

**Comment by ceddlyburge** [comment]
Hi There, I ran this through with the craziest nested comments I could imagine and it all worked perfectly, thanks :)

**Comment by AlDanial** [comment]
Cool, thanks for testing.
