### ISSUE TITLE
File paths in the output while running with --by-file flag are all lowercase on Windows

### ISSUE THREAD

**Issue by ybalcanci** [AlDanial/cloc#540]
I am trying to get cloc results file by file with file names with original case they are in on Windows. But
`cloc <direction> --by-file`
gives results with file names all lowercase.

I think it is because of the fix of https://github.com/AlDanial/cloc/issues/501 which makes Cloc process paths in lowercase on Windows.

**Comment by AlDanial** [comment]
@ybalcanci : Please test the code pushed with c82cf38 .   I'll leave this issue open for a while because there are many combination of options to try that I haven't checked, notably ``--diff --by-file``.
@Sori31 : if you could test too that would be great.

**Comment by ybalcanci** [comment]
I got the following output:
```
       7 text files.
       7 unique files.
       1 file ignored.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.
Use of uninitialized value within %upper_lower_map in hash element at cloc line 3859.

github.com/AlDanial/cloc v 1.89  T=0.05 s (18.9 files/s, 4477.5 lines/s)
-------------------------------------------------------------------------------
File                             blank        comment           code
-------------------------------------------------------------------------------
                                    31              5            201
-------------------------------------------------------------------------------
```

**Comment by AlDanial** [comment]
Ooof.  A fix will have to wait for this weekend.  Would be helpful if you posted a zip file of the files you're counting (replace the files' contents with junk if that matters) so I can duplicate your setup.

**Comment by Sori31** [comment]
with error on you to delete the row after: file cloc.pl (V.189)
 1601:  my %upper_lower_map = ();  # global variable (needed only on Windows) to
                                                         # track case of original filename
 1619 -> 1623  , 1627 -> 1631
           if ($ON_WINDOWS) {
            my $lc = lc $F;
            $upper_lower_map{$lc} = $F;
            $F = $lc;
             }
3853 -> 3863
my %orig_case = ();
    if ($ON_WINDOWS and $report_type eq "by file") {
        # restore the original upper/lowercase version of the file name
        foreach my $lc_file (sort keys %{$rhh_count}) {
            foreach my $cat (sort keys %{$rhh_count->{$lc_file}}) {
                $orig_case{ $upper_lower_map{$lc_file} }{$cat} =
                           $rhh_count->{$lc_file}{$cat};
            }
        }
        $rhh_count = \%orig_case;
    }

**Comment by Sori31** [comment]
@AlDanial : 
current function $upper_lower_map : convert path file to upper char .  In some cases, the Japanese file name will not be read
   Ex: C:\Abc\FileNam.VB  -> c:\abc\filename.vb
     read file   clsミエライス_販売管理_bas.vb  :   cloc skipped
Where when I compare files I want to lower the extension file
  Ex :  C:\Abc\FileName.**VB**  ->  C:\Abc\FileName**.vb**

**Comment by AlDanial** [comment]
I tested the latest push on Windows and it looks good now (US style filenames).

**Comment by ybalcanci** [comment]
Hi, it looks fine now, thanks. But some special characters like "ü" cannot be displayed correctly.

**Comment by Sori31** [comment]
CLoc can't read file format shift jis (ex: clsミエライス_販売管理_bas.vb 
http://www.fl.reitaku-u.ac.jp/~schiba/perl/perlEncoding.html

**Comment by AlDanial** [comment]
Closing this issue because the original problem has been resolved.  The issues with character encoding look to be something fundamental with Perl itself; I'm not sure there's much I can to to cloc to overcome these.
