### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [AlDanial/cloc#541]
The markup version of the readme that is displayed for the main page in this repo contains the following bad links:

"Bulgarian"
Status code [404:NotFound] - Link: http://www.ajoft.com/wpaper/aj-cloc.html
"Arabic"
Status code [404:NotFound] - Link: http://healthcareadministrationdegree.co/socialwork/aldanial-cloc/
"perl2exe"
Status code [404:NotFound] - Link: http://www.indigostar.com/perl2exe.htm
"Polish"
Status code [404:NotFound] - Link: http://www.trevister.com/blog/cloc.html

**Extra**

Theses bad links were found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or log an “Issue”.

**Comment by AlDanial** [comment]
Good tool!  I starred.
