### ISSUE TITLE
Counting file as comments

### ISSUE THREAD

**Issue by forgotPassword** [AlDanial/cloc#542]
Hi,

I have a `setup.txt` file, I would like to count the whole file as comments/blank (without modifying the file). Is it possible with cloc?

Thanks!

**Comment by AlDanial** [comment]
Not quite sure what you're after because by default cloc ignores ``.txt`` files.

You can force it to count ``.txt`` files if you use a custom language definition file (https://github.com/AlDanial/cloc#create-custom-language-definitions-), is that what you had in mind?

**Comment by forgotPassword** [comment]
Yes. But is there some language definition that will count all lines as comments? I tried Markdown/reStructuredText but it counts the lines as `code` ant not `comment`.

**Comment by AlDanial** [comment]
The language definition part is simple:  make a file with these lines:
<pre>Text File
    filter remove_matches .*
    extension txt
    3rd_gen_scale 1.00
</pre>
(replace ``Text File`` with whatever title you want to call these) then invoke cloc with
``cloc --read-lang-def txt_definition.txt  stuff/to/count``

The bad news is you'll additionally need to comment out the hard-coded entry in cloc that says ``.txt`` files are never code.  Using the file from the current git HEAD, the line to comment is 9721:
<pre> 9718    'tgz'       => 1,  # gzipped tarball
 9719    'tiff'      => 1,
 9720    'tsv'       => 1,  # tab separated values
 9721 #  'txt'       => 1,
 9722    'vf'        => 1,
 9723    'wav'       => 1,
</pre>

**Comment by forgotPassword** [comment]
Thank you.
I used the following:

`cloc --read-lang-def=txt_definition --force-lang="Text File",txt .`

Work great :)

**Comment by AlDanial** [comment]
I realized the need to comment out the ``txt`` entry (which you found a work-around to, great) reveals a logic flaw.  I need to remove from the ``%Not_Code_Extension`` hash any extension that appears in user-defined entries.  I'll push an update in a bit.
