### ISSUE TITLE
How to define a new language as an "Alias" to existing language supported by CLOC?

### ISSUE THREAD

**Issue by hegdemk2004** [AlDanial/cloc#543]
I would like to count the LoC for EGL language. The single line and block comments in EGL code are same as C++. So I would like to Alias .egl files as .cpp and the LoC I get from this aliasing should be fine for me. From the documentation I think I can use --read-lang-def to achieve this aliasing. However I do not see any example of the lang-def file. Please share a sample lang-def file

**Comment by forgotPassword** [comment]
try `--force-lang="C++",egl`

**Comment by AlDanial** [comment]
From https://github.com/AlDanial/cloc#create-custom-language-definitions- :

"The easiest way to create a custom language definition file is to make cloc write its definitions to a file, then modify that file:

``Unix> cloc --write-lang-def=my_definitions.txt``"
