### ISSUE TITLE
Using --git-diff-all with cloc-1.88.exe only produce a single archive of 100 files (remaining files are omitted)

### ISSUE THREAD

**Issue by savignac** [AlDanial/cloc#545]
Using --git-diff-all with cloc-1.88.exe only produce a single archive of 100 files (remaining files are omitted). Only the first 100 files from git are archived and examined.

Looking at cloc source code ($FILES_PER_ARCHIVE =   100 if $ON_WINDOWS), I would expect to produce as many archives of 100 files maximum as needed, but it isn't so.  It doesn't produce a second, a third and more archives if needed to examine.

**Comment by AlDanial** [comment]
Please re-run with ``-v 3`` and post the output (I'm interested in just the sequence of  git commands issued) so I have an idea of the logic flow you're seeing.

**Comment by savignac** [comment]
When I use "-v 3", I see that the problem is that when it tries to concatenate the following archives together, it makes use of tar instead of zip: "tar -A -f C:\temp\sTEgExW1uM.zip C:\temp\sTEgExW1uM.zip_extra"

Shouldn't it concatenate using zip if it found zip and compressed the first one with zip ?

I found a version of tar for windows but it doesn't support "-A" for concatenation.  :-( 
(http://stahlworks.com/dev/index.php?tool=zipunzip)
Do you have a link for to find a version of tar for Windows 10 ?

**Comment by AlDanial** [comment]
That's right, zip should be used instead of tar on Windows.  Looks like I'd planned to add that and never got around to implementing it.  I'll take a crack at it this weekend.

**Comment by savignac** [comment]
Thank you! However since there exists a GNU tar version for Windows that supports the -A for concatenate, you may be willing to be put a switch like --tar or --zip to force the use of either tar or zip regardless of the OS as long as the user knows what he or she is doing. The GNU tar version of Windows that I found may do the job pretty well of archiving and concatenating archives. Food for thoughts.

**Comment by AlDanial** [comment]
I tried to keep things simple by working around the limitations of tar that comes with Windows.  Give the latest a try.

**Comment by savignac** [comment]
I don't have the environment setup to compile it for Windows. I used to take the versions already compiled for Windows from your release folder. But I will give a try with your next upcoming one. I thank you for the fix!

**Comment by AlDanial** [comment]
I added a Windows executable of the latest git development version to #552 in case you want to give the fix a test.

**Comment by savignac** [comment]
It works now with cloc-1.89.exe.

**Comment by AlDanial** [comment]
Thanks for testing.
