### ISSUE TITLE
CLOC is counting LoC for only the first file in the folder

### ISSUE THREAD

**Issue by hegdemk2004** [AlDanial/cloc#548]
Hi Al, not sure it is an issue introduced by one of the latest bug fixes or something. I am running CLOC Version 1.88. The LoC I am getting only for the first file in the folder even though CLOC reports all the files are recognized and counted. All subsequent files report 0 for both Blank and Comment lines. Please check.

**Comment by AlDanial** [comment]
On Windows?  Can you post a small zip file with an example of a file that reports no blank or comment lines?

**Comment by hegdemk2004** [comment]
Hi Al,
thanks for responding. 
Attached is a set of SSIS script files which are actually XML files. They had .dtsx extension originally, I renamed them to .xml. 
Same issue on both Windows and Mac. Only the first file LoC is reported. All subsequent files have been reported as 0 LoC for all 3 categories - Code, Blank and Comment. 
    On Sunday, December 20, 2020, 04:33:43 AM GMT+5:30, AlDanial <notifications@github.com> wrote:  
 Not sure, if this is an issue with XML files only?
Regards,Mahesh 


On Windows? Can you post a small zip file with an example of a file that reports no blank or comment lines?

**Comment by AlDanial** [comment]
The attachments don't appear...

**Comment by hegdemk2004** [comment]
Hi Al,
Forwarding the attachments again. 
Not sure why u r not seeing the attachments. It is a 2.2 MB Zip File named SSIS-Archive.zip.

Both your email Ids look strange. One is cloc@noreply.github.com, another one is AlDanial/cloc <reply@reply.github.com>. Are they correct email IDs allowed to receive any attachment?
Regards,Mahesh

   ----- Forwarded Message ----- From: mahesh hegde <hegdemk2004@yahoo.com>To: AlDanial/cloc <cloc@noreply.github.com>; AlDanial/cloc <reply@reply.github.com>Cc: Author <author@noreply.github.com>Sent: Tuesday, December 29, 2020, 12:05:47 AM GMT+5:30Subject: Re: [AlDanial/cloc] CLOC is counting LoC for only the first file in the folder (#548)
  Hi Al,
thanks for responding. 
Attached is a set of SSIS script files which are actually XML files. They had .dtsx extension originally, I renamed them to .xml. 
Same issue on both Windows and Mac. Only the first file LoC is reported. All subsequent files have been reported as 0 LoC for all 3 categories - Code, Blank and Comment. 
    On Sunday, December 20, 2020, 04:33:43 AM GMT+5:30, AlDanial <notifications@github.com> wrote:  
 Not sure, if this is an issue with XML files only?
Regards,Mahesh 


On Windows? Can you post a small zip file with an example of a file that reports no blank or comment lines?

**Comment by AlDanial** [comment]
The attachment needs to be added to the issue via the github web site, at the bottom of https://github.com/AlDanial/cloc/issues/548, not sent by email.

See https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests for details.
