### ISSUE TITLE
Small and innocuous-looking Go file triggers timeout

### ISSUE THREAD

**Issue by ALTree** [AlDanial/cloc#549]
```
$ perl --version
This is perl 5, version 32

$ perl cloc-1.88.pl --version
1.88
```

Running `cloc` on this file in the Go repository: https://raw.githubusercontent.com/golang/go/master/src/net/http/requestwrite_test.go gives

```
$ perl ~/Downloads/cloc-1.88.pl ~/go/src/net/http/requestwrite_test.go

1 error:
Line count, exceeded timeout:  XXX/go/src/net/http/requestwrite_test.go
```

(raising the timeout to e.g. `--timeout 2` fixes the issue).

The file is not unusual in any way (< 1kloc of Go source code, no long lines) - I'd say it's very typical - so the fact that it triggers a timeout seems to suggest that something is going wrong while counting the lines.

**Comment by AlDanial** [comment]
The cause of the timeouts are the occurrences of ``*/*`` on lines 46, 63, and 73.

cloc, for better or worse (worse, in this case) is regex-based.  It doesn't do lexically correct parsing of the different languages; instead it uses regex rules to try to figure out what is code and what is commented out.  One of the rules for Go is to treat text between ``/*`` and ``*/`` as comments.  When these comment markers are inside strings, as in this file, cloc gets pretty confused.

There's a switch, ``--strip-str-comments``, which uses slower logic to figure such cases out.  With it, cloc counts this file quickly.
A bit more info at https://github.com/AlDanial/cloc#complex-regular-subexpression-recursion-limit- and https://github.com/AlDanial/cloc#limitations- .

**Comment by ALTree** [comment]
Thanks. Closing here since this is working as intended then.
