### ISSUE TITLE
Mentioning the whole URL causes issues in small terminals

### ISSUE THREAD

**Issue by mafagafogigante** [AlDanial/cloc#55]
Although I suppose everyone has monitors for 200+ characters per line today, I am certain that I am not the only one using small windows for quick tasks. These windows usually have the very sensible width of 80 columns, as you seem to know very well by the code.

However, see

```
[mg@localhost cloc]$ ./cloc .
      14 text files.
       9 unique files.                              
      11 files ignored.

https://github.com/AlDanial/cloc v 1.66  T=0.16 s (24.4 files/s, 124011.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
```

I know you want credit, but do you need the whole URL? It will wrap very often.

I would change it to AlDanial/cloc (5 top results in google for this string is you anyway).

If you really need a URL, consider using a shortener.

Thanks, and note that I am just trying to improve everyone's experience when using your software.

**Comment by AlDanial** [comment]
Yes, I agree completely, no sense in wrapping past 79 chars (even exactly 80 is problematic when doing cut/paste of the output to something else) for small runs.  While I usually work in a terminal with >250 columns, it is usually subdivided into small panes with tmux so I hit the wrap-around myself.

git commit 3f096f0 saves 8 characters on the header by removing 'https://' which should suffice for most runs.
