### ISSUE TITLE
CLOC does not count vb.net, visual basic script, visual basic for application and vb6 separately

### ISSUE THREAD

**Issue by mbarzanti** [AlDanial/cloc#551]
CLOC should threat vb.net, vbs, vba and vb6 files separately.
Something like:
            'vba'         => 'Visual Basic for Application'          ,
            'VBA'         => 'Visual Basic for Application'          ,
            'vbp'         => 'Visual Basic'          , # .vbp - autogenerated
            'vbw'         => 'Visual Basic'          , # .vbw - autogenerated
            'cls'         => 'Visual Basic'          ,
            'bas'         => 'Visual Basic'          ,
            'vb'          => 'Visual Basic .NET'          ,
            'VB'          => 'Visual Basic .NET'          ,
            'vbproj'         => 'Visual Basic .NET'      , # .vbproj - autogenerated 
            'vbs'         => 'Visual Basic Script'          ,
            'VBS'         => 'Visual Basic Script'          ,

**Comment by AlDanial** [comment]
I made the change but "Visual Basic for Applications" is simply too long for clean output formatting; I renamed that one to "VB for Applications".  Give it a try.

**Comment by mbarzanti** [comment]
Thank you, Where may I download the Windows exe of modified version please?

**Comment by AlDanial** [comment]
https://github.com/AlDanial/cloc/files/5840210/cloc-1.89.zip (It is a ``.exe`` rather than ``.zip``, you'll need to rename it)
