### ISSUE TITLE
using --git --diff on windows not working - produces unable to read error

### ISSUE THREAD

**Issue by jkwinder** [AlDanial/cloc#552]
This is windows 10 enterprise  - can't seem to get this to work.  Current directory is the root of the repository.

C:\Dev\cloc\Service>C:\tools\cloc-1.88.exe --git --diff 6e9ef7cdd08cfb68a24f6800207717aa949d534f 886115bf4b842fa82780ea5126a3b2c42456d2f0
assertion failed: open my_perl
assertion failed: MZ magic bytes
assertion failed: PE header
assertion failed: IMAGE_NT_OPTIONAL_HDR_MAGIC
'unzip' is not recognized as an internal or external command,
operable program or batch file.
One or more inputs looks like a git hash but either git or tar is unavailable.
'unzip' is not recognized as an internal or external command,
operable program or batch file.
One or more inputs looks like a git hash but either git or tar is unavailable.
       0 text files.
       0 text files.
       0 files ignored.

2 errors:
Unable to read:  6e9ef7cdd08cfb68a24f6800207717aa949d534f
Unable to read:  886115bf4b842fa82780ea5126a3b2c42456d2f0
Nothing to count.

**Comment by AlDanial** [comment]
To fix #545 I rewrote the way ``--git --diff`` works on Windows.  The update uses the Windows 10 ``tar`` command instead of ``unzip`` so it should be friendlier to standard Windows installations.  As that code update isn't in a formal release yet at best I can give you an exe of the current development version.  Please see if it fixes your issue too.  The attached file is a Windows ``.exe``; I renamed it to ``.zip`` since github doesn't allow ``.exe``'s to be uploaded; you'll need to rename it back.
[cloc-1.89.zip](https://github.com/AlDanial/cloc/files/5840210/cloc-1.89.zip)

**Comment by savignac** [comment]
Hello @AlDanial ,

Thank you for making available here a compiled version of cloc-1.89 for Windows.  I will be pleased to give it a try shortly to check whether it fixes #545.

**Comment by jkwinder** [comment]
@AlDanial  - the dev version 1.89 has resolved that problem for me and seems to be working well for me on windows 10.  I will be using it more broadly today to see how it works on some larger repos.  I'm unsure if the issue mentioned with the 100 file limit is going to pop-up in my case.  I haven't noticed that yet but I'm using the --git and --diff options not the --git-diff-all.  I'm not sure how they differ.
Thanks!

**Comment by AlDanial** [comment]
I'm pleased to hear the latest exe works for you.  The difference between ``--git --diff`` and ``--git-diff-all`` is the former only checks differences in files which have changed between the two commits.  The latter does a diff between everything in the repo at the two commits, including files that haven't changed.
Please reopen this if you hit any quirks with the 1.89 exe (will be v 1.90 when released).

**Comment by savignac** [comment]
> Hello @AlDanial ,
> 
> Thank you for making available here a compiled version of cloc-1.89 for Windows. I will be pleased to give it a try shortly to check whether it fixes #545.

It works now with cloc-1.89.exe.
