### ISSUE TITLE
CLOC version 1.88 returns incorrect results

### ISSUE THREAD

**Issue by mr2001** [AlDanial/cloc#553]
Latest version, 1.88 does not seem to work correctly. It does not calculate SAME and MODIFIED any more? Or maybe I am doing something wrong? I tested many times though.
 
Please see below what I am getting if I use ver.1.88 vs, ver. 1.80

With 1.88

"C:\CLOC\cloc-1.88.exe" --diff  "C:\CLOC\CM_OK"  "C:\CLOC\baseline" --diff-timeout 60 --out="C:\CLOC\ATS_DIFF.txt"

github.com/AlDanial/cloc v 1.88  T=165.08 s (109.1 files/s, 46956.0 lines/s)

Language                             files          blank        comment           code
SUM:
 same                                    0              0              0              0
 modified                                0              0              0              0
 added                                8627         283545         315790        2873466
 removed                              9389         312839         358378        3607590

And now I use 1.80 with the same arguments:

"C:\CLOC\cloc-1.80.exe" --diff  "C:\CLOC\CM_OK"  "C:\CLOC\baseline" --diff-timeout 60 --out="C:\CLOC\ATS_DIFF.txt"

github.com/AlDanial/cloc v 1.80  T=581.00 s (0.0 files/s, 0.0 lines/s)

Language                             files          blank        comment           code
SUM:
 same                                 7432         216382         309134        2422416
 modified                             1004              0           2729          43250
 added                                  38           2506           3068          82822
 removed                               776          31776          45542         782581

Regards,
Marc

**Comment by AlDanial** [comment]
The development version of cloc, not yet released, has several improvements for ``--git --diff`` on Windows (see also #552 for a similar problem report).  Earlier this week I uploaded a Windows exe of this dev version to https://github.com/AlDanial/cloc/files/5840210/cloc-1.89.zip please try that (it isn't a zip file, but an exe; you'll need to rename it).

**Comment by mr2001** [comment]
Yes, it works correctly now but I can see some changes in the counts compared to Ver. 1.80
Is version 1.89 count more accurate? Waiting for a documentation update.

Regards,
Marc

**Comment by AlDanial** [comment]
Yes, I believe the current code, as seen in the 1.89 executable, is more accurate.  btw, v1.89 isn't a formal release, just a development snapshot.  I plan to make the next release (v1.90) in February.
