### ISSUE TITLE
Make the exported ignored file better parsable

### ISSUE THREAD

**Issue by Roemer** [AlDanial/cloc#555]
With the `--ignored` option, you get the ignored files and why they are ignored. I am writing a GUI application for cloc and would like to show the ignored files as well and the reason.
Unfortunately, the ignored file is pretty simple: `filepath,reason`. Now the files can include a comma as well, in the filepath and in the reason. Best would be I think to allow set the delimiter with an option like `--ignored-delimiter` (like `--csv-delimiter`) so that one can choose the delimiter themselves (I usually use `|` on Windows).

As a side note, If there is some interest, I could probably open source this tool. It's just an early alpha that allows browsing a given folder inside the tool:
![image](https://user-images.githubusercontent.com/393641/105355762-de9d5c00-5bf2-11eb-83f7-dfea05bc10bc.png)

**Comment by AlDanial** [comment]
I'm reluctant to add a new switch just for the ignored file delimiter.  I'm thinking of using ``--csv-delimiter`` to define the delimiter for ignored (and categorized, counted, and diff-aligned) outputs, in addition to regular cloc outputs.  Works for you?
The GUI looks like a nice project.  If you decide to open source it I'll add a link from the cloc documentation.

**Comment by Roemer** [comment]
I think just using the `--csv-delimiter` is totally fine.
Regarding the UI: I finally found some time to clean it up a bit and expose the needed settings.
You can find the project over here: https://github.com/Roemer/ClocViewer
Right now you can find the executables in the github actions build artefacts (the current one is here: https://github.com/Roemer/ClocViewer/actions/runs/669497961), I am still working on a release pipeline so I can do normal github releases.

**Comment by AlDanial** [comment]
Please re-open if the previous commits to resolve this were insufficient.
