### ISSUE TITLE
lines of code counted as comments in PHP

### ISSUE THREAD

**Issue by mcorne** [AlDanial/cloc#556]
The following snippet has 5 lines of code but cloc finds 3 lines of comments. Strings $a and $d seem to be mistaken for the beginning and the end of a multiple line comment. 
```php
<?php
$a = "/*";
$b = 1;
$c = 2;
$d = "*/";
```

**Comment by AlDanial** [comment]
That's correct, the ``/*`` and ``*/`` within the strings fool cloc.  The work-around is to use the switch ``--strip-str-comments``.
Ref:  https://github.com/AlDanial/cloc#limitations- , https://github.com/AlDanial/cloc#complex-regular-subexpression-recursion-limit-
