### ISSUE TITLE
Maybe tool is ignoring the .lpr file for Free Pascal

### ISSUE THREAD

**Issue by Alexey-T** [AlDanial/cloc#557]
In stat I see it's not counted. 

- .lpr is extent for FreePascal, 
- .dpr for Delphi (also Pascal).

**Comment by AlDanial** [comment]
Looks OK to me:
<pre>
> cloc j.lpr j.dpr
       2 text files.
       2 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.89  T=0.01 s (251.4 files/s, 2011.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Pascal                           2              2              6              8
-------------------------------------------------------------------------------
SUM:                             2              2              6              8
-------------------------------------------------------------------------------
</pre>
Can you post the files that aren't being counted?
