### ISSUE TITLE
Division by zero error on Ubuntu 20.04

### ISSUE THREAD

**Issue by danilaml** [AlDanial/cloc#564]
When running cloc on llvm repository I get
```
$ cloc llvm
   81814 text files.
Unable to read llvm/build/test/tools/llvm-ar/Output/error-opening-permission.test.tmp/permission.b
Illegal division by zero at /usr/bin/cloc line 6334.
```

cloc was installed via apt on Ubuntu 20.04.2 x64
Could be due to some permission errors it complained about previously. IMHO, it should just ignore files it can't open.
Running with `sudo` solved the issue, so it appears that permissions were indeed the underlying cause.

**Comment by stsnel** [comment]
I believe the division occurs on this line in the current version of cloc if a .b file is nonreadable: https://github.com/AlDanial/cloc/blob/8587bd76de3da446cc919d2aa5354e9dfe50fb12/cloc#L7086

The above PR should fix this

**Comment by AlDanial** [comment]
The fix by @stsnel solves the problem.  Rather than wait for update to appear in the apt repositories (months from now?), grab the latest development code directly with ``wget https://github.com/AlDanial/cloc/raw/master/cloc``.
