### ISSUE TITLE
Add support for Godot Text Scene/Resource files

### ISSUE THREAD

**Issue by zacryol** [AlDanial/cloc#566]
These are declarative code formats used with Godot Engine (the main scripting language, GDScript, is already supported).
`*.tscn` for Scenes, `*.tres` for other Resources
> A TSCN file may contain single-line comments starting with a semicolon (`;`). However, comments will be discarded when saving the file using the Godot editor.

> Like TSCN files, a TRES file may contain single-line comments starting with a semicolon (`;`). However, comments will be discarded when saving the resource using the Godot editor.

Both use `;` to start comment lines
Sample links: https://github.com/zacryol/spindle-of-serendipity/blob/develop/godot/game/GamePanel.tscn
https://github.com/godotengine/tps-demo/blob/master/door/model/door.tres
https://docs.godotengine.org/en/stable/development/file_formats/tscn.html (Syntax definition doc)

**Comment by AlDanial** [comment]
To clarify, would ``.tscn`` and ``.tres`` files be identifed as GDScript or as Godot Engine (or something else)?

**Comment by zacryol** [comment]
they are separate from GDScript
the names for them would probably be `Godot Scene` and `Godot Resource` respectively
