### ISSUE TITLE
cloc 1.89 for Linux

### ISSUE THREAD

**Issue by dsyman** [AlDanial/cloc#569]
Hi,
You gently made available cloc.exe 1.89 for Windows, including separated check of VB, VB.NET and VBA.
Currently under Centos 7 Linux is available cloc 1.70 only.
I cannot compile 1.89 from source code.
May you make 1.89 for Linux, please?

Thank you

**Comment by AlDanial** [comment]
Centos comes with Perl which is all you need to run any version of the cloc source code.  Simply download the latest released version of cloc from https://github.com/AlDanial/cloc/releases/download/1.88/cloc-1.88.pl then make the file executable with ``chmod a+x cloc-1.88.pl``.  Now you have an executable that works on Linux.
