### ISSUE TITLE
support for tsx files

### ISSUE THREAD

**Issue by HenrikBechmann** [AlDanial/cloc#57]
Hi,

I can't get a count of my tsx files (Typescript + JSX) with cloc.

Would it be possible to add this feature?

**Comment by AlDanial** [comment]
Yes... but what language do tsx files contain?  Typescript?  JavaScript?

In the meantime, until I implement this, you can always create your own language
definitions via https://github.com/AlDanial/cloc#create-custom-language-definitions-

**Comment by HenrikBechmann** [comment]
@AlDanial tsx contains typescript and jsx (typescript alone is .ts). See https://github.com/Microsoft/TypeScript/wiki/JSX

Thanks for the tip, I'll check it out.

**Comment by AlDanial** [comment]
A limitation of cloc is that it cannot identify different languages within one  file.  Therefore you'll have to associate .tsx with either JSX or Typescript.

**Comment by phiresky** [comment]
@AlDanial  Please associate TSX files with TypeScript. There is basically no difference with regards to comment matching.

**Comment by AlDanial** [comment]
<tt>.tsx</tt> added for TypeScript with git commit 16d4893
