### ISSUE TITLE
Add support for Juniper Junos configuration files

### ISSUE THREAD

**Issue by freundm** [AlDanial/cloc#570]
Junos is the OS running on Juniper products.  Details on the syntax can be found in https://www.juniper.net/documentation/en_US/junos/information-products/pathway-pages/junos-cli/junos-cli.pdf.

There isn't a standard extension associated with the configuration files as most people just use *.txt or *.conf, but to differentiate them from other files we've been using *.junos (also driven by the use of https://github.com/ClockworkNet/vim-junos-syntax). 

Comments can be formatted in the following ways:
- Start the comment with a /* and end it with a */. The comment text can be on a single line or can span multiple lines.
- Start the comment with a # and end it with a new line (carriage return).

Here's a sample configuration file from the Juniper GitHub, https://github.com/Juniper/Intro-to-Using-Ansible-with-Junos-OS/blob/master/library/config.conf.

**Comment by AlDanial** [comment]
I've assigned the language 'Junos' to *.junos files -- or should it be 'Juniper Junos'?

**Comment by freundm** [comment]
Thanks! I'd go with 'Juniper Junos'.
