### ISSUE TITLE
Complex regular subexpression recursion limit (32766) exceeded

### ISSUE THREAD

**Issue by valeriyvan** [AlDanial/cloc#572]
8614 text files.
    8235 unique files.                                          
Complex regular subexpression recursion limit (32766) exceeded at /usr/local/Cellar/cloc/1.88_1/libexec/bin/cloc line 10408.
    3183 files ignored.

version 1.88

**Comment by AlDanial** [comment]
https://github.com/AlDanial/cloc#complex-regular-subexpression-recursion-limit-
