### ISSUE TITLE
sum-reports doesn't work for csv of diffs.

### ISSUE THREAD

**Issue by pplupo** [AlDanial/cloc#573]
After I saw what seems to be an undocumented feature (sum reports of diffs): https://sourceforge.net/p/cloc/feature-requests/16/
I tried it out and I was able to make it work.

However, what I need is the output in csv. I understand that I cant sum CSV reports, so I tried to sum plain reports into a CSV result.
It works with non-diff reports.
`cloc --sum-reports --csv --out=sum.csv test.plain test2.plain` <- test.plain and test2.pain are NOT diffs. I get the result in csv.
`cloc --sum-reports --csv --diff --out=sum.csv test.diff test2.diff` <- test.diff and test2.diff ARE diffs. I do *not* get the result in csv.

**Comment by AlDanial** [comment]
I'm surprised that summing diffs worked for you; I get errors ("Unrecognized language ' same' in...").  Can you post a short example and the exact commands you issued?

**Comment by pplupo** [comment]
I'm using version 1.89 found here: https://github.com/AlDanial/cloc/issues/552
This is the command I issue to create the diff files:
`cloc --config options.txt --diff 5e932d5995f36a977915b9a5b92484127c179e7f 65357b82f1d3bd68a5425d9ad3455b4d41276fcf`

This is how I sum them:
`cloc --sum-reports --out=result churn1.txt  churn2.txt`
This is options.txt:
`--git

--ignore-whitespace
--ignore-case

--force-lang=HTML,html5
--ignore-case-ext
--exclude-ext=svg
--exclude-dir=.settings,target
--exclude-list-file=..\ignore.txt
--fullpath

#--csv
#--csv-delimiter=;
#--out=churnReport.csv

--report-file=churn.txt`

Note that if I uncomment the CSV parameters it won't work either. I wish I could sum CSV files.
So my hope was that I could generate plain diffs and have the sum result in CSV. Unfortunately, I can't do it with diffs but I can do it with simple counts.
