### ISSUE TITLE
How to read files with .bin and .esql extensions using cloc

### ISSUE THREAD

**Issue by pratiksajjanwar** [AlDanial/cloc#574]
Hi, 
I am completely new to cloc and I have setup cloc on my windows operating system using npm package manager :- (npm install -g cloc). I am using cloc to count lines of code of project which is on my local file system. Project includes .bin & .esql files which are getting ignored. Some help here would be really appreciated. 
<img width="672" alt="Cloc_OP" src="https://user-images.githubusercontent.com/26156526/110329006-11d06900-8042-11eb-9286-019d285289f8.PNG">

**Comment by AlDanial** [comment]
From https://github.com/AlDanial/cloc : "cloc counts blank lines, comment lines, and physical lines of source code in many programming languages."

How many lines of source are in a .bin file?  I don't know the answer--I wonder if anyone does?--therefore cloc ignores these files.

.esql is not a recognized extension.  Provide the information at https://github.com/AlDanial/cloc#requesting-support-for-additional-languages- if you want it added.
