### ISSUE TITLE
Dockerfiles excluded from report if they have more characters than 'Dockerfile' in file name.

### ISSUE THREAD

**Issue by huornlmj** [AlDanial/cloc#576]
A directory containing a file called Dockerfile.proj will not be reported by cloc.

**Comment by AlDanial** [comment]
``Dockerfile.proj`` does not follow any accepted naming scheme for Dockerfiles that I'm aware of.  If the ``.proj`` extension is unique to your Dockerfiles you could do
``cloc --force-lang=Dockerfile,proj ...``

Having said that, I see that cloc does fail to recognize the ``.Dockerfile`` extension as well as ``Dockerfile.debug`` and ``Dockerfile.prod`` which are mentioned in the documentation.  I'll add those.  I'm not keen to add ``Dockerfile.<anything>`` though.

**Comment by huornlmj** [comment]
Having worked on a lot of open source projects that use Dockerfiles, you do tend to see a large set of Dockerfile.* instances.  It's not a niche occurrence and becoming more prevalent.  I rely on cloc to help identify Dockerfiles as they contain the most potential for security focus, but I miss a few when I only use cloc.  Which is why I have to manually _find . -name "Dockerfile.*"_ as well.  Here are a few I have found over the last few months of git clones, all true Dockerfiles.

Dockerfile.1.launcher
Dockerfile.1.txt
Dockerfile.arm64
Dockerfile.j2
Dockerfile.m4
Dockerfile.original
Dockerfile.ppc64le
Dockerfile.rhel7
Dockerfile.scratch
Dockerfile.webhook
Dockerfile.webhook.rhel7

**Comment by AlDanial** [comment]
One of your examples above, ``Dockerfile.m4``, perfectly captures my concern--is this a Dockerfile or an m4 file?  The general question is would the  "Dockerfile" prefix or a recognized extension take priority?

**Comment by huornlmj** [comment]
In the repos I've found Dockerfile.m4 files in they are still Dockerfiles.  I expect Dockerfile.* is a Dockerfile and *.m4 isn't (and this only is valid if cloc is reporting using the blanket wildcard.).  IMO if cloc acknowledges Dockerfile.proj and Dockerfile.debug then you're probably better off using the wildcard.  Otherwise you'll need to explicitly cover all possible permutations of Dockerfile.something.

**Comment by AlDanial** [comment]
OK, I'm coming around, but my feeling is still that the extension takes precedence so that's what the latest commit implements.  Give it a shot and let me know what fraction of true Dockerfiles are misidentified.

**Comment by AlDanial** [comment]
(forgot to link the issue to the commit; I'm referring to 8c57fd1)

**Comment by AlDanial** [comment]
I downloaded a few popular repos containing Dockerfiles,
<pre>
https://github.com/tensorflow/tensorflow/archive/refs/heads/master.zip
https://github.com/ansible/ansible/archive/refs/heads/devel.zip
https://github.com/pytorch/pytorch/archive/refs/heads/master.zip
https://github.com/grafana/grafana/archive/refs/heads/master.zip
https://github.com/home-assistant/core/archive/refs/heads/dev.zip
https://github.com/spring-projects/spring-framework/archive/refs/heads/master.zip
</pre>
then checked that cloc identifies these files properly.  Results look pretty good now.
