### ISSUE TITLE
Relative path to options file for exclude-list-file

### ISSUE THREAD

**Issue by Roemer** [AlDanial/cloc#577]
I tend to create an options.txt file with my settings for cloc and alongside I usually have an excludes.txt file in the same folder as the options.txt
Right now, I need to specify the full path to the excludes file in the options file:
```
--exclude-dir=bin,obj
--exclude-ext=resx
--read-lang-def=new_definitions.txt
--exclude-list-file=c:\analysis\project_a\excludes.txt
```
I think it would make sense to allow a relative path for `exclude-list-file` which uses the directory of `--config` (if specified).
So then my config would look like:
```
--exclude-dir=bin,obj
--exclude-ext=resx
--read-lang-def=new_definitions.txt
--exclude-list-file=excludes.txt
```

So I could move both those files freely around and they would still work.

**Comment by AlDanial** [comment]
I'm wondering--wouldn't the same problem happen for the ``read-lang-def`` file also?  Should the same fix be done for that too?

**Comment by Roemer** [comment]
Yes that would probably make sense for all path-related settings.

**Comment by AlDanial** [comment]
Let me know if the update solves the problem the way you expected.
