### ISSUE TITLE
C# Generated Code

### ISSUE THREAD

**Issue by Roemer** [AlDanial/cloc#579]
In C#, there are a few classes that contain generated code.
One of those are designer files which I already handle in PR #578 .

On the other side, for example generated service files are standard .cs files but they to contain the following header:
```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
```
It is extremely useful to separately show this files, maybe as Type "C# Generated". To detect this, it would be enough to check the first 2 lines and compare them to the header above to find out if it is a generated file or not.

In my C# wrapper around CLOC I do it like this:
```csharp
if (filePath.EndsWith(".cs", StringComparison.InvariantCultureIgnoreCase))
{
    using (var reader = new StreamReader(filePath))
    {
        for (int i = 0; i < 2; i++)
        {
            var fileLine = reader.ReadLine();
            if (fileLine != null && fileLine.Contains("<auto-generated>"))
            {
                type = "C# Generated";
                break;
            }
        }
    }
}
```
but I have no clue right now how to integrate this in CLOC.

**Comment by Roemer** [comment]
Here is a sample file:
[csharp-autogen.zip](https://github.com/AlDanial/cloc/files/6185435/csharp-autogen.zip)

**Comment by samzullyls-blip** [comment]
code-generated-file-3343163773123380482]
