### ISSUE TITLE
Files Encoded with UCS-2 LE BOM are not processed

### ISSUE THREAD

**Issue by Roemer** [AlDanial/cloc#580]
To reproduce:

- Create a new file with Notepad++
- Set Encoding to `UCS-2 LE BOM`
- Add some code like:
```
public void HelloWorld()
{
}
```
- Save the file as `test.cs`
- Run cloc in the folder where you saved that file

You will see that this file is neither processed nor in the ignore list.
If you change the encoding of said file to something else, it will work correctly.

**Comment by AlDanial** [comment]
To make sure we're on the same page could you attach a small sample file?

**Comment by Roemer** [comment]
[encodingtest.zip](https://github.com/AlDanial/cloc/files/6185365/encodingtest.zip)
Here is the file. My main problem is not that it does not work, the problem is that it does not even show up in the log or in the ignorelist. So at least show it there or even better, process it :)

**Comment by AlDanial** [comment]
The fix should solve both problems (not counting the file, and if it can't be counted, having it appear in the ignored log).  cloc will need the ``--unicode`` switch to recognize the .cs file.
