### ISSUE TITLE
Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498

### ISSUE THREAD

**Issue by osbornemj** [AlDanial/cloc#581]
When running cloc on a directory, I get
Can't use an undefined value as an ARRAY reference at /usr/bin/cloc line 1498

**Comment by AlDanial** [comment]
I can't help unless you describe a way for me to replicate the problem.

**Comment by osbornemj** [comment]
That makes perfect sense, but I don't know how to do it.  The error occurred when using cloc on a Laravel installation, but it may of course be specific to my installation.

**Comment by AlDanial** [comment]
I'll close this since there's nothing I can act on.  If you're able to reproduce the problem please open a new issue.
