### ISSUE TITLE
Qt .pro files classifies as Prolog files

### ISSUE THREAD

**Issue by iEPCBM** [AlDanial/cloc#585]
**Describe the bug**
Qt .pro files classifies as Prolog files.

**cloc; OS; OS version**
 - cloc version: 1.64
 - If running the cloc source, Perl version: -
 - OS (eg Linux, Windows, macOS, etc): Windows
 - OS version: Windows 10 Home

**To Reproduce**
When I trying count lines of code of Qt Project, Cloc classifies .pro files as Prolog files

**Expected result**
.pro files classifies as Qt project files

**Comment by AlDanial** [comment]
Please try with the latest release of cloc, 1.88 https://github.com/AlDanial/cloc/releases/tag/1.88
