### ISSUE TITLE
Add ReScript Support

### ISSUE THREAD

**Issue by ryyppy** [AlDanial/cloc#588]
- language name: [ReScript](https://rescript-lang.org)
 - file extension(s): .res | .resi
 - method(s) of commenting text: `/* */` and `//`
 - location of sample code: https://github.com/github/linguist/blob/master/samples/ReScript/RedBlackTree.res

This should be very similar to the ReasonML support. Also happy to create a PR if this gets accepted!

**Comment by AlDanial** [comment]
give the latest dev version a try

**Comment by ryyppy** [comment]
Thanks, will try that later today!

**Comment by ryyppy** [comment]
I ran the new cloc on the rescript-lang.org codebase and I found some interesting pattern:

```
./cloc src --ignored=ignored.txt
cat ignored.txt
src/Design.resi:  duplicate of src/Playground.resi
src/SyntaxLookup.resi:  duplicate of src/components/Footer.resi
src/components/ApiIntro.resi:  duplicate of src/components/Button.resi
src/layouts/ApiOverviewLayout.resi:  duplicate of src/layouts/ApiOverviewLayout8_0_0.resi
src/layouts/BeltDocsLayout.resi:  duplicate of src/layouts/JsDocsLayout8_0_0.resi
src/layouts/BeltDocsLayout8_0_0.resi:  duplicate of src/layouts/JsDocsLayout8_0_0.resi
src/layouts/DomDocsLayout.resi:  duplicate of src/layouts/JsDocsLayout8_0_0.resi
src/layouts/DomDocsLayout8_0_0.resi:  duplicate of src/layouts/JsDocsLayout8_0_0.resi
src/layouts/JsDocsLayout.resi:  duplicate of src/layouts/JsDocsLayout8_0_0.resi
src/layouts/LandingPageLayout.resi:  duplicate of src/layouts/ReasonCompilerDocsLayout.resi
src/layouts/MainLayout.resi:  duplicate of src/layouts/ReasonCompilerDocsLayout.resi
```

In ReScript, it's common that `.res` (implementation) and `.resi` (interface) contain the exact same code due to technical reasons, but they are not duplicated content per se.

Is there a way to disable this particular behavior? If not, it's also fine.

**Comment by AlDanial** [comment]
use ``--skip-uniqueness``

**Comment by ryyppy** [comment]
Ah wonderful. Thank you!
