### ISSUE TITLE
Add Zig Support

### ISSUE THREAD

**Issue by jsutton** [AlDanial/cloc#589]
**If you want an unsupported language added, provide:**
 - language name: Zig
 - file extension(s): .zig
 - method(s) of commenting text: //, ///, //!
 - location of sample code: https://github.com/ratfactor/ziglings/blob/main/exercises/001_hello.zig

**For other enhancements:**
Give a concise description of what you want cloc to be able to do.

**Comment by AlDanial** [comment]
Duplicate of #523.  Zig support exists in the development version.
