### ISSUE TITLE
Bazel isn't a language per-say.  Should we print Starlark instead?

### ISSUE THREAD

**Issue by luxe** [AlDanial/cloc#591]
**Describe the bug**
I see both Bazel and Starlark being used:  
```
            'bzl'         => 'Bazel'                 ,
            'bazel'       => 'Bazel'                 ,
            'BUILD'       => 'Bazel'                 ,
            ...
            'bzl'         => 'Starlark'              ,
```
Bazel isn't a language but a build system.  I think only Starlark should be used.
For context, running cloc over our codebase shows:  
```
Bazel: 5.38K
Starlark: 435
```

I'm thinking it should all be only Starlark (i.e. 5.38K + 435).
Thoughts?

**cloc; OS; OS version**
1.82

**Comment by AlDanial** [comment]
I know little about Bazel and Starlark so I can't offer much of an opinion.  The ``BUILD`` mapping to Starlark seems odd though.  ``BUILD`` sounds like a makefile to me, shouldn't at least that be Bazel?  If that, too, really is Starlark it would mean no extensions map to Bazel and it should be removed from cloc?

**Comment by akshayjshah** [comment]
Piping in, despite this issue being closed. Bazel uses Starlark to describe build rules, so `BUILD` files should be considered Starlark. From the perspective of a tool like `cloc`, there's no Bazel language per se.

(Bazel is a big execution engine for Starlark-defined build files, all of which have access to a set of build-specific Starlark libraries. Starlark began life as Bazel's built-in Python-ish build language, and it was later separated out and formally specified, and it's now occasionally used in other contexts too.)
