### ISSUE TITLE
Cloc --unicode Skips binary files

### ISSUE THREAD

**Issue by myadav0327** [AlDanial/cloc#594]
**Describe the bug**
CLoc --unicode <binary name > is not processing binary files, exits marking file as ignored

**cloc; OS; OS version**
 - cloc version:  1.90
 - If running the cloc source, Perl version: perl 5, version 26, subversion 3 (v5.26.3)
 - OS (eg Linux, Windows, macOS, etc): Linux
 - OS version: "CentOS Linux 8"

**To Reproduce**

      cloc --unicode  a.out
       0 text files.
       0 unique files.
       1 file ignored.

> file a.out
> a.out: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, 
 BuildID[sha1]=bc5cf08b72ffb67101529c6dc703dbf2a6c94ecd, for GNU/Linux 3.2.0, not stripped

**Comment by AlDanial** [comment]
This is a feature, not a bug.   
The ``--unicode`` switch attempts to detect text encoded in UTF-8 or UTF-16 files--which your ``a.out`` is not.  Extraction from these encodings happens in the subroutine ``unicode_to_ascii()``.  You could try modifying it if you can think of a way to extract source code from your binary files.
