### ISSUE TITLE
Crash with --force-lang-def when XML is not present in the definition

### ISSUE THREAD

**Issue by ptupitsyn** [AlDanial/cloc#596]
**Describe the bug**

When `--force-lang-def` is used, and the provided definition file does not have an entry for `XML`, the app crashes:
```
Can't use an undefined value as an ARRAY reference at /home/pavel/w/cloc/cloc line 2317, <$fh> line 1401.
```

**cloc; OS; OS version**
 - cloc version: from 1.86 and later
 - Perl version: 5.30.0
 - OS: Ubuntu
 - OS version: 20.04

**To Reproduce**
1. Prepare a file `def.txt` with the following contents:
    ```
    Yarn
        filter remove_matches ^\s*#
        filename yarn.lock
        3rd_gen_scale 2.11
    ```
2. Run `cloc --force-lang-def=def.txt .`

**Expected result**
No crash, no errors

**Additional context**
The problem was introduced by commit https://github.com/AlDanial/cloc/commit/ad343cfd4baefab1f37e87d1447f2b5a97e96fe4.
It assumes that XML definition is present.

**Comment by AlDanial** [comment]
Thanks for reporting this.  Fixed in 35a1348
