### ISSUE TITLE
If the CSV separator uses characters other than commas (,), statistics cannot be collected.

### ISSUE THREAD

**Issue by mms0536** [AlDanial/cloc#597]
**Describe the bug**
A concise description of the problem you found with cloc.

**cloc; OS; OS version**
 - cloc version:35a134836173bbe6496e5a3ac6a4288100c5226a
 - If running the cloc source, Perl version: 5.10.1
 - OS (eg Linux, Windows, macOS, etc):Centos
 - OS version:6.9

**To Reproduce**
Steps one can follow reproduce the behavior you're seeing.

**Expected result**
A concise description of what you expected to happen.
`cloc --csv  --csv-delimiter='#'  /code` The statistics result cannot be obtained.
`cloc --csv  --csv-delimiter=','  /code` The correct result can be obtained.
**Additional context**

**Comment by AlDanial** [comment]
That was a pretty bad blunder, thanks for reporting.

**Comment by AlDanial** [comment]
@ipalo : Is this what you see for the cloc version in Docker?
<pre>
docker run --rm -v $PWD:/tmp aldanial/cloc --version
1.89
</pre>
If so, I mistakenly pushed an old version.  I plan to release 1.96 soon and will pay closer attention to the Docker image.

**Comment by AlDanial** [comment]
@ipalo : let me know if the Docker image for the latest version, 1.96, uploaded a couple of hours ago, works correctly for  you.
