### ISSUE TITLE
PlantUML support

### ISSUE THREAD

**Issue by fcorneli** [AlDanial/cloc#598]
- language name: PlantUML
 - file extension(s): *.puml
 - method(s) of commenting text: ' comments like this
 - location of sample code: https://plantuml.com

**Comment by fcorneli** [comment]
That was fast @AlDanial, thanks!

**Comment by AlDanial** [comment]
I use PlantUML myself and so was stunned by your submittal--I thought I'd added PlantUML years ago.

**Comment by fcorneli** [comment]
I also found it quite weird that -for me- such an important project was not supported yet.

BTW: regarding the extensions, there could be some more out there:
https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml

Supported Formats within this Visual Studio Code plugin (which is like really really good):
```
*.wsd, *.pu, *.puml, *.plantuml, *.iuml
```
