### ISSUE TITLE
 Incorrect detection of .o.cmd files as batch files 

### ISSUE THREAD

**Issue by AlDanial** [AlDanial/cloc#6]
When build a Linux Kernel, .o.cmd files can be created as part of the build process. These are definitely not "DOS batch" files, but are detected as such by CLOC (1.64) 
-----------------
copied from https://sourceforge.net/p/cloc/bugs/138/

**Comment by pombredanne** [comment]
@aldanuial thanks for migrating the ticket

**Comment by AlDanial** [comment]
I was mistaken, this was very easy to fix.  See if the code in git commit b710ae2 works for you.

**Comment by pombredanne** [comment]
Thx++
