### ISSUE TITLE
Count python lines without docstrings

### ISSUE THREAD

**Issue by thuandt** [AlDanial/cloc#60]
Hi,
How I can mark docstrings as comment to counting line of code?

**Comment by AlDanial** [comment]
cloc already counts Python docstrings as comments.

Please post an example if you find this not to be the case.

**Comment by thuandt** [comment]
So it's impossible to count docstrings and comments separate?

```bash
$ pylint command/db.py 2>/dev/null | grep '|code' | sed 's/|//g' | awk '{print $2}'
171

$ cloc command/db.py
       1 text file.
       1 unique file.                              
       0 files ignored.

https://github.com/AlDanial/cloc v 1.66  T=0.01 s (135.9 files/s, 35602.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1             41             44            177
-------------------------------------------------------------------------------
```

**Comment by AlDanial** [comment]
That's correct.  The first line exlaining cloc at https://github.com/AlDanial/cloc says
"cloc counts blank lines, comment lines, and physical lines of source code in many programming languages."

docstrings are unique to Python as best I know.  cloc currently counts them as comments, but could also be configured to count them as code.
