### ISSUE TITLE
Java Properties files

### ISSUE THREAD

**Issue by ThexXTURBOXx** [AlDanial/cloc#600]
Please add the following language:
 - language name: `Java Properties`
 - file extension(s): `.properties`
 - method(s) of commenting text: A `#` or `!` at the start of a line. HOWEVER: These are not counted if there is a `\` at the end of the preceding line (the `\` means, the current value should continue in the next line)
 - location of sample code: This one handles most cases: https://en.wikipedia.org/wiki/.properties#Format

If you need more examples or have some other questions about this language, feel free to reach out to me. Also, [some user](https://sourceforge.net/p/cloc/feature-requests/118/#df0b) proposes this custom configuration as a workaround for now (if that helps):
```
Properties
    filter remove_matches #
    extension properties
    3rd_gen_scale 1.36
```
But as you can see, this doesn't handle the cases where a `#` is predeceded by a `\` at the end of the previous line and also misses the `!` character (which should be handled exactly like the `#` character)

This is meant as a continuation of #467

**Comment by AlDanial** [comment]
A few remarks:  "Properties" strikes me as unnecessarily broad, would "Java Properties" be a more suitable name?  Also, cloc counts physical rather than logical lines of code so no logic is implemented to handle ``\`` at the end of a line.

**Comment by ThexXTURBOXx** [comment]
Sounds good. I renamed the file type to `Java Properties`.

I guess, counting the physical lines is completely sufficient as most of the time, the special case won't apply
