### ISSUE TITLE
Does cloc will find if any file/folder is being added to target directory?

### ISSUE THREAD

**Issue by mageshsankar** [AlDanial/cloc#602]
How to find the if the file/folder is being added into the target directory.?

**Scenario 1:**

Base Directory: 18 Folders

Target Directory: 19 Folders

Does cloc will find the new folder is being added into the target directory? if yes how to get that report? Eg: New Folder Name

**Scenario 2:**

Base Directory: 18 Files

Target Directory: 19 Files

Does cloc will find the new fileis being added into the target directory? if yes how to get that report? Eg: New fileName

**Comment by AlDanial** [comment]
<pre>cloc --by-file --diff base target</pre>
then look for files with only ``added`` counts
