### ISSUE TITLE
Line continuation and split in Fortran

### ISSUE THREAD

**Issue by Jellby** [AlDanial/cloc#604]
I would like to count Fortran "logical" lines, i.e., to count continued lines as a single one, and several statements on a single line as several lines. For example:

This should be 1 line:
```
call foo(a, b, c, d, &
         e, f, g)
```

This should be 1 line (and 1 comment)
```
call foo(a, b, c, d, &
         ! some more stuff
         e, f, g)
```

This should be 3 lines:
```
a = 1 ; b = 2 ; c = 3
```

**Comment by AlDanial** [comment]
As mentioned in the documentation, cloc only counts physical, not logical, lines of code.  To count logical lines, you'll need to find a code counter that understands the languages' grammars.
