### ISSUE TITLE
On 1.90 version, --unicode flag don't work

### ISSUE THREAD

**Issue by ijwmiranda** [AlDanial/cloc#606]
OS: windows 10
Example: cloc-1.90.exe %FOLDER% --unicode --report-file=report.txt
Description: On 1.90 version, --unicode flag don't work, running with this flag, produces the following error:

**Use of uninitialized value $companion in ord at script/cloc-1.90.pl line 12425.**

**Comment by AlDanial** [comment]
Thanks for reporting this, is resolved with 08807b2
