### ISSUE TITLE
Azure Devops / TFS CLOC Task requires specific agent version

### ISSUE THREAD

**Issue by iMortalitySucks** [AlDanial/cloc#609]
When using the "Count Lines of Code" pipeline task found here : https://marketplace.visualstudio.com/items?itemName=Dealogic.cloc-vsts-extension, we have found that the task forces the Agent Version to be 1.95.1.  However, we are already running 2.153.1, and can't seem to get the plug in working, and since that is a system capability, we can't seem to fake it out either.  Any Help would be appreciated!

**Comment by AlDanial** [comment]
I wasn't aware of the VS Code plugin for cloc until now.  I'm unfamiliar with Azure and have no clue what the Agent is.  I suppose you've already made Dealogic aware of the issue?  I'd help if I could but this looks out of my hands.

**Comment by iMortalitySucks** [comment]
I actually figured out that I didn't have node.js installed, because I didn't see that as a requirement. Its fixed now, but thanks for reaching back to me!

Collin

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
