### ISSUE TITLE
Add support for TTCN (.ttcn/.ttcnpp/.tpc) 

### ISSUE THREAD

**Issue by stefanbj** [AlDanial/cloc#61]
Please add support for TTCN (a general testing language)
Patch with a suggestion for implementation: [cloc-1.66.e1.patch.txt](https://github.com/AlDanial/cloc/files/141645/cloc-1.66.e1.patch.txt)

Ref:
https://en.wikipedia.org/wiki/TTCN-3
http://ttcn-3.net

**Comment by AlDanial** [comment]
I implemented your patch (thanks, btw) with git commit 28af97e.  (I did leave out the small modification relating to --md, didn't understand what that was for.)
