### ISSUE TITLE
Use of implicit split to @_ is deprecated 

### ISSUE THREAD

**Issue by hakanmentor** [AlDanial/cloc#62]
Hi!
Downloaded and tested cloc-1.66 today and got this warning:
Use of implicit split to @_ is deprecated at ../scripts/cloc-1.66.pl line 3027.
It's easily fixed by chaning line 3027 to:
from:
          my $n_cols = scalar(split(' ', $data_line));
to:
 my @items = split(' ', $data_line);
 my $n_cols = @items;

**Comment by AlDanial** [comment]
ah, this answers my question in issue #61 about --md.  I'll have time to fix this tomorrow.

**Comment by AlDanial** [comment]
fixed on the master branch with git commit f2b3668
