### ISSUE TITLE
When the .gitignore file is deleted, other files are modified. As a result, statistics cannot be collected.

### ISSUE THREAD

**Issue by OpenHarmonySCM-noreply** [AlDanial/cloc#625]
**Describe the bug**
When the .gitignore file is deleted, other files are modified. As a result, statistics cannot be collected.

**cloc; OS; OS version**
 - cloc version:1.91
 - If running the cloc source, Perl version:v5.26.1
 - OS (eg Linux, Windows, macOS, etc): linux
 - OS version: ubuntu18.04

**To Reproduce**
1. Add and commit the .gitignore file.
2. Delete the .gitignore file, add a new file, and commit the file.
3. cloc --diff --git --csv --by-file HEAD-1 HEAD
**Expected result**
Statistics can be collected in new files.
**Additional context**

**Comment by AlDanial** [comment]
I don't think this has anything to do with cloc.  "HEAD-1" is not a correct commit identifier, you probably meant "HEAD~1" ?

If that was a cut/paste error the next thing to try is getting file listings between HEAD and HEAD~1:
``git ls-tree --full-tree -r --name-only HEAD~1``
``git ls-tree --full-tree -r --name-only HEAD``
Does the output from each command look right?

**Comment by OpenHarmonySCM-noreply** [comment]
> 

HEAD~1 is indeed a paste error, I'm sorry.

-  Reproduce the git submission record.
```
# init git dir
git init issues_625
cd issues_625
mkdir dir
echo '*.log'>dir/.gitignore
git add .;git commit -m 'add .gitignore'
echo '''#!/bin/bash
git ls-tree --full-tree -r --name-only HEAD~1
git ls-tree --full-tree -r --name-only HEAD'''>dir/test.sh
rm -f dir/.gitignore
git add .; git commit -m 'delete  .gitignore and add test.sh'
```
Run the following command in the git directory:`cloc --diff --git --csv --by-file HEAD~1 HEAD`
The execution result is:
```
[root@hostname issues_625]# cloc --diff --git --csv --by-file HEAD~1 HEAD
       1 text file.
       1 text file.
       7 files ignored.                             
Nothing to count.
```
---

`git ls-tree --full-tree -r --name-only HEAD~1
`
The execution result is:
```
[root@hostname  issues_625]# git ls-tree --full-tree -r --name-only HEAD~1
dir/.gitignore
```
`git ls-tree --full-tree -r --name-only HEAD`
The execution result is:
```
[root@hostname issues_625]# git ls-tree --full-tree -r --name-only HEAD
dir/test.sh
```

**Comment by AlDanial** [comment]
OK I see what the problem is, actually has nothing to do with git.  The issue is that one of the directories has nothing but the ``.gitignore`` file which is explicitly ignored by cloc.  However, rather than simply ignoring the file, it gets classified as having the language "(unknown)" and goes down a bad code path.  Fixing it isn't hard; finding the time will be more of a challenge.
