### ISSUE TITLE
Could the 'strip comments' feature recognize the 'triple quotes' variable in python?

### ISSUE THREAD

**Issue by liventang** [AlDanial/cloc#626]
Hello, cloc is really a great tool to me. I even use it to generate 'no comments' files with the '--strip-comments=nc' parameter,  to reduces file size before deployment. Everythin works well till the  'triple quotes' variable exists in the code, e.g.  json_str = """ {'key':'value'}""" . I can of course modify my code to avoid using  'triple quotes' variable, but if you can add this feature to the cloc, it would be great.

**Comment by AlDanial** [comment]
cloc already does what you want--perhaps you're working with a really old version of the tool?  Here's proof:

<pre>
> cat test.py
#/usr/bin/env python
print('abc')
json_str = """ {'key':'value'}""" 
""" Docstring, also counted as comment.  """

> cloc --strip-comments=nc test.py 
       1 text file.
       1 unique file.                              
Wrote test.py.nc
       0 files ignored.

github.com/AlDanial/cloc v 1.91  T=0.01 s (110.2 files/s, 441.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1              0              2              2
-------------------------------------------------------------------------------

> cat test.py.nc 
print('abc')
json_str =  
</pre>

**Comment by OpenHarmonySCM-noreply** [comment]
According to liventang's description, he wants to keep the content in the middle of """after json_str.

**Comment by AlDanial** [comment]
@OpenHarmonySCM-noreply : thanks for the clarification

@liventang : use the ``--docstring-as-code`` switch to keep triple quoted strings from being removed with ``--strip-comments``

**Comment by liventang** [comment]
@AlDanial: Thanks, it works. I should read the help message carefully before bothering you.
@OpenHarmonySCM-noreply : Thanks too.
