### ISSUE TITLE
Document how to cite cloc

### ISSUE THREAD

**Issue by lpsinger** [AlDanial/cloc#627]
I am using cloc in an article that I am writing to submit to a peer-reviewed astrophysics journal. Is there a reference that I can use to cite cloc: a peer reviewed article or a software DOI? If so, it would be great to have it in the README file. Thanks for maintaining this excellent software!

**Comment by AlDanial** [comment]
This is a first--I don't think cloc has ever been formally cited before.  How about

<pre>
@software{adanial_cloc,
  author       = {Albert Danial},
  title        = {cloc},
  version      = {1.90},
  year         = 2021,
  url          = {https://github.com/AlDanial/cloc}
}
</pre>

Please follow up with an update to this issue containing the publication details once your article appears!

**Comment by AlDanial** [comment]
I registered cloc with Zenodo and will have a DOI when I release v1.92, hopefully before the end of 2021.

**Comment by lpsinger** [comment]
I don't think that `@software` is supported as BibTeX entry type. How about `@misc`?

**Comment by wcjcn** [comment]
您的邮件已经收到，谢谢您。祝您生活愉快。

**Comment by AlDanial** [comment]
``@software`` looks legit, ref https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
Examples: 

- https://geopandas.org/en/stable/about/citing.html
- https://www.scikit-yb.org/en/latest/about.html 
- https://awesomeopensource.com/project/oeg-upm/Morph-OME?mode=...

**Comment by AlDanial** [comment]
Sure, if ``@software`` isn't suitable for your journal feel free to replace it with ``@misc``.
