### ISSUE TITLE
Translation files of Qt are detected as "TypeScript"

### ISSUE THREAD

**Issue by misery** [AlDanial/cloc#63]
We have some Qt translation files (*.ts / like *.po(t) of gettext) in our repository and cloc detect this as "TypeScript" because of the file ending.

http://doc.qt.io/qt-5/linguist-ts-file-format.html

Example file:
http://code.qt.io/cgit/qt/qtbase.git/tree/examples/widgets/tools/i18n/translations/i18n_de.ts

`<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de">
<context>
`

**Comment by AlDanial** [comment]
git commit 9afbdd8 on the master branch adds support for Qt Linguist files and distinguishes them from TypeScript
