### ISSUE TITLE
Expect to add support for ixx file for module file in Visual Studio

### ISSUE THREAD

**Issue by YbJerry** [AlDanial/cloc#632]
As I know, the filename extension of the module file is ixx in Visual Studio. But I found there is no support for ixx when I used cloc to count lines of code. I expect to add it to default support. Thanks very much.

**Comment by AlDanial** [comment]
Provide a link to a sample ixx file.  Provide information on what comments look like in ixx files.

**Comment by YbJerry** [comment]
You can find it in [MSVC's modules document](https://docs.microsoft.com/en-us/cpp/cpp/tutorial-named-modules-cpp?view=msvc-170). In fact, there is no difference in comments between cpp files, h files and ixx files. Just Microsoft's rules.
