### ISSUE TITLE
Languages specified in arguments should ignore whitespace and be case insensitive

### ISSUE THREAD

**Issue by MiguelGuthridge** [AlDanial/cloc#637]
**Describe the bug**
A concise description of the problem you found with cloc.

**cloc; OS; OS version**
 - cloc version: 1.82
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc): Linux
 - OS version: Ubuntu 20.04

**To Reproduce**
* Run the command `cloc . --include-lang Python, Markdown`, and observe that `" Markdown"` isn't recognised as a language.
* Run the command `cloc . --include-lang python`, and observe that `"python"` isn't recognised as a language.

**Expected result**
The program executes normally, after stripping whitespace from the arguments, and making them case insensitive.

**Comment by AlDanial** [comment]
Allowing spaces before or after the comma separator produces parsing ambiguity with the item(s) to be counted.  cloc uses Perl's [Getopt::Long](https://perldoc.perl.org/Getopt::Long) module to parse arguments and I don't see a way to make it work with what you have in mind.  I'd have to manually parse the arguments (and that's not going to happen).  I'll consider a PR or a sample Perl program that demonstrates your logic with Getopt::Long.
