### ISSUE TITLE
Permission denied error with Cloc Exe on running for the first time

### ISSUE THREAD

**Issue by Bharathir97** [AlDanial/cloc#638]
**Describe the bug**
We have used the Cloc Exe for counting the Lines of code in our source. When we run the cloc exe for the first time, we get a permission denied error. **can't read C:\Users\Username\AppData\Local\Temp\par-72616a6162686172\cache-37291f193d6cfca74d7ed42d4903ba2e68c784a4/61f55ee6.pm: Permission denied at -e line 126.** It cant be reproduced on running it again.

**Version details**
 - cloc version: 1.92
 -Edition:	Windows 10 Enterprise
 -Version:	20H2

**To Reproduce**
Step 1: Use Cloc exe with version [1.92]  and run it to check the Lines of code.
Step 2: Note the permission denied error occurs with the Cmd.
Note : Replace the Cloc exe with other version [1.90 or any version], the same permission denied issue occurs. It cant be reproduced for the second time. 
Attached the screenshot below for reference.
![image](https://user-images.githubusercontent.com/87690114/154224760-0d765fdd-e399-437f-b8dc-435fe1857410.png)

**Expected result**
Permission denied errors should be avoided, and the counting procedure should proceed with the result.

**Comment by AlDanial** [comment]
cloc writes temporary files as it runs.  It uses Perl's ``File::Temp`` module to create a suitable temporary file.  It seems the location ``File::Temp`` picks has permission issues at your site.  No matter, you can force cloc to use a different location with the ``--sdir`` switch.  For example try ``--sdir=C:\TEMP``.  If that's successful you can add that switch and its value to a config file, ref https://github.com/AlDanial/cloc#optionstxt-configuration-file-

**Comment by Bharathir97** [comment]
Hi AIDaniel,
I verified it by changing the directory, but it still doesn't work, and I'm still having problems. This issue was only ever replicated once in a system. (The issue can be reproduced by executing the Cloc for the first time with any version and then replacing the Cloc with a different version)

**Comment by AlDanial** [comment]
Are you able to make folders and add files to``C:\Users\Username\AppData\Local\Temp``  and ``C:\TEMP``?  If yes, post the output of
``cloc -v 3 --sdir=C:\TEMP your_directory``
That may help isolate where things are going wrong.

**Comment by Bharathir97** [comment]
I created a folder and used that directory; when the application is executed, it creates a **cloc_file_list** text file in the path, which contains our data. It rewrites the data in the cloc_file_list and generates some.pm files in the path after replacing the Cloc exe with the 1.84 version. I've attached the snapshot of the issue, as well as the files created and the Appdata/temp files. Please assist us in resolving this problem.
<img width="947" alt="error_cloc" src="https://user-images.githubusercontent.com/87690114/154904168-5152c0ee-2e03-4db1-8b39-6f91851cf0de.png">
[1.zip](https://github.com/AlDanial/cloc/files/8106974/1.zip)
[cache-9a1081f244251f82f6c0773040029dbfb22c87a7.zip](https://github.com/AlDanial/cloc/files/8106977/cache-9a1081f244251f82f6c0773040029dbfb22c87a7.zip)

**Comment by mageshsankar** [comment]
@Bharathir97  @AlDanial  I'm having the same problem at my site, and I can only reproduce it the first time I use any version of cloc exe.

**Comment by Bharathir97** [comment]
Hi, Expected files are not generated in the new folder. 
<img width="947" alt="issue_" src="https://user-images.githubusercontent.com/87690114/155108856-b4d3927a-f5b9-4b61-8e21-56d6a0050699.png">

**Comment by AlDanial** [comment]
The two zip files you attached are not useful.  Post the output from the command I showed earlier,
``cloc -v 3 --sdir=C:\TEMP your_directory``
