### ISSUE TITLE
Diff with two commits causes error "The process cannot access the file because it is being used by another process."

### ISSUE THREAD

**Issue by nbiefeld** [AlDanial/cloc#639]
I have a very light weight repository that I am using to check the lines of code, and I am comparing two different commits and branches.  Yet I constantly receive the following error message:

```
The process cannot access the file because it is being used by another process.
tar: Removing leading drive letter from member names
'unzip' is not recognized as an internal or external command,
operable program or batch file.
Unable to expand C:\Users\nwbie\AppData\Local\Temp\B5FkCorwT6.zip because external
utility 'unzip' is not available.
Another possibility is to use the --extract-with option.
```

Using the Verbose option, I get some detailed logs.

```
type nul > C:\Users\nwbie\AppData\Local\Temp\fD99sq1CNv.zip
The process cannot access the file because it is being used by another process.
```

I tried changing the temp directory and did not have any luck.  I tried to use the extract-with option with CMD but it just changes the directory to the temp directory.

I tried to look for an existing issue, or in the documentation and I did not see anywhere I was missing.  If I missed the instructions please let me know.  I am running on both Windows 10 64-bit and Windows 11 64-bit systems and am receiving this error on both systems.  Is there some option I am missing?  It looks like it is just generating an error when its making the file in the temp directory.

**Comment by nbiefeld** [comment]
Ah I figured it out.  Turns out Windows 10 post build 17063 and Windows 11 includes tar that works with the extract-with option.  This has resolved my issue.

**Comment by abdurraheemali** [comment]
I'm running into this exact problem. Any details?

**Comment by abdurraheemali** [comment]
Figured it out. I used git archive to make two tar.gz files, then passed those to cloc.
