### ISSUE TITLE
read-lang-def is broken

### ISSUE THREAD

**Issue by achikin** [AlDanial/cloc#64]
--read-lang-def seems to be doing nothing
Happens under MacOSX both on brew-installed 1.64 and downloaded 1.66 release from this repo.
```
> cloc --write-lang-def=def.txt
> cloc --read-lang-def=def.txt

Usage: cloc [options] <file(s)/dir(s)> | <set 1> <set 2> | <report files>
[the rest of help here]

> echo $?
255
```

**Comment by AlDanial** [comment]
It was broken in 1.64, but it works fine in 1.66--you're just not invoking cloc correctly.  In the second line where you read back the definitions, you are also expected to provide file/dir inputs to count.
<pre>
> cloc --read-lang-def=def.txt  dir1  dir2  ...
</pre>
