### ISSUE TITLE
Language Support .gdshader

### ISSUE THREAD

**Issue by AdrKacz** [AlDanial/cloc#641]
# Language Support *.gdshader -  [Language Reference](https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html)

`cloc` already supports Godot Ressource, Godot Scene, and GDScript. However, it misses Godot Shaders.

**If you want an unsupported language added, provide:**
 - language name: Godot Shaders 
 - file extension(s): .gdshader
 - method(s) of commenting text: `//`
 - location of sample code:

*Thank you for this superb tool! It helps me a lot to keep track of the codebase of my projects.*

*PS: it's my first-time contribution to an Open Source project that is not mine. I don't know if I'm supposed to solve the problem already, please let me know. I would be happy to help!*

**Comment by AlDanial** [comment]
I'll take care of updating the code, no worries there.  I do need one more thing from you though:  a representative .gdshader file that I can use to make a test case.

**Comment by AdrKacz** [comment]
Super, thank you very much!

I don't know where I am supposed to put these files. I may not have counted the number of lines with the correct rules. Let me know if there is any problem.

### Example2D.gdshader

```
#! 9 codes, 3 blanks, 5 comments
shader_type canvas_item;

uniform float blue = 1.0; // you can assign a default value to uniforms

void vertex() {
  // Animate Sprite moving in big circle around its location
  VERTEX += vec2(cos(TIME)*100.0, sin(TIME)*100.0);
}

void fragment(){
    // this shader will result in an more bluish sprite
    COLOR = texture(TEXTURE, UV); //read from texture
    COLOR.b = blue; //set blue channel to <blue>
}
```


### Example3D.gdshader

```
#! 13 codes, 4 blanks, 3 comments
shader_type spatial;

varying vec2 tex_position;

uniform float height_scale = 0.5;
uniform sampler2D normalmap;
uniform sampler2D noise; // select an noise to apply

void vertex() {
    // read heigh from <noise>
    tex_position = VERTEX.xz / 2.0 + 0.5;
    float height = texture(noise, tex_position).x;
    VERTEX.y += height * height_scale;
}

void fragment() {
  NORMALMAP = texture(normalmap, tex_position).xyz;
}
```
