### ISSUE TITLE
JavaScript counter not recognizing CJS and MJS files

### ISSUE THREAD

**Issue by jlarmstrongiv** [AlDanial/cloc#643]
**Describe the bug**
The JavaScript file count is incorrect.  It does not count `.cjs` and `.mjs` files.

**cloc; OS; OS version**
 - cloc version: 1.92
 - OS (eg Linux, Windows, macOS, etc): macOS
 - OS version: 10.15.7

**Expected result**
Accurate file count with all types of JS files.

**Additional context**
Unfortunately, I do not know perl, but I’m assuming tests should be updated here https://github.com/AlDanial/cloc/blob/9c833b0d158e81c7b03a6d6170aa6c483b277470/Unix/t/00_C.t

**Comment by AlDanial** [comment]
``.cjs`` was missing but ``.mjs`` was already defined in 1.92
<pre>$ ./cloc-1.92.pl --show-ext  | grep JavaScript
_js             -> JavaScript
bones           -> JavaScript
es6             -> JavaScript
jake            -> JavaScript
jakefile        -> JavaScript
js              -> JavaScript
jsb             -> JavaScript
jscad           -> JavaScript
jsfl            -> JavaScript
jsm             -> JavaScript
jss             -> JavaScript
mjs             -> JavaScript
njs             -> JavaScript
pac             -> JavaScript
sjs             -> JavaScript
ssjs            -> JavaScript
xsjs            -> JavaScript
xsjslib         -> JavaScript
</pre>

**Comment by jlarmstrongiv** [comment]
@AlDanial thank you 🚀
