### ISSUE TITLE
Use of uninitialized value in concatenation (.) or string at script/cloc-1.92.pl line 5999,

### ISSUE THREAD

**Issue by yaqian256** [AlDanial/cloc#644]
**Describe the bug**
Saw the following warnings when running cloc-1.92.exe on Windows 10.

`Use of uninitialized value in concatenation (.) or string at script/cloc-1.92.pl line 5999...`

**cloc; OS; OS version**
 - cloc version: 1.92
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc): Windows
 - OS version: Windows 10

**To Reproduce**
Run the cloc-1.92.exe with a folder, eg `cloc-1.92.exe "somefolder"`

**Expected result**
not showing the "Use of uninitialized value"

**Additional context**
The warning seems is from the first_line method:
```
-> first_line(somefolder/foo.cs, 2)
Use of uninitialized value in concatenation (.) or string at script/cloc-1.92.pl line 5999, <GEN390> line 1.
<- first_line(somefolder/foo.cs, 2, '﻿abc')
```

**Comment by AlDanial** [comment]
I'm unable to duplicate this problem.  Does it happen with all folders or only with this particular one?  Perhaps it is caused by a specific file, ie your ``foo.cs``?

**Comment by OlafRoesler** [comment]
The file inside the attached archive can be used to reproduce the problem. When loading the file into an editor (Notepad++) it appears to be empty, but the operating system (Windows 10) reports a length of 3 bytes.
I received the following message.

> Use of uninitialized value in concatenation (.) or string at script/cloc-1.92.pl line 5999, <GEN4> line 1.

[UInt8.zip](https://github.com/AlDanial/cloc/files/8430610/UInt8.zip)

**Comment by AlDanial** [comment]
@OlafRoesler : very helpful, thanks!
