### ISSUE TITLE
Language Support .heex

### ISSUE THREAD

**Issue by xward** [AlDanial/cloc#645]
**If you want an unsupported language added, provide:**
 - language name: Html EEx
 - file extension(s): .heex
 - method(s) of commenting text: <%# ... %>
 - location of sample code:
 
### exemple.heex
```
<%= for entry <- entries do %>
  <article class="dummy">
    <%# this is a nice comment about progress %>
    <progress value={entry.progress} max="100"> <%= entry.progress %>% </progress>
  </article>
<% end %>
```

_ps: thank you for this tool !_

**Comment by Gladear** [comment]
Beware `<%# %>` comments are to be deprecated, and replaced with `<% # single line comment %>` and `<%-- multi line comment --%>` (see https://hexdocs.pm/elixir/main/changelog.html#3-soft-deprecations-no-warnings-emitted)

**Comment by AlDanial** [comment]
@Gladear : thanks for the update on comments
