### ISSUE TITLE
Installation instruction for RedHat 8 doesn't work

### ISSUE THREAD

**Issue by tfendin** [AlDanial/cloc#648]
**Describe the bug**
In the README in section "Install via package manager" it says that `cloc` can be install in RedHat with `sudo yum install cloc`. However, that doesn't work in RedHat 8.5, the package can't be found.

**cloc; OS; OS version**
 - cloc version:
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc): Linux
 - OS version: RedHat 8.5

**To Reproduce**
sudo yum install cloc

**Expected result**
cloc should be installed by yum

**Comment by wcjcn** [comment]
您的邮件已经收到，谢谢您。祝您生活愉快。

**Comment by AlDanial** [comment]
The README says "Depending your operating system, one of these installation methods may work for you."

Note:  "_may_ work".  That is quite different from "can be installed".

If the package manager option doesn't work you'll need to download cloc from the Releases area.
