### ISSUE TITLE
How to change output style?

### ISSUE THREAD

**Issue by AdrKacz** [AlDanial/cloc#649]
Is it possible to change the style of the output?

For example, with the `--md` flag, the `SUM` is as:

```md
...
--------|--------|--------|--------|--------
SUM:|63|16.96|14.61|6227
```

However, I'd like to have it as:
```md
...
**SUM:**|**63**|**16.96**|**14.61**|**6227**
```

I don't think it is a viable option to provide as many styles as wanted. Nonetheless, it would be great to offer a *style template*.

That's just an idea; feel free to tell me if it is not the place 😌 (or if the feature already exists 😇)

*PS: thank you for your package. It helps me keep track easily of my codebase 🥰*

**Comment by AlDanial** [comment]
Regretfully I have to decline adding such an option to cloc as it would open the door to an unmanageable number of format styles.

My recommendation would be to use option like ``--json`` or ``--yaml`` to write cloc's output to a format that is easily ingested by a separate program then use that separate program to style the output.
