### ISSUE TITLE
git source location in xml output

### ISSUE THREAD

**Issue by AaronRidoutAE** [AlDanial/cloc#652]
it would help me if the xml output included the source information so the output document says what version of code it refers to for traceability once the file is copied or published outside the git root; perhaps linked to --vcs=git if it was specified? i.e. git origin, branch & hash for my current HEAD:
E.g. 
<header>
  <cloc_url>github.com/AlDanial/cloc</cloc_url>
  <cloc_version>1.92</cloc_version>
  ...
  <source>
        <origin>https://mickey.mouse@github.com/myproject/root</origin>
        <branch>feature/killer_ideas_r_us</branch>
        <head>db426708d5c24664cbc0bfa2e3fd8dc35cad3ea0</head>
  </source>
</headers>

pseudo code: <source>\n<origin>`git remote get-url origin`</origin>\n<branch>`git symbolic-ref --short HEAD`</branch>\n<head>`git rev-parse HEAD`</head>\n</source>\n

Thanks for a great tool - Aaron

**Comment by wcjcn** [comment]
您的邮件已经收到，谢谢您。祝您生活愉快。

**Comment by AlDanial** [comment]
Post a sample XML file containing the entries you have in mind.  I'll have a much better understanding of your request that way.

**Comment by AaronRidoutAE** [comment]
<header>
  <cloc_url>github.com/AlDanial/cloc</cloc_url>
 ...
  <source>
    <origin>https://mickey.mouse@github.com/myproject/root feature/killer_ideas_r_us</origin>
    <branch>feature/killer_idea</branch>
    <head>db426708d5c24664cbc0bfa2e3fd8dc35cad3ea0</head>
  </source> 
</header><languages>...</languages>

**Comment by AlDanial** [comment]
Please give 0e927cc a try.  If it looks OK I'll add the capability for YAML & JSON output as well.

**Comment by AlDanial** [comment]
You also need the ``--git`` switch.  Try
`  cloc-master/cloc --git --xml --out=MySource_sloc.xml MySource
`
Without ``--git``, cloc will think ``MySource`` is a regular directory rather than a git repo.

**Comment by AaronRidoutAE** [comment]
Hi,
Thanks that works a charm!
--Aaron

From: AlDanial ***@***.***>
Sent: 04 July 2022 15:40
To: AlDanial/cloc ***@***.***>
Cc: Ridout, Aaron [Industrial Power/GB/LIT] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [AlDanial/cloc] git source location in xml output (Issue #652)

You also need the --git switch. Try cloc-master/cloc --git --xml --out=MySource_sloc.xml MySource Without --git, cloc will think MySource is a regular directory rather than a git repo. — Reply to this email directly, view it on GitHub
ZjQcmQRYFpfptBannerStart
NOTE: This email originated from outside the Advanced Energy organization.
Do not click links or open attachments unless you recognize the sender and know the content is safe.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/Mbt2!QBe86dXJOPmmIKWB4WPWZW7VNBkgLSIHVWkE-XPCGuTYkoWVMMQEK8_1ByX7uxD8Aoi-6PCj7NqKgbwa3Nen8RPEVzrfLYRu$>   ‌
ZjQcmQRYFpfptBannerEnd

You also need the --git switch. Try
cloc-master/cloc --git --xml --out=MySource_sloc.xml MySource
Without --git, cloc will think MySource is a regular directory rather than a git repo.
