### ISSUE TITLE
No directory recursion option?

### ISSUE THREAD

**Issue by nurbles** [AlDanial/cloc#657]
Back on 2014-12-05 (when cloc was still on sourceforge) I found this comment from [**Al Danial**](https://sourceforge.net/p/cloc/feature-requests/99/):
> I like the idea of --no-recursion and will add its implementation to my to-do list. 

I cannot find anything like this feature in the documented comment line options, but I truly wish it existed so that I could avoid the need to create a custom --exclude-dir option for every folder. Is there some reason this (simple appearing) option was never implemented, or was it just forgotten?  If the latter, perhaps it could be resurrected?  Please?

**Comment by AlDanial** [comment]
Eight years is a long time to wait, sorry about that and thanks for the reminder.  Give 5bce3b2 a try & let me know if it works the way you expect.

**Comment by AlDanial** [comment]
This is now in the v1.94 release.
