### ISSUE TITLE
Please document the release process

### ISSUE THREAD

**Issue by StoneCypher** [AlDanial/cloc#659]
If you will document the release making process, I will tool it under Github Actions for you, so that every time a language is added, you get a new release with zero effort and guaranteed (eventually) correctness

I ask for this because your previous release was six months ago, and I don't actually use `cloc` directly; rather, I use a wrapping of it from `npm`, which relies on your releases, and I can't ask them to bump

**Comment by AlDanial** [comment]
Thanks for the offer.  I'll partially take you up on it:  if you can figure out a Github Actions configuration that builds a Windows executable from the Perl source on each commit using steps such as
```
C:> cpan -i Digest::MD5
C:> cpan -i Regexp::Common
C:> cpan -i Algorithm::Diff
C:> cpan -i PAR::Packer
C:> pp -M Digest::MD5 -c -x -o cloc-1.92.exe cloc
```
then I'll definitely add it.

Aside from that, I prefer to keep a six month release schedule... which reminds me a release is now overdue.  I'll prepare to release tomorrow.

**Comment by StoneCypher** [comment]
I can happily take a stab at that.  I'm a Windows user who uses GH actions across all three major OSes.

Is it just those five steps?  Does it matter which Perl I use?

**Comment by StoneCypher** [comment]
In case it helps to see that this is work I've done a bunch on my own hobby repos, and that I probably will follow through, here's the root of the build automation I have around my FSM library:

* https://github.com/StoneCypher/jssm/blob/main/.github/workflows/nodejs.yml

Which feeds into these:

* https://github.com/StoneCypher/jssm-viz/blob/main/.github/workflows/lib_update.js.yml
* https://github.com/StoneCypher/jssm-viz/blob/main/.github/workflows/nodejs.yml

Which in turn feed into these:

* https://github.com/StoneCypher/jssm-viz-cli/blob/master/.github/workflows/lib_update.js.yml
* https://github.com/StoneCypher/jssm-viz-cli/blob/master/.github/workflows/nodejs.yml

And these:

* https://github.com/StoneCypher/jssm-viz-demo/blob/main/.github/workflows/lib_update.js.yml
* https://github.com/StoneCypher/jssm-viz-demo/blob/main/.github/workflows/node.js.yml
