### ISSUE TITLE
Missing perl module

### ISSUE THREAD

**Issue by xapple** [AlDanial/cloc#66]
I just wanted to test "CLOC" so I typed these two lines in bash, but it didn't work.

    xapple@local ~ $ brew install cloc
    ==> Downloading https://homebrew.bintray.com/bottles/cloc-1.66.el_capitan.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring cloc-1.66.el_capitan.bottle.tar.gz
    🍺  /usr/local/Cellar/cloc/1.66: 5 files, 526K
    xapple@local ~ $
    xapple@local ~ $
    xapple@local ~ $ cloc /repos/cool_project/
    Can't locate Algorithm/Diff.pm in @INC (@INC contains: /Users/xapple/perl5/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0/darwin-2level /Users/xapple/perl5/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0 /Users/xapple/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/darwin-2level /Users/xapple/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0 .) at /usr/local/bin/cloc line 71.
    BEGIN failed--compilation aborted at /usr/local/bin/cloc line 71.
    xapple@local ~ $

**Comment by AlDanial** [comment]
Evidently the homebrew cloc maintainer for cloc (I don't know who it is) did not include a dependency definition for Algorith::Diff.  I'll try to figure out who it is & report the issue.

In the meantime, you can get the all-dependencies-included version of 1.66 from
https://github.com/AlDanial/cloc/releases (the file https://github.com/AlDanial/cloc/releases/download/v1.66/cloc-1.66.pl).  I'm confident you won't have problems with it.

**Comment by xapple** [comment]
OK thanks for the answer ! In the end the easiest solution was to type:

     $ cpanm Algorithm/Diff.pm
