### ISSUE TITLE
Request for language support, four variants: PEG, peg.js, peggy, tspeg

### ISSUE THREAD

**Issue by StoneCypher** [AlDanial/cloc#661]
# Main language

* language name: PEG
* file extension(s): `.peg`
* method(s) of commenting text: c/c++ style - line comments with `//`, non-nesting block comments with `/* */`
* location of sample code: below.  Also,
    * [here](https://moodle.org/mod/forum/discuss.php?d=346431)
    * [here](https://github.com/StoneCypher/short_offer/blob/main/src/peg/sdp_parser.pegjs)

```pegjs
Expression
  = head:Term tail:(_ ("+" / "-") _ Term)* {
      return tail.reduce(function(result, element) {
        if (element[1] === "+") { return result + element[3]; }
        if (element[1] === "-") { return result - element[3]; }
      }, head);
    }

Term
  = head:Factor tail:(_ ("*" / "/") _ Factor)* {
      return tail.reduce(function(result, element) {
        if (element[1] === "*") { return result * element[3]; }
        if (element[1] === "/") { return result / element[3]; }
      }, head);
    }

Factor
  = "(" _ expr:Expression _ ")" { return expr; }
  / Integer

Integer "integer"
  = _ [0-9]+ { return parseInt(text(), 10); }

_ "whitespace"
  = [ \t\n\r]*
```

# Variant language 1

* language name: peg.js
* file extension(s): `.pegjs`

# Variant language 2

* language name: peggy
* file extension(s): `.peggy`

# Variant language 3

* language name: tspeg
* file extension(s): `.tspeg`, `.jspeg`

**Comment by StoneCypher** [comment]
The four languages I'm involved with look good to me

Really surprising to see perl there - I thought this was written in perl?

**Comment by StoneCypher** [comment]
Notably, the part of the SDP parser you took, while valid, isn't normative PEG

If you want a short example you're probably better off with the arithmetic example from this issue

**Comment by StoneCypher** [comment]
The part in the actual code examples is fine though

**Comment by StoneCypher** [comment]
As far as giving it a try, I don't actually know how to install CLOC without using the `npm` wrapper I've been using

Do I pop it from CPAN?  If so, how, please?  I'm not a perl person

**Comment by AlDanial** [comment]
To run cloc using its [Perl source code](https://github.com/AlDanial/cloc/raw/master/cloc) on Windows instead of the .exe, you'll need to install a Perl interpreter for Windows.  I use [Strawberry Perl](https://strawberryperl.com/). Then you can do, for example, ``C:> perl cloc my_source_dir``

Regarding the SDP parser fragments I copied for testing, the stuff I extracted doesn't need to be real PEG code, just something representative of what PEG might look like.

**Comment by StoneCypher** [comment]
Appears to work

**Comment by StoneCypher** [comment]
Confirmed working in my stack.  Thank you

![image](https://user-images.githubusercontent.com/77482/177408163-6d2dd608-ac8f-439e-b802-ef5ef47b2bb7.png)
