### ISSUE TITLE
Logtalk language support

### ISSUE THREAD

**Issue by pmoura** [AlDanial/cloc#67]
Would it be possible to add support for the Logtalk programming language? Logtalk extends Prolog and thus uses the same line comment and block comment syntax. Logtalk source files extensions are `.lgt` and `.logtalk`. For some sample code see e.g.

https://github.com/LogtalkDotOrg/logtalk3/blob/master/core/logtalk.lgt
https://github.com/LogtalkDotOrg/logtalk3/blob/master/core/expanding.lgt

Thanks for developing `cloc`.

**Comment by AlDanial** [comment]
I'll add support for Logtalk later this week.

**Comment by AlDanial** [comment]
git commit 48aa430 adds Logtalk support.  Please test it out and let me know if it looks OK.

**Comment by pmoura** [comment]
Tested. The directory and file stats are accurate as expected. Thanks!

**Comment by pmoura** [comment]
Mentioned here: https://twitter.com/LogtalkDotOrg/status/710765972488114177
