### ISSUE TITLE
Version 1.94 Error with format comma csv : --csv-delimiter="|"

### ISSUE THREAD

**Issue by Sori31** [AlDanial/cloc#670]
**Describe the bug**
With Ver1.94: Show message Error  When I export -csv with format --csv-delimiter="|"

 - cloc version: 1.94
 - OS : Windows

Message Error
   Can't use an undefined value as an ARRAY reference at script/cloc line 2335, <$fh> line 1

**Comment by AlDanial** [comment]
Thanks for reporting this problem, should work in c91e8c5.
