### ISSUE TITLE
Support for WGSL (WebGPU Shading Language)

### ISSUE THREAD

**Issue by aabizri** [AlDanial/cloc#672]
- language name: WGSL (WebGPU Shading Language)
 - file extension(s): .wgsl *[0]*
 - method(s) of commenting text: 
   - `// single-line comment`
   - `/* a comment block /* these can nest ! */ */`  *[1]*
   - See [the standard](https://gpuweb.github.io/gpuweb/wgsl/#comments) for the standardese.
 - location of sample code:
   - sample code in [the standard](https://gpuweb.github.io/gpuweb/wgsl/#comments)
   - some real-life examples found on github on [github.com/hexops/mach](https://github.com/hexops/mach/tree/f299d87aa2391e219abdd403d5aa31350a9bb81f/examples)

*[0] while it doesn't seem to be official, that's the one that's been adopted by most users (see [github search](https://github.com/search?l=&p=1&q=extension%3Awgsl&ref=advsearch&type=Code) as well as the [wgsl vscode extension fogcity/vscode-wgsl](https://github.com/fogcity/vscode-wgsl/blob/5ee93c87c75c7a5058d9c32590c760e2e36572fc/package.json))*
*[1] the nesting ability of the blocks means the parsing logic differs from C & C++'s comment blocks*

**Comment by AlDanial** [comment]
cloc's support for WGSL isn't perfect because cloc, being regex-based, can't handle nested comments.  I updated the README to mention this in the Limitations section.
