### ISSUE TITLE
Enhancement request: language support for .p4 extension

### ISSUE THREAD

**Issue by GreenieQwQ** [AlDanial/cloc#684]
- language name: P4
 - file extension(s): .p4
 - method(s) of commenting text: just c-like commenting method
 - location of sample code: https://github.com/p4lang/tutorials/tree/master/exercises

And is there some way to add file extension for an existing language with cloc cli command? (namely, we can just treat .p4 as a c file -- as they're almost the same!)

**Comment by AlDanial** [comment]
https://github.com/AlDanial/cloc/commit/4aa0eecaee1d768eb8ca0f14ffa6f8abd7c4647e has the update.

To answer your question, yes you can add the extension for p4 yourself with a [custom language definition file](https://github.com/AlDanial/cloc#create-custom-language-definitions-).
