### ISSUE TITLE
[Help] Need help comparing two Git commits

### ISSUE THREAD

**Issue by huornlmj** [AlDanial/cloc#685]
Does the following actually show the reported difference between two Git commit?  Or does it just show the report of the first Git commit and ignore the second as an unknown or unexpected argument?

```console
$ cloc 0356685c5d7e9456e46c99b51ca72a902e9d7805 8310fca354fbca60219fa212034714b1d338a4fe
```

I need to summarize the amount of change between two commits in cloc format.

**Comment by AlDanial** [comment]
Yes, cloc can show counts of code added, removed, modified, and unchanged between two code bases (ref the ``--diff`` option).  For git inputs best also to pass in ``--git`` to make sure there's no confusion that the inputs are git-like.  In your case that would be
``cloc --git --diff 0356685c5d7e9456e46c99b51ca72a902e9d7805 8310fca354fbca60219fa212034714b1d338a4fe``

The default comparison strategy is to only compare files that have changed between commits.  If you want to do a diff of every file in the repo at those commits, also pass in ``--git-diff-all``.
