### ISSUE TITLE
Exclude node_modules and other similar folders by default

### ISSUE THREAD

**Issue by ReCore-sys** [AlDanial/cloc#690]
99% of the time, you don't care about how many lines of javascript are in your very bloated node_modules folder and can have a huge performance impact on the time taken to work out the total loc. I suggest automatically excluding node_modules and any other module/library folder for other languages. 
There are probably cases where people would want to scan these folders though, so maybe a command line flag to enable scanning these folders.

**Comment by AlDanial** [comment]
This is already possible with the ``--exclude-dir`` switch, ref the documentation.  You can automatically include ``--exclude-dir=node_modules`` (or whatever the right name would be) with every run by adding it to a [config file](https://github.com/AlDanial/cloc#optionstxt-configuration-file-).

**Comment by tjx666** [comment]
I think cloc should ignore search files defined in .gitignore by default @AlDanial

**Comment by AlDanial** [comment]
@tjx666 : cloc can already do this.  See  the documentation for ``--vcs``.  In your case run cloc with ``--vcs=git``
