### ISSUE TITLE
The program treats a UTF-16 LE encoded text file as a binary file and skiped this file.

### ISSUE THREAD

**Issue by ZjzMisaka** [AlDanial/cloc#696]
**To reproduce:**
1. Create a new file
2. Set Encoding to UTF-16 LE
3. Add some random code
4. Save the file as test.cs
5. Run cloc in the folder where you saved that file
6. You will see that this file is neither processed nor in the ignore list.
7. Use the parameter "--ignored" to output the file, the content is "1:  binary file"
- If change Encoding to UTF-8 or Shift-JIS, run again, you will find that the program runs correctly.

**cloc; OS; OS version**
 - cloc version: v1.94
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc): Windows
 - OS version: 21H2

**Comment by AlDanial** [comment]
1.  Did you try running with ``--unicode``?
2. If the ``--unicode`` switch doesn't help, please attach a sample UTF-16LE file so that we can work with the identical input.

**Comment by ZjzMisaka** [comment]
> 1. Did you try running with `--unicode`?
> 2. If the `--unicode` switch doesn't help, please attach a sample UTF-16LE file so that we can work with the identical input.

--unicode worked, thank you
