### ISSUE TITLE
Appear to be getting invalid counts for .htm file

### ISSUE THREAD

**Issue by rschaeferhig** [AlDanial/cloc#7]
I'm evaluating this for use in our CI Build/Metrics workflow. I ran it against a .Net Solution that has one .htm file (attached). CLOC returned: 
files	language	blank	comment	code
1	HTML	4	0	57

The file is mostly JavaScript and mostly commented out. It appears to be counting the commented Javascript as code.
![10-5-2015 12-28-10 pm](https://cloud.githubusercontent.com/assets/7859432/10286675/e736777a-6b5c-11e5-8133-0ac1702b562e.jpg)

**Comment by AlDanial** [comment]
cloc isn't smart enough to see there is Javascript inside the HTML.  Basically it works as one file = one language.  I can think of a couple of work-arounds, but they will just count the Javascript block as comments, not as actual Javascript code.

1. You could create a custom language definition file (ref --write-lang-def/--read-lang-def, https://github.com/AlDanial/cloc#custom_lang) that recognizes /* and */ as comments for HTML
2. You could surround your Javascript code with HTML comment markers , ie
  
But that would mean modifying all your HTML files which would be a total drag.

**Comment by rschaeferhig** [comment]
Given the prevalence of models such as MVC where HTML pages contain large amounts of Javascript I would think that it might be beneficial for the strategic direction of cloc to be able to count Javascript lines inside HTML. I’m not a developer so writing that level of code is beyond me, but as a DevOps Engineer the functionality is important. Any chance to put it on the backlog of potential enhancements that another contributor might pick up? I can’t be the only person wondering about this…

Thanks for the quick response.

**Comment by AlDanial** [comment]
I'm certainly not opposed to counting code embedded within HTML, it's just that I don't know how to do it properly.  I'm happy to accept pull requests from smarter people who can implement this.

**Comment by rschaeferhig** [comment]
Do you have a backlog of enhancements that people can look at? If not you might want to consider publishing a list of potential enhancements that contributors could look at and tackle if they so desire.

Anyway, thanks for the explanation. It’s a great tool.

**Comment by AlDanial** [comment]
Good idea.  I added a new section to the README,
https://github.com/AlDanial/cloc/blob/master/README.md#in_progress, that
shows what I'm working on (or at least thinking of working on).
