### ISSUE TITLE
Support jade files

### ISSUE THREAD

**Issue by keverw** [AlDanial/cloc#70]
Could jade files be added please? They are template files mainly used with Node.js. http://jade-lang.com/ has a sample on the left, and more infomation on the lanaguage.

**Comment by keverw** [comment]
Hmm just was reading GitHub.

Looks like it's now called pug, because of some trademark thing.

https://github.com/pugjs/pug - https://github.com/pugjs/pug/issues/2184

**Comment by AlDanial** [comment]
Please point me to a reference showing how pug comments are defined.

**Comment by keverw** [comment]
Here's how comments are handled. http://jade-lang.com/reference/comments/

Looks like they haven't set up new doc's yet with the new name.

Pretty much the same as javascript:

`// this is a comment`

but block comments are like support too:

```
//
  this
  is
  a
  comment too`
```

**Comment by AlDanial** [comment]
commit 6bbf37c adds support for Pug; please test it and let me know if it works as expected

**Comment by keverw** [comment]
I just gave it a quick test with this file:

```
//list
ul.lol
	li.foo=cow
	
//
	this
	is
	a
	block
	comment
```

and got this for the output

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Pug                              1              1              7              2
-------------------------------------------------------------------------------
```

So it looks like it's counting correctly. Thanks :)
