### ISSUE TITLE
Latest Docker Image is broken

### ISSUE THREAD

**Issue by CodeMan99** [AlDanial/cloc#703]
**Describe the bug**

```bash
$ docker run --rm -v $PWD:/tmp aldanial/cloc:latest HEAD
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "HEAD": executable file not found in $PATH: unknown.
```

This seems to stem from the change to drop `ENTRYPOINT` and instead use `CMD`. The following works as expected.

```bash
$ docker run --rm -v $PWD:/tmp --entrypoint /usr/src/cloc aldanial/cloc:latest HEAD
```

 - cloc version: 1.96
 - OS (eg Linux, Windows, macOS, etc): [docker image](https://hub.docker.com/layers/aldanial/cloc/latest/images/sha256-38b65cc2e0eadd23b8e67b21553ca8a727a5f77c12a3e2d4f7dde0ec9150e2f0?context=explore)

**Comment by AlDanial** [comment]
Thanks for reporting this.  I wish I were more docker-savvy, looks like I'll have to revert the older commit, will do a bit of docker 101 first.

**Comment by AlDanial** [comment]
@Treehopper your PR #679 forces the use of ``--entrypoint`` on the command line.  Is there a way to achieve what you need on Windows without removing the ``ENTRYPOINT`` definition in ``Dockerfile``?

**Comment by AlDanial** [comment]
@Treehopper hope to hear from you soon.  I'll revert the commit in your PR this weekend if there's no work-around.

**Comment by AlDanial** [comment]
I updated the images at docker.io.

**Comment by nre-ableton** [comment]
It looks like the 1.96 tag was replaced by a newer image after this PR was merged. In the future, could you please push a new version tag instead of overwriting existing tags? This broke some of our CI builds and we had to revert to 1.94. Thanks, and keep up the good work! 👍 🙏

**Comment by AlDanial** [comment]
@nre-ableton sorry about that!  I think I've made about every possible mistake with Docker there is to make.  (Actually, when I think about it I'm probably underestimating myself there.)  At least this particular mistake won't be repeated.

**Comment by nre-ableton** [comment]
@AlDanial It's no problem, as I said, we have a workaround in place. Just something to keep in mind for future releases!

**Comment by gute-kunst** [comment]
@AlDanial hey, I it seems like the "latest" tagged image was not overwritten. Therefore the bug still persists when pulling aldanial/cloc.

**Comment by AlDanial** [comment]
I just re-pushed `latest` , let me know if you're not getting 1.96 from that.
