### ISSUE TITLE
Broken linux installation

### ISSUE THREAD

**Issue by lightningnetworkstores** [AlDanial/cloc#705]
**Describe the bug**
Can't install in Ubuntu 18 with `apt install`

**cloc; OS; OS version**
 - cloc version: latest
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc): Ubuntu
 - OS version: 18

**To Reproduce**
run `sudo apt install cloc` and observe the error

```
sudo apt install cloc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libmodule-runtime-perl : Depends: libparams-classify-perl but it is not going to be installed
 libparallel-forkmanager-perl : Depends: libmoo-perl but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

Trying with `--fix-broken` doesn't solve.

**Expected result**
Successul instalation.

**Comment by AlDanial** [comment]
hi, as mentioned [here](https://github.com/AlDanial/cloc#install-via-package-manager), I don't control the Ubuntu or any other package manager's bundling of cloc.  You can installing from the Releases page here isn't hard though; download it from https://github.com/AlDanial/cloc/releases/download/v1.96/cloc-1.96.pl, ``chmod a+x cloc-1.96.pl`` and you're good to go.
