### ISSUE TITLE
Request for language support: Constraint Grammar / cg3

### ISSUE THREAD

**Issue by unhammer** [AlDanial/cloc#709]
Thanks for making cloc, very nice tool :-) I'd like to request support for:

 - language name: [Constraint Grammar](https://github.com/GrammarSoft/cg3) ([Wikipedia article](https://en.wikipedia.org/wiki/Constraint_grammar))
 - file extension(s): `.cg3`, `.rlx`
 - method(s) of commenting text: shell-style `#` 
    - but not inside double-quoted strings `"like#this"`
    - there are no single-quoted strings
    - the `#` must be at start of line or preceded by whitespace, e.g. in the line `LIST kh#fv = pres pret;` there is no comment
 - location of sample code: https://raw.githubusercontent.com/apertium/apertium-dan/master/apertium-dan.dan.rlx

**Comment by AlDanial** [comment]
I didn't add logic to support ``#`` within double quotes because a line of code with a string will be counted as code regardless of whether or not it contains a ``#``.  Regular shell rules seem sufficient.
