### ISSUE TITLE
v1.96: --diff-list-file fails with undefined $this_lang for removed files

### ISSUE THREAD

**Issue by mr-ssi** [AlDanial/cloc#710]
**Describe the bug**
When using --diff-list-file with a removed file with an unkown language, it will fail at https://github.com/AlDanial/cloc/blob/v1.96/cloc#L2510
```
./cloc-1.96.pl --diff-list-file=test-files.list
       1 text file.
       0 text files.
Use of uninitialized value $this_lang in string eq at ./cloc-1.96.pl line 2549.
Use of uninitialized value $this_lang in hash element at ./cloc-1.96.pl line 2553.
Use of uninitialized value $this_lang in hash element at ./cloc-1.96.pl line 2557.
Use of uninitialized value $this_lang in sprintf at ./cloc-1.96.pl line 2558.
Use of uninitialized value $language in string eq at ./cloc-1.96.pl line 6664.
Use of uninitialized value $language in hash element at ./cloc-1.96.pl line 6668.
Use of uninitialized value $language in string eq at ./cloc-1.96.pl line 6686.
Use of uninitialized value $language in hash element at ./cloc-1.96.pl line 6702.
Can't use an undefined value as an ARRAY reference at ./cloc-1.96.pl line 6702.
```

I patched it locally by adding  following before the if condition:
```
if (not defined $this_lang) {
            printf "WARNING: SKIP - No language definition found for %s\n", $f;
            $this_lang = "(unknown)"
        }
```

**cloc; OS; OS version**
 - cloc version: 1.96
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc): linux
 - OS version: Fedora 37

**To Reproduce**
* create 2 folders (test1, test2)
* add file test.data with random content (in my case: 'Data file') to test1/
* create diff-file-list like:
> Files removed: 1
>   \- test1/test.data ; text
> 
* execute `./cloc-1.96.pl --diff-list-file=test-files.list`

**Comment by AlDanial** [comment]
Thanks for the well-written bug report.

**Comment by mr-ssi** [comment]
Thanks for this amazing tool and the fast response!
