### ISSUE TITLE
How to get the repeated file list

### ISSUE THREAD

**Issue by songgeb** [AlDanial/cloc#711]
**For other enhancements:**
There are 100 text files and 80 unique files.
Can I get the repeated file list?

**Comment by AlDanial** [comment]
The ``# unique`` output is misleading since that count also excludes other things--I should get rid of it to avoid confusion.  If you run with ``--ignored files.txt``  you'll find repeated files listed in ``files.txt`` as being duplicates.

**Comment by AlDanial** [comment]
Tangentially related, added a `--unique` switch to write a file containing names of unique files found by cloc.
