### ISSUE TITLE
cloc diff showing the same file as both added and removed

### ISSUE THREAD

**Issue by takadappara** [AlDanial/cloc#712]
**Describe the bug**
This bug is similar to #378 , but different.
It can also be reproduced with the latest version, 1.96.
This bug occurs when the directory structure is as follows.

dir1/
  sub_dir1/foo.txt
  main.c
dir2/
  foo.txt
  main.c

main.c and foo.txt in each directory are the same file.
The execution command is "cloc --include-lang='C' --by-file --diff dir1/ dir2/".
The reproducibility is about 3/10.

**cloc; OS; OS version**
 - cloc version: v1.96
 - OS (eg Linux, Windows, macOS, etc): macOS
 - OS version: Ventura 13.1

**To Reproduce**
[cloc_bug_reproduce.tar.gz](https://github.com/AlDanial/cloc/files/10733804/cloc_bug_reproduce.tar.gz)
1. Untar the attachment tar.gz file.
2. Go the directory 'cloc_bug_reproduce'
3. Run the following command.
cloc --include-lang='C' --by-file --diff dir1/ dir2/
If you run it 10 times, I think this phenomenon will occur 2 or 3 times.

**Expected result**
Expected result is
```
-------------------------------------------------------------------------------
File                           blank        comment           code
-------------------------------------------------------------------------------
dir1/main.c
 same                              1              0              5
 modified                          0              0              0
 added                             0              0              0
 removed                           0              0              0
-------------------------------------------------------------------------------
SUM:
 same                              1              0              5
 modified                          0              0              0
 added                             0              0              0
 removed                           0              0              0
-------------------------------------------------------------------------------
```
But sometimes I get unexpected results.
```
-------------------------------------------------------------------------------
File                           blank        comment           code
-------------------------------------------------------------------------------
dir1/main.c
 same                              0              0              0
 modified                          0              0              0
 added                             0              0              0
 removed                           1              0              5
dir2/main.c
 same                              0              0              0
 modified                          0              0              0
 added                             1              0              5
 removed                           0              0              0
-------------------------------------------------------------------------------
SUM:
 same                              0              0              0
 modified                          0              0              0
 added                             1              0              5
 removed                           1              0              5
-------------------------------------------------------------------------------
```

**Comment by takadappara** [comment]
Since this is my first post, I forgot to say hello. sorry
Thanks for the great tool!

I have new information.
This bug does not occur in version 1.88.
Occurs in versions 1.90 and later.
So I think the fix during this time has an effect.

**Comment by takadappara** [comment]
The following two lines were added from version 1.90.
```
         $L_drop = $L_drop . "/" if $L_drop;
         $R_drop = $R_drop . "/" if $R_drop;
```
I think these two lines are causing this problem.
I tried to print L_common, R_common, L_drop, L_common for debugging.
For the OK case, it resulted in:
```
L_common=dir1
R_common=dir2
L_drop=dir1/
R_drop=dir2/
```
But for the NG case, I got the following result.
```
L_common=dir1/sub_dir1
R_common=dir2
L_drop=dir1//
R_drop=dir2/
```
In the NG case, there are two slashes like '//', so I think this is bad.

For the above reasons, I think it is better to correct the first two lines as follows.
```
       if ((length($L_drop) > 0) && (substr($L_drop, -1) ne '/')) {
           $L_drop = $L_drop . "/";
       }
       if ((length($R_drop) > 0) && (substr($R_drop, -1) ne '/')) {
           $R_drop = $R_drop . "/";
       }
```
What do you think?

Thanks,

**Comment by AlDanial** [comment]
Thanks for your report, the file ``cloc_bug_reproduce.tar.gz``, and the results of your investigation -- yes, definitely a bug.  Sometimes ``main.c`` appears once, sometimes twice, crazy.  I suspect it has to do with looping over a Perl hash; keys are returned in arbitrary order unless you explicitly sort them.  May be a week before I have time for a thorough debug session however.

**Comment by takadappara** [comment]
Thank you for your response. I understand that this bug may or may not occur due to Perl hash.
This bug only occurs with certain file and directory patterns, but I would be very happy if it was fixed.

**Comment by AlDanial** [comment]
Sure enough it was related to different hash traversals between runs, but not at all in the part of the code I suspected.  Quite a journey to find this one!

**Comment by takadappara** [comment]
That's excellent! I'm glad you fixed it. thank you very much!!

**Comment by takadappara** [comment]
Thank you for fixing the bug. This bug no longer occurs in the Mac OS environment.
However, this problem also occurs in Windows 10, and it seems that it has not been fixed on the Windows 10 side.
Could you please check again?

Thanks again for your response!!
