### ISSUE TITLE
--hide-rate is not working for YAML, XML, JSON

### ISSUE THREAD

**Issue by kartben** [AlDanial/cloc#713]
**Describe the bug**
The CLI help might make one think that --hide-rate will remove "line and file processing rates in the output header", but this does not work for YAML, CSV or JSON output format.

cloc version: 1.96

**Comment by AlDanial** [comment]
An oversight, thanks for pointing this out.

**Comment by kartben** [comment]
Fantastic, and thank *you*! :)
