### ISSUE TITLE
"Trailing \ in regex" error when using vcs flag

### ISSUE THREAD

**Issue by cglong** [AlDanial/cloc#715]
**Describe the bug**
Running `cloc --vcs=git .\src\` in PowerShell yields this error message:

> Trailing \ in regex m/^.\src\/ at script/cloc-1.96.pl line 5542, <FH> line 1.

Running the same command without the `vcs` flag works as expected.

**cloc; OS; OS version**
 - cloc version: 1.96.1
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc): Windows
 - OS version: 11 Version 22H2

**To Reproduce**
1. Type `cloc --vcs=git `
2. Begin typing a directory name, then hit <kbd>Tab</kbd> to allow autocomplete to populate the full directory name
3. Observe that PowerShell automatically prepends the directory name with `.\` and appends `\` at the end
4. Try to execute the command and observe the above error message

**Expected result**
cloc should run as expected.

**Additional context**
N/A

**Comment by AlDanial** [comment]
Give this one a try; works for me in PowerShell.

**Comment by AlDanial** [comment]
Hmmm, by "this one" I meant the lastest on master, https://github.com/AlDanial/cloc/blob/master/cloc

**Comment by cglong** [comment]
Thank you for taking care of this so quickly! 🙂 It looks like this fixed the bug in this issue, but now I'm seeing a different one. Let me know if you'd like me to file a new issue for this:

```console
❯ perl cloc --vcs=git src
      35 text files.
      35 unique files.
       0 files ignored.

github.com/AlDanial/cloc v 1.97  T=1.63 s (21.4 files/s, 1534.2 lines/s)
------------------------------------------------------------------------------------
Language                          files          blank        comment           code
------------------------------------------------------------------------------------
# snip...
------------------------------------------------------------------------------------
SUM:                                 35            235            191           2082
------------------------------------------------------------------------------------

❯ perl cloc --vcs=git .\src\
       0 text files.
       0 unique files.
       0 files ignored.
```

**Comment by AlDanial** [comment]
PowerShell isn't doing cloc any favors with the ".\" prefix.  Anyway try the latest on master.
