### ISSUE TITLE
On Windows, cloc diff showing the same file as both added and removed

### ISSUE THREAD

**Issue by takadappara** [AlDanial/cloc#716]
**Describe the bug**

This bug is exactly the same as #712 reported last time, and it still occurs on Windows.
The point is that it still occurs on **Windows** .

The reproduction scenario is the same as #712, and can be reproduced with the script attached last time.

**cloc; OS; OS version**
 - cloc version: v1.97 (I used the latest master as of today.)
 - If running the cloc source, Perl version: Strawberry Perl 5.32.1.1
 - OS (eg Linux, Windows, macOS, etc): Windows
 - OS version: Windows 10

**To Reproduce**
same as #712

**Expected result**
same as #712

**Additional context**
I thought of a good way to fix this, but haven't found one.
However, when I commented out the following line that I commented last time, this problem no longer occurred.
https://github.com/AlDanial/cloc/blob/master/cloc#L12317
```
        $L_drop = $L_drop . "/" if $L_drop;
        $R_drop = $R_drop . "/" if $R_drop;
```

Lastly, thank you for fixing the bug last time.
I appreciate it very much.

**Comment by takadappara** [comment]
I suspect that the '\\' in the path has been already replaced with '/' at this point.
In other words, '//' is used in the path even in ON_WINDOWS.

https://github.com/AlDanial/cloc/blob/3d0fdea3eacd41d3102ef37f2a2c49b2247d5f50/cloc#L12336-L12342

Probably, I think that it is rewritten at the following place of the align_by_pairs function.

https://github.com/AlDanial/cloc/blob/3d0fdea3eacd41d3102ef37f2a2c49b2247d5f50/cloc#L12367-L12370

Therefore, I think that the ON_WINDOWS conditional statement is not necessary, and simply replace the following.
What do you think?

```perl
        $L_drop =~ s{\\}{/}g;
        $R_drop =~ s{\\}{/}g;
```

**Comment by AlDanial** [comment]
Good catch, your proposed fix is exactly correct.

(Incidentally I first ran on Windows under Cygwin and was unable to reproduce the problem.  Only when I went to a conventional Windows command prompt did the problem appear--and this was a clear indication that the problem is related to path separators.)

**Comment by takadappara** [comment]
I think it was difficult to find the separator issue because it depends on the environment.
Thank you very much for the quick fix!!
