### ISSUE TITLE
add winget package

### ISSUE THREAD

**Issue by thewh1teagle** [AlDanial/cloc#728]
It will be more convenient to have it on [winget package manager](https://learn.microsoft.com/en-us/windows/package-manager/winget/), other than on chocolate pm.

**Comment by AlDanial** [comment]
Yes, would be great to have someone create and manage the cloc package for winget.  Interested in volunteering?

**Comment by hayschan** [comment]
`cloc v1.94` has been requested to include into winget's library last year. https://github.com/microsoft/winget-pkgs/issues/83318
