### ISSUE TITLE
Support trailing slash with --match-d

### ISSUE THREAD

**Issue by PMExtra** [AlDanial/cloc#732]
For example, we have the structure:

```plain
|- src
|  |- foo
|  |  |- bar.cpp
|  |- baz.cpp
|- srcx
|  |- x.cpp
```

If I specified `--match-d=/src/` options, it will only match the `src/foo` folder and only found the `src/foo/bar/cpp` file. The `src/baz.cpp` will be not matched.

It's not my expected result. I think `--match-d=/src/` should also match itself rather than subdirectory only.

For now, I have to set `--match-d=/src(/|$)` to achieve.

**Comment by AlDanial** [comment]
Re: ``return unless "$Dir/" =~ m{$opt_match_d} or $Dir =~ m{$opt_match_d}`` .
Good idea.
