### ISSUE TITLE
Using option --no-recurse the report shows no file.

### ISSUE THREAD

**Issue by paulvirtuel** [AlDanial/cloc#736]
**Describe the bug**
I tried using the --no-recurse option like this:
       cloc-1.96.exe --no-recurse "full path 1" "full path 2"
But I got this below, even though each path contains several .cpp/.h files:
       0 text files.
       0 unique files.                              
       0 files ignored.

**cloc; OS; OS version**
 - cloc-1.96
 - Windows 10

**To Reproduce**
I duplicated my folders and just removed all the sub-folders and still got the problem when adding the option --no-recurse.  Without the option, the lines get counted properly.
Not sure if this is a specific issue with my folder paths.

**Expected result**
Files in the path supplied counted over 100 files, ~100000 lines of code.

**Additional context**
none

**Comment by AlDanial** [comment]
Your issue showed me the ``Win32::LongPath`` module has unexpected behavior for non-recursive directory reads.  A small code tweak was necessary.  Try the attached executable.  First unzip it, then rename the extension from ``.ex`` to ``.exe``.
[cloc-issue-736.ex.zip](https://github.com/AlDanial/cloc/files/12136824/cloc-issue-736.ex.zip)  If it looks like it works I'll push the code change.

**Comment by paulvirtuel** [comment]
Yes, it looks like it works with your new version.Thanks for your tool, and such a fast response!

**Comment by AlDanial** [comment]
Thanks for testing.  Aside from the test exe, the fix won't appear in a formally released exe until the next version of cloc is out (I'm estimating December 2023).
