### ISSUE TITLE
Latest VirusTotal findings - please review and comment - thank you!

### ISSUE THREAD

**Issue by tlinAspenESS** [AlDanial/cloc#739]
**Describe the bug**
From your Windows download link, I found the [VirusTotal page ](https://www.virustotal.com/gui/file/00b1c9dbbfb920dabd374418e1b86d2c24b8cd2b8705aeb956dee910d0d75d45?nocache=1)you reference.  Once there, I clicked "Reanalyze" and it produced the two red flags you'll find therein.  

**cloc; OS; OS version**
 - cloc version:  1.96/1.96.1 (Windows)
 - If running the cloc source, Perl version:  N/A
 - OS (eg Linux, Windows, macOS, etc):  N/A
 - OS version:  N/A

**To Reproduce**
Link provided above for analysis and consideration.

**Expected result**
Zero detections....hopefully :-).

**Additional context**
I'm a big fan of CLOC....thank you for maintaining it.  It's been years since I frequently leveraged it but find myself, once again, in need of its capabilities.  Cheers!

**Comment by AlDanial** [comment]
In a perfect world no one would use the .exe and instead run the Perl source directly (requires a Perl installation like Strawberry Perl).  
Beyond that, two possibilities come to mind:
* 2 out of 70 virus detections are false positives
* you could build your own .exe from the Perl source as explained in the docs & then run that through VirusTotal.  My guess is you'll get a similar result.

**Comment by tlinAspenESS** [comment]
I appreciate the feedback.  Perfect World - wouldn't that be nice?  

I ran CLOC tonight multiple times against several source directories, working just fine....closing out the issue I opened.
