### ISSUE TITLE
More detailed output (list each file and its language)

### ISSUE THREAD

**Issue by oorestisime** [AlDanial/cloc#74]
Hello,

Maybe this is already implemented and I just can't find the correct option but I'd like a more detailed output in the sense of having the programming language of each file in addition to the overall summary.
Something like a mapping between path and a programming language.

Unfortunately I don't speak Perl but maybe if you already have this info and it's just a matter of formatting you can point me to the code and try to implement this.

Cheers,

Orestis

**Comment by AlDanial** [comment]
Yes, cloc already has this capability -- provided you're willing to work with output in one of these formats: comma separated values, YAML, XML, JSON, or SQL.  To the detailed output in these fomats use one of

<pre>
  cloc --by-file --csv  dir1 dir2 ..
  cloc --by-file --yaml  dir1 dir2 ..
  cloc --by-file --xml  dir1 dir2 ..
  cloc --by-file --json  dir1 dir2 ..
  cloc --by-file --sql=results.sql  dir1 dir2 ..
</pre>

The last one is only useful if you load the results.sql file into a database engine then query the database.

**Comment by oorestisime** [comment]
Ah wonderful i missed that!
Thanks a lot :)
