### ISSUE TITLE
some labeling issue with the 1.96.1 release

### ISSUE THREAD

**Issue by chenrui333** [AlDanial/cloc#742]
👋 it looks like 1.96.1 release did not get marked as latest release (just labeling issue), raise this issue for some awareness, thanks!

![image](https://github.com/AlDanial/cloc/assets/1580956/306addb5-c4ac-4c25-98cf-631622c999c8)

relates to https://github.com/Homebrew/homebrew-core/pull/138312

**Comment by osalbahr** [comment]
Interesting. I’ve not seen something like this before.

**Comment by AlDanial** [comment]
I hope to release 1.98 within the month and that will resolve this.

**Comment by AlDanial** [comment]
v1.98 is now the latest release
