### ISSUE TITLE
Add support for counting directly from Github/Bitbucket etc.

### ISSUE THREAD

**Issue by prathamcoral** [AlDanial/cloc#743]
When I try to run : "cloc https://github.com/username/somerepo" for counting the lines of code from a public repo, this gives an error. I have checked the examples in the README as well where first the repo is wither downloaded or cloned and then cloc is used with it. 
Please add support for directly counting from the github repo.

**Comment by AlDanial** [comment]
Sorry, I have no plans to support this.
