### ISSUE TITLE
Add support from counting directly from Github/Bitbucket etc's repos.

### ISSUE THREAD

**Issue by prathamjagga** [AlDanial/cloc#744]
When I try to run : "cloc https://github.com/username/somerepo" for counting the lines of code from a public repo, this gives an error. I have checked the examples in the README as well where first the repo is wither downloaded or cloned and then cloc is used with it.
Please add support for directly counting from the github repo.

**Comment by AlDanial** [comment]
Sorry, I have no plans to support this.

**Comment by prathamjagga** [comment]
Okay, can you tell me the reason for this @AlDanial.
Thanks.

**Comment by AlDanial** [comment]
I'm reconsidering my position.  I'll update here if I have a change of heart.
