### ISSUE TITLE
Add language support for Typst

### ISSUE THREAD

**Issue by TheLukeGuy** [AlDanial/cloc#746]
This is a request for language support for [Typst](https://typst.app).

- language name: Typst
- file extension(s): `.typ`
- method(s) of commenting text:
    - Single-line comments start with `//`
    - Multi-line comments start with `/*` and end with `*/`
- location of sample code:
    - [The comment compiler test](https://github.com/typst/typst/blob/main/tests/typ/compiler/comment.typ)
    - [A random library with both comment types](https://github.com/tudborg/notes.typ/blob/main/notes.typ)
    - [A longer compiler test](https://github.com/typst/typst/blob/main/tests/typ/compute/construct.typ)

Thanks! :)

**Comment by LingkKang** [comment]
I just thought about it last night!

But I found that `typ` is not an exclusive extension for Typst. GitHub Linguist have some discussion on it: https://github.com/github-linguist/linguist/issues/6358#issuecomment-1493706282 and they finally use some pattern matching like `pattern: '^#(import|show|let|set)'` to tell the file type. 

I'm not sure is this applicable to `cloc`.

**Comment by LingkKang** [comment]
As a temporary workaround, put the following cloc definition under a text file such as `typst-def.txt`

``` txt
Typst
    filter rm_comments_in_strings " /* */
    filter rm_comments_in_strings " // 
    filter call_regexp_common C++
    extension typ
    3rd_gen_scale 1.00
```

And instruct `cloc` to recognise Typst locally:

``` sh
cloc --read-lang-def=typst-def.txt .
```

The result should be fine with Typst.
