### ISSUE TITLE
`--include-ext=csv` counts only first file

### ISSUE THREAD

**Issue by gitmalong** [AlDanial/cloc#748]
**Describe the bug**
A concise description of the problem you found with cloc.

**cloc; OS; OS version**
 - cloc version: 1.96
 - OS (eg Linux, Windows, macOS, etc): macOS 
 - OS version: Ventura 13.5

**To Reproduce**
Put several csv files into folder.

```bash
cloc . --include-ext=csv
       2 text files.
       2 unique files.                              
       4 files ignored.

github.com/AlDanial/cloc v 1.96  T=0.02 s (111.8 files/s, 304965.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSV                              2              0              0           5454
-------------------------------------------------------------------------------
SUM:                             2              0              0           5454
```

```bash
ls .                    
2020-12-30 0:00:00.0 +01:00:00-2022-01-01 0:00:00.0 +01:00:00-abc.csv
2020-12-30 0:00:00.0 +01:00:00-2022-01-01 0:00:00.0 +01:00:00-def.csv
2020-12-30 0:00:00.0 +01:00:00-2022-01-01 0:00:00.0 +01:00:00-ghi.csv
2020-12-30 0:00:00.0 +01:00:00-2022-01-01 0:00:00.0 +01:00:00-jkl.csv
2020-12-30 0:00:00.0 +01:00:00-2022-01-01 0:00:00.0 +01:00:00-mno.csv
```

My file names are actually like this:
`2020-12-30 0/00/00.0 +01/00/00-2022-01-01 0/00/00.0 +01/00/00-abc.csv`

Maybe the `/` is causing the issue.

**Expected result**
Each csv file to be not ignored.

**Additional context**

**Comment by AlDanial** [comment]
I can't duplicate this problem.  Are your files unique?  Try running with the ``--skip-uniqueness`` switch to suppress cloc's logic to skip duplicate files.

**Comment by AlDanial** [comment]
Reopen if you can provide a file set that reproduces this problem.
