### ISSUE TITLE
Extract comments from files (reverse of --strip-comments)

### ISSUE THREAD

**Issue by tillheilmann** [AlDanial/cloc#750]
Thanks for this great tool! I have found no good way to get only (and all) the lines containing comments from input source code files. What I am looking for is, so to speak, the reverse of the --strip-comments option. I have tried to produce comments from a diff between original and stripped source code file but failed. I am, as you probably suspect, not very good at this. ;-)

**Comment by AlDanial** [comment]
Give b05640c a try, see if `--strip-code` works.

**Comment by tillheilmann** [comment]
Yes, it works. That's great! And many thanks for the swift response. (Now, `cloc` doesn't correctly recognize all comments in older Pascal source, but that's another story.)
