### ISSUE TITLE
Add foreign key to t table to relate to the metadata table.

### ISSUE THREAD

**Issue by MaxMacleod** [AlDanial/cloc#761]
Dear Al,
firstly, thanks for a very useful and rock solid tool! cloc is fantastic!

Please, if I could request a feature enhancement that would make it even better.

Running multiple times with `—sql-append `inserts one row into `metadata`, and per file rows into `t`. However, there is - from what I see - no relationship between these tables. For example, running ten times, file `foo.c`  might appear ten times in `t` with varying line counts, unrelated to `metadata.timestamp`.

With a foreign key relating both tables, one would be able to track lines of code changes in files over time.

Thanks and Best Wishes.

**Comment by MaxMacleod** [comment]
```
create table metadata (    
                id        INTEGER PRIMARY KEY,  
                timestamp varchar(500),
                Project   varchar(500),
                elapsed_s real);

create table t (
                id            INTEGER        ,
                Project       varchar(500)   ,
                Language      varchar(500)   ,
                File          varchar(500)   ,
                File_dirname  varchar(500)   ,
                File_basename varchar(500)   ,
                nBlank        integer        ,
                nComment      integer        ,
                nCode         integer        ,
                nScaled       real           ,
    FOREIGN KEY (id)
       REFERENCES metadata (id));
```

**Comment by MaxMacleod** [comment]
Hello Al,
it looks great! 

On SQLite, using the schema above, the id - if omitted on the insert - will be generated based on `rowid`. Having said that, using Unix epoch seconds alleviates the need for vendor specific implementations (SQLite, MySQL, PostgreSQL, Oracle, and Microsoft SQL).

Overall, this is a super nice addition as now it's possible to track metrics over time. 

Thank you!

**Comment by AlDanial** [comment]
cool, thanks for your support

**Comment by rlandolt** [comment]
@AlDanial Now it always is in the file but the description (https://github.com/AlDanial/cloc?tab=readme-ov-file#sql-)

**Comment by AlDanial** [comment]
@rlandolt : thanks for the reminder
