### ISSUE TITLE
How to see the full file names as well as the language types

### ISSUE THREAD

**Issue by huornlmj** [AlDanial/cloc#764]
If I run cloc I get a table of languages, but I want to find the files that are in a particular language group.  E.g., 10 TCL files are found, I want to see the full path to these 10 files.  I read the docs and the help but I couldn't figure out if this functionality is present or not.

**Comment by AlDanial** [comment]
cloc *can* produce filename + language results (except for the full file path; output paths are relative to the location you run cloc from), try for example
<pre>
  cloc --by-file --csv  your_directory
</pre>
but the format isn't neatly aligned in columns.  Ref the discussion for #756, the output gets crowded when including results by filename and language.  A work-around to getting full paths is by providing a fully qualified path as input, ie,
<pre>
  cloc --by-file --csv  /path/to/your/directory
</pre>
See also ``--yaml``, ``--xml``, or ``--json`` as alternate output formats containing filename and language (if running with ``--by-file``).

**Comment by yikengboy** [comment]
Can diff function support displaying file names?

**Comment by AlDanial** [comment]
@yikengboy: yes.  Try, for example,
`cloc --by-file --git --diff HEAD~2 HEAD`

**Comment by yikengboy** [comment]
@AlDanial great!

**Comment by AlDanial** [comment]
@huornlmj try, using the latest dev code,
<pre>
cloc --fmt 3 my_code/
</pre>
to see both the full path and language for each file

**Comment by huornlmj** [comment]
> @huornlmj try, using the latest dev code,
> 
> cloc --fmt 3 my_code/
> to see both the full path and language for each file

Thank you @AlDanial this worked exactly as desired!  Do you know when this will make it into the next release?

**Comment by AlDanial** [comment]
@huornlmj I'm hoping to make the next release within a month.
