### ISSUE TITLE
The result of diff is different from the result of git diff

### ISSUE THREAD

**Issue by yikengboy** [AlDanial/cloc#765]
**Describe the bug**
Comparing the two commitIds with git diff and cloc --git-diff-rel respectively, the results seem to be completely different.

**cloc; OS; Centos
 - cloc version: lastest
 - OS version: Linux

**To Reproduce**
`git diff --shortstat ff2a43717e7f9d2d3966b155912c0c4b9b3009da 18d4f379a1424c4a23995b6e1cf9a1f939b10379`
![image](https://github.com/AlDanial/cloc/assets/76463236/3614cea4-aa1a-48d8-8f6d-5b4a9ef9d98b)

`cloc --git-diff-rel ff2a43717e7f9d2d3966b155912c0c4b9b3009da 18d4f379a1424c4a23995b6e1cf9a1f939b10379 `
![image](https://github.com/AlDanial/cloc/assets/76463236/dab2d86a-d7e4-440b-8ccd-1fbb4939b316)

**Comment by AlDanial** [comment]
Point me to the repo with these commits.  Or, if that's not practical, find a common repo we can both access which demonstrates the problem you have in mind.

**Comment by yikengboy** [comment]
Okay, I'll get a common repo when I have time, thanks for your answer

**Comment by yikengboy** [comment]
Well ! I know it. Because I change file-name in one commit, `git diff` can discern this change.
however, `cloc --git-diff-rel`  will generated two records of increase and decrease!
How can I identify this situation?

**Comment by AlDanial** [comment]
git returns a "similarity index" on with diff `--find-renames` which can identify this situation.  I even have a place-holder option in cloc, currently commented out, called `--git-diff-simindex` to support this capability but I have not implemented it yet. It is tricky.

**Comment by AlDanial** [comment]
It is possible, but as to when, I can't say.  The cleanest thing to do will be close this issue then create a new one specifically requesting this feature, ie, "implement `--git-diff-simindex`".  You're welcome to do that and it will keep my mind on it.
