### ISSUE TITLE
Extraneous comma in JSON output after `n_lines` in header

### ISSUE THREAD

**Issue by jwoytek** [AlDanial/cloc#768]
The header adds a comma after the value for `n_lines` in the JSON report. It then adds a second comma when adding the `report_file`. 

https://github.com/AlDanial/cloc/blob/c3011eb40fd6496593c59667914c2e7675f64356/cloc#L3524

It seems that the referenced line should NOT add a comma, and let the code that is adding `report_file` do that if needed.

PR coming shortly.

**Comment by AlDanial** [comment]
Took a while to figure out what you meant.  I had to study the code to see the extra comma only happens with `--hide-rate`.   Thanks for the fix in any case.
