### ISSUE TITLE
Add new lang(SLIM)

### ISSUE THREAD

**Issue by luanjampa** [AlDanial/cloc#77]
http://slim-lang.com/about.html

**Comment by AlDanial** [comment]
https://github.com/AlDanial/cloc/#AdditionalLanguages

**Comment by AlDanial** [comment]
I'm a bit confused by the three different comment types; should cloc only count code comments or HTML and IE comments too?

**Comment by luanjampa** [comment]
exactly, but I do not know why.

**Comment by AlDanial** [comment]
help me out here... count only code comments, yes/no?

**Comment by luanjampa** [comment]
Just code comments. thanks

**Comment by AlDanial** [comment]
I went to add support for slim today but was unable to determine a way for cloc to identify a file as containing slim code.  The documentation page does not identify a file extension for slim and the git repository's test directory https://github.com/slim-template/slim/tree/master/test just has Ruby files.

How can one tell whether or not a file contains slim code?

**Comment by luanjampa** [comment]
Extension: namefile.html.slim

Example; 

```
<div class="widget-test-holder"></div>
<ul class="widget-test-items">
  - @test.each do |test|
    <li>
      <a href="#{chamada.conteudo_url}">
        - if test.midia and test.midia.add(params[:arg1]).present?
          <img src="#{test.midia.add(params[:arg1])}" alt="#{strip_tags(test.title)}" />
      </a>
    </li>
</ul>

```
I hope it helps

**Comment by AlDanial** [comment]
git commit f50e564 has support for Slim
