### ISSUE TITLE
Include .mts and .mjs files for TS/JS

### ISSUE THREAD

**Issue by hansjhoffman** [AlDanial/cloc#773]
Currently `cloc` doesn't recognize `.mjs` and `.mts` as Javascript and Typescript files respectively. 

**Provide support for:**

 - Javascript:
   - `.mjs` files (ES module of JS)
 - Typescript:
   - `.mts` files (ES module of TS)

**For other enhancements:**
Extend current implementation to include both file extensions

**Comment by AlDanial** [comment]
`.mjs` has been a JavaScript extension in cloc for several years (since release 1.84).

ce69aac adds `.mts` for TypeScript
