### ISSUE TITLE
Need to exclude .o.d file automatically, currently recognized .o.d as .d file

### ISSUE THREAD

**Issue by WanchaoYao** [AlDanial/cloc#775]
**Describe the bug**
A concise description of the problem you found with cloc.

**cloc; OS; OS version**
 - cloc version:1.82
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc):
 - OS version:Linux(Ubuntu 20.04)

**To Reproduce**
```
git clone https://github.com/apache/tvm.git
cd tvm
git submodule update --init --recursive
mkdir build && cd build
cmake .. # build all test and examples
make -j32
cd ..
cloc .
```
![image](https://github.com/AlDanial/cloc/assets/8121751/f8945876-6c5f-4c64-a04f-387013642572)
![image](https://github.com/AlDanial/cloc/assets/8121751/08cc106b-9db4-4a5d-a7d1-b49a83561371)
cloc recoginized .o.d file (cmake object dependency file) as .d file(D language src code file)

**Expected result**
exclude .o.d file automatically

**Additional context**
NA

**Comment by AlDanial** [comment]
thanks for the tip, wasn't aware of this file extension
