### ISSUE TITLE
cloc returns different data on stdout when run with Node exec function on Ubuntu and on Mac

### ISSUE THREAD

**Issue by EnricoPicci** [AlDanial/cloc#778]
I want to run the command cloc --csv ./ within a node app.

The code is pretty straightforward

```
command = 'cloc --csv ./'
exec(command, (error, stdout, stderr) => {
        if (error) {
            // handle error
        }
        if (stderr.length > 0) {
            // handle stderr;
        }
        // do stuff with stdout
    });
```

If I do run this snippet on Ubuntu, the string stored in the stdout variable shows something like this

```
files,language,blank,comment,code,"github.com/AlDanial/cloc v 1.96  T=1.40 s (141.5 files/s 13072.9 lines/s)"
20,TypeScript,100,200,300
5,Markdown,10,20,30
```

But is I do run the same command on a Mac, the stdout variable will contain the following

```
 700 text files.
 700 unique files.                                          
 100 files ignored.

files,language,blank,comment,code,"github.com/AlDanial/cloc v 1.96  T=1.40 s (141.5 files/s 13072.9 lines/s)"
    20,TypeScript,100,200,300
    5,Markdown,10,20,30
```

In other words, on Mac, I get 4 lines more at the beginning of the value returned to stdout.

In both cases, if I run the command from the command line, the terminal will show the same output I get on the Mac, i.e. with the starting lines.

Which is the reason for the different behaviour?

**Comment by AlDanial** [comment]
For whatever reason it seems Ubuntu is able to realize cloc is not being run from a terminal (instead is it called from another program's exec() (, but on Mac it doesn't.

In any event it isn't really that important.

What is important when you call cloc from another program is to also give cloc the `--quiet` switch.  This suppresses the progress update print statements and makes for cleaner and more consistent results.

**Comment by EnricoPicci** [comment]
Thanks for the explanation. I agree it is not a big issue, more of a curiosity.
Thanks

**Comment by EnricoPicci** [comment]
The explanation is clear
