### ISSUE TITLE
Add support for .astro files

### ISSUE THREAD

**Issue by Kostas-Xafis** [AlDanial/cloc#779]
- language name: Astro
 - file extension(s): .astro
 - method(s) of commenting text: A 💩 tone (All 3 HTML, CSS, JS)
 - location of sample code: [sample](https://github.com/Kostas-Xafis/byzantini-website/blob/main/src/pages/anakoinoseis/%5Bslug%5D.astro)

**Comment by AlDanial** [comment]
Are you referring to this Astro https://github.com/astrolang/astro ?

**Comment by Kostas-Xafis** [comment]
No, it's about yet another javascript framework [https://astro.build/](https://astro.build/).
