### ISSUE TITLE
Fortran "include" files incorrectly identified as pascal

### ISSUE THREAD

**Issue by dwmckee** [AlDanial/cloc#781]
**Describe the bug**

Cloc does not know that `.inc` sometimes indicates a Fortran file.

It is not uncommon in Fortran code to see constants and common blocks defined in "include" files that are then included in multiple source files. Such files are often give the `.inc` suffix.

A project I support at work on has a couple dozen such files and six of them are incorrectly identified as pascal. The rest are not ID'ed at all.

**cloc; OS; OS version**

cloc 1.82 (from the OS package manager)
Perl 5.30.0
Linux under WSL1
Ubuntu 20.04 LTS

**To Reproduce**
1. Copy to a local file named `consts.inc` 
```fortran
c ----------------------------------------------------------------------
c                              CONSTS.H
c
c DESCRIPTION ----------------------------------------------------------
c
c    Physical and numerical constants
c
c USED BY --------------------------------------------------------------
c
c    hits
c    readcomp
c    setspar
c    solode2
c    rolling
c    initlz
c    csubl
c    netflx
c    emits
c    xqstar
c    chemrx
c    funca
c
c GLOSSARY -------------------------------------------------------------
c
c Parameter   Defintion
c --------    ---------
c  Boltz      Stefan-Boltzmann constant = 5.6696E-12 W/cm**2/K**4
c  R          universal gas constant = 8.314 J/K/mole
c  Pi         ratio of circumference of circle to diameter
c
c ----------------------------------------------------------------------

      Real      Boltz, R, Pi

      PARAMETER (Boltz = 5.6696E-12, R = 8.314, Pi = 3.141592654)
```
2. Run cloc on the file

**Expected result**
Ideally, ID'ed as Fortran. Certainly not ID'ed as pascal.

**Additional context**
Low priority. This is not hard to overcome locally, but having been an active Fortran programmer at one point it seemed weird to me.

Also, it's amusing that the top of file comment gives the name with a .H ending, but that's legacy code for 'ya.

**Comment by AlDanial** [comment]
Give cfa784d a try.
