### ISSUE TITLE
Master Archive 

### ISSUE THREAD

**Issue by hrieke** [AlDanial/cloc#783]
Something small went wrong somewhere.
Downloaded and installed cloc using the following commands (Linux):

```
cd ~/temp/
curl -O -J -L https://github.com/AlDanial/cloc/archive/master.zip
unzip cloc-master.zip
cd cloc-master
cloc --version
1.95
```

It appears that the (master) archive has not been updated.

**Comment by hrieke** [comment]
Just did the following:

```
curl -O -J -L https://github.com/AlDanial/cloc/archive/refs/tags/v1.98.zip
unzip cloc-1.98.zip
cd cloc-1.98
cloc --version
1.95
```

Of course. 😃

**Comment by AlDanial** [comment]
What's your output for `which cloc` ?  I suspect you're picking up a version elsewhere in your path.  If you repeat the commands above with `./cloc` instead of just `cloc` I suspect your version number will change.  Here's what I get:

<pre>
> curl -O -J -L https://github.com/AlDanial/cloc/archive/master.zip
> unzip -d . cloc-master.zip cloc-master/cloc
> ./cloc-master/cloc --version
1.99

> curl -O -J -L https://github.com/AlDanial/cloc/archive/refs/tags/v1.98.zip
> unzip -d . cloc-1.98.zip
> cd cloc-1.98
> ./cloc --version
1.98
</pre>

**Comment by hrieke** [comment]
I'd blame it on insomnia, but, yeah, the problem was between the chair and the keyboard.
