### ISSUE TITLE
--exclude-list-file not working on directory name containing parentheses or brackets

### ISSUE THREAD

**Issue by microdou** [AlDanial/cloc#785]
**Describe the bug**
The `--exclude-list-file` option does not exclude the directory containing a pair of parentheses `(dir)` or brackets `[dir]`.

**cloc; OS; OS version**
 - cloc version: 1.90
 - If running the cloc source, Perl version: -
 - OS (eg Linux, Windows, macOS, etc): Ubuntu
 - OS version: 22.04

**To Reproduce**

Example code base structure:
```
❯ tree -a
.
├── (dir)
│   └── test.svelte
└── .cloc-ignore

4 directories, 3 files
```

ignore file content:

```
❯ cat .cloc-ignore
(dir)/
```

execution result
```
cloc --exclude-list-file=".cloc-ignore" .
       2 text files.
       2 unique files.                              
       1 file ignored.

github.com/AlDanial/cloc v 1.90  T=0.00 s (268.0 files/s, 14737.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Svelte                           1              9              0             46
-------------------------------------------------------------------------------
```

**Expected result**
files under `(dir)` directory should be ignored as specified in .cloc-ignore.

**Additional context**
1. When there are no parentheses on directory name, cloc ignore work as expected.
2. When parentheses are on a file name (even when the parentheses are coded in the ignore file), cloc ignore work as expected.
3. In addition to Ubuntu cloc 1.90, I tested the released .pl version 1.98 and the latest commit https://github.com/AlDanial/cloc/commit/dc4a3c5a32df38d1d7d3d38578bc8d8ecd281797. None works.
4. SvelteKit uses directories named with parentheses/brackets for advanced routing. https://kit.svelte.dev/docs/advanced-routing

**Comment by AlDanial** [comment]
try 888d24c

**Comment by microdou** [comment]
@AlDanial Works brilliantly! Thanks for the super fast fix! 🎉
