### ISSUE TITLE
Bug Suggested by Github

### ISSUE THREAD

**Issue by Gmonga08** [AlDanial/cloc#788]
We can make this file [beautiful and searchable](https://docs.github.com/articles/rendering-csv-and-tsv-data) if this error is corrected: It looks like row 2 should actually have 2 columns, instead of 1. in line 1.

Above is Suggested by Github Itself when I created CSV file for stats and and pushed it to github

**Comment by AlDanial** [comment]
Post the CSV file in question.  The error doesn't make sense to me because the 2nd row of output has multiple columns--5 for a straight count and 17 for a diff.

**Comment by Gmonga08** [comment]
[lang_stats.csv](https://github.com/AlDanial/cloc/files/13349282/lang_stats.csv)
Here is the CSV file

**Comment by AlDanial** [comment]
That's not a CSV file.  If you want CSV output from cloc you need to pass it the `--csv` switch.
