### ISSUE TITLE
How to exclude a given filename no matter its location?

### ISSUE THREAD

**Issue by stefanobartoletti** [AlDanial/cloc#793]
I'm having an issue when trying to exclude a given filename from my line counts.

The file is `pnpm-lock.yaml`, and it is the `pnpm` equivalent of  `package.lock` for `npm` and `yarn.lock` for `yarn`.

As far as I can see, the lockfiles for `npm` and `yarn` are not counted (maybe because of their `.lock` extension?), but for `pnpm` I have to manually set this exclusion.

This is my configuration:

```cfg
# /home/stefano/.config/cloc/options.txt
vcs=git
v 
exclude-list-file /home/stefano/.config/cloc/exclude.txt
```

```cfg
# /home/stefano/.config/cloc/exclude.txt
pnpm-lock.yaml
```

The problem is that when  I use an exclusion file, its entries are evaluated for their relative path, so the files have to be in the same directory where I invoke `cloc`. This is not always the case, as sometimes I can have the lockfile in a subdirectory, or I may want to invoke `cloc` from another location (i.e. `cloc path/to/my/project`)

I need the ability to exclude a given name no matter its location, ideally something that works like `exclude-ext` but that do not consider only the file extensions but its full name (or, maybe, a regex)

Is it possible to do this with the current version of `cloc`?

**Comment by AlDanial** [comment]
Yes, this is possible with `--not-match-f` which uses a regular expression to exclude filenames.  In your case the regular expression just needs to be the filename itself.  Try
<pre>
cloc --not-match-f pnpm-lock.yaml  path/to/project
</pre>

**Comment by stefanobartoletti** [comment]
Thanks! I somehow missed it even by reading the docs, I searched for "exclude" :)
