### ISSUE TITLE
Request multiple outputs

### ISSUE THREAD

**Issue by PMExtra** [AlDanial/cloc#794]
**For other enhancements:**

In my case, I run cloc in CI pipelines. I have to save a JSON report for other QA pipeline usage. But I also want a human-readable output that prints to stdout in CI logs.

So, I request cloc to support multiple outputs simultaneously.

**Comment by AlDanial** [comment]
Try
<pre>
cloc --out results.json --fmt -1 my_code/
</pre>
or other values for ``--fmt`` -2 .. -5
