### ISSUE TITLE
Markdown output should be supported.

### ISSUE THREAD

**Issue by jolkdarr** [AlDanial/cloc#8]
Option allowing Markdown output should be provided.
For instance: --md

**Comment by AlDanial** [comment]
Good idea.  I'll do --rst too.

**Comment by zbeekman** [comment]
:+1:

**Comment by AlDanial** [comment]
git commit 80754af adds --md (it was mostly implemented already but I got side-tracked), please open a new issue if you discover problems with the output format.  I used https://www.npmjs.com/package/markdown-to-html to check the outputs.
