### ISSUE TITLE
undefined value

### ISSUE THREAD

**Issue by sakra** [AlDanial/cloc#80]
I am using a custom language definition file with the following language added to a definition file exported with `--write-lang-def`:

```
Mathematica
    filter call_regexp_common Pascal
    extension m
    extension mt
    3rd_gen_scale 4.00
    end_of_line_continuation \\$
```

Upon using the definition file on a code base, cloc 1.66 raises the following error:

```
$ cloc --force-lang-def=/path/to/my_definitions.txt .
    3505 text files.
    3486 unique files.                                          
Can't use an undefined value as an ARRAY reference at /usr/local/bin/cloc line 1631.
```
Running cloc 1.66 without the custom definition file does not result in the error.

**Comment by AlDanial** [comment]
The <code>.m</code> extension is problematic in that it maps to many languages:  matlab, mumps, Objective C for starters.  Such conflicts are resolved in cloc with dedicated subroutines that attempt to identify the language from text within the files.  Unfortunately this complication hasn't yet made it to the external language definition reader & writer.

I can build support for Mathematica into cloc itself if you provide some heuristics as to how to identify Mathematica source to distinguish it from matlab, mumps, Objective C and mercury.  See the subroutine <code>matlab_or_objective_C()</code> in the cloc source for ideas.  May be a couple of weeks before I get around to this though.

**Comment by sakra** [comment]
Possible heuristics for detecting Mathematica code:

 * has Pascal style (* ... *) comments
 * contains the string `BeginPackage`.

**Comment by AlDanial** [comment]
git commit af1a630 adds support for Mathematica.  Please test it and report back.  The logic to distinguish between the five languages that end with <code>.m</code> is pretty hairy now.

**Comment by sakra** [comment]
af1a630 has detected all .m files correctly as Mathematica code. There are also some MATLAB files in the project which have beed detected correctly as well.

One further addition would be nice. Mathematica code may also uses the extensions `.wl` (aka Wolfram language) and `.mt` and `.wlt` (for Mathematica unit test files).

**Comment by AlDanial** [comment]
3c72897 adds the three extensions.  Please close this issue if you're satisfied with the Mathematica implementation.

**Comment by sakra** [comment]
Works for new extensions now. Thanks!
