### ISSUE TITLE
Trying to ignore the C# generated files using --no-autogen but its not working

### ISSUE THREAD

**Issue by maggi0207** [AlDanial/cloc#803]
**Describe the bug**
Trying to ignore the C# generated files using --no-autogen but its not working

**cloc; OS; OS version**
 - cloc version: 1.98v
 - OS (eg Linux, Windows, macOS, etc): Windows
 - OS version: 11

**To Reproduce**
Using below command
cloc.exe  --no-autogen M:\test\BuildTools\NewUser

**Expected result**
should ignore c# generated files

**Additional context**

**Comment by maggi0207** [comment]
@AlDanial  can you please address it

**Comment by AlDanial** [comment]
"should ignore c# generated files" ... what are these files exactly?  what are their names and/or file extensions?

**Comment by AlDanial** [comment]
Reopen once you can provide a list of files to ignore.
