### ISSUE TITLE
Wrong comment results for Java

### ISSUE THREAD

**Issue by PavelTurk** [AlDanial/cloc#804]
**Describe the bug**
Cloc doesn't count comment lines in Java correctly.

**cloc; OS; OS version**
 - cloc version: 1.98
 - If running the cloc source, Perl version: This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi
 - OS (eg Linux, Windows, macOS, etc): Linux
 - OS version: Ubuntu 20.04.3 LTS

**To Reproduce**
This is a piece from H2 Trace class:

```
    public void infoSQL(String sql, String params, long count, long time) {
        if (!isEnabled(TraceSystem.INFO)) {
            return;
        }
        StringBuilder buff = new StringBuilder(sql.length() + params.length() + 20);
        buff.append(lineSeparator).append("/*SQL");
        boolean space = false;
        if (params.length() > 0) {
            // This looks like a bug, but it is intentional:
            // If there are no parameters, the SQL statement is
            // the rest of the line. If there are parameters, they
            // are appended at the end of the line. Knowing the size
            // of the statement simplifies separating the SQL statement
            // from the parameters (no need to parse).
            space = true;
            buff.append(" l:").append(sql.length());
        }
        if (count > 0) {
            space = true;
            buff.append(" #:").append(count);
        }
        if (time > 0) {
            space = true;
            buff.append(" t:").append(time);
        }
        if (!space) {
            buff.append(' ');
        }
        buff.append("*/");
        StringUtils.javaEncode(sql, buff, false);
        StringUtils.javaEncode(params, buff, false);
        buff.append(';');
        sql = buff.toString();
        traceWriter.write(TraceSystem.INFO, module, sql, null);
    }

    /**
     * Write Java source code with trace level DEBUG to the trace system.
     *
     * @param java the source code
     */
```
Save this piece and run cloc. It will give the following result:

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                             1              4             34              6
-------------------------------------------------------------------------------
```
As you see the count of comment lines (and code lines) is wrong. What confuses cloc is this line `buff.append(lineSeparator).append("/*SQL");`

**Expected result**
Correct count of comment lines is 11.

**Additional context**

**Comment by AlDanial** [comment]
with the fix you'll see
<pre>
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                             1              1             11             29
-------------------------------------------------------------------------------
</pre>
