### ISSUE TITLE
Add support of Java text blocks

### ISSUE THREAD

**Issue by PavelTurk** [AlDanial/cloc#805]
**For other enhancements:**
Since Java 15, text blocks are available as a standard feature. Text blocks is a feature to declare multi-line strings most efficiently using three double quotes `"""`. For details see https://www.baeldung.com/java-text-blocks 

An example of text block:
```
public String getBlockOfHtml() {
    return """
            <html>
              /* 
               * NOT comment
               */
                <body>
                    <span>example text</span>
                </body>
            </html>
            """;
    }
```
So, when cloc sees text blocks it mustn't  count comments in it.

**Comment by AlDanial** [comment]
I can't reproduce on Ubuntu 22.04.  My result:
<pre>
/tmp/jetty.project [jetty-12.0.x] » cloc .          
    7733 text files.
    6516 unique files.                                          
    1728 files ignored.

github.com/AlDanial/cloc v 1.99  T=5.89 s (1107.0 files/s, 209867.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                          4743         117650         152935         685997
JSON                            36              0              0         131654
Maven                          470           1849            611          39937
Text                           128            998              0          30552
AsciiDoc                       308           7798           3971          22575
XML                            473           1893           3890          16595
SVG                              8             11             16           4332
HTML                            67            254             29           2240
JavaScript                       5             61             36           1140
Bourne Shell                     8            155            198            742
DTD                              8            397           1079            608
PlantUML                         8             72              1            507
Groovy                          39            144            375            491
Properties                     143             14            639            452
CSS                             11             76             28            440
JSP                             27             55              0            395
YAML                             8             27             40            375
Markdown                        11            126              4            320
XSD                              1             23              0            264
XSLT                             2             16              0            114
SQL                              2              8              0             40
INI                              9              5              0             25
Protocol Buffers                 1              3              0             16
-------------------------------------------------------------------------------
SUM:                          6516         131635         163852         939811
-------------------------------------------------------------------------------


/tmp/jetty.project [jetty-12.0.x] » cloc ./jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/compression/Huffman.java
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.99  T=0.86 s (1.2 files/s, 411.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                             1             13             17            322
-------------------------------------------------------------------------------
</pre>

**Comment by AlDanial** [comment]
Try running with `--timeout 2` (for 2 seconds max, per file) or a higher value if necessary.  You can completely disable timeouts with a value of 0.
