### ISSUE TITLE
Cloc doesn't count  XML file

### ISSUE THREAD

**Issue by PavelTurk** [AlDanial/cloc#808]
**Describe the bug**
Cloc doesn't count  XML file

**cloc; OS; OS version**
- cloc version: 1.99
- If running the cloc source, Perl version: v5.30.0 built for x86_64-linux-gnu-thread-multi
- OS (eg Linux, Windows, macOS, etc): Linux
- OS version: Ubuntu 20.04.3 LTS

**To Reproduce**
[This](https://gitlab.com/graphviz/graphviz/-/blob/9.0.0/windows/build/graphviz.wxs.in?ref_type=tags) is a XML file from graphviz project . Download it and try to count. Cloc will ignore this file.

**Expected result**
Cloc shoul count this file

**Additional context**

**Comment by AlDanial** [comment]
Not a bug.  Files with the `.in` file extension are explicitly ignored by cloc.

You can force the count with `cloc --force-lang XML graphviz.wxs.in`
