### ISSUE TITLE
Cloc doesn't support <![CDATA[ .... ]]]]><![CDATA[> ...]]>  in XML

### ISSUE THREAD

**Issue by PavelTurk** [AlDanial/cloc#810]
**Describe the bug**
Cloc doesn't support  `<![CDATA[ .... ]]]]><![CDATA[> ...]]>`  in XML . See https://stackoverflow.com/a/223782/5057736

**cloc; OS; OS version**
 - cloc version:
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc):
 - OS version:

**To Reproduce**
```
<![CDATA[Certain tokens like ]]]]><![CDATA[> 
<!-- COMMENT -->
]]>
```
```
github.com/AlDanial/cloc v 1.99  T=0.01 s (114.0 files/s, 342.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              1              2
-------------------------------------------------------------------------------

```
**Expected result**
3 lines of code, 0 of comment

**Comment by AlDanial** [comment]
Unraveling `CDATA` might appear in a future release but for now I'm listing it as a limitation.
