### ISSUE TITLE
Cloc counts line where comment starts as comment in XML

### ISSUE THREAD

**Issue by PavelTurk** [AlDanial/cloc#811]
**Describe the bug**
Cloc counts line where comment starts as comment in XML

**cloc; OS; OS version**
 - cloc version:
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc):
 - OS version:

**To Reproduce**
```
<?xml version="1.0" encoding="UTF-8"?>
<foo>
    <bar/><!-- bar 
            is not 
            foo -->
</foo>

github.com/AlDanial/cloc v 1.99  T=0.01 s (139.1 files/s, 834.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              3              3
-------------------------------------------------------------------------------
```

**Expected result**
4 comment and 2 code

**Additional context**
Yes, I know that cloc doesn't provide exact results, but this comment style is rather popular. For example, see
https://github.com/usnistgov/metaschema-xslt/blob/2515000d028af35183ecda8f4c55cd42f1adf09d/src/metapath/REx/metapath01.xslt#L637 
or
https://github.com/usnistgov/metaschema-xslt/blob/2515000d028af35183ecda8f4c55cd42f1adf09d/src/metapath/REx/metapath01.xslt#L772

So in all cases users will have wrong results.

**Comment by AlDanial** [comment]
Thanks for reporting this bug, b2a3851 gives 
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              2              4
-------------------------------------------------------------------------------
```
