### ISSUE TITLE
exe version of cloc not support file name with chinese character

### ISSUE THREAD

**Issue by tzleon** [AlDanial/cloc#813]
**Describe the bug**
when execute command:
`cloc-2.00.exe "d:\code\example\通讯录.c" --quiet --xml`
I get result:
```
1 error:
Unable to read:  d:\code\example\通讯录.c
<?xml version="1.0" encoding="UTF-8"?><results/>
```
But when I execute command:
`perl cloc-2.00.pl "d:\code\example\通讯录.c" --quiet --xml `
the result is fine

**cloc; OS; OS version**
 - 2.0
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc): Windows
 - OS version: windows 11 23H2

**To Reproduce**
execute command:
`cloc-2.00.exe "d:\code\example\通讯录.c" --quiet --xml`
I get result:
```
1 error:
Unable to read:  d:\code\example\通讯录.c
<?xml version="1.0" encoding="UTF-8"?><results/>
```

**Expected result**
return correct result

**Additional context**
no

**Comment by AlDanial** [comment]
I doubt I'll be able to fix this.  Evidently the [pp](https://metacpan.org/pod/PAR::Packer) utility which I use to create the `.exe` changes the behavior of Perl's file open command.  Still, two things to try:
1. run `cloc-2.00.exe -v 5 "d:\code\example\通讯录.c" ` and post the output
2. create an empty directory, copy the `.c` file there, then run cloc against the directory

**Comment by AlDanial** [comment]
This is beyond my ability to fix.

**Comment by xz0620** [comment]
> This is beyond my ability to fix.

but version 1.96 doesn't have this issue

**Comment by AlDanial** [comment]
I reinstalled Perl on my Windows machine between 1.96 and 2.00 releases. The `pp` utility or any of its dependencies may have changed enough to cause the problem.

I'd still like to see the output from the command I mentioned on Feb 24 (as well as the output from the source version of cloc).

**Comment by cccyyyyy** [comment]
1.96 OK
1.96.1 not OK
