### ISSUE TITLE
Language support for Luau .luau

### ISSUE THREAD

**Issue by Jerse1** [AlDanial/cloc#814]
**If you want an unsupported language added, provide:**
 - language name: Luau
 - file extension(s): .lua, .luau
 - method(s) of commenting text: The same as Lua 5.1, since it's backward-compatible.
-- comment here
--[[
comment here
 ]]
 - location of sample code:
https://github.com/dphfox/Fusion
**For other enhancements:**
Give a concise description of what you want cloc to be able to do.
https://luau-lang.org/

**Comment by AlDanial** [comment]
Can't use `.lua` as an extension for Luau since it already maps to Lua (and I don't know of a way to tell whether a `.lua` file contains Lua or Luau).
