### ISSUE TITLE
Cloc has problems with */* in Go

### ISSUE THREAD

**Issue by PavelTurk** [AlDanial/cloc#816]
**Describe the bug**
Cloc doesn't count correctly when there are `*/*` in code.

**cloc; OS; OS version**
 - cloc version:
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc):
 - OS version:

**To Reproduce**
This is a modified piece of Go code from kubernetes:

```
func TestNewRequestSetsAccept(t *testing.T) {
	if r.headers.Get("Accept") != "application/other, */*" {
		t.Errorf("unexpected headers: %#v", r.headers)
	}
}

func clientForFunc(fn clientFunc) *http.Client {
	return &http.Client{
		Transport: fn,
	}
}

func TestRequestSetsHeaders(t *testing.T) {
	server := clientForFunc(func(req *http.Request) (*http.Response, error) {
		if req.Header.Get("Accept") != "application/other, */*" {
			t.Errorf("unexpected headers: %#v", req.Header)
		}
	})
}
```
save it to test.go and run cloc. Here is the result:
```
github.com/AlDanial/cloc v 1.99  T=0.01 s (121.2 files/s, 2544.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                               1              4             11              6
-------------------------------------------------------------------------------
```

**Expected result**
There are no comments in that code

**Additional context**

**Comment by AlDanial** [comment]
`cloc --strip-str-comments test.go` gives
<pre>
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                               1              2              0             17
-------------------------------------------------------------------------------
</pre>

You'll probably always want to use `--strip-str-comments` when dealing with codebases that use combinations of `*` and `/` even though this will give cloc a small performance hit.

**Comment by AlDanial** [comment]
With 84d7457, this code
<pre>
foo: = "*/*"
a: = 10
b: = 20
foo: = "*/*"

/*
 a comment
 */

foo: = `*/*`
a: = 10
b: = 20
foo: = `*/*`
</pre>

counted with `cloc --strip-str-comments` yields this count:

<pre>
------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                               1              2              3              8
-------------------------------------------------------------------------------
</pre>
