### ISSUE TITLE
Add Modelica language

### ISSUE THREAD

**Issue by hkiel** [AlDanial/cloc#819]
- language name: **Modelica** / MetaModelica
 - file extension(s): `.mo`
 - method(s) of commenting text: C++/Java-style: `// ...` till line-end and `/* ... */` multiline. There are also String `"..."` comments.
    See https://specification.modelica.org/v3.4/A2.html
 - location of sample code:
Modelica (Modelling language): https://github.com/casella/ScalableTestSuite
MetaModelica (Programming language): https://github.com/OpenModelica/OpenModelica/tree/master/OMCompiler/Compiler

**Comment by hkiel** [comment]
Thanks for the quick reply and implementation!

I forgot to mention that anything inside `annotation()` is considered to be comment as well. This is the place for "official" documentation of the model and for graphical annotations used by graphical modelling tools.

**Comment by AlDanial** [comment]
Text in `annotation()` can be treated as comments if cloc uses `annotation(` as the "start of comment" marker and `)` as the "end of comment marker."  However this means matching will fail on the first `)` within the comment text.  Doing this rigorously means applying string parsing rules to see if the `)` is protected by a `\` or embedded in single or double quotes.  That's a bit than I want to commit to this language.  I can either leave the Modelica counter as-is or add the likely-to-be-wrong version that stops counting comments at the first `)`.   I'm always happy to consider a PR for a robust implementation.

**Comment by hkiel** [comment]
I guess that any substructure inside `annotation()` is not considered as extra code lines, so that there is merely an off-by -one error in loc for each model. I would then leave the current implementation untouched.

I would count by hand 8 lines of code (1, 2, 3, 4, 6, 7, 8 and 33) for the following example code from Modelica Standard Library.
Maybe equation as a "section prefix" is not detected as a line of code for it's own.

```modelica
1 within Modelica.Electrical.Analog.Basic;
2 model Capacitor "Ideal linear electrical capacitor"
3   extends Interfaces.OnePort(v(start=0));
4   parameter SI.Capacitance C(start=1) "Capacitance";
5
6 equation
7   i = C*der(v);
8   annotation (
9     Documentation(info="<html>
10 <p>The linear capacitor connects the branch voltage <em>v</em> with the branch current <em>i</em> by <em>i = C * dv/dt</em>. The Capacitance <em>C</em> is allowed to be positive or zero.</p>
11
12 </html>",
13         revisions="<html>
14 <ul>
15 <li><em> 1998   </em>
16        by Christoph Clauss<br> initially implemented<br>
17        </li>
18 </ul>
19 </html>"),
20     Icon(coordinateSystem(preserveAspectRatio=true, extent={{-100,-100},{100,
21             100}}), graphics={
22         Line(points={{-6,28},{-6,-28}}, color={0,0,255}),
23         Line(points={{6,28},{6,-28}}, color={0,0,255}),
24         Line(points={{-90,0},{-6,0}}, color={0,0,255}),
25          Line(points={{6,0},{90,0}}, color={0,0,255}),
26         Text(
27           extent={{-150,-40},{150,-80}},
28           textString="C=%C"),
29         Text(
30           extent={{-150,90},{150,50}},
31           textString="%name",
32           textColor={0,0,255})}));
33 end Capacitor;
```
