### ISSUE TITLE
--fullpath does not work with --vcs=git

### ISSUE THREAD

**Issue by luxaritas** [AlDanial/cloc#822]
**Describe the bug**
When specifying --vcs=git, running cloc with and without --fullpath does not change its behavior as intended

**cloc; OS; OS version**
 - cloc version: 2.00
 - OS (eg Linux, Windows, macOS, etc): Manjaro Linux
 - OS version: 23.1.3

**To Reproduce**
Create a file structure like:
```
a/
  b.csv
```
and initialize it as a git repository.

Run `cloc . --fullpath --not-match-f "^b.csv"` and compare it to `cloc --vcs git --fullpath --not-match-f "^b.csv"`

**Expected result**
Both commands should result to the same thing - b.csv should be included. Instead, when specifying `--vcs git, `b.csv` is ignored

**Comment by luxaritas** [comment]
I think there are actually two issues I've encountered here:
1) There is handling for fullpath for not-match-d (https://github.com/AlDanial/cloc/blob/61817f54228d461845e41ce94605c9eee170b2a1/cloc#L5807) that is missing for the following block that handles not-match-f
2) The logic here (in `invoke_generator`, right now only implemented for not-match-d) falls through to the basename case if a match against the full path is not found. This is not the same behavior as in the non-vcs case (as implemented in `files`

I can submit a patch for this if my understanding here is correct!

**Comment by luxaritas** [comment]
The prior issue appears to have been introduced in b79313598a83e0142590fe135c3cd293c4532a35, and the latter in c4da737ac3f90687100882f82ce773c27f14e859

**Comment by AlDanial** [comment]
Thanks for starting the troubleshooting work.  Will be a few days before I can dive in.

**Comment by luxaritas** [comment]
I've gone ahead and submitted a PR, let me know if anything looks off!
