### ISSUE TITLE
Possible inconsistent counting of "same" lines

### ISSUE THREAD

**Issue by capSAR273** [AlDanial/cloc#826]
Hello, I am running into some inconsistency between versions of cloc and I was hoping you could help me understand what is going on. I am required to use a certain older version of cloc (1.77) but this version does not support .txt (support was added in 1.94). However, when I try to use the latest version of cloc to diff two folders with a mix of .cpp/.txt, it is reporting far more changed lines than what is actually being changed. For example, one .cpp file has 3 lines added and 3 lines modified according to 1.77, but on the 2.00 report it is counting every line in the new file's version as added and every line in the old version as removed. This results in a SLOC of hundreds, which is not correct. It seems like the latest cloc is having trouble recognizing "same" lines, but I am not sure if this is because of a mistake I've made or if I am missing an argument. All files are using Unix line endings. Thank you for your time, any help is greatly appreciated!

**Comment by AlDanial** [comment]
Can you post a pair of files that exhibit this problem?

**Comment by capSAR273** [comment]
I cannot due to the nature of the work, but I can say that they were fairly standard .cpp files with only about 100 lines of new/modified code between versions, but the latest cloc was counting the entire file as new code. This happened to multiple cpp file pairs. I wish I could provide more detail, I realize it is tough to debug without examples. Could there be any change from 1.77 to 2.00 with how C++ language is handled?

**Comment by AlDanial** [comment]
Sure, I get that you have proprietary files you can't share.  I don't need those, per se, but *any* pair of files that exhibit the problem.  Can you download some random  C++ file from a tutorial site for example, modify it, run the pair through cloc diff and show that the same count is messed up?

I took a shot with the prime number example at https://www.programiz.com/cpp-programming/examples/prime-interval-function but cloc's result always makes sense.

**Comment by capSAR273** [comment]
Well now I feel silly, I re-ran cloc 1.77 and 2.00 against the original set of files I thought it was over-counting and it is reporting the exact same number of changed/added lines. I'll keep testing between the two versions as I use the tool for future sets of files, but until then I'd say this was a false alarm. Thank you again for this wonderful tool :)
