### ISSUE TITLE
dotnet tool

### ISSUE THREAD

**Issue by johnwc** [AlDanial/cloc#829]
Amound all of the current ways to install this utility, can we get it added as a dotnet tool as well? So we can install it during build pipelines like `dotnet tool install cloc` or globaly `dotnet tool install -g cloc`

**Comment by AlDanial** [comment]
I agree that would be desirable.  I don't control any of the package manager installation methods for cloc.  Perhaps you could volunteer to be cloc's package manager for `dotnet`?
