### ISSUE TITLE
cloc on CPAN

### ISSUE THREAD

**Issue by fibo** [AlDanial/cloc#83]
Hi,

I packaged cloc to make it installable via CPAN with `cpan App::cloc` command.

It would be nice if the two repos could be merged in some way. I am opening this issue cause there was a bug fix to make cloc working on Perl 5.22, is this fix something you can find useful?

https://github.com/fibo/App-cloc-pm/pull/1

**Comment by AlDanial** [comment]
Ref my post at https://github.com/fibo/App-cloc-pm/pull/1, I'd like to see the CPAN version updated to at least the 1.66 release of cloc -- which is Perl 5.22 clean.

**Comment by fibo** [comment]
## cloc updated on CPAN

I updated to `v1.67` and published on CPAN: see [here](https://metacpan.org/pod/App::cloc).

Consider that I am running almost no test, aside a pod checker, but maybe you want to take a look to the [matrix test](http://matrix.cpantesters.org/?dist=App-cloc).

## About CPAN distribution

Please tell me if you would like to be able to push on [App-cloc-pm](https://github.com/fibo/App-cloc-pm) so you can control when cloc is released on CPAN.

**Comment by AlDanial** [comment]
I'm glad to see the update of cloc on CPAN.  Although 1.67 is a development release (my convention is odd numbers are development and even numbers, eg 1.66, are formal releases), I feel confident that the code is stable.  In the future I'd prefer only formal releases to go to CPAN though.

I'm happy to have you continue being the sole owner of App-cloc-pm.  I'll make a note to myself to notify you the next time I issue a release (shooting for summer or fall of this year).

Regarding tests, yes, this is a huge weakness in the project.  A goal for me this year is to assemble a solid test suite.

**Comment by fibo** [comment]
As a user, I am glad to contribute packaging it.
A test suite would be great, please use a t/ folder and Test::More and related like any other Perl software.
If you adhere to conventions you gain a team of volunteers that will test cloc on every platform (see the test matti I linked).

In App-cloc-pm there are already few tests, take a look please.

For the future: just open an issue here when you think cloc is ready For a next Version.

Cheers,
Gianluca

**Comment by fibo** [comment]
Sorry, I meant open an issue on App-cloc-pm or drop me an email
