### ISSUE TITLE
Attempt to create a file in the present working directory.

### ISSUE THREAD

**Issue by eyalroz** [AlDanial/cloc#834]
**Describe the bug**
I run cloc as a non-root user in a folder which I can read from, but not write to, with `cloc --fmt 3`. I get:

```
Error in tempfile() using template ./XXXXXXXXXX.json: Could not create temp file ./gUbE4WVx4L.json: Permission denied at /usr/local/bin/cloc line 1011.
```
this is when running `cloc` without the format spec works fine.

**cloc; OS; OS version**
 - cloc version: 2.0.0 release
 - If running the cloc source, Perl version: v5.26.1
 - OS (eg Linux, Windows, macOS, etc): GNU/Linux
 - OS version: SLES 15.1 SP5

**Expected result**
Expected to see code line counts

**Additional context**

**Comment by AlDanial** [comment]
64005f3 has updates that remove the need to write a temporary file with ``--fmt``, give it a try
