### ISSUE TITLE
Using --vcs=git may encounter "detected dubious ownership" error

### ISSUE THREAD

**Issue by Mattwmaster58** [AlDanial/cloc#838]
**Describe the bug**
When using `--vsc=git`, the following error may be raised in some cases (in my case I was using an Admin prompt on Windows):
```
PS C:\<git repo path>> cloc . --vcs=git -v=3
-> load_from_config_file(C:\Users\<user>\AppData\Roaming\cloc)
<- load_from_config_file() (no such file: C:\Users\<user>\AppData\Roaming\cloc)
-> invoke_generator(git submodule status, .)
fatal: detected dubious ownership in repository at 'C:/<git repo path>'
'C:/<git repo path>' is owned by:
        <domain>/<other user> (S-1-5-21-527237240-764733703-725345543-517076)
but the current user is:
        <domain>/<user> (S-1-5-21-527237240-764733703-725345543-517764)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/<git repo path>
```

**cloc; OS; OS version**
 - cloc version: 2.00
 - OS (eg Linux, Windows, macOS, etc): Windows 11
 - OS version: N/A

**To Reproduce**

Run `cloc --vcs=git` in a git directory that is owned by another user.

**Expected result**
The dubious ownership issues should not prevent cloc from counting IMO.
**Additional context**
The git commands can be prepended with `-c safe.directory=*` to ignore the error about folder ownership, eg:
```bash
git -c safe.directory=* submodule status
```
Perhaps the same approach should be taken for any commands that the `--git` flags uses as well. This is a no-op for git clients which don't have the option.

Fantastic tool btw, I enjoy using it

**Comment by AlDanial** [comment]
Thanks for the tip on ``-c safe.directory=*``.  Give 9b97b60 a try.

**Comment by Mattwmaster58** [comment]
Broken on windows:
```
cloc>perl cloc <path> --vcs=git
error: invalid key: 'safe.directory
fatal: unable to parse command-line config
error: invalid key: 'safe.directory
fatal: unable to parse command-line config
       0 text files.
       0 unique files.
       0 files ignored.
```

**Comment by AlDanial** [comment]
That's a test fail on my part:  I actually did test on Windows, but in a git bash terminal, not a conventional Windows cmd terminal.  Your code in #842 works in both while mine only worked in the git bash term.
