### ISSUE TITLE
Usage of CLOC as an embedded API

### ISSUE THREAD

**Issue by dabico** [AlDanial/cloc#839]
Hi @AlDanial, thank you for this amazing CLI tool. I use it for many projects I work on. I typically invoke it from a JVM application through patterns like command line wrappers (i.e. Java's `ProcessBuilder`). I wondered if the tool has some form of "API" that could be wrapped with something like the Java Native Interface (or the more recent Foreign Function and Memory API) to allow for better integration. I wasn't able to find much information about this. Thanks!

**Comment by AlDanial** [comment]
cloc doesn't have a programmatic API so the brief answer to your question is No.  Even if it did, the API would be in Perl.  It would take skills that I don't have to create a Java interface.

Unfortunately, ``ProcessBuilder`` is your only option for the foreseeable future.

**Comment by dabico** [comment]
I've started working on a Java API implementation that uses Codehaus Plexus to abstract away the command execution and Jackson to parse and process the JSON output. For those interested visit: https://github.com/seart-group/jcloc.
