### ISSUE TITLE
Brainfuck support

### ISSUE THREAD

**Issue by matthieucan** [AlDanial/cloc#84]
Hi,
We plan to run cloc on the whole Debian archive, to output programming language statistics. I know there is at least Brainfuck that is not supported by cloc but present in Debian (quite rare obviously).
That would be an awesome feature to have :)

**Comment by matthieucan** [comment]
Update after having read guidelines:

* The most popular file extensions are .b and .bf
* Comments are everything that is not one of the 8 operations in brainfuck: ><+-.,][
* Sample code can be found on Wikipedia: https://en.wikipedia.org/wiki/Brainfuck#Hello_World.21

**Comment by AlDanial** [comment]
a9247ad adds support for Brainfuck.  Comments are harder to identify than you'd think, and my solution, implemented in <code>sub remove_bf_comments</code>, is not very accurate.  I initially tried <code>Regexp::Common::comment</code>'s Brainfuck comment identifier but that is even worse.

On a side note, Brainfuck is a dumb-ass name for a language.  While <code>cloc</code> will count and show this result in output, you won't see mention of Brainfuck with <code>--show-lang</code>, <code>--show-ext</code>, or <code>--write-lang-def</code>.  Naturally you can edit the source code to bring these back.

**Comment by matthieucan** [comment]
Thanks a lot for implementing this! Cheers.
