### ISSUE TITLE
if rename files. statistics are inaccurate

### ISSUE THREAD

**Issue by fcl564764633** [AlDanial/cloc#841]
Hi @AlDanial, thank you for this amazing CLI tool. one git merge, file is renamed or moved to new directory , How to accurately calculate the amount of code, rather than making a full count of the changed files? thanks！

**Comment by AlDanial** [comment]
File renames could be captured with git's "similarity index" but this capability isn't available in cloc yet.  I'll close this issue as it duplicates #765, #780, and #800.
