### ISSUE TITLE
Pawn language

### ISSUE THREAD

**Issue by Tornamic** [AlDanial/cloc#843]
**If you want an unsupported language added, provide:**
 - language name: Pawn
 - file extension(s): .pwn .inc .pawn
 - method(s) of commenting text: `//...` or `/*...*/`
 - location of sample code: https://github.com/Aureliusnull/admin_sys/blob/main/admin_sys.inc

**For other enhancements:**
Give a concise description of what you want cloc to be able to do.

**Comment by AlDanial** [comment]
The `.inc` extention makes things difficult as it already maps to three languages:
```
» cloc --show-ext | grep ^inc
inc             -> PHP/Pascal/Fortran

```
Adding Pawn means updating subroutine `php_pascal_or_fortran()` that attempts to distinguish Pawn code from these three.  Can you recommend heuristics for this?

**Comment by Tornamic** [comment]
some unique and popular expressions
```pawn
#pragma
#error
#define
#endinput
Float:
bool:
new
static
stock
forward
#include
#undef
defined
```
