### ISSUE TITLE
Publish v2.02 container to Docker hub

### ISSUE THREAD

**Issue by aarongoldenthal** [AlDanial/cloc#847]
**For other enhancements:**

Is there a plan to publish a v2.02 container image and update `latest` on Docker hub?

**Comment by AlDanial** [comment]
Just a few days ago when I released cloc 2.02 Docker Engine wasn't supported on Ubuntu 24.04.  I now see at https://docs.docker.com/engine/install/ubuntu/ that it is available.  Due to other time commitments it will take me a couple of weeks before I can push images to Docker hub though.

**Comment by AlDanial** [comment]
Done:
<pre>
» sudo docker run --rm -v $PWD:/tmp cloc:latest --version           
2.02
» sudo docker run --rm -v $PWD:/tmp aldanial/cloc:2.02 --version
2.02
</pre>

**Comment by aarongoldenthal** [comment]
Thanks @AlDanial
