### ISSUE TITLE
`--include-ext` shouldnt require the language to be explicitly supported

### ISSUE THREAD

**Issue by nektro** [AlDanial/cloc#854]
**For other enhancements:**
Give a concise description of what you want cloc to be able to do.

`--include-ext=foo` should not leave the files still ignored even if cloc doesnt otherwise recognize it automatically

**Comment by AlDanial** [comment]
I don't understand this request; can you give an example of how cloc gets it wrong in the situation you have in mind?

**Comment by nektro** [comment]
![image](https://github.com/user-attachments/assets/32130450-bddd-47f6-b157-e9d1c0011362)

![image](https://github.com/user-attachments/assets/9b889c6c-878c-4827-a951-e70f4a8262ce)

![image](https://github.com/user-attachments/assets/23a55348-9aef-4a67-bcc1-9fbbedc1d7d0)

**Comment by AlDanial** [comment]
The only way to know what is being ignored is to use the `--ignored=FILE` switch to write a file containing the names of files that were ignored (as well as the reason for their exclustion).

When I run with `--include-ext=`, the explicitly-included files don't appear in the ignored list.  Here's an example counting files from cloc's git repo:

<pre>
 » cd /tmp
 » git clone https://github.com/AlDanial/cloc.git
 » cd cloc/Unix/
 » git clone https://github.com/AlDanial/cloc_submodule_test.git
 » ../cloc --ignored=ign.txt --by-file .
        20 text files.
        13 unique files.
  Wrote ign.txt
         8 files ignored.
  
  github.com/AlDanial/cloc v 2.03  T=0.03 s (433.3 files/s, 618336.7 lines/s)
  ----------------------------------------------------------------------------------------------------
  File                                                             blank        comment           code
  ----------------------------------------------------------------------------------------------------
  ./cloc                                                             730           1408          12975
  ./t/00_C.t                                                           3              3           1432
  ./t/01_opts.t                                                      105             28            811
  ./cloc_submodule_test/aa/bb/cc/plasma.c                             47             24            184
  ./cloc_submodule_test/dd/bb/ee/TeapotRenderer.cpp                   49             55            182
  ./t/02_git.t                                                        17              1            146
  ./Makefile                                                          27             36             79
  ./cloc_submodule_test/dd/bb/config.c                                23             22             47
  ./pod2man.mk                                                         9             38             29
  ./why_this_directory_exists.txt                                      4              0             16
  ./cloc_submodule_test/Octave_or_matlab.m                             0              1              2
  ./cloc_submodule_test/README.md                                      0              0              2
  ./cloc_submodule_test/hi.py                                          4             11              2
  ----------------------------------------------------------------------------------------------------
  SUM:                                                              1018           1627          15907
  ----------------------------------------------------------------------------------------------------
</pre>

Eight files were ignored.  Their names and the reason they were ignored are in `ign.txt`:

<pre>
  » cat ign.txt
  ./AUTHORS:  listed in $Not_Code_Filename{AUTHORS}
  ./COPYING:  listed in $Not_Code_Filename{COPYING}
  ./INSTALL:  listed in $Not_Code_Filename{INSTALL}
  ./NEWS:  listed in $Not_Code_Filename{NEWS}
  ./README:  listed in $Not_Code_Filename{README}
  ./cloc.1.pod:  language unknown (#3)
  ./cloc_submodule_test:  --exclude-dir=1
  ./cloc_submodule_test/.gitignore:  listed in $Not_Code_Extension{gitignore}
</pre>

Now another run, this time only counting files with extensions `.c` and `.cpp`:
<pre>
  » ../cloc --ignored=ign.txt --include-ext=c,cpp --by-file .
        21 text files.
        14 unique files.
  Wrote ign.txt
        19 files ignored.

  github.com/AlDanial/cloc v 2.03  T=0.01 s (573.0 files/s, 120895.9 lines/s)
  ----------------------------------------------------------------------------------------------------
  File                                                             blank        comment           code                                                                                                                                                              
  ----------------------------------------------------------------------------------------------------                                                                                                                                                              
  ./cloc_submodule_test/aa/bb/cc/plasma.c                             47             24            184                                                                                                                                                              
  ./cloc_submodule_test/dd/bb/ee/TeapotRenderer.cpp                   49             55            182                                                                                                                                                              
  ./cloc_submodule_test/dd/bb/config.c                                23             22             47
  ----------------------------------------------------------------------------------------------------
  SUM:                                                               119            101            413
  ----------------------------------------------------------------------------------------------------
</pre>

As expected, many more files were excluded.  None of the excluded files have the requested extension though:

<pre>
  » cat ign.txt
  ./AUTHORS:  listed in $Not_Code_Filename{AUTHORS}
  ./COPYING:  listed in $Not_Code_Filename{COPYING}
  ./INSTALL:  listed in $Not_Code_Filename{INSTALL}
  ./Makefile:  not in --include-ext=c,cpp
  ./NEWS:  listed in $Not_Code_Filename{NEWS}
  ./README:  listed in $Not_Code_Filename{README}
  ./cloc:  not in --include-ext=c,cpp
  ./cloc.1.pod:  language unknown (#3)
  ./cloc_submodule_test:  --exclude-dir=1
  ./cloc_submodule_test/.gitignore:  listed in $Not_Code_Extension{gitignore}
  ./cloc_submodule_test/Octave_or_matlab.m:  not in --include-ext=c,cpp
  ./cloc_submodule_test/README.md:  not in --include-ext=c,cpp
  ./cloc_submodule_test/hi.py:  not in --include-ext=c,cpp
  ./ign.txt:  not in --include-ext=c,cpp
  ./pod2man.mk:  not in --include-ext=c,cpp
  ./t/00_C.t:  not in --include-ext=c,cpp
  ./t/01_opts.t:  not in --include-ext=c,cpp
  ./t/02_git.t:  not in --include-ext=c,cpp
  ./why_this_directory_exists.txt:  not in --include-ext=c,cpp
</pre>

If I'm still missing your point, show me the sequence of commands that clarify the problem using this collection of files.

**Comment by nektro** [comment]
![image](https://github.com/user-attachments/assets/0204bf5b-821a-4db2-a126-69b79ebaf466)

**Comment by AlDanial** [comment]
cloc does not recognize files with a `.pek` extension.  These will be ignored despite your request to count them with `--include-ext`.  If you want cloc to be able to count `.pek` files, [supply the necessary information](https://github.com/AlDanial/cloc?tab=readme-ov-file#requesting-support-for-additional-languages-) for this language.

**Comment by nektro** [comment]
hence the title of the issue, it shouldnt need to be a supported language to be counted

**Comment by AlDanial** [comment]
That's not possible.  cloc needs to know how comments are defined in a language so it can distinguish code lines from comment lines.  Look at it another way:  say cloc was told to count a file type it didn't understand.  What filters should it apply to count the file's code and comments--the Fortran filters?  JavaScript's?  It's not a solvable problem.
