### ISSUE TITLE
GTK xml files .ui

### ISSUE THREAD

**Issue by keygenqt** [AlDanial/cloc#857]
**Describe the bug**
Files with the *.ui extension for GTK are detected as Qt.

**cloc; OS; OS version**
 - cloc version: 1.98 & 2.02
 - If running the cloc source, Perl version: 2.02
 - OS (eg Linux, Windows, macOS, etc): Linux, Ubuntu 
 - OS version: 24.04

**To Reproduce**
Just execute the count command with the presence of GTK xml files .ui

**Expected result**
Perhaps it is better to consider these as xml files.

**Additional context**
You can check on the project https://github.com/keygenqt/aurora-toolbox, it contains such files https://github.com/keygenqt/aurora-toolbox/tree/main/data/ui

**Comment by keygenqt** [comment]
![image](https://github.com/user-attachments/assets/4653e786-e828-4e5f-921f-c652a1596caf)

**Comment by AlDanial** [comment]
Identifying such `.ui` files as XML is certainly correct but that loses what I feel is valuable information in that they are XML files associated with the creation of a GUI.  What do you think about labeling these as `XML (Qt/GTK)` ?

**Comment by keygenqt** [comment]
`XML (Qt/GTK)`, or just `Design (Qt/GTK)`, or just `Design`
