### ISSUE TITLE
cloc --help not working

### ISSUE THREAD

**Issue by al-martyn1** [AlDanial/cloc#858]
**Describe the bug**
While typing `cloc --help` it doesn't show the help, it starts hanging. It seems like `cloc` waiting for input from stdin. First I found this behavior on cloc 1.84, and I upgrade clock to actual 2.02 version, but begavior is the same. To get the help it needed ty type something wrong after `cloc --help`, like next:
```
cloc --help aaa
```

**cloc; OS; OS version**
 - cloc: 2.02
 - OS: Windows
 - OS version: 10

**To Reproduce**
Type
```
cloc --help
```
in command prompt

**Expected result**
Expected that clocl displays it's CLI help page

**Comment by AlDanial** [comment]
Before cloc shows the help output it tries to read the optional configuration file which on Windows is under the `APPDATA` environment variable.  Possibly it is getting hung up there.  Try running with verbose level 3 to see more information about what's happending:
`cloc -v 3 --help`

**Comment by AlDanial** [comment]
Actually, before that it does a temp install of the `Algorithm::Diff` module.  Another possibility is cloc can't write to the scratch directory.  Try explicitly defining a temporary write location with
`cloc --sdir C:\TEMP --help`
(assuming you have write permission to `C:\TEMP`).  I need to update cloc to do temporary module installs *after* parsing command line arguments.

**Comment by MitzDS21** [comment]
Why does the cloc provide different output on a directory that has not changed at all since May 2024? I used versions 1.72, 1.90, 1.94, on the same directory, and each version produces a different output, with different languages listed.

**Comment by AlDanial** [comment]
The directory didn't change but cloc did:  bug fixes, support for additional languages, parsing improvements.
