### ISSUE TITLE
Support for CUDA header files

### ISSUE THREAD

**Issue by sakra** [AlDanial/cloc#86]
The extension `.cuh` should be recognized as a CUDA file. See http://www.file-extensions.org/cuh-file-extension

**Comment by jolkdarr** [comment]
In addition, `hpp` should be directly recognized as C++ file.

_I didn't want to add a new report just for that ;)_

**Comment by AlDanial** [comment]
8589b23 adds cuh for CUDA

hpp is already associated with C/C++, as a header file:
<pre>
> cloc --show-ext hpp
hpp             -> C/C++ Header
</pre>

**Comment by jolkdarr** [comment]
If needed, the following option may help: `--force-lang="C++",hpp`
