### ISSUE TITLE
XML files begin with `<?xml` not `<xml`.  Try changing your files to include a question mark after the first `<`.

### ISSUE THREAD

**Issue by salix2022** [AlDanial/cloc#861]
Hello AlDanial

              XML files begin with `<?xml` not `<xml`.  Try changing your files to include a question mark after the first `<`.

_Originally posted by @AlDanial in https://github.com/AlDanial/cloc/issues/856#issuecomment-2379912647_
 

I have checked my code, and the question mark at the beginning is fine. I found that if there is a space before the question mark at the end of the statement, it can be counted by cloc. However, if there is no space before the question mark, the code size will not be counted by cloc. Both of these coding styles exist and the code runs without any issues. Shouldn't cloc count both of these coding styles?

 `<?xml version="1.0" encoding="Shift-JIS" ?>`  OK!! It is included in count result.
 `<?xml version="1.0" encoding="Shift-JIS"?>`  NG!! It isn't included in count result.

**Comment by AlDanial** [comment]
The space before the trailing `?` is irrelevant:

```
» cat 861.xml 
 <?xml version="1.0" encoding="Shift-JIS"?>
 <text><string>abc</string></text>
```

then

<pre>
» cloc  861.xml 
github.com/AlDanial/cloc v 2.03  T=0.00 s (264.3 files/s, 528.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              1              0              0              2
-------------------------------------------------------------------------------
</pre>

Post a file that cloc fails on; the failure must have some other cause.

**Comment by salix2022** [comment]
The phenomenon I'm experiencing is quite strange. When there's a full-width Japanese hyphen in the file, cloc seems to ignore counting the size of that file. However, if I remove the full-width hyphen, it can then count the size of the file normally. I'm not sure why this is happening.

![1729241298470](https://github.com/user-attachments/assets/e1986ad8-4a13-4e85-9f10-bca34b0ee9d1)
![Uploading 1729241578437.png…]()

**Comment by salix2022** [comment]
The XML file I tested was ignored by the CLOC tool for unknown reasons.
[861.zip](https://github.com/user-attachments/files/17442485/861.zip)

**Comment by salix2022** [comment]
thank you very much!
