### ISSUE TITLE
Lines containing both source code and comments are counted as lines of comments for some extensions 

### ISSUE THREAD

**Issue by simahao** [AlDanial/cloc#875]
**Describe the bug**
In your limitations, first point is that lines containing both source code and comments are counted as lines of code, but I got different resut for different languages, e.g. java and javascript are right, but vue and bdy/bod(PL/SQL) are opposite, result of vue or bdy(bod) is lines of comments.

**cloc; OS; OS version**
 - cloc version:2.02
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc):Windows
 - OS version:Windows11

**To Reproduce**
You can reproduce with `cloc --force-lang='Oracle PL/SQL,bdy' a.bdy`, a.bdy like below, I also test vue extension, has same problem like Oracle PL/SQL.

```plsql
/*
 * bubble sort
 */
DECLARE
  TYPE number_array IS VARRAY(100) OF NUMBER;
  arr number_array := number_array(64, 34, 25, 12, 22, 11, 90);
  n NUMBER := arr.COUNT;
  i NUMBER := 0;
  j NUMBER := 0;
  temp NUMBER;
BEGIN
  FOR i IN 1 .. (n - 1) LOOP -- outer
    FOR j IN 1 .. (n - i - 1) LOOP -- inner
      IF arr(j) > arr(j + 1) THEN
        temp := arr(j);
        arr(j) := arr(j + 1);
        arr(j + 1) := temp;
      END IF;
    END LOOP;
  END LOOP;
  -- print
  FOR i IN 1 .. n LOOP
    DBMS_OUTPUT.PUT_LINE(arr(i));
  END LOOP;
END;
/
```

**Expected result**

|   Language    | files | blank | comment | code |
| :-----------: | :---: | :---: | :-----: | :--: |
| Oracle PL/SQL |   1   |   0   |    4    |  22  |

**Actual result**

|   Language    | files | blank | comment | code |
| :-----------: | :---: | :---: | :-----: | :--: |
| Oracle PL/SQL |   1   |   0   |    6    |  20  |

By the way, if I execute cmd like this  `cloc --force-lang='sql,bdy'  a.bdy` , result is ok,so I guess, some extension like java,js,sql are right, but some extensions like bdy(bod),vue are wrong.

**Comment by AlDanial** [comment]
I was relying on the `Regexp::Common` provided regex filter for PL/SQL but it fails with your example.  I used my own filter instead.
