### ISSUE TITLE
vue extension has problem like Oracle PL/SQL

### ISSUE THREAD

**Issue by simahao** [AlDanial/cloc#876]
**Describe the bug**
Like #875 ,vue has same problem.

**cloc; OS; OS version**
 - cloc version:2.02
 - If running the cloc source, Perl version:
 - OS (eg Linux, Windows, macOS, etc):windows
 - OS version:windows11

**To Reproduce**

execute cmd like this  `cloc a.vue`

```vue
<template>
    <div v-loading="loading">
        <div>aaa</div>
    </div>
</template>
<script>
import(menCommonConstant } from '@/utils/menConstant'
// test
export detault,
    name: 'SpecProgramClientNotice',
    components: {
        vxeTable, //table
        menClientInout
    }
</script>
<style lang="scss" scoped></style>
```

**Expected result**
comments: 1

**Actual result**
comments: 2

**Comment by AlDanial** [comment]
This reveals a deeper problem, will take some time to figure out

**Comment by AlDanial** [comment]
0774046 should give the expected result

**Comment by simahao** [comment]
> [0774046](https://github.com/AlDanial/cloc/commit/0774046b062827cca0c081cdb4e193f1ea44ea64) should give the expected result

Yes, thanks for your fix
