### ISSUE TITLE
Has JSX supported in npm cloc@2.0.0?

### ISSUE THREAD

**Issue by Huxpro** [AlDanial/cloc#90]
Well, `cloc` ignore all my `.jsx` files.
So I checked the issues, found the PR <https://github.com/AlDanial/cloc/pull/69> and download the newest version with npm, which show the version is 2.0.0, but I still get all my JSX file ignored :(

I tried `cloc --show-lang` but there is no JSX listed! I convinced I need newer version.
I also tried brew one which show v1.64 and it is no surprising there is not JSX listed in supported lang.

**Comment by AlDanial** [comment]
JSX support exists in the latest version of cloc which you can pull directly from github, https://github.com/AlDanial/cloc/raw/master/cloc 

(I don't control the npm version)

**Comment by Huxpro** [comment]
@AlDanial God Im fool. Thx It works
