### ISSUE TITLE
About the usage of 7zip

### ISSUE THREAD

**Issue by fhy19770227** [AlDanial/cloc#93]
I use 7zip ,not winzip.
Could you give me a sample using 7zip in Dos?
Could the cloc-1.66.exe support 7zip?

I input the command line in Dos:
"C:\Infra\SLOC Count Tool\cloc-1.66.exe" --extract-with="\"c:\Program Files (x86)\7-Zip\7z.exe\" e -aoa >FILE< ." C:\Code\Code.zip

I get the error message:
Cannot use absolute pathnames for this command

**Comment by AlDanial** [comment]
I believe there is a superfluous . in your command right after <code> >FILE< </code>.  Try with
<pre>
"C:\Infra\SLOC Count Tool\cloc-1.66.exe" --extract-with="\"c:\Program Files (x86)\7-Zip\7z.exe\" e -aoa >FILE< " C:\Code\Code.zip
</pre>

**Comment by fhy19770227** [comment]
Thanks a lot.
I got it.
