### ISSUE TITLE
cloc.xml on windows with chinese charset

### ISSUE THREAD

**Issue by nickelee** [AlDanial/cloc#94]
when i use cloc.exe on windows, it make the cloc.xml file with ansi encode.
so, if the project name or file path has the chinese string(or other not ansi string), the xml can not parse by webbrowser or jenkins.
Also i can not find any running option for specific charset(ex:utf-8)
Hope anybody can give us some suggests.
Thanks.

**Comment by AlDanial** [comment]
Try some of the xml encodings described at http://xml.ascc.net/en/utf-8/faq.html by manually editing the first line of your cloc.xml file and replacing
`<?xml version="1.0"?><results>`
with
`<?xml version="1.0" encoding="Big5"?><results>`

If that works I can add options to cloc to pass in the encoding on the command line.

**Comment by AlDanial** [comment]
no follow-up, closing
