### ISSUE TITLE
Strange error when running latest version on Ubuntu 16.04

### ISSUE THREAD

**Issue by milasudril** [AlDanial/cloc#96]
I wanted JSON support so I tried to copy the latest version. I get the following error:

> Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /usr/local/bin/cloc line 1284.

perl version is 

> This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 58 registered patches, see perl -V for more detail)

**Comment by f2404** [comment]
This has been fixed in 1.66.

**Comment by AlDanial** [comment]
Which version are you currently running?  Do
`cloc --version`

1.66 can be found at https://github.com/AlDanial/cloc/releases

**Comment by milasudril** [comment]
Indeed, it was 1.64.
